* Investing
  投資についての情報収集.

* 投資信託
* ヘッジファンド
  私募によって機関投資家や富裕層などから私的に大規模な資金を集め, 
  金融派生商品などを活用した様々な手法で運用するファンド.

 - [[http://ja.wikipedia.org/wiki/%E3%83%98%E3%83%83%E3%82%B8%E3%83%95%E3%82%A1%E3%83%B3%E3%83%89][ヘッジファンド - Wikipedia]]

** 特徴
 - 投資の最低額が, 日本円で 1 億円以上と高額である場合が多く
 - 絶対的収益の追求を目標としている (c.f. Benchmark Return)

** 投資手法
   
   - [[http://ja.wikipedia.org/wiki/%E3%83%98%E3%83%83%E3%82%B8%E3%83%95%E3%82%A1%E3%83%B3%E3%83%89][ヘッジファンド - Wikipedia]]

*** ロング・ショート
    ロング・ショートという名前からもわかるように, 株式等の有価証券のロング
    (買い持ち) とショート (売り持ち) の双方のポジションを同時に取るもので
    ある. アナリストまたはファンドマネージャーが割安つまり過小評価されてい
    ると判断した銘柄については一般的な投資信託と同じく買い (ロング) のポジ
    ションを取り, 逆に割高つまり過大評価されていると判断した銘柄については
    売り (ショート) のポジションを取る.

    不況等の相場全体が下げの環境下では積極的に空売りを仕掛けることで, 絶対
    的な収益を生み出すことが可能になる. 逆に, 好況期の相場全体が上げの環境
    下では, 相場全体について行けずインデックス以下またはマイナスの運用実績
    しか上げられず苦戦しているファンドも多い. マイナスの運用成績は問題であ
    るが, そもそもヘッジファンドの本質は相場環境にかかわらず長期的に安定的
    にプラスのリターンを達成し続けることにあるので, 好況期にインデックスに
    対して勝った負けたと議論するのはナンセンスであるとの論もある.

    また, 売りと買いの両方を仕掛けているので, 相場全体の動きがどちらに進ん
    でも, 片方の玉がヘッジ (保険つなぎ) となり, 損失は最小になるとの考えも
    あり, ヘッジファンドの名前はこの点に由来する. しかし, 買建て玉が下がり,
    売建て玉が上がる場合も当然ありうるので, このような状況が生じると莫大な
    損失を出す可能性を秘めている. 同方式は, 思惑売買を売り買い両面で仕掛け
    ているにすぎず, 売建て玉と買建て玉の価格連動性も考慮していないので, 本
    来の意味でのヘッジにはなっていない. このような売買手法に対して, ヘッジ
    ファンドという名称を付けたのは, 一種の誤解に基づくものといえる. ただし,
    売建て玉を利用できる点については相場技法上, 多大なメリット (特に短期売
    買の場合には顕著) がある. 近年では, 売立て玉と買建て玉の価格連動性を考
    慮した方式が取られる場合も多い.

    なお, 株式ロング・ショートのヘッジファンドには, 特定の業種・セクター
    に絞った運用をするものが多い. 一般的な株式投資信託では広範な業種の
    銘柄を買いながら, その銘柄選択効果で TOPIX 等の市場インデックスを
    上回ることを追求するのに対し, ロング・ショートでは買い・売り双方の
    機会を求め, 特定業種・セクターにおける, より徹底したボトムアップ調
    査を基に運用することに起因する. したがって, 多くの株式ロング・ショー
    トヘッジファンドの運用成績は, その専門分野におけるボトムアップ調査・
    運用能力に比例すると考えられる. なお, 経験測では多くのロング・ショー
    トファンドにおいてネット・ロング (買いポジション>売りポジション)
    の状態にいるケースが多いことが確認されている.

*** アービトラージ Arbitrage
   市場にできる価格差を利用して利益を獲得しようとする取引.
   
   - [[http://ja.wikipedia.org/wiki/%E8%A3%81%E5%AE%9A%E5%8F%96%E5%BC%95][裁定取引 - Wikipedia]]

   人類の歴史は, アービトラージの歴史であった, といっても過言では無いかもしれない.

   同一の取引銘柄が, 複数の市場に上場されている場合, 同じ銘柄であるに
   もかかわらず, 価格に乖離が生じることがある. この場合, 一時的にバイ
   アスがかかっても, 長期的には必ず乖離が修正されるので, 高いほうを売っ
   て, 安いほうを買っておき, 乖離が修正された時点で反対の売買を行えば,
   安全かつ確実に利益を出すことができる. また, 市場間のバイアスを利用
   した取引なので, 上げ下げには依存せず相場に動きがない局面でも利益を
   生み出せる.

   ただし, 裁定取引での投下資金に対する利益は 1/1000~1/10000 程度
   (0.1~0.01%) と極めて微小なものとなる. したがって, レバレッジ比率と売買
   頻度を高めなければ, 高い利回りは望めない. 一般的にヘッジファンドのレバ
   レッジ比率は, 3~5 倍程度といわれている.

*** マーケット・タイミング
    マーケット・タイミングは伝統的なロング・オンリー運用と異なり, ロン
    グ (買い) ポジションに入るタイミングを見計らいながら, それまでは主
    に現金や短期金融資産等で安全運用を行う戦略である. 一般的には株式相
    場全体の上昇基調入りを見計らいながら, 下げ相場では現金運用を行い,
    上昇期にはインデックス運用を行うタイプが多い. トップダウン型の一種
    であり, 金融政策や財政, 主要な経済指標などを分析しマクロ経済のサイ
    クルを見計らうアプローチが取られる.

    マーケット・タイミングは, その特性上, 一般的な株式投資信託よりもリ
    スクが低い運用手法と考えられる.

*** レラティブ・バリュー
    上述の裁定取引 (アービトラージ) と混同して議論されることが多いが, レラ
    ティブバリューは, 広義では相対的な割安・割高を収益機会と捉える手法であ
    る. 裁定取引は厳密には市場における完全なミスプライス (全く同じ経済効果
    をもたらす複数の資産やポートフォリオの間で異なる価格が存在している状態)
    を収益機会と捉えるのに対し, レラティブ・バリューではあくまで相対的な割
    安・割高をもって収益機会と捉える点で異なる (なお, 実運用においては完全
    なミスプライス状態はそうそう頻出するものではないので, ほぼ完全なミスプ
    ライス状態をもって裁定機会と捉えるアービトラージャーが多い).

    LTCM の運用手法は裁定取引型と表現されるケースもあるが, むしろレラ
    ティブバリュー型の方が実態に近かったと考えられる.

*** イベント・ドリブン Event-Driven
    企業の合併・買収, 再編・提携, 新商品開発などの企業の流れを
    変える大きなイベントが発生することを予想してポジションを取る運用手法.

    - [[http://www.daiwa.jp/glossary/jpn/00808.html][大和証券/ 用語集/ イベント・ドリブン]]

*** マーケット・ニュートラル
    マーケット・ニュートラル (市場中立型) とは, その名のとおり市場に対
    して中立なポジションを取る運用手法である. 一般的な株式投資信託では,
    株式市場全体の動き (TOPIX など) をベンチマークとし, そのベンチマー
    クに対するポートフォリオの感応度をベータ, ベンチマークの動きにかか
    わらず生じる収益をアルファと表現する. ベータのリスクを排除した運用
    手法ともいえる.

    マーケットニュートラルでは, 市場全体の値動きに左右されず, 銘柄選定効果
    (アルファ) だけを積み上げていくリターン特性をもつので, ヘッジファンド
    の中で最もリスクが低く安定した運用手法の一つである. また, 伝統的な資産
    クラスとの相関が低いので, 既存の伝統的ポートフォリオに追加した際に得ら
    れる分散効果が最も高いともいわれている.

*** グローバル・マクロ
    グローバル・マクロは, 実質的には特定の運用手法を指すものではなく,
    多種多様な市場において多種多様な資産を多種多様な手法で運用するファ
    ンドの総称である. その多くが, 世界のマクロ経済動向見通しをベースに
    したトップダウンアプローチに基づき, 世界各市場で多種多様なポジショ
    ンを張っている. 有名なものではジョージ・ソロスのクオンタムファンド
    がこの分類に入る. 一時期はヘッジファンド=グローバルマクロというよ
    うなイメージで語られることもあったが, 機関投資家側のヘッジファンド
    に対するニーズが具体化・特定化している現在においては, 主要な地位を
    占める戦略ではなくなっている.

*** マネージド・フューチャーズ
    マネージド・フューチャーズは, 取引所に上場している先物に投資する運用手
    法. カテゴリーとしてはヘッジファンドではなくコモディティ投資とする見解
    が多く, 広義では代替投資の一つである. 元来は商品に限らず各種金融資産,
    通貨等も含めた先物全体を活用した運用手法で, 運用者はコモディティ・トレー
    ディング・アドバイザー (CTA) と呼ばれ, 米国では CFTC の管轄下である.
    投資対象の定義を除けば, ロング・ショート・タイミングなどの具体的な戦略
    を特定するものではない.

*** プライベート・エクイティ
    未上場企業に投資するベンチャー・キャピタルや, 企業の買収, 再生, 売
    却を通じて収益を上げるバイアウト・ファンドなどの総称. 一投資家に過
    ぎない一般的な株式投資と異なり, 大株主として企業の経営に対しより直
    接的な関与をし, 企業価値を向上させながら最終的に IPO や M&A による
    売却など (Exit, エグジット) を目指す. その特性から, 中長期的な投資
    が多く, 流動性も低い投資手法である.

* Computational Investing
  アルゴリズム取引.

  [[http://en.wikipedia.org/wiki/Algorithmic_trading][Algorithmic trading - Wikipedia, the free encyclopedia]]

** Motivations
   売買するときに「ためらい」や「迷い」がなく, 
   短時間の売買でもタイミングを逃さないというメリットがある一方,
   瞬間的に注文が成立するため, あらかじめ注文条件を指値で設定するなど戦略的な売買が重要.
   

   自ら開発したアルゴリズム取引をする「株ロボット」を使い, 
   2010 年 10 〜 12 月の収益額で 1 億 801 万円を稼ぎ出した個人投資家もいた.
   - [[http://news.biglobe.ne.jp/economy/0207/jc_110207_6229416623.html][コンピューター使ったアルゴリズム取引 機関投資家から個人投資家に広がる - BIGLOBE ニュース]]

*** カブロボ・コンテスト  
    カブロボは, 利用者の方にカブロボの開発を通じて
    「サイバーファンドマネージャー」になってもらうためのプロジェクト.

   - [[http://www.kaburobo.jp/about][カブロボ・コンテスト 自動株式売買ロボット・カブロボ]]
   - [[http://kaburobo.net/][カブロボ公式 BLOG - kaburobo.net  日々の最新情報をご提供しています]]
   - [[http://www.itmedia.co.jp/enterprise/articles/0503/18/news107.html][優勝者は年利 332%--カブロボ・コンテストが残したもの - ITmedia エンタープライズ]]
   - [[http://www.jcfia.gr.jp/channel/gm_report/gm_report3.html][第 3 回 アルゴリズム取引がやってくる]]


* テクニカル指標
  過去のチャートから次の値動きの目安になる情報を抽出するための計算アルゴリズム.

  トレンド・偏差・最高価格からの比率・市場心理等
  様々な観点から指標が作成されて発表されている.

  - [[http://ja.wikipedia.org/wiki/%E3%83%86%E3%82%AF%E3%83%8B%E3%82%AB%E3%83%AB%E6%8C%87%E6%A8%99%E4%B8%80%E8%A6%A7][テクニカル指標一覧 - Wikipedia]]

** トレンド系指標
   トレンドの方向性を判定する. 移動平均から派生した物など.

** オシレーター系指標
   過去の値動きから, 今の価格が高い位置にいるのか安い位置にいるのかを判定する. 
   トレンドの転換点を判定する. パーセントで表示する物が多い.

*** Bollinger Bands
    今後の相場のレンジ (値幅) や反転を判断する指標です.
    上下に一本づつバンドが引かれ上下幅は移動平均線を基準とした標準偏差で決まります.

    買われすぎや売られすぎを判断することが出来る有効なテクニカル指標.
    - [[http://www.k3.dion.ne.jp/~forex/tc/bl.htm][ボリンジャーバンド (Bollinger bands)-テクニカル分析指標解説]]
    - [[http://www.gaitameonline.com/academy_chart02.jsp][FX 実戦チャート術 第 2 回 ボリンジャーバンド・ MACD|FX|外為オンライン  FX 取引 - あなたの為の, 外為を. ]]

#+begin_src python
Bollinger_val = (price - rolling_mean) / (rolling_std)
#+end_src

* 用語集
** adjusted close
   調整後終値. 株式分割を考慮した株価.

   - [[http://www.yahoo-help.jp/app/answers/detail/p/546/a_id/45316/~/%E8%AA%BF%E6%95%B4%E5%BE%8C%E7%B5%82%E5%80%A4%E3%81%A8%E3%81%AF][Yahoo! ファイナンスヘルプ - 調整後終値とは]]
   - [[http://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q10112859395][株について教えてください. 株価において「終値」と「修正後終値」があ... - Yahoo! 知恵袋]]
** Back Test
   バックテスト (Back Test) とは, システムトレードなどを利用する場合に
   プログラムなどを利用して当該ストラテジーを過去の為替レートや株価な
   どに当てはめた場合にどのような動きをするのかをチェックするテストのこと.

   - [[http://www.finance-dictionay.com/2012/02/post_886.html][バックテストとは]]

** CAPM
   ボートフォリオのための理論.
   - [[http://ja.wikipedia.org/wiki/%E8%B3%87%E6%9C%AC%E8%B3%87%E7%94%A3%E4%BE%A1%E6%A0%BC%E3%83%A2%E3%83%87%E3%83%AB][資本資産価格モデル - Wikipedia]]

#+begin_src language
E (r)  =  rf  +  β (rM-rf )

E (r):  任意の株式の期待リターン
rf:  リスクフリー・レート
β:  任意の株式のβ値
rM-rf:マーケットリスク・プレミアム
#+end_src


*** 説明
   ある資産の分散可能でないリスクが既に分かっていて, 
   その資産をすでによく分散されたポートフォリオに組み入れる時に, 
   要求されるリターンの理論的に適切な値 
   (および, その資産の将来のキャッシュフローの期待値を見積もることが
   できるならばその資産の価格) を決定するために用いられる.

*** 資産価格
   理論的には, その資産の価格の観測値が, 
   CAPM によって導出された割引率を使って計算された価値と等しいならば, 
   資産は適正に価格付けされている. 価格の観測値が計算された価値よりも高ければ,
   その資産は過大評価されている. 
   価格の観測値が計算された価値よりも低ければ, その資産は過小評価されている.
** Efficient-market hypothesis.
  効率的市場仮説.

  市場参加者は利用可能なすべての情報を迅速に取り入れており, 
  新規情報によって他の市場参加者より有利になるという状況は生じないため, 
  市場の挙動はランダムウォークになるという仮説.

  - [[http://en.wikipedia.org/wiki/Efficient-market_hypothesis][Efficient-market hypothesis - Wikipedia, the free encyclopedia]]
  - [[http://ja.wikipedia.org/wiki/%E4%BA%BA%E5%B7%A5%E5%B8%82%E5%A0%B4#.E5.8A.B9.E7.8E.87.E7.9A.84.E5.B8.82.E5.A0.B4.E4.BB.AE.E8.AA.AC][人工市場 - Wikipedia]]

** Event study
   企業の活動に関する何らかの情報の発表が, 
   その企業の市場価値にどのような影響を与えるかという問題を分析・研究すること.

   1. 影響を与える期間を設定する
   2. 推定するモデルを決めて, 『起こらなかった状態』を推定する
   3. 『実際に起こった状態』と 2. を比較する
   4. 仮説検定する
   5. 解釈する

   参考:
   - [[http://miyazakidesu.hatenablog.com/entry/2014/08/04/111449][(データ分析) イベント・スタディ ~ イベントが企業価値に与える影響を計る~ - 駆け出しコンサル日記. ]]
   - [[http://money.infobank.co.jp/contents/A200098.htm][イベント・スタディ ~ インフォバンク  マネー百科]]

** Sharp Ratio
    シャープレシオ.

    - 投資の効率性を語るメジャー.
    - リスクを取って運用した結果, 
      安全資産 (リスクがゼロと仮定した資産) から得られる収益 (リターン) 
      をどの位上回ったのか, 比較できるようにした指標.
    - ファンドの運用成績を比較する場合に広く用いられています.
    - Reward/Risk

*** 算出方法
    リターンから安全資産 (たとえば国債) の収益率を引いたものを, 
    そのファンドの標準偏差で除したもの.

    Reward/Risk

*** Links
    - [[http://allabout.co.jp/gm/gc/8879/][シャープレシオは投資の効率性を示す指標 All About]]
** Short Selling
   投資対象である現物を所有せずに, 対象物を (将来的に) 売る契約を結ぶ行為.

   - [[http://ja.wikipedia.org/wiki/%E7%A9%BA%E5%A3%B2%E3%82%8A][空売り - Wikipedia]]

** Sytem Trade
   裁量を排し一定売買ルールに従って売買を行う方法.
   - [[http://ja.wikipedia.org/wiki/%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0%E3%83%88%E3%83%AC%E3%83%BC%E3%83%89][システムトレード - Wikipedia]]
** Retrun
   投資を行うことで得られる収益.

** Risk
   リスク.

   - リターン (収益) の振れ幅.
   - 標準偏差.

* 現代ポートフォリオ理論 (MPT)
  ハリー・マーコウィッツの論文からはじまった理論

  - [[http://ja.wikipedia.org/wiki/%E3%83%8F%E3%83%AA%E3%83%BC%E3%83%BB%E3%83%9E%E3%83%BC%E3%82%B3%E3%82%A6%E3%82%A3%E3%83%83%E3%83%84][ハリー・マーコウィッツ - Wikipedia]]
  - [[http://money.infobank.co.jp/contents/K400060.htm][現代ポートフォリオ理論 (MPT) ~ インフォバンク  マネー百科]]

** ポートフォリオ最適化
   - Given:
     - A set of equities, and
     - Target return
   - Find:
     - Allocation to each equity that minimizes risk 
