#+OPTIONS: toc:nil
* Logical Thinking
  [[http://ja.wikipedia.org/wiki/%E3%83%AD%E3%82%B8%E3%82%AB%E3%83%AB%E3%82%B7%E3%83%B3%E3%82%AD%E3%83%B3%E3%82%B0][ロジカルシンキング - Wikipedia]]

* MECE(Mutually Exclusive and Collectively Exhaustive)
  情報や分析対象をグループ分けする際に、
  「重複なく・漏れなく」行うべきであるということを示した指針。

* So What / Why So
  結論と根拠が適切につながっていることを確認するためのテクニック。
  「So What?」はその根拠がどういう結論を導くのかを、
  「Why So?」はその結論の根拠が適切かをそれぞれ確認するために用いる。

* ピラミッドストラクチャ
  結論と根拠を多段に組み立てることによって作られる構造で、
  ドキュメントの骨子全体の構造を表現するものとされる。

* ロジックツリー
  問題の分析や、課題の整理の結果をツリー構造として表現したものであり、
  目的によって様々な種類がある。

* フレームワーク
  コンサルティングを行う際に広く使うことのできる構造のひな形であり、
  項目はMECEになっているとされる。
  3Cや4Pといったものがその具体例として示されることが多い。 
  -> ビジネス・フレームワーク

* 仮説思考
  [[http://www.nsspirit-cashf.com/logical/kasetsu_shikou.html][N's spirit　仮説思考　仮説とは　仮説の立て方]]

** 空・雨・傘
* Books
  『問題解決プロフェッショナル「思考と技術」』(齋藤 嘉則, ダイヤモンド社, 1997年)
  『経営参謀が明かす論理思考と発想の技術』(後 正武, プレジデント社, 1998年)
  『考える技術・書く技術』(バーバラ・ミント, グロービスマネジメントインスティテュート, 1999年)
  『ロジカル・シンキング』(照屋華子・岡田恵子, 東洋経済新報社, 2001年)
  『マッキンゼー式 世界最強の仕事術』( イーサン・M. ラジエル, 英治出版, 2001年)
