#+OPTIONS: toc:nil
* Logical Thinking
  [[http://ja.wikipedia.org/wiki/%E3%83%AD%E3%82%B8%E3%82%AB%E3%83%AB%E3%82%B7%E3%83%B3%E3%82%AD%E3%83%B3%E3%82%B0][ロジカルシンキング - Wikipedia]]

* 問題定義
  問題とは, 理想と現実との差異, ギャップ.

  - 顕在問題
  目の前の問題. 目に見える問題. 悪い状況をよくしたい.

  - 潜在問題
  目に見えない問題. 見つけ出す問題.
  現状は悪くないがもっとよくしたい.

** 分析のフレームワーク
   - 現実
   - 感情 (なんとかしたい, もっとこうしたい)
   - 理想, あるべき姿

** 3 厶主義
   無駄, 無理, ムラ. [[http://kotobank.jp/word/%E3%83%A0%E3%83%AA%E3%83%BB%E3%83%A0%E3%83%80%E3%83%BB%E3%83%A0%E3%83%A9][ムリ・ムダ・ムラ とは - コトバンク]]

   - ムリとは負荷が能力を上回っている状況
   - ムダとは逆に負荷が能力を下回っている状況
   - ムラはムリとムダの両方が混在して時間によって表れる状況

* 課題定義
** 課題とは
   課題とは, 問題を解決するために, 行動を起こすことを意志表明したもの.
   問題は, 主体的に解決する意志を持って行動を起こすことによって解決に向かう.

   - [[http://www.recruit-ms.co.jp/issue/feature/kaihatsu/200702/01.html][今月の特集 |人材育成のリクルートマネジメントソリューションズ]]

   「すべての原因に対し, あらゆる手を打とう」と考えるのは間違いです.
   どこを攻めるのが効果的か, つまり攻めどころを見極めなくてはいけません

   - [[http://kantokushi.or.jp/lsp/no672/672_02.html][7.  問題を課題化し, さらに取り組み課題へと具体化する]]

*** 問題と課題の違い
   問題を課題に落とし込まないと解決できない.
   課題とは, 問題を解決するために何をすべきか, ということを設定したもの.

   - [[http://blogs.itmedia.co.jp/tani/2012/11/post-f0b6.html][「問題」と「課題」の違い・その 2:谷誠之の 「カラスは白いかもしれない」]]

** 課題の表現方法
   課題の表現方法としては, 問題提起型や行動ベースの表し方があります.

   - A 社の攻勢に対抗するには」 (問題提起型)
   - A 社への対抗手段を講じる」 (行動ベース) 

   - [[http://kantokushi.or.jp/lsp/no672/672_02.html][7.  問題を課題化し, さらに取り組み課題へと具体化する]]

** ブレインストーミング
   アイデアを出すための方法.

*** ブレインストーミングの 4 原則
    Wikipedia から引用する. [[http://ja.wikipedia.org/wiki/%E3%83%96%E3%83%AC%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%9F%E3%83%B3%E3%82%B0][ブレインストーミング - Wikipedia]]

    - 判断・結論を出さない (結論厳禁)
    自由なアイデア抽出を制限するような, 判断・結論は慎む.
    判断・結論は, ブレインストーミングの次の段階にゆずる.
    ただし可能性を広く抽出するための質問や意見ならば, その場で自由にぶつけ合う.

    - 粗野な考えを歓迎する (自由奔放)
    誰もが思いつきそうなアイデアよりも,
    奇抜な考え方やユニークで斬新なアイデアを重視する.
    新規性のある発明はたいてい最初は笑いものにされる事が多く,
    そういった提案こそを重視すること.

    - 量を重視する (質より量)
    様々な角度から, 多くのアイデアを出す. 一般的な考え方・アイデアはもちろん,
    一般的でなく新規性のある考え方・アイデアまであらゆる提案を歓迎する.

    - アイディアを結合し発展させる (結合改善)
    別々のアイデアをくっつけたり一部を変化させたりすることで,
    新たなアイデアを生み出していく. 他人の意見に便乗することが推奨される.

** MECE
   Mutually Exclusive and Collectively Exhaustive.
   (相互に排他的な項目」による「完全な全体集合」)

   - [[http://ja.wikipedia.org/wiki/MECE][MECE - Wikipedia]]

   情報や分析対象をグループ分けする際に,
   「重複なく・漏れなく」行うべきであるということを示した指針.
   
   - 最低限 2 x 2 のマトリックスで考える
   - 既存の MICE 用フレームワークで考える

** ロジックツリー
   問題の分析や, 課題の整理の結果をツリー構造として表現したものであり,
   目的によって様々な種類がある.

   - 結果-原因 (why)
   - 目的-手段 (how)
   - 全体-部分 (what)

   といった推論を繰り返して論理展開を行う場合,
   その概念・事象間の論理的なつながりをツリー状に図示すること.

   問題解決などに使う場合には, 上位概念から下位概念への分岐を 2~3 程度,
   多くても 5 つぐらいまでにするのがよいとされる.

   - [[http://www.itmedia.co.jp/im/articles/0609/01/news133.html][情報マネジメント用語辞典:ロジックツリー (ろじっくつりー)]]

*** MECE とロジックツリーの違い
    MICE は「もれなく, だぶりなく」数え上げるという考え方.
    ロジックツリーは MECE を実行するためのツール (フレームワーク) の一つ.

    - [[http://oshiete.goo.ne.jp/qa/3869287.html][MECE とロジックツリーの違いとは? - 教えて!goo]]
   
** ピラミッドストラクチャ
   結論と根拠を多段に組み立てることによって作られる構造で,
   ドキュメントの骨子全体の構造を表現するものとされる.

*** ロジックツリーとピラミッドストラクチャーの違い
   以下のサイトでロジックツリーとピラミッドストラクチャーの違いが紹介されている.

   [[http://d.hatena.ne.jp/ohshi004/20080803/1217755608][ロジックツリーとピラミッドストラクチャー - Thinking Room で何想ふ. ]]

   - ロジックツリー
   MECE を意識して, 上位概念を下位の概念にトップダウン式に分解していく形式.
   帰納的.

   - ピラミッドストラクチャー
   具体的な情報や観察事項から上位の概念としてのメッセージを
   ボトムアップに抽出していく形式. 演繹的.

*** So What / Why So
    結論と根拠が適切につながっていることを確認するためのテクニック.

    - [[http://logical.tokusen-info.com/sowhat.html][ロジカルシンキング情報館:ロジカルシンキングの基礎技術「 So What?/Why So? 」]]

**** So What?  
    その根拠がどういう結論を導くのか.
    現在持っている情報から導き出せる結論を見つけ出す作業.

    だからなに?
    だから xxx だよ.

**** Why So?
     その結論の根拠が適切か.

     本当にそうなの? 
     ○○だから本当にそうなんだよ

*** 帰納法
    複数の特定の前提から結論を導くロジック展開.
    結論は, 常に推論となる.

    つなぎ言葉をいれることで, 前後の関係をチェック

    - なぜそう判断するかと言えば
    - なぜならば
    - たとえば
    - 具体的には
    
    結論から表現する.

#+begin_src language
私の考えは・・・です. 理由は 3 つあります. 一つめは, xxx です. 2 つめは・・・.
#+end_src

*** 演繹法
    絶対的に正しいことや一般的に正しいと判断されることから,
    妥当と思われる結論を導くロジック展開.
    結論は, 常に正しい.

*** How 構造と Why 構造
    - How 構造
      どのようにすべきか? -> 具体的には・・・

    - Why 構造
      なぜか? -> なぜならば・・・

** 仮説思考
   仮説思考とは, 何かに取り組む際に,
   その時点で考えられる仮説 (仮の結論) を置いて考える思考方法.

   - [[http://www.nsspirit-cashf.com/logical/kasetsu_shikou.html][N's spirit  仮説思考  仮説とは  仮説の立て方]]

   仮説とはその時点で「こうすれば, こうなる」という結論をその理由とともに 設定すること.
   一般的な「原因解明」次に「行動決定」の流れではなく,
   「行動決定」次に「検証」の逆の順に進める.

   - [[http://fk-plaza.jp/Solution/solu_kasetsu.htm][問題解決手法>仮説思考法]]

   仮説は事実かどうか検証する. まちがっているかもしれないので.
   - 統計データやグラフ (定量的)
   - ヒヤリング (定性的)

   すぐに課題を出すのは, 仮説思考ではない. 課題は必ず事実で裏付けをとる.

#+begin_quate
仮説 <-> 事実 => 課題
#+end_quate

*** 空・雨・傘

    - 空 (事実)
    - 雨 (解釈)
    - 傘 (行動)

    [[http://blog.livedoor.jp/kimura_nya/archives/30321835.html][「空・雨・傘」の枠組みをいかに利用するか : コンサルティングとファイナンス]]

** フレームワーク思考  
   コンサルティングを行う際に広く使うことのできる構造のひな形であり,
   項目は MECE になっているとされる.
   3C や 4P といったものがその具体例として示されることが多い.
   -> ビジネス・フレームワーク

** ゼロベース思考
** ポジティブ思考
** グラフ分析
   仮説を裏付けるグラフを作成して事実を確認する.
   また, グラフで気づいた部分をメッセージとして書き込む.
*** 代表的なグラフ
    - 棒グラフ
    - 折れ線グラフ
    - 二軸グラフ
    - 円グラフ
    - 帯グラフ

* 解決策
  MECE とロジックツリーで解決策を考える.
  解決策の方向性でロジックツリーを展開する.
* Links
* Books
  -『問題解決プロフェッショナル「思考と技術」』 (齋藤 嘉則, ダイヤモンド社, 1997 年)
  -『経営参謀が明かす論理思考と発想の技術』 (後 正武, プレジデント社, 1998 年)
  -『考える技術・書く技術』 (バーバラ・ミント, グロービスマネジメントインスティテュート, 1999 年)
  -『ロジカル・シンキング』 (照屋華子・岡田恵子, 東洋経済新報社, 2001 年)
  -『マッキンゼー式 世界最強の仕事術』 ( イーサン・ M. ラジエル, 英治出版, 2001 年)
