#+OPTIONS: toc:nil
* Logical Thinking
  [[http://ja.wikipedia.org/wiki/%E3%83%AD%E3%82%B8%E3%82%AB%E3%83%AB%E3%82%B7%E3%83%B3%E3%82%AD%E3%83%B3%E3%82%B0][ロジカルシンキング - Wikipedia]]

* 問題定義
  問題とは, 理想と現実との差異, ギャップ.

  - 顕在問題
  目の前の問題. 目に見える問題. 悪い状況をよくしたい.

  - 潜在問題
  目に見えない問題. 見つけ出す問題.
  現状は悪くないがもっとよくしたい.

** 分析のフレームワーク
   - 現実
   - 感情 (なんとかしたい, もっとこうしたい)
   - 理想, あるべき姿

** 3 厶主義
   無駄, 無理, ムラ. [[http://kotobank.jp/word/%E3%83%A0%E3%83%AA%E3%83%BB%E3%83%A0%E3%83%80%E3%83%BB%E3%83%A0%E3%83%A9][ムリ・ムダ・ムラ とは - コトバンク]]

   - ムリとは負荷が能力を上回っている状況
   - ムダとは逆に負荷が能力を下回っている状況
   - ムラはムリとムダの両方が混在して時間によって表れる状況

** issue の定義
   issue とは, 以下の両方を備えるものを言う.
   - a matter that is in dispute between two or more parties
   2 つ以上の集団の間で決着のついていない問題
   - a vital or unsettled matter
   根本に関わる, もしくは白黒がはっきりしていない問題

** イシュードリブン-「解く」前に「見極める」.
  世の中にある「問題かもしれない」と言われていることのほとんどは, 
  実はビジネス・研究上で本当に取り組む必要のある問題ではない.
  世の中で「問題かもしれない」と言われていることの総数を 100 とすれば, 
  今, この局面で本当に白黒をはっきりさせるべき問題はせいぜい 2 つか 3 つくらい

  「イシュー度」の高い問題を絞り込み, 時間を浮かせることが不可欠

  G3 課題研修では, 6 回テーマを変更した.初めの issue のたて方を誤った実体験の例.(2014/07)

** 問題・仮説の表現方法
   疑問文あるいは「複数の変数間にどんな関係があるのか」という疑問を投げかけたものである.

   - 問題は 2 つ以上の変数との関係を記述すべき
   - 問題は疑問形でかつ曖昧さが残らないように記述されるべき.

   [[http://kjs.nagaokaut.ac.jp/watahiki/himitsu/labo_only/study/2QandH.htm][2 章              問題と仮説]]

*** 主語, 動詞で表現する
*** WHY よりも WHERE, WHAT, HOW で表現する
    Why という表現には仮説がなく, なにに白黒をはっきりさせるべきかが曖昧.
    答えをだすという視点で issue を定義する.

    - WHERE どちらか, どこを目指すべきか?
    - WHAT  なにを行うべきか, なにをさけるべきか?
    - HOW   どう行うべきか? どう進めるべきか?
 
*** 比較表現で表現する
    A か B かという見極めが必要な issue では, A よりもむしろ B という表現にする.

** よいイシューの 3 条件
   - 本質的な選択肢である (その結論によって大きく意味合いが変わる)
   - 深い仮説がある
   - 答えを出せる

* 課題設定
  ここでは, 仮説思考について扱う. 課題設定には, 2 つのフェーズがある.

  - 仮説設定: 問題を妨げる要因の原因を設定する.
  - 仮説検証: 仮説を事実で裏付ける.

** 仮説
*** 仮説の定義
    物事を考える際に「最も確からしいと考えられる仮の答え」のこと.
    ファクト (事実) を知ろうとするとき, 観察や情報収集が欠かせないが,
    何を求めているのかがわからなければ, 必要な情報を効率よく集めることはできない.
    「もしかしたらこうなるのではないか」「このようなことが起こっているに違いない」という
    , 仮の答えを持つことが重要になってくる

    - [[http://kotobank.jp/word/%E4%BB%AE%E8%AA%AC][仮説 とは - コトバンク]]

   真偽はともかくとして, 何らかの現象や法則性を説明するのに役立つ命題.

   - [[http://ja.wikipedia.org/wiki/%E4%BB%AE%E8%AA%AC][仮説 - Wikipedia]]

     仮説とはその時点で「こうすれば, こうなる」という結論をその理由とともに 設定すること.

*** 仮説と問題の関係
    問題の原因のなかで, 最も確からしいと考えられる仮の答え.
    問題の原因に裏付けがとれれば, それが課題になる.

*** 仮説の表現方法
    白黒をはっきりさせるような表現をする. 平叙文.

    複数の変数間の関係についての, 推測的記述である. 
    仮説は, 平叙文の形をとっており, 
    そしてそれらは全般的あるいは明確に変数を関連付けている

** 仮説思考
   仮説思考とは, 何かに取り組む際に,
   その時点で考えられる仮説 (仮の結論) を置いて考える思考方法.

   - [[http://www.nsspirit-cashf.com/logical/kasetsu_shikou.html][N's spirit  仮説思考  仮説とは  仮説の立て方]]

   一般的な「原因解明」次に「行動決定」の流れではなく,
   「行動決定」次に「検証」の逆の順に進める.

   - [[http://fk-plaza.jp/Solution/solu_kasetsu.htm][問題解決手法>仮説思考法]]

   仮説は事実かどうか検証する. まちがっているかもしれないので.
   - 統計データやグラフ (定量的)
   - ヒヤリング (定性的)

   すぐに課題を出すのは, 仮説思考ではない. 課題は必ず事実で裏付けをとる.

   仮説思考とは, 情報収集の途中や分析作業以前にある一定の「結論」
   (仮説) を導き出し, その仮説を検証することにより真の結論を導き出す手法である.
   仮説を用いることで効率的に真の結論にたどりつくことができる点がメリットとなる.
   
   仮説の検証は, 仮説→実験→検証を繰り返すことによって,
   より真なる結論に近い仮説として進化していくため, 当該プロセスを繰り返せば繰り返すほどよい.

   - [[http://www.weblio.jp/content/%E4%BB%AE%E8%AA%AC%E6%80%9D%E8%80%83][仮説思考とは - MBA 用語 Weblio 辞書]]

#+begin_quate
仮説 <-> 事実 => 課題
#+end_quate

*** フィーチャードリブンとイシュードリブンの比較
**** フィーチャードリブン
    フィーチャードリブンとは, アジャイルプラクティスの一つ.
    それらは全て, 顧客にとっての機能価値 (feature) という観点で駆動される. 
    その主な目的は, 実際に動作するソフトウェアを繰り返し, 適切な間隔で提供することである.

    - [[http://ja.wikipedia.org/wiki/%E3%83%A6%E3%83%BC%E3%82%B6%E3%83%BC%E6%A9%9F%E8%83%BD%E9%A7%86%E5%8B%95%E9%96%8B%E7%99%BA][ユーザー機能駆動開発 - Wikipedia]]

**** イシュードリブン
    自分が今取り組もうとしている課題が本当に解くべき課題なのかを再度確認して, 
    最終的なアウトプットのインパクトを強める.

    - [[http://d.hatena.ne.jp/fulic/20110812/1313159016][イシューからはじめよ-知的生産の「シンプルな本質」 - THINK CIRCUIT]]

*** TDD/BDD と仮説思考の比較
    - TDD/BDD:
      * テストからはじめる.
      * テストを通すために実装する.
      * 必要のないコードは書かない. 
    - 仮説思考: 
      * 課題の仮説からはじめる.
      * 仮説を証明するために分析する.
      * 必要のない分析はしない.

*** ウォーターフォールとなぜなぜ思考の比較
    - ウォーターフォール:
      * 実装からはじめる.
      * 実装をしてからテストをする.
    - なぜなぜ分析
      * 分析からはじめる.
      * 分析をした結果を整理して課題を導く.




** 仮説設定・問題分析 = ストーリーライン×絵コンテ
   イシューの構造を明らかにし, そのなかに潜むサブイシューを洗い出すとともに, 
   それに沿った分析のイメージ作りを行う過程.

   - ストーリーライン
   - 絵コンテ

   大まかなアウトラインをつくれば, それを検証するための工数が見積もれる.

*** 仮説設定のスタート地点
    問題は理想と現実のギャップ. 理想を妨げる要因, 原因のなかで, もっともらしいものを選ぶ.
    選んだ仮説は検証によって課題となる.

    原因仮説ともいう. (解決策仮説と対比)

*** 仮説を引き出すトリガ
    - xxx を妨げる原因は?
    - xxx が xxx である原因は?
    - xxx を実現するための要因は? (How)

** ブレインストーミング
   アイデアを出すための方法.

*** ブレインストーミングの 4 原則
    Wikipedia から引用する. [[http://ja.wikipedia.org/wiki/%E3%83%96%E3%83%AC%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%9F%E3%83%B3%E3%82%B0][ブレインストーミング - Wikipedia]]

    - 判断・結論を出さない (結論厳禁)
    自由なアイデア抽出を制限するような, 判断・結論は慎む.
    判断・結論は, ブレインストーミングの次の段階にゆずる.
    ただし可能性を広く抽出するための質問や意見ならば, その場で自由にぶつけ合う.

    - 粗野な考えを歓迎する (自由奔放)
    誰もが思いつきそうなアイデアよりも,
    奇抜な考え方やユニークで斬新なアイデアを重視する.
    新規性のある発明はたいてい最初は笑いものにされる事が多く,
    そういった提案こそを重視すること.

    - 量を重視する (質より量)
    様々な角度から, 多くのアイデアを出す. 一般的な考え方・アイデアはもちろん,
    一般的でなく新規性のある考え方・アイデアまであらゆる提案を歓迎する.

    - アイディアを結合し発展させる (結合改善)
    別々のアイデアをくっつけたり一部を変化させたりすることで,
    新たなアイデアを生み出していく. 他人の意見に便乗することが推奨される.
** 空・雨・傘

   - 空 (事実)
   - 雨 (解釈)
   - 傘 (行動)

   [[http://blog.livedoor.jp/kimura_nya/archives/30321835.html][「空・雨・傘」の枠組みをいかに利用するか : コンサルティングとファイナンス]]

** MECE
   Mutually Exclusive and Collectively Exhaustive.
   (相互に排他的な項目」による「完全な全体集合」)

   - [[http://ja.wikipedia.org/wiki/MECE][MECE - Wikipedia]]

   情報や分析対象をグループ分けする際に,
   「重複なく・漏れなく」行うべきであるということを示した指針.
   
   - 最低限 2 x 2 のマトリックスで考える
   - 既存の MICE 用フレームワークで考える

** ロジックツリー
   問題の分析や, 課題の整理の結果をツリー構造として表現したものであり,
   目的によって様々な種類がある.

   - 結果-原因 (why)
   - 目的-手段 (how)
   - 全体-部分 (what)

   といった推論を繰り返して論理展開を行う場合,
   その概念・事象間の論理的なつながりをツリー状に図示すること.

   問題解決などに使う場合には, 上位概念から下位概念への分岐を 2~3 程度,
   多くても 5 つぐらいまでにするのがよいとされる.

   - [[http://www.itmedia.co.jp/im/articles/0609/01/news133.html][情報マネジメント用語辞典:ロジックツリー (ろじっくつりー)]]

** MECE とロジックツリーの違い
   MICE は「もれなく, だぶりなく」数え上げるという考え方.
   ロジックツリーは MECE を実行するためのツール (フレームワーク) の一つ.

   - [[http://oshiete.goo.ne.jp/qa/3869287.html][MECE とロジックツリーの違いとは? - 教えて!goo]]
  
** ピラミッドストラクチャ
   結論と根拠を多段に組み立てることによって作られる構造で,
   ドキュメントの骨子全体の構造を表現するものとされる.

*** ロジックツリーとピラミッドストラクチャーの違い
   以下のサイトでロジックツリーとピラミッドストラクチャーの違いが紹介されている.

   [[http://d.hatena.ne.jp/ohshi004/20080803/1217755608][ロジックツリーとピラミッドストラクチャー - Thinking Room で何想ふ. ]]

   - ロジックツリー
   MECE を意識して, 上位概念を下位の概念にトップダウン式に分解していく形式.
   帰納的.

   - ピラミッドストラクチャー
   具体的な情報や観察事項から上位の概念としてのメッセージを
   ボトムアップに抽出していく形式. 演繹的.

*** So What / Why So
    結論と根拠が適切につながっていることを確認するためのテクニック.

    - [[http://logical.tokusen-info.com/sowhat.html][ロジカルシンキング情報館:ロジカルシンキングの基礎技術「 So What?/Why So? 」]]

**** So What?  
    その根拠がどういう結論を導くのか.
    現在持っている情報から導き出せる結論を見つけ出す作業.

    だからなに?
    だから xxx だよ.

**** Why So?
     その結論の根拠が適切か.

     本当にそうなの? 
     ○○だから本当にそうなんだよ

*** 帰納法
    複数の特定の前提から結論を導くロジック展開.
    結論は, 常に推論となる.

    つなぎ言葉をいれることで, 前後の関係をチェック

    - なぜそう判断するかと言えば
    - なぜならば
    - たとえば
    - 具体的には
    
    結論から表現する.

#+begin_src language
私の考えは・・・です. 理由は 3 つあります. 一つめは, xxx です. 2 つめは・・・.
#+end_src

*** 演繹法
    絶対的に正しいことや一般的に正しいと判断されることから,
    妥当と思われる結論を導くロジック展開.
    結論は, 常に正しい.

*** How 構造と Why 構造
    - How 構造
      どのようにすべきか? -> 具体的には・・・

    - Why 構造
      なぜか? -> なぜならば・・・

** なぜなぜ分析
   なぜなぜ分析とは, ある問題とその問題に対する対策に関して,
   その問題を引き起こした要因 (『なぜ』) を提示し,
   さらにその要因を引き起こした要因 (『なぜ』) を提示することを繰り返すことにより,
   その問題への対策の効果を検証する手段.

   - [[http://ja.wikipedia.org/wiki/%E3%81%AA%E3%81%9C%E3%81%AA%E3%81%9C%E5%88%86%E6%9E%90][なぜなぜ分析 - Wikipedia]]

   なぜなぜ分析」は, 重要な問題解決法の 1 つであるが,
   その対象は「なぜ」の問いかけが意味を持つ問題に限られる.

   「なぜなぜ分析」は「原因のある問題」のうち特定化された困った
   問題の原因分析への適用においてのみ効果がある.

   - [[http://www.ltkensyu.com/confidential2.html][どこがマズイ|なぜなぜ分析]]

*** なぜ 5 回

** フレームワーク思考  
   コンサルティングを行う際に広く使うことのできる構造のひな形であり,
   項目は MECE になっているとされる.
   3C や 4P といったものがその具体例として示されることが多い.
   -> ビジネス・フレームワーク

** 特性要因図
   特性要因図は問題の要因を自由な発想で出来るだけ多く提示するもの.

** 分析とは比較, すなわち比べること
*** グラフ分析
    仮説を裏付けるグラフを作成して事実を確認する.
    また, グラフで気づいた部分をメッセージとして書き込む.

**** 代表的なグラフ
     - 棒グラフ
     - 折れ線グラフ
     - 二軸グラフ
     - 円グラフ
     - 帯グラフ

** 結論主導型と理由主導型
   - 結論主導型
     結論 ->(なぜならば) 理由 1, 理由 2, 理由 3  ->(最後にもう一度) 結論

   - 理由主導型
     理由 1, 理由 2, 理由 3 ->(だから) 結論

** 仮説思考となぜなぜ分析の比較

 | 仮説思考           | なぜなぜ分析   |
 | 結論主導型         | 理由主導型     |
 | コンサル業界の手法 | 製造業の手法   |
 | マッキンゼー       | トヨタ         |
 | 演繹的             | 帰納的         |
 | 事実で裏付ける     | 推論で裏付ける |

 - [[http://d.hatena.ne.jp/sekiguchizemi/20061030/p1][トヨタ自動車とマッキンゼー - 関口ゼミのページへようこそ!]]
 - [[http://kamawada.com/~masanori/blog/2007/06/it_3.html][問題解決型か仮説検証型か - 働きたくなる IT (4) (mark-wada blog)]]

** ゼロベース思考
** ポジティブ思考


* 課題設定
** 課題とは
   課題とは, 問題を解決するために, 行動を起こすことを意志表明したもの.
   問題は, 主体的に解決する意志を持って行動を起こすことによって解決に向かう.

   - [[http://www.recruit-ms.co.jp/issue/feature/kaihatsu/200702/01.html][今月の特集 |人材育成のリクルートマネジメントソリューションズ]]

   「すべての原因に対し, あらゆる手を打とう」と考えるのは間違いです.
   どこを攻めるのが効果的か, つまり攻めどころを見極めなくてはいけません

   - [[http://kantokushi.or.jp/lsp/no672/672_02.html][7.  問題を課題化し, さらに取り組み課題へと具体化する]]

   仮説を設定し, 検証した結果, 発見した解決の鍵が課題.(by とみおかたけし)

*** 問題と課題の関係
    問題を課題に落とし込まないと解決できない.
    課題とは, 問題を解決するために何をすべきか, ということを設定したもの.

   - [[http://blogs.itmedia.co.jp/tani/2012/11/post-f0b6.html][「問題」と「課題」の違い・その 2:谷誠之の 「カラスは白いかもしれない」]]
     
   - 課題とは, 能動的なものです. "あるべき姿"を思い描いて, 現実をそこに向かって変えていくためのポイント
   - 問題とは, 意識的にであれ無意識であれ)"期待していた状況"と, 現実の状況のギャップ

*** 仮説と課題の関係
    仮説を証明すると, 課題になる.
    問題の原因が事実で裏付けされたものが, 課題.
    問題の原因を, 行動の意思表明によってポジティブに表現したもの.

** 課題の表現方法
   課題の表現方法としては, 問題提起型や行動ベースの表し方があります.

   - A 社の攻勢に対抗するには」 (問題提起型)
   - A 社への対抗手段を講じる」 (行動ベース) 

   - [[http://kantokushi.or.jp/lsp/no672/672_02.html][7.  問題を課題化し, さらに取り組み課題へと具体化する]]

* 解決策
  MECE とロジックツリーで解決策を考える.
  解決策の方向性でロジックツリーを展開する.

** 課題と解決策の関係
   行動を具体的に表すことが必要です.
   取り組み課題を解決策ともいう.

* Links
#+BEGIN_HTML
<iframe src="//www.slideshare.net/slideshow/embed_code/6908366" width="427" height="356" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC; border-width:1px; margin-bottom:5px; max-width: 100%;" allowfullscreen> </iframe> <div style="margin-bottom:5px"> <strong> <a href="https://www.slideshare.net/KeitaENOMOTO/ss-6908366" title="『イシューからはじめよ』サマリ" target="_blank">『イシューからはじめよ』サマリ</a> </strong> from <strong><a href="http://www.slideshare.net/KeitaENOMOTO" target="_blank">Keita Enomoto</a></strong> </div>
#+END_HTML

* Books
  -『問題解決プロフェッショナル「思考と技術」』 (齋藤 嘉則, ダイヤモンド社, 1997 年)
  -『経営参謀が明かす論理思考と発想の技術』 (後 正武, プレジデント社, 1998 年)
  -『考える技術・書く技術』 (バーバラ・ミント, グロービスマネジメントインスティテュート, 1999 年)
  -『ロジカル・シンキング』 (照屋華子・岡田恵子, 東洋経済新報社, 2001 年)
  -『マッキンゼー式 世界最強の仕事術』 ( イーサン・ M. ラジエル, 英治出版, 2001 年)
