#+OPTIONS: toc:nil
* DokuWiki
おもに, この DokuWiki の管理についての覚書.

- http://futurismo.biz/dokuwiki/doku.php
- http://futurismo.biz/archives/2500

ウォード・カンニガムがプログラムに関する,パターンを記述して閲覧するた
めにはじめたのが起源. WikiWikiWeb というパターンブラウザ.

** ブログと wiki の根本的な違い
ブログと wiki の根本的な違いは, 以下.

  - ブログは情報を日付で管理するシステム
  - wiki はページ名で情報を管理するシステム

* メンテナンス
** アップグレード
  サイトをアップグレードするためプラグインを利用する.
  - [[https://www.dokuwiki.org/ja:install:upgrade][ja:install:upgrade]]

** 記事のアップロード
*** org-wk で org 形式から dokuwiki 形式に変換
   - [[https://github.com/w-vi/ox-wk.el][w-vi/ox-wk.el]]   

   #+begin_src sh
#!/bin/sh
DIR=`pwd`
FILES=""

for i in $@; do
    FILES="$FILES \"$i\""
done

emacs -Q --batch \
    --eval "(progn
     (add-to-list 'load-path (expand-file-name \"~/.emacs.d/el-get/repo/org-mode/lisp/\"))
     (add-to-list 'load-path (expand-file-name \"~/.emacs.d/el-get/repo/ox-wk/\"))
     (require 'org) (require 'ox-wk)
     (mapc (lambda (file)
            (find-file (expand-file-name file \"$DIR\"))
            (org-wk-export-to-wiki)
            (kill-buffer)) '($FILES)))" 2>&1
   #+end_src

*** ncftpput でアップロード

#+begin_src sh
$ ncftpput -R lolipop ./wordpress/dokuwiki/data pages
#+end_src

** ディレクトリ構造の整理
   一旦すべてを削除したあとに, 再度アップロードする. 暫定対処.

* プラグイン
  - [[https://www.dokuwiki.org/ja:plugins][ja:plugins]]
    プラグインマネージャーを利用する.(bundle).

  - [[https://www.dokuwiki.org/ja:plugin:plugin][ja:plugin:plugin]]

** Indexmenu
   名前空間にもとづいて, メニュー作成.
   これで, トップページの目次を作成する.

* SEO 対策

  - [[https://www.dokuwiki.org/ja:seo][ja:seo]]
  - [[http://en.seowiki.info/best_practices/seo_optimized_dokuwiki][SEO Optimized DokuWiki]]

** SEO Tips
   SEO につよい設定方法は以下にある.これはすごい.

  - [[http://en.seowiki.info/best_practices/seo_optimized_dokuwiki/basic_configuration][SEO Optimized DokuWiki: Basic Configuration]]

  簡単なメモ.

    - URL 上の名前空間の区切りにスラッシュを使用 -> On
      - ページのランクをさらに高める?
    - canonical URL (正準 URL) を使用 -> On
    - 文書が存在しないページに"HTTP404/Page Not Found"を使用 -> On
   
** Google にインデックスの許可
   管理者メニュー > サイト設定から

   - rel="nofollow"を付加 -> Off に
   - インデックスを許可 (何秒後) -> 0 に
     - [[http://hain.jp/index.php/tech-j/2007/11/12/p191][dokuwiki が検索エンジンに載りにくい理由 - ぎじゅっやさん]]

** Google ウェブマスターツール
   default では, サイトマップが作成されないので設定する.

   - [[https://www.dokuwiki.org/ja:sitemap][ja:sitemap ]]

   管理者メニュー > サイト設定から
   - Google サイトマップ作成頻度 (日数)  -> 1

   これで, サイトマップが作成されるようになった. doku.php?do=sitemap に
   アクセスすると, サイトマップが取得できる.

   Google ウェブマスターツールにサイトを登録して, サイトマップの URL で
   doku.php?do=sitemap を指定して, 登録完了.

   - https://www.google.com/webmasters/tools/home?hl=ja

** Google Analytics for DokuWiki
   Google Analytics でアクセス解析.
  
    - [[http://en.seowiki.info/best_practices/seo_optimized_dokuwiki/integration/google_analytics][SEO Optimized DokuWiki: Google Analytics Integration]]

    まずは, Google Analytics でトラッキング ID 取得.

*** DokuWiki の設定 
    以下のコードをテーマのテンプレートの main.php の中の <body>タグ直後に挿入.
    
#+begin_src php
    <script>
  (function (i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function (){
  (i[r].q=i[r].q||[]).push (arguments)},i[r].l=1*new Date ();a=s.createElement (o),
  m=s.getElementsByTagName (o) [0];a.async=1;a.src=g;m.parentNode.insertBefore (a,m)
  }) (window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga ('create', 'UA-16438908-13', 'auto');
  ga ('send', 'pageview');

</script>
#+end_src

  analyticstracking.php というファイルにまとめて, 以下のように書いてもいい.

#+begin_src php
<?php include_once ("analyticstracking.php") ?>
#+end_src


