#+BLOG: English Hacks
#+POSTID: 133
#+DATE: [2017-01-08 日 19:04]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+CATEGORY: 本
#+TAGS:
#+DESCRIPTION: やりぬく力(GRIT)を読んだ
#+TITLE:  やり抜く力(GRIT)を TOEIC に活かすには？

* はじめに
  やり抜く力(GRIT)を読んだ。

#+begin_html
<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//rcm-fe.amazon-adsystem.com/e/cm?lt1=_blank&bc1=000000&IS2=1&bg1=FFFFFF&fc1=000000&lc1=0000FF&t=fox10225fox-22&o=9&p=8&l=as4&m=amazon&f=ifr&ref=as_ss_li_til&asins=4478064806&linkId=d85961d87067cb409479a8f969665a93"></iframe>
#+end_html

　著者の TED 動画もネット上に上がっているので、まずはこれを見るのが良い。
  - [[https://www.ted.com/talks/angela_lee_duckworth_grit_the_power_of_passion_and_perseverance?language=ja][アンジェラ・リー・ダックワース 「成功のカギは、やり抜く力」 | TED Talk | TED.com]] 

* 内容
** グリットとはなにか
   グリットとは、「情熱」と「粘り強さ」をあわせた言葉だ。

#+begin_quote
どんな分野であれ、大きな成功を収めた人たちには断固たる強い決意があり、それがふたつの形となって表れていた。第一に、このような模範となる人たちは、並外れて粘り強く、努力家だった。第二に、自分がなにを求めているのかをよく理解していた。決意だけでなく、方向性も定まっていたということだ。
このように、みごとに結果を出した人たちの特徴は、「情熱」と「粘り強さ」をあわせ持っていることだった。つまり、「グリット」（やり抜く力）が強かったのだ。
#+end_quote

** 才能や IQ は成功に関係ない
本書には、将来成功するかどうかは、生まれ持った才能や IQ よりも、情熱と粘り強さによってきまる可能性が高いと書かれている。それは、数々のインタビューや調査から明らかになったことだ。

** 努力が大事
 努力が大事だ。努力しなければ、才能があっても宝の持ち腐れだ。

 やり抜く力と言うのは、一つの重要な目標に向かって、長年の努力を続けることだ。

 知能のレベルは最高でなくても、最大限の粘り強さを発揮して努力する人は、
 知能のレベルが最高に高くてもあまり粘り強く努力しない人より、遥かに偉大な功績を収める。

** どうすればやり抜く力を強くできるか
  4 ステップで示されている。

*** 興味
    自分のやっていることを心から楽しんでこそ「情熱」が生まれる。

    ほとんどの人は、これだと思うものが見つかるまでに何年もかかっており、
    その間、さまざまなことに興味をもって挑戦してきたことがわかった。
    今は、寝ても覚めても、そのことばかり考えてしまうほど夢中になっていることも、
    最初からこれが自分の天職だと悟っていたわけではなかった。

    一生をかけてやりたいものが見つかるまでには、かなりの時間がかかった場合が多い。

    興味は、内省によって発見するものでなく、外との世界との交流するなかで生まれる。

    打ち込みたいものがみつからず、毎日何時間も努力する覚悟ができていないうちは、
    興味を持ったことをひたすら楽しんで、どんどん興味が湧くようにしたほうがよい。

*** 練習
    「粘り強さ」の一つの表れは、
    昨日よりも上手になるように、と日々の努力を怠らないこと。
    
    一つの分野に深く興味を持ったら、わき目もふらずに打ち込んで、
    自分のスキルを上回る目標を設定してそれをクリアする練習に励む必要がある。

    やり抜く力の強い人は普通の人よりも、一つのことにじっくりと取り組むことが、
    多くの研究によってわかっている。

    エキスパートたちは新たなストレッチ目標を設定し、弱点の克服に務める。
    小さな弱点の克服をこつこつと積み重ねていくことが、驚異的な熟練の境地に至る道なのだ。

*** 目的
    自分の仕事は重要だと確信してこそ、「情熱」が実を結ぶ。
    自分のしごとは個人的に面白いだけでなく、
    ほかの人々のためにも役立つと思えることが絶対に必要だ。

*** 希望
    希望は困難に立ち向かうための「粘り強さ」だ。
    最初の一歩を踏み出すときからやり遂げるときまで、ときには困難にぶつかり、
    不安になっても、ひたすら自分の道を歩み続ける姿勢は、計り知れないほど重要だ。

    やり抜く力の強い人は、自分の努力次第で将来はよくなるという信念を持っている。
    
    人間は変われる、成長できる、と信じている人たちは、チャンスと周囲のサポートに
    恵まれ「やればできる」と信じて一生懸命努力すれば、
    自分の能力をもっと伸ばすことは可能だと考える。

    成長思考の人は、努力すればきっとうまくできると信じている。

    成長思考でいると、逆境を楽観的に受け止められるようになり、
    そのおかげで粘り強くなれる。新しいしれんが訪れてもおくせずに立ち向かうため、
    さらなる強さが培われる。

* 本を読んだ理由
  現在、会社を休職している。なぜ、休職してしまったのだろうか？

  それは、やり抜く力が足りなかったからかもしれない。
  難しい課題を克服できず、途中でうつ病になってしまった。
  
  どうすれば、やり抜く力が身につくのだろうか？ その答えを見つけるために、この本を読んだ。
  
* 感想
** グリット・スコア
  自分のグリッド・スコアを算出してみた。グリット・スコアとは、グリットを測る指標だ。
  算出の方法は以下の記事にまとまっている。
  - [[http://www.lifehacker.jp/2016/09/160927book_to_read.html][やってみよう。あなたの「やり抜く力」を 5 段階で測るテスト ｜ ライフハッカー［日本版］]]

  結果は、3.0 平均的な数値がでた。

** IQ テスト
  産業医から、IQ テストをうけるように言われた。
  - [[http://hmi-me.ciao.jp/toeic/archives/84][IQ テスト | English Hacks]]

  IQ テストの結果はまだでていないけれども、悪くても気にしない。
  才能は努力で克服できる、そう信じることが大事なのだと学んだ。

** やり抜く力を鍛える
   自分は、やり抜く力が人並み、いや人並み以下だ。
   やり抜けずに、会社を休職してしまった。

   しかし、この本には、やり抜く力は鍛えることができると書いてある。

   それは、興味、練習、目的、希望をもつことで鍛えられる。

   書き出したことを自分の信念になるまで、なんども読み直そう。
   とくに、成長思考をもち、楽観主義で生きていこう。

* これからどうするか
  さて、TOEIC の話である。
  TOEIC900 を目標にしている。どうやって、900 取得までやり抜く力を出すか？

  今まで書き出したことを当てはめて考えてみよう。

** 希望
  TOEIC に興味を持つ。常に TOEIC のことを頭にいれて生きる。
  それは、StudyPlus のタイムラインをしょっちゅうチェックすることによって、
  実現できる気がする。みんな、TOEIC を頑張っている。自分も負けてられない。

** 練習
  練習する。弱点を冷静に分析して、反復練習によって弱点を潰していく。
  自分の場合は、Part5 に時間がかかりすぎて、Part7 を読む時間がなくなることだ。
  まずは、目の前の弱点を潰す努力をしよう。

** 目的
  目的をもつ。TOEIC 自体を目的にしない。
  TOEIC で培った英語力を元に、英語を自由に扱えるソフトウエア開発者になる。
  そのことを忘れない。
  
** 希望
  希望をもつ。毎日自分は進歩している。
  たとえ、スランプに落ち込んでいようとも、楽観主義でいること。

  努力は裏切らない。しかし、効果的な努力が必要だ。
  本書でいうところの意図的な練習が必要だ。

  意図的な練習を通じて TOEIC における自分の弱点を潰す。
