#+BLOG: Futurismo
#+POSTID: 4649
#+DATE: [2015-08-24 月 00:47]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+CATEGORY: Clojure, 日記
#+TAGS:
#+DESCRIPTION: Clojureの思想はカッコいい
#+TITLE: シンプルさが前に進む力となる Clojure

最近、Clojureに惹かれる. なぜだろうか？ 以下、ポエム.

* 自分にはプログラミングの思想があるのだろうか？
  自分がをプログラミングをするとき、よりどころとなる思想がない。

  別に、思想なんかなくたって、プログラミングはできる. 
  でも、どこか、虚しい。それは、人生の意味と同じだ.

  つらいときも、苦しいときも、よりどころとなる思想があれば、
  立ち向かっていけるような気がする.
  どんなにつらい境遇にいようとも、たちどころに力がみなぎってくる.
  言葉には、そういう力があると信じている.

  そんな、力がみなぎる思想が自分のプログラミングにも欲しいのだ.

* プログラミング Clojure
  プログラミング Clojureの 文章に心を打たれた.

  - Clojureはエレガントだ。
  - Clojureは「Lisp・リローデッド」だ。
  - Clojureは関数型言語だ。
  - Clojureは並行プログラミングを簡単にする。
  - ClojureはJavaを歓迎する。
  - Clojureは速い。

#+begin_src text
Clojureのあらゆる要素は、次の2つの概念から導かれる --- 簡潔さと力だ
#+end_src
    
  カッコいいと思った. それは、理屈なく、感覚的にだ.
  この憧れの気持ちを大切にしよう. こういう気持ちが、熱意になるんだ.

* 簡潔さと力
  小さいこと、一つずつのステップが大きなことへとつながっていくこと.
  そのような、考え方が好きだ. 

  それは、以前, 以下の文章にまとめた.
  - [[http://futurismo.biz/archives/2101][ストレスフリーの境地、だからGTDとTDDが好きだ | Futurismo]]

  この文書にも感銘を受けた.
  - [[http://postd.cc/why-im-productive-in-clojure/][Clojureだと生産性が上がるわけ | プログラミング | POSTD]]

  シンプルさが前に進む力となる.  Clojureの思想は、魅力的だ.
  Clojureには、TDDやGTDに似たような魅力を感じている.

  簡潔さと力、これを自分の拠り所にしようと思った.

  小さく、一つずつ シンプルな関数を積み上げていく. 
  それはやがて、大きな構造をなす. 
  全体は大きく、しかし秩序だっていて、シンプルにまとまっている. 
  そんな、世界をClojureはみさせてくれるのだろうか？
