#+OPTIONS: toc:nil
* Literature: 文学
  文学について
* ドイツ文学
** ファウスト    ゲーテ  高橋義孝訳
*** 
    ファウスト
    いやはや, これまで哲学も, 法律学も, 医学も, むだとは知りつつ神学まで, 営々辛苦, 究めつくした. その結果がどうだといえば, 昔にくらべて少しも利口になってはおらぬ.
    なるほど己は, そこらの医者や学者, 三百代言, 坊主などという, いい気な手合いよりは賢いし, 要らざる迷い, 疑いも知らず, 地獄や悪魔も怖いとは思わぬが, その代わりに, 生きる楽しみというものが全くなくなってしまった.  なんと, 己はまだこの牢獄の中に屈まっているのか. 呪わしい陰気な, この壁穴の中に. これがお前の世界だが, これでも世界といえようか.
    お前はこんなところにいて, なぜ胸が息苦しいと訊ねたりするのだ. なぜ不可解な苦痛が, お前の生命の動きを阻むのかと訊ねるのだ. 神が人間を創って, 人間の居場所と定めたもうたあの活き活きとした自然のかわりに, すすやカビだらけのこの部屋でお前はただ人や動物の骸骨にかしずかれているのだ. 逃げ出せ, さあ, 広やかな精霊の世界へ. お前はそのような世界へ行かれるはずだ. 自然の教えを受けたならば, 魂の力が目覚めてきて, 精霊どもの交わす言葉もわかろうというものだ. こんなところに座り込んでいたのでは, この書の神聖な記号が解けるはずのものではない.

*** 
    メフィゥトーフェレス
    いかがです, 弁舌巧みに快楽と行為を勧めるじゃありませんか. 心身とも
    に腐らせる孤独の境涯を去って, 広い世界へおでなさいと. どうです, わ
    たしを家来にしてごらんなさい. 仰せのままになんでも致しましょう.

    ファウスト
    その代わり己はなにをすればいいのだ.

    メフィストーフェレス
    この世ではあなたにお仕え申しますが, あの世でお会いしたら, 今度はあ
    なたが私の家来になる, というのではいかがです.

    ファウスト
    あの世のことは己にはどうでもいい. 己の喜びが湧き出るのは, この世の
    この大地からだ. 己の苦しみを照らすのは, この世のこの太陽なのだ. 己
    が死んでしまったそのあとのことは, どうであろうと一向に構わぬ.

    メフィストテーレス
    そういうお考えなら, どうです, 手を打ちませんか. あなたがこの世にあ
    る限りは, わたしの術でたんとおもしろい目を見せて差し上げます.

    ファウスト
    君になにが見せられることやら.
    すでに久しく己は一切の知識に吐き気を催しているのだ. 官能の深みで, この燃える情熱の炎を静まらせてくれ. 見通すことのできない魔法の垂幕の向こうに, 奇跡という奇跡をすぐに用意しておいてくれ. 「時」のざわめきの中へ, 事件の動きの中へ飛び込んでゆこうではないか. そして苦痛と快楽, 成功と不満が代わりがわりやってくるがいい, 己は一向に驚きはしない. 休みなく活動するのが男というものだ.
    己がある刹那に向かって, 「とまれ, お前は本当に美しい」といったら, 己はお前に存分に料理されていい. 己は喜んで滅んで行く. そうしたら葬式の鐘がなるがいい. そのときは君の奉公も終わるのだ. 時計が停まり, 針も落ちるがいい. 己のすべては終わるのだ.
    快楽などが問題ではない. めくるめくような想いがしてみたいのだ. 死なんばかりの快楽, 恋から出た憎しみ, 胸のすくような立腹など. 知識欲とは縁を切った己の胸は, 今後どんな苦痛をも避けぬつもりだ. 己は自分の心で, 全人類に課せられたものをじっくりと味わってみたい. 自分の精神で, 最高最深のものをつかんでみたい. そして己の心を人類の心にまで拡大し, 最後には人類同様, 己も滅んで行こうと思うのだ.

*** 
    マルガレーテ
    「あなた, 神を信じていらっしゃらないの」

    ファウスト
    「神の名を唱えて, 自分は神を信ずると, 告白できるものがいるだろうか. 心に神を感じていながら, 自分は神を信じないなどと, はたして言いきれるものであろうか. すべてを包む者, すべてを保つ者, その神は君をも私をも, 自分自身をも包み支えているのではあるまいか. 大空は大きな円天上を作っているし, 大地は足の下にしっかりと横たわっていて, 優しいまなざしで星星が, 永遠にさしのぼってくる. 君と眼と眼を見合わせていると, すべてが君の頭, 君の心におしせまってきて, 君の傍らでは, すべてが見ゆるが如く見えざるが如くに, 永遠の神秘のうちに動き働いているではないか. その気分で君の胸をいくらでも膨らませるがいいのだ. そうして君がその気持ちに浸りきって, もう何もいうことがなかったならば, その気持ちをなんとでも呼べばいいのだ, 幸福とも, まごころとも, 愛とも, 神ともね. それをなんと呼んでいいか, 私にはわからない. 気持ちが一番大切なんだ. 名など, 天の炎を霧のように包み隠す空虚な響き, 煙のようなものに過ぎない. この世に生を受けたものはみな, どこにいてもそういうことを言うはずだ, 各人各様の言葉遣いで. だから私だって同じことを私の流儀でいっているに過ぎないのだ.

*** 
    ファウスト
    己は幾百万の民に土地を拓いてやる. 安全とはいえないが, 働いて自由な生活の送れる土地なのだ. 野は緑して, よく肥えて, 人も家畜も, すぐに新開地に心地よく, 大胆で勤勉な民が盛り上げた頼もしい丘の周りに平等に移り住むだろう. 潮が力ずくで土地を噛み削ろうとしても, 万人が力を合わせて急いで穴をふさぐだろう. そうだ, 己はこういう精神にこの身を捧げているのだ. それは叡智の, 最高の結論だが,
    「日々に自由と生活とを闘い取らねばならぬ者こそ, 自由と生活とをうくるに値する」.
    そしてこの土地ではそんな風に, 危険に取り囲まれて, 子供も大人も老人も, まめやかな歳月を送る迎えるのだ. 己はそういう人の群れを見たい, 己は自由な土地の上に, 自由な民とともに生きたい. そういう瞬間に向かって, 己は呼びかけたい,
    「とまれ, お前はいかにも美しい」
    と. 己の地上の生活の痕跡は, 幾世を経ても滅びるということがないだろう, そういう無上の幸福を想像して, 今, 己はこの最高の刹那を味わうのだ.

*** 
    #+begin_src text
   すべて移ろい行くものは,
  永遠なるものの比喩にすぎず.
  かつて満たされざりしもの,
  今ここに満たさる.
  名状すべからざるもの,
  ここに遂げられたり.
  永遠にして女性的なるもの,
  われらを引きて昇らしむ.
    #+end_src

** トニオ・クレエゲル  トーマス・マン  岩波文庫 
   ところで恋というものは, 彼に多くの苦痛と災厄と屈辱とを招くに決まっていること, その上平和を乱して, 心にさまざまな旋律を溢れさせるから, あることをまとめ上げて, ゆっくりとその中から完全なものを作り出すだけの余裕がなくなってしまうことを知っていたけれど, そのくせやはりお喜びで恋を迎え入れて, すっかりそれに身を委ねながら, 心情の力をつくしてそれをはぐくんでいった. なぜといえば, 彼は恋が人を豊かに元気にすることを知っていたし, またゆっくりと完全なものを創り上げる代わりに, 豊かな元気な心持でいたいと切望したからである.

   彼が地上で最も崇高だと思った力, それに仕えるのを天職だと感じた力, 彼に尊厳と栄誉とを約束した力, つまり, 微笑しつつ無意識な無言の人生に君臨している, 精神と言語との力に, 彼はまったく身をゆだねた. ところが, 彼の見たものはこれだった・・・滑稽と悲惨, 滑稽と悲惨

   官能に対する嫌悪と憎悪とが, そして純潔と端正な平和とに向かっての渇望が彼を襲った. 同時に彼は芸術の空気を・・・ひそやかな生みの喜びの中で, すべてが萌え, かもされ, 芽生えてゆく不断の春の, なまあたたかい, 甘い, 芳香に満ちた空気を呼吸していた. だから結局, 彼はふらふらと, 激しい極端から極端へ, 氷のような精神偏重から, 身を蝕むような官能灼熱へ, 投げやられてはまた投げ返されながら, 良心の呵責のもとに, 精根の尽きるような生活を, 典型的な放恣な異常な, 自分でも心のそこではいやでたまらない生活を送るほかなかった.

   本当にぼくは, 人間的なことに参与しないで, 人間的なことを表現するのが, 往々死ぬほどいやになるのですよ. ・・・芸術家というものは, そもそも男でしょうか. それは「女」にきくがいい.

   感情という涙のヴェールを貫いてまでも, 透視し認識し記憶し観察して, しかもその観察したものを, 手と手がもつれ合い, 唇と唇とが触れ合う瞬間, 人間の目が感覚にくらまされて見えなくなる瞬間に及んで, 微笑しながら片寄せてしまわなければならない・・・これはふとどきなことです, リザベタさん, けしからんことです. 憤慨すべきことです・・・しかし憤慨したところで, なんの役に立つのでしょう.

   精神と芸術とに, 永遠の対立として向かい合っている「人生」は, 決して血なまぐさい偉大さいさとか, 荒々しい美とかいう幻影として・・・つまり異常なものとして, われわれ異常な者たちの目に映じているのではありませんよ. ただ尋常な端正な快適なものこそは, われわれの情景の国土であり, 誘惑的に平凡な姿をした人生なのです. 最後の最も深い心酔が, 洗練された奇矯な悪魔的なものである人, 無邪気な単純な溌剌としたものへの憧憬や, いささかの友情, 献身, 親睦, 人間的幸福への憧憬・・・そういう憧憬を知らない人は, 芸術家とはいわれないのですよ.

   ある奇跡を, ある妖幻な証明の魔術を, 現前に眺めるような気がした. 海峡の方へ向かって, ガラス扉と露台がついていて, 薄い白妙の幕で, 今と寝室に仕切られている彼の部屋は, 薄いろの壁紙と軽い白っぽい家具とがあるので, いつも晴れやかな心地よい趣を呈していた. ところが今, 彼のねぼけまなこは, その部屋がこの世ならぬ浄化と光燿のうちに, すぐ前に横たわっているのを見た. えもいわれぬ優しい匂やかなばら色の光が, 隅から隅まで満ち渡って, 壁と家具を金で染めた上, 妙の戸張を柔らかく赤く燃えたたせている.

   〓我は寝ねまし, されど汝は踊らでやまず」. この文句の語る憂鬱で北国的な, 誠実で不器用な感覚の重苦しさを, 彼はじつによく知っている. 眠るのだ・・・動くとか踊るとかいう義務なしに, 甘く物憂くそれ自身の中に安らいでいる感情・・・まったくその感情のみに生きられるようになりたい, と憧れるのだ. ・・・しかもそれでいて, 踊らずにはいられないのだ. 敏活に自若として, 芸術という難儀な難儀な, そして危険な白羽踊りを演ぜずにはいられないのだ・・・恋をしながら踊らずにいられぬという, その屈辱的な矛盾を, 一度もすっかり忘れきることなしに・・・

   自分が今の自分になるまでに至った年月を通じていったいなにがあったのであろう・・・凝結だ. 荒涼だ. 氷だ. そうして精神だ. そうして芸術なのだ・・・.
   彼は着物をぬいで寝床に入って, 灯りを消した. 彼にとっては, 本来の根源的な恋と悩みと幸福との様式を, 生活を, 素朴で誠実な感情を, 故郷を意味するものである. 彼はあの頃から今日までの歳月を省みた. おのれの経てきた官能と精神と思想との, すさみ果てた冒険を思い起こした. 溌剌と精神とに蝕まれ, 認識に荒らされ, しびらされ, 創造の熱と悪寒とに半ば摩滅され, 頼るところもなく, 良心に苛まれつつ, 森厳と情欲という激しい両極端の間を, あっちこっちへ投げ飛ばされ, 冷ややかな, わざとえり抜いた高揚のために, 過激にされ貧しくされたあげく, 乱れてすさみきって責めぬかれて, 痛み衰えてしまった自分の姿を眺めた・・・そして悔恨と郷愁とにむせび泣いた.

   あなたはかつて僕を名づけて, 俗人, 道に迷った俗人と呼ばれたことを, 覚えていますか?
   世の中には凡庸性の法悦に対する憧憬を, ほかのいかなる憧憬よりも, さらに甘くさらに味わいがいがあるように感ずるほど, それほど本源的で運命的な芸術生活があるのです.
   僕は偉大な悪魔的な美の道で, 冒険を試みながら, 「人間〓を軽蔑する, あの誇らかな冷静な人々を賛美します. しかし彼らをうらやましいとは思いません.

* ロシア文学
* ドストエフスキー
** 悪霊    江川卓    新潮文庫
  そこなる山辺に, おびただしき豚の群れ, 飼われありしかば, 悪霊ども, その豚に入ることを許せと願えり. イエス許したもう. 悪霊ども, 人より出でて豚に入り足れば, その群れ, 崖より湖に駆け下りて溺る. 牧者ども, 起こりしことを見るや, 逃げ行きて町にも村にも告げたり. 人々, 起こりしことを見んとて, 出でてイエスのもとに来たり, 悪霊の離れし人の衣服をつけ, 心もたしかにて, イエスの足元に座しおるを見て懼れあえリ. 悪霊に憑かれる人の癒えしさまを見し者, これを彼らに告げたり. (ルカ福音書, 第八章三十二-三十六節)

*** キリーロフ
  二つの偏見が自殺を思いとどまらせてますね. 一つは小さなことで, 痛いことです. 二種類の人があって, 非常な悲しみや憎しみから自殺する人たち, でなければ気が違うとか, いや, なんでも同じだけれど・・・要するに, 突然自殺する人たちがいます. この人たちは苦痛のことはあまり考えないで, 突然です. ところが思慮を持ってやる人たち, この人たちはたくさん考えますね.

  「第二の原因は, 大きいほうは, あの世です. 自由というのは, 生きていても生きていなくても同じになるとき, はじめて得られるのです. これがすべての目的です. 人間が死を恐れるのは, 生を愛するからでそれが自然の命ずるところでもあるという考え, そこにいっさいの欺瞞のもとがあるんだよ! 生は苦痛です. 生は恐怖です, だから人間は不幸なんです. いまは苦痛と恐怖ばかりですよ. いま人間が生を愛するのは, 苦痛と恐怖を愛するからなんです. そういうふうに作られてもいる. いまは生が, 苦痛や恐怖の代償に与えられている, ここにいっさいの欺瞞のもとがあるわけです. 今の人間はまだ人間じゃない. 幸福で, 誇り高い新しい人間が出てきますよ. 生きていても, 生きていなくても, どうでもいい人間, それが新しい人間なんです. 苦痛と恐怖に打ち勝つものが, みずから神になる, あの神はいなくなる.

  神はいないが, 神はいるんです. 石に痛みはないが, 石からの恐怖には痛みがある. 神は死の恐怖の痛みですよ. 痛みと恐怖に打ち勝つものが, みずから神になる. そのとき新しい生が, 新しい人間が, 新しいいっさいが生まれる・・・そのとき歴史が二つの部分に分けられる・・・ゴリラから神の絶滅までと, 神の絶滅から地球と, 人間の肉体的な変化までです. 世界も変わるし, 事物も, 思想も, 感情のすべても変わる. どうです, そのときは人間も肉体的に変化するでしょう?
  「生きていても, 生きていなくても同じだということになったら, みんな自殺してしまうだろうし, それが変化ということになりますかね」
  それはどうでもいい. 欺瞞が殺されるんです. 最高の自由を望むものは, 誰も自分を殺す勇気を持たなくちゃならない. そして自分を殺す勇気のあるものは, 欺瞞の秘密を見破ったものです. その先には自由がない. ここにいっさいがあって, その先には何もないんです. あえて自分を殺しえるものが神です. いまや, 神をなくし, 何もなくなるようにすることは誰にもできるはずです. ところが, 誰もまだ一度としてそれをしたものがない
  「自殺者は何百万人となくいましたよ」
  ところが, いつもそのためにではない. いつだって恐怖を感じながらで, その目的のためではなかった. 恐怖を殺すためではなかった. 恐怖を殺すためだけに自殺するものが, たちまち神になるのです.

  いや, 未来の永遠のじゃなくて, この地上の永遠のせいですよ. そういう瞬間がある. その瞬間まで行き着くと, 突然時間が静止して, 永遠になるのです. 全人類が幸福に達すれば, 時はもはやなくたってしまいますよ, その必要がないんだから. じつに正しい考えです.

  
  人間が不幸なのは, 自分が幸福であることを知らないから, それだけです. いっさいなんです! 知るものはただちに幸福になる. 赤ん坊の頭をぐしゃぐしゃに叩き潰すものがいても, やっぱりすばらしい. 叩きつぶさないものも, やっぱりすばらしい. すべてがすばらしい, すべてがです. すべてがすばらしいことを知るものには, すばらしい. もしみなが, すばらしいことを知るようになれば, すばらしくなるのだけれど, すばらしいことを知らないうちは, ひとつもすばらしくないでしょうよ. ぼくの考えはこれですべてです, これだけ, ほかには何もありません. 人間がよくないのは, 自分たちがいい人間であることを知らないからです. それを知れば, 女の子に暴行を加えたりはしない. 人間は自分がいい人間であることを知る必要がある. そうすればすべての人が, ひとり残らず, 即座にいい人間になる.

  ある瞬間がある, ・・・そのときだしぬけに, 完全に自分のものとなった永久調和の訪れが実感されるのだよ. これは地上のものじゃない. と言って, なにも天上のものだというのじゃなくて, 地上の姿のままの人間には耐え切れないという意味なんだ. 肉体的に変化するか, でなければ死んでしまうしかない. これは明晰で, 争う余地のない感覚なんだ. 神は, 天地の創造に当たって, その創造の一日が終わるごとに, 『然り, そは正し, そは善し』と言った. これは・・・これは感激というのではなくて, なんというか, おのずからなる喜びなんだね人は何を赦すこともしない, というのはもう赦すべきものが何もないからだ. 人は愛するのでもない, おお・・・それはもう愛以上だ! 何より恐ろしいのは, それがすさまじいばかり明晰で, すばらしい喜びであることなんだ. もし五秒以上つづいたら・・・魂がもちきれなくなくて, 消滅しなければならないだろう. この五秒間にぼくは一つの生を生きるんだ. この五秒間のためなら, ぼくは全人生を投げ出しても惜しくはない, それだけの値打ちがあるんだよ. 十秒間持ちこたえるためには, 肉体的な変化が必要だ.

  いや, だれにしても, それなりの快適さを求めているわけで, それだけのことさ. いや, うまい言葉だ, 快適さでいい. 神は必要だから, 存在するはずだ. ところがぼくは, 神は存在しなし, 存在しえないことを知っている. きみにはわからないかな, 人間はそんな二種の思想をもちながら生きていけないことが? きみにはわからないのかな, これ一つだけでも自殺に値するということが? 何十億というきみたちのような人の中に, それを望まない, それに耐えられない人間が一人, 一人だけは存在することが分からないのかな

  もし神がいないとしたら, ぼくが神だ. [(ピョートル) そこですね, きみの説でどうしてもぼくにわからないのは, なぜきみが神なんです?] もし神があるとすれば, すべての意志は神のもので, ぼくはその意志から抜け出せない. もしないとすれば, すべての意志はぼくのもので, 僕は我意を主張する義務がある. [我意? でも, どうして義務なんです?] なぜなら, すべての意志がぼくの意志になったから. この地上に, 神を滅ぼして我意を信じ, 最も完全なる点まで我意を主張する人間は一人もいないではないか. ぼくには自殺の義務がある. なぜなら, ぼくの我意の頂点は, 自分で自分を殺すことだから. ぼくは自分の不信を宣言する義務がある. 僕にとって, 神がないという思想以上に高いものはない. 人類の歴史がぼくに味方している. 人間がしてきたことといえば, 自分を殺さず生きていけるように, 神を考え出すことに尽きた. これまでの世界史はそれだけのことだった. ぼく一人が, 世界史上はじめて神を考え出そうとしない. 永遠に記憶にとどめるがいい. [誰が記憶にとどめるのですね?] 誰もが記憶にとどめるのだ. 誰もが知るのだ. 顕るるためならで, 隠るるものなし. これはあの人の言葉だ. [すると, きみはまだあの人を信じていて, 燈明なんぞもともしているんですか. 《万一に備えて》とちがいますか?

  いいかね, この人は地上における最高の人間で, この大地の存在の目的をなすほどの人物だった. 全地球が, その上のいっさいを含めて, この人なしには, 狂気そのもでしかないほどだった. 後にも先にも, これほどの人物はついに現れなかったし, 奇跡とも言えるほどだった. このような人がそれまでにも現れなかったし, 今後も現れないだろうという点が, 奇跡だったのだ. ところで, もしそうなら, つまり自然の法則がこの人にさえ憐れみをかけず, 自身の生み出した奇跡をさえいつくしむことなく, この人をも虚偽の上に, 愚かな嘲笑の上にこそ成り立っているとするなら, 当然, 全地球が虚偽であって, 虚偽の上に, 愚かな嘲笑の上にこそ成り立っているということになる. つまりは, この地球上の法則そのものが虚偽であり, 悪魔の茶番劇だということになる. 何のために生きるのか, きみが人間であるなら, 答えてみたまえ [それは問題の局面がちがう. 君は二つの原因を混同しているように思うし, それは心もとない話ですよ. でも, 失礼だが, きみが神であるとしたら? 虚偽が終わりを告げて, もしきみが, いっさいの虚偽の根源は古き神の存在にあることを悟ったとしたら?]

  とうとうきみにもわかったな! してみれば, きみのような男にもわかる以上, これは理解可能なわけだ! さあ, これでわかったろう, 万人にとっての唯一の救いは一つ・・この思想を万人に証明すること鬼こそあることが. 誰が証明する? ぼくだ! どうしてこれまでの無神論者が, 神はいないことを知りながら, 同時に自分を殺さないでこれたのか, ぼくにはわからない. 神がいないことを知りながら, 同時に自分が神になったことを意識しないのは・・・不条理そのものだし, でなければ, かならず自分で自分を殺すはずだ. もし意識すれば・・・きみは皇帝でもはや自分を殺すどころか, 最大の栄光のうちに生きればよい. しかし一人は, つまり最初の一人は, どうあっても自分で自分を殺して見せなければならない. でなければ, だれがそれをはじめ, それを証明するんだ. ぼくがどうあっても自分で自分を殺すのは, それをはじめ, それを証明するためなんだ. ぼくがまだ余儀なくされた神にすぎないから, ぼくは不幸だ. なぜって, 我意を宣言する義務があるからだ. 万人が不幸であり, 貧しくあったのは, 彼らがすべて我意の頂点を宣言するのを恐れているからだ. 人間がこれまで不幸であり, 貧しくあったのは, 我意の最頂点を宣言することを恐れて, 小学生のように, 隅っこの方でちょっぴり我意を張っていたからだ. ぼくは恐ろしく不幸だよ, なぜなら, 恐ろしくおそれているから. 恐怖は人間の呪いなんだ・・・しかし, ぼくは我意を宣言するぞ, ぼくには, 自分が信仰をもっていないことを信ずる義務があるのだ. ぼくは自分ではじめ, 自分で結末をつけ, 扉を開いてやるのだ. そして救ってやるのだ. このことだけがすべての人を救い, 次の世代を肉体的に生まれ変わらすことができる方法なんだ. なぜって, ぼくの考えだと, いまの肉体の有様では人間は古い神なしにはとてもやっていけないからね. ぼくは三年間自分の神の属性を探し求めて, それを発見した. ぼくの神の属性は・・・我意だよ! これこそ, ぼくの不服従と新しい恐ろしい自由をその頂点において示すことのできるすべてなんだ. なぜって, この自由はじつに恐ろしいものだからね. ぼくが自殺するのは, ぼくの不服従と新しい恐ろしい自由を示そうためなんだ. (下巻 533P)

*** ピョートル・ヴェルホーヴェンスキー
  人類を二つの不均等な部分に分割することを提案しているのです. その十分の一が個人の自由と他の十分の九に対する無制限の権利を獲得する. で, 他の十分の九は人格を失って, いわば家畜の群れのようなものになり, 絶対の服従の元で何代かの退化を経たのち, 原始的な天真爛漫さに到達すべきだというのですよ, これはいわば原始の楽園ですな.

  社会の基礎の系統的な震撼, 社会とその全根幹の系統的な解体のためです. すべての人々の自信を喪失させ, 全体を混沌状態に落としこみ, このようにしてぐらつきだし, 病的に無気力化し, 冷笑癖と不信心に取りつかれ, しかも同時になんらかの指導的思想や自己保存を際限もなく貪欲に求めている社会を, 謀反の旗を掲げて一挙に手中に収めてしまうのです. そしてそのよりどころとなるのが, 全国にくまなく広がっている五人組網で, 彼らはこの間にも, たえず行動して, あらたな同志を獲得し, つけいることのできるあらゆる手段, あらゆる弱点を実践的に探求しているのです.

*** ステパン・トロフィーモヴィチ・ヴェルホーヴェンスキー
  私は宣言するものです, シェイクスピアとラファエルは・・・ほとんど全人類より上である, なぜなら彼らはすでにして成果, 全人類の真の成果であり, おそらくは, 存在しうるかぎりの最高の成果だからであります! すでに達成された美の形態, いや, この達成なくしては, 生きることをさえ, おそらく, 私は肯んじえないでありましょう・・・おお, なんたること!
  科学なしで結構, パンなしで結構, ただ一つ, 美なくしてはいかんともしがたい, なぜならばこの世界においてなすべきことが何もなくなってしまうからです! 秘密のいっさいはここに, 歴史のいっさいはここにあります!

  ぼくにとって不死が欠かせないのは, 神が不正を行うのを望まれず, またぼくの胸の中にひとたび燃え上がった神への愛の火をまったく消し去ることを望まれないという理由によるものです. 愛より尊いものがあるでしょうか? 愛は存在よりも高く, 愛は存在の輝ける頂点です. だとしたら, 存在が愛に従わないなどということがありうるでしょうか? もしぼくが神を愛し, 自分の愛に喜びをおぼえているとするなら・・・神がぼくの存在をも, 僕の愛をも消し去って, ぼくらを無に変えてしまうなどということがありうるでしょうか? もし神が存在するとすれば, このぼくも不死なのです.

  おお, ぼくはぜひとももう一度生きたい! 人生の一刻一刻, 一刹那, 一刹那が人間にとって至福のときとならなければいけないのです・・・かならず, かならずそうならなければいけない! そのようにすることが個々人の義務なのです. これは人間の掟です.
  自分自身より限りなく正しく, 勝つ幸福なものが存在しているのだとたえず考えるだけで, ぼくの心はもういいしれない感動と, それから・・・栄光に満たされるのです. おお, このぼくがたとえ何者であろうと, ぼくが何をしようと, それはもうどうでもいい! 人間にとっては自分一個の幸福よりも, この世界のどこかに万人万物のための完成された, 静かな幸福が存在することを知り, 各一瞬ごとにそれを信じることの方が, はるかに必要なこととなのです・・・人間存在の全法則は, 人間が常に限りなく偉大なものの前にひれ伏すことができたという一事につきます. もし人間から限りなく偉大なものを奪い去るなら, 人間は生きることをやめ, 絶望のあまり死んでしまうでしょう. 無限にして永遠なる者は, 人間にとって, 彼らがいまその上に住んでいるこの小さな惑星と同様, かかすべからざるものなのです・・・友よ, すべての, すべての人たちよ, 偉大なる思想万歳! 永遠にして無限なる思想万歳! 人間は, 誰であれ, 偉大なる思想の現れであるものの前にひれ伏す必要があるのです. どんな愚かな人間にも, なんらかの偉大なものが必要です. (下巻 616P)

*** シャートフ
  いかなる国民もいまだかつて科学と理性に基づいて存在したためしはない. ほんの一時期, ばかげた気の迷いでそうなったのをべつにすれば, そんな実例は一度としてなかった. 社会主義はその本質からいってすでに無神論たるべきものである. なぜなら社会主義は, まず開口一番, それが無神論的な制度であって, 科学と理性のみに基づいて存立するものであることを宣言しているからだ. 科学と理性は諸国民の生活においてはつねに, 現在も, また天地開闢以来, 単に第二儀的な, 副次的な役割を果たしてきたに過ぎない. 世界の終結の日までこのことは変わらないだろう. 諸国民を組織し, 動かしているのは, 命令的で支配的な別の力であるが, この力の起源は不明であり, 説明不可能である. この力はあくことなく究極に到達しようとする願望の力であると同時に, この究極を否定する力でもある. これは己の存在を絶え間なく, やむことなく確認し, 死を否定する力である. それは生の精神, 聖書が『生ける水の流れ』と説き, その枯渇を《黙示録》が警告してやまないものである. 哲学者に言わせれば, それは美の原理であり, 哲学者自身が同一視しているように, 同時にそれは道徳の原理でもある.
  私はそれを最も完結に《神の探求》と呼ぶ. 一国民の全運動の目的は, いかなる国民においても, またその国民の存在のいかなる時期においても, 唯一つの神の探求, 自身の神, ぜひとも己自身の神の探求でしかありえないし, またその神を唯一真実のものとして信仰することでしかありえない. 神は, 一国民の起源から終末にいたるまでの全体を代表する総合的人格である. すべての国民, といわぬまでも多くの国民が一つの共通の神を持っていた例はいまだかつてなく, つねにそれぞれの国民が独自の神を持っていた. 神が共通のものになりはじめるのは, その民族の滅亡の前兆である. 神が共通のものとなれば, 神も神への信仰も, その国民自身とともに死滅する. 一国民が協力であればあるほど, その神は独自である. 宗教を持たぬ国民, つまり善悪の観念を持たぬ国民はいまだかつてなかった. あらゆる国民が善悪についてのおのれの観念を持ち, おのれの善悪を持ってきた. 多くの国民の間で善悪の概念が共通のものになりはじめると, 国民は死滅し, 善悪のけじめそのものも崩壊し, 消え去っていく.
  理性はかつて善悪を規定しえたことがないし, たとえ近似的にでも善悪を区別しえたことさえない. それどころか, いつも無様な, 惨めな混同をやってきた. 科学にいたっては, 力ずくの解決しかもたらさなかった. この点で特に際立っているのは反科学であって, 今世紀まではまだ知られていないけれど, これは疫病や飢餓や戦争よりもひどい, 人類に対する最も恐るべき鞭である. 半科学・・・それは今日までまだ現れたことのない専制者である. この専制者は, おのれの神官と奴隷を持ち, すべてのものが, これまで考えられもしなかったような愛と迷信を抱いてその前にひざまずき, 科学そのものさえもその前では震えおののいて, 恥ずかしげもなくそのご機嫌を取り結ぶ.
  
  神を民族の属性に引きおろしたのではない. 反対です. 国民を神にまで引き上げたんです. 国民は神の肉体です. あらゆる国民は, 自身の独自の神を持ち, この世のほかのあらゆる神を妥協なく排除するかぎりにおいてのみ国民なのです. 自身の神によって他のすべての神を征服し, 世界から追放できると信じているかぎりにおいてのみ, 国民なのです. 開闢以来, どの国民もそう信じてきました. すくなくとも大国民, 多少とも名を知られ, 人類の先頭に立った国民はすべてそうでした. もし大国民が, 自分たちだけに (まさしく自分たち一人だけにです) 真理があると信じられないようなら, もし自国民だけが自身の真理によって他国民を蘇生させ, 救済する使命を持つと信じられないようなら, その国民はたちまち人類学上の資料に成り下がって, 大国民ではなくなってしまう. 真の大国民は決して人類における二流の役割に甘んずることはできないし, 一流の役割にさえ甘んじられない. どうあってもかならず第一の役割でなければならないのです. この信念を失ったものは, もはや国民ではない. しかし真理は一つですから, したがって, 諸国民の間でただ一つの国民だけが真実の神を持つことができる. 《神の体得者》である唯一の国民・・・それはロシア国民です, ・・・そして・・・そして・・・スタヴローギン, いったいあなたはぼくをそれほどの馬鹿だと思っているのですか. ・
  
  人しかいなかったところへ, ふいに第三の人間が, 新しい魂が生まれる. 人間の手では決してできないような, 完璧に完成された魂がです. 新しい思想と新しい愛, 恐ろしいみたいだ・・・世界にこれ以上すばらしいものはない!

*** ニコライ・スタヴローギン
  この生涯ですでに何度かあったことであるが, 私は, 極度に不名誉な, 並外れて屈辱的で, 卑劣で, とくに, 滑稽な立場に立たされるたび, きまっていつも, 度外れな怒りと同時に信じられないほどの快感を描き立てられてきた. これは犯罪の瞬間にも, また生命の危険の迫ったときにもそうなのである. 仮に私が何か盗みを働くとしたら, 私はその盗みの瞬間, 自分の卑屈さの底深さを意識することによって, 陶酔を感じることだろう. 私は卑屈さを愛するのではない (この点, 私の理性は完全に全きものとしてあった), ではなくて, その下劣さを苦しいほど意識する陶酔感が私にはたまらなかったのである. 同様に, 決闘の場に立って, 相手の発射を待ち受ける瞬間にも, 私はいつもそれと同じ恥辱的な, 矢も立てもたまらぬ感覚を味わっていた.
  こんなことを書くのは, この感情がいまだかつて私を全的に征服しつくしたことがなく, 常に意識が全きままに残っていたことを, みなに知ってもらいたいためである. (しかし, すべてが意識の上にこそ成り立っていたのだ). そして, ときに分別を失うほどまで, いや, というより, 滅茶苦茶なほどにその感情に支配されることはあったが, 我を忘れるということは一度もなかった. それが私の内部で火そのもののようになっていっても, 私は同時にそれを完全に支配することができたし, その絶頂でおしとどめることさえできた. もっとも, 自分から抑えようと思ったことは一度もない. 私は生まれつき獣的な情欲を授けられ, またつねにそれを掻き立ててきはしたが, 一生涯, 修道僧のように暮らすこともできただろうと確信している. 私は, その気になれば, つねに自分の主人であった. だから, 知ってほしいのだが, 私は環境とか病気のせいにして, わたしの犯罪の責任を逃れようとは思わないのである.

  ちょうどそのころ, 決して理由のあることではないのだが, なんとかして自分の人生を滅茶苦茶にしてやりたい, それもできるかぎり醜悪に, という考えが浮かんだ. あるとき, アパートで女中代わりのようなこともしていたびっこのマリヤ・チモフェーヴナ・レビャートキナを見ているうちに, 私はふいに彼女と結婚しようと決心した. スタヴローギンがこのような最低の女と結婚するという思いつきが, 私の神経をくすぐった. これ以上醜悪なことは考えつけもしなかった. 15:39 2007/04/15

** カラマーゾフの兄弟  米川正夫訳  
   ヨハネ伝第十二章二十四節
   誠に実に爾曹に告げん, 一粒の麦もし地に落ちて死なずばただ一つにてあらん. もし死なば多くの実を結ぶべし

*** イヴァン・フョードロヴィチ・カラマーゾフ
    地球上には人間同士の愛を強いるようなものは決してない. 人類を愛すべしという法則はぜんぜん存在していない. もしこれまで地上に愛があったとすれば, それは, 自然の法則によるものでなく, 人間が自己の不滅を信じていたからだ. 人類から自己の不滅に対する信仰を滅したならば, 人類の愛がただちに枯死してしまうのみならず, この世の生活を続けていくために必要な, あらゆる生命力をなくしてしまう. そればかりか, そのときは非道徳的なものはすこしもなくなって, すべてのことが許される. おまけに, こんにちのわれわれのように, 神も不死も信じない各個人にとって, 自然の道徳律はたちまちにして, これまでの宗教的なものとぜんぜん正反対になり, 悪行といいうるほどの利己主義が人間に許されるのみならず, かえってそういう状態において避けることのできない, もっとも合理的な, いわば最も高尚な帰結として認められざるをえない.

*** イヴァン 
    「よしんばぼくが人生に信を失い, 愛する女に失望し, ものの秩序というのをほんとうにすることができなくなったあげく, いっさいのものは混沌として呪われたる悪魔の世界だと確信して, 人間の幻滅の恐ろしさをことごとく味わい尽くしたとしても・・・それでも, ぼくは生きて生きたい. いったんこの杯に口をあてた以上, それを征服しつくしたあとでなければ, 決して口を放しゃしない! 三十まではぼくの青春が, いっさいのものを征服しつくすにちがいない, 生にたいする嫌悪の念も, いっさいの幻滅もね. ぼくはよく心の中で, 自分の持っている狂暴な, ほとんど無作法といっていいくらいな生活を征服しうる絶望が世界の中にあるかしらん, とこう自問自答するのだ.

    ぼくは生活したい, だから, 論理に逆らっても生活するだけの話だ. たとえものの秩序を信じないとしても, ぼくにとっては春芽を出したばかりの, 粘っこい若葉が尊いのだ. るり色の空が尊いのだ. そうして, 今ではとうから意義を失っているけれど, 古い習慣のため感情のみで尊重しているような, ある種の功名が尊いのだ.
    ぼくが涙を流すのは, 絶望のためじゃない, ただ自分の流した涙で幸福を感ずるために過ぎない. つまり, 自分で自分の感動に酔おうと言うのだ. ぼくはねばっこい春の若葉やるり色の空を愛するのだ, それだけのことなんだ! ここには, 知識も論理もない, ただ内発的な愛があるばかりだ, 自分の若々しい力に対する愛があるばかりだ」.
    アリョーシャ「地上に住むすべての人は, まず第一に生を愛さなければならないと思いますよ」.
    イヴァン「生の意義以上に生そのものを愛するんだね? 」
    アリョーシャ「むろん, そうでなくっちゃなりません. あなたのおっしゃるように論理以前にまず愛するんです. ぜひとも論理以前にですよ. そこでこそはじめて意義もわかってゆきます.

    十八世紀ごろにある年とった無心論者が, 「もし神がいなかったらつくり出す必要がある」といったね. ところが, はたして人間は神というものを考え出した. しかし, 神が本当にいるということが不思議じゃなくって, そんな考えが・・・神は必要なりという考えが, 人間みたいに野蛮で意地悪な動物の頭に浮かんだ, ということが驚嘆に値するのだ. それくらいこの考えは神聖で, 感動的で, 懸命で, 人間の名誉をなすべきものなんだ. ぼく一個に関しては, 人間が神を創ったのか, 神が人間を創ったのかということはもう考えまいと, だいぶ前から決心しているのさ. ところで, ぼくたちどんな問題を論じたらいいと思う! ほかでもない, すこしも早くぼくの本質を明らかにすることだ. つまり, ぼくがどんな人間で, なにを信じなにを望んでいるかを明らかにすればいいのだ, ね, そうじゃないか? だから, こう明言しておく・・・ぼくは直接に, 簡単に神を承認する. 神はありやなしや? なんてことは決して考えないほうがいいよ. 自白するが, ぼくにはこんな問題を解釈する能力が一つもない, 地上的のものだ, それだのに, 現世外の事物を解釈するなんてことが, どうしてぼくらにできるものかね. ぼくは神を承認する, 単に喜んで承認するばかりでなく, その英知をも目的をも承認する (もっとも, われわれには皆目わからないがね) それから, 人生の秩序も意義も信じるし, われわれをいつか統合してくれるとかいう永久の調和をも信じる. それから, 宇宙の努力の目標であり, かつ神とともにあるところの道, また同時に神自身であるところの道も信じるよ. つまり, まあ, 永遠というやつを信じるよ. ・・・おい? ところが, どうだい, ぎりぎり決着のところ, ぼくはこの神の世界を承認しないのだ. 何も神を承認しないといってるんじゃないよ, いいかい. ぼくは神のつくった世界, 神の世界を承認しないのだ. どうしても甘んじて承認するわけにゆかないのだ. ちょっと断っておくが, ぼくはこどものように, こういうことを信じてるんだ, ・・・いつかずっと先になったら, 苦痛も癒され償われ, 人生の矛盾の忌々しい喜劇もあわれな蜃気楼として, 弱く小さいもののいとわしいつくりごととして, 人間のユウクリッド的知性の一分子として消えてしまい, 世界の終局においては, 永遠な調和の瞬間に, 一種たとえようのないような高貴な現実が出現して, それがすべての人々の胸に満ち渡り, すべての人の不平を満たし, すべての人の悪行や, 彼らが互いに流しあった血潮をあがない, 人間界に生じたいっさいの事を単に許すばかりでなく, 進んで弁護するにたるほど十分であるというのだ. しかし, 僕はこれを許容することができないのだ. 許容することを欲しないのだ! これがぼくのテーゼなんだ.

    ねえ, 隠遁者君, この地上においては, ばかなことが必要すぎるくらいなんだ. 世界はばかなことを足場にして立ってるので, それがなかったら世の中には何事もおこりゃしなかったろうよ. われわれは知ってるだけのことしか知らないんだ! 今となってぼくは, 何ひとつ理解しようとも思わない. 僕は事実にとどまるつもりだ. ぼくはずっと前から理解すまいと決心したのだ. なにか理解しようと思うと, すぐに事実を曲げたくなるから, それで僕は事実にとどまろうと決心したのだ.
    罪びとがいなくて, すべては直接に簡単に事件から事件を生んでいく, という事実がぼくにとってなんになる? またこの事実を知ってるからって, それがそもそもなんになる? ぼくには応報が必要なのだ. でなければ, ぼくは自滅してしまう. しかも, その応報もいつか無限の中のどこかで与えられる, というのではいやだ. ちゃんとこの地上で, ぼくの目の前で行われなくちゃいやだ. ぼくは自分で見たいのだ. ぼくのいないところでそんなことをするなんて, あんまりしゃくにさわるじゃないか. 実際, ぼくが苦しんだのは, 何も自分自身の身体や, 自分の悪行や, 自分の苦痛を肥やしにして, どこの馬の骨だかわからないやつの未来のハーモニイを培ってやるためじゃないんだからね. つまり, みなのものがいっさいの事情を知るときに, ぼくもその場にいあわせたいのだ. 地上におけるすべての宗教は, この希望の上に立てられているのだ. しかし, ぼくは信仰する.

*** 大審問官
    人間や人間社会にとって自由ほどたえがたいものはないのだ! そうとも, われわれがいなかったら, 彼らは永久に食をうることができないのだ! 彼らが自由でいるあいだは, いかなる科学でも彼らにパンを与えることはできないのだ! しかし, とどのつまり, 彼らは自分の自由をわれわれの足元に捧げて, 「私どもを奴隷にしてくだすってもよろしいから, どうぞ食べ物をくださいませ」というに違いない. つまり, 自由とパンとはいかなる人間にとっても両立しがたいものであることを, 彼ら自身が悟るのだ. 実際どんなことがあっても, 彼らは自分たちの間でうまく分配することができないに決まっているからな! で, 最後に彼らは, 自由になるのを恐ろしいと感じ始めるに違いない! さあ, 荒野における第一の問いはこういう意味を持っているのだ. そのほか, この問題の中には, 現世の大秘密が含まれている. それは「なんびとを崇拝すべきか? 」という疑問なのだ. 自由になった人間にとって最も苦しい, しかもたえまのない問題は, すこしも早く自分の崇拝すべき人を捜し出すことである. しかし, 人間というものは間違いなく崇拝に値するものを求めている. このあわれな生物の心配は, めいめい勝手な崇拝の対象を求めるばかりでなく, 万人が信仰してその跪くようなものを捜し出すことにある. つまり, どうしてもすべての人と一緒でなければ承知しないのだ. この共通な崇拝の要求が, この世の始まりから, 各個人および全人類の主な苦悶となっている. 崇拝の共通のために, 彼らは互いに剣を持って殺しあった. 彼らは神をつくりだして, 互いに招き合っている. つまり, 「お前たちの神を捨てて, われわれの神を奉じないか. そうしないと, お前たちもお前たちの神も命が危ないぞ! 」というのだ. これは世界の終わるまでこのとおりだ.
    われわれの仲間はおまえでなくて, きゃつ (悪魔) なのだ, これがわれわれの秘密なのだ. われわれはもうずっと前から, もう八百年の前におまえを捨てて, きゃつと一緒になっているのだ. ちょうど八世紀以前, われわれはきゃつの手から, おまえが憤然と退けたものを取ったのだ. われわれは彼の手からローマとケーザルの剣を取って, われわれのみが地上における唯一の王者だと宣言した. おまえは地上の人類が求めているいっさいのものを満たすことができたのだ. ほかでもない, 崇拝すべき人と, 良心を託すべき人と, すべての人間が世界中に一致してあり塚のように結合する方法である. 世界的結合の要求は, 人間が第三にしてかつ最後の苦悶だからである. 全体としての人類は, 常に世界的に結合しようと努力している.

    おれの考えでは何も破壊する必要はない. ただ人類の中に存在する神の観念さえ破壊すればいいのだ. まずこれから仕事にかからなけりゃならない! まずこれからはじめなけりゃならないのだ, ・・・ああ, なんにもわからないめくらめ! いったん人類がひとり残らず神を否定してしまえば, そのときは, 以前の世界観, ことに以前の道徳が, 食人肉主義をまたなくとも自然に滅びて, 新しいものが起こって来る. 人間は, 生活の提供しうるすべてをとるために集まるだろう. しかし, それはただ現在, この世における幸福と喜びのためなんだ. 人間は神聖な巨人的倨傲の精神によって偉大かされそこに人神が出現する, 人間は意志と科学とによって, 際限もなく, 刻一刻と, 自然を征服しながら, それによって, 天上の喜びに対するそれまでの強い希求に変わりうるほどの, 高遠なる快楽を不断に感じるようになる. すべての人間は, 自分が完全に死すべきもので, 復活しないことを知っているが, しかも神のように傲然として, ゆうゆう死につく. 彼はその自尊心のために, 人生が瞬間にすぎないことをうらむべきでないと悟って, なんの報いも期せずに, 自分の同胞を愛する. 愛は生の瞬間に満足を与えるのみだが, 愛が瞬間的であるという意識は, かえって愛の炎をますますさかんならしめる.
    しかし, 人類の無知が深く根を下ろしているから, ことによったら, 千年かかってもうまくゆかないかもしれない. だから, 今この真理を認めたものは, だれでもその新しい主義の上へ, 勝手に自分の基礎を立てることができる. この意味において, 人間は「何をしてもかまわない」わけだ. それに, もしこの時代がいつまでも来なくたって, どうせ神も霊魂の不死もないんだから, 新しい人はこの世にたった一人きりであろうとも, 人神になることができる. そして, 人神という新しき位についた以上, 必要な場合には, 以前の奴隷人の道徳的限界を平気で飛び越えても, さしつかえないはずだ. 神のためには法律はない! 神の立つところは, すなわち神の場所だ! おのれの立つところは, ただちに第一の場所となる・・・「何をしてもかまわない」それっきりだ! これははなはだけっこうなことだよ. だが, もし詐欺をしようと思うくらいなら, なぜそのために, 真理の裁可を要するのだろう? それは, 真理の裁可なしに詐欺一つする勇気もない, それほどロシア人は真理を愛しているのだ・・・

*** ゾシマ長老
    人生は楽園です. ぼくたちはみんな楽園にいるのです. ただぼくたちはそれを知ろうとしないだけなんです. もしそれを知る気にさえなったら, 明日にもこの地上に楽園が現出するのです. いったいぼくはどんな値打ちがあって, あなたがたに愛していただけれるのでしょう. 何のためにあなたがたはぼくみたいな人間を愛してくださるのでしょう? そして, ぼくはなぜ今までそれに気がつかなかったのでしょう? なぜありがたいと思わなかったのでしょう? ねえ, お母さん, まったくどんな人でもすべての人に対して, すべてのことについて罪があるのです. まったくぼくたちは今までこの世に暮らしていながら, どうしてこれに気がつかないで, 腹を立てたりなんかしたのでしょう?

    全世界を改造しようというのは, 人間自身が心理的に新しい道へ転じなければなりません. 人間がすべての人に対して本当に兄弟同様にならないうちは, 世界同胞の実現されるはずがありません. まず最初に人間の孤独時代というものを閉ざされねばなりません. しかし, この時代はまだなかなか閉ざされません. まだ終わるべき時期が来ないのです. 今すべての人はできるだけ自分を切り離そうと務め, 自分自身の中に生の充実を味わおうと欲しています. ところで, 彼のあらゆる努力の結果はどうかというと生の充実どころか, まるで自殺に等しい状態が襲うてくるのです. なぜというに, 彼らは自分の本質を十分に究めようとして, かえって極度な孤独に陥っているからです. 現代の人はすべて個々の分子に別れてしまって, だれもかれも自分の穴に隠れてしまいます. だれもかれもおたがいに遠く隔てて, 姿を隠しあっています. 持ち物を隠しあっています. そして, 結局自分で自分を他人から切り離し, 自分で自分から他人を切り離すのがおちです. なぜというに, われひとりを頼むことになれて, 一個の分子として全を離れ, 他の扶助も人間も人類も, 何者も信じないように, おのれの心に教え込んで, ただただおのれの金やおのれの獲得した権利を失いはせぬかと, 戦々兢々としているからです. 真の背活の保障は決してここの人間の努力でなく, 人類全体の結合に存するものですが, 今どこの国でも人間の理性はこの事実を一笑に付して, 理解しまいとする傾向を示しています. しかし, この恐ろしい孤独もそのうちに終わりを告げて, すべての人が互いに乖離するということが, いかに不自然であるかを理解する, そういった時期が必ず到来するに違いありません. たといただひとりであろうとも, 自ら進んで範を示し, 人間の霊魂を孤独の中から, 相互的結合の努力の道へ導いてゆくものが出現するべきはずです.

    余はある「思想のための戦士」を知っている. 人類のために戦うなどといっているのだ. いったいこういう連中がどこへいって, なにをしようというのか? ただ一時的な仕事に向かうくらいのもので, 長く持ちこたえることは到底できない. それゆれ, 彼らが自由の隷属に陥り, 同胞愛想と人類結合に対する奉仕の変わりに乖離と孤独に陥ったのは, あえて怪しむにたらぬ. かようなわけで, 人類に対する奉仕とか, 人間の同胞的団結とかいう思想が, だんだん世の中に隠滅していって, 今ではほとんど冷笑をもって向かえられるようにさえなった. 実際, 自ら案出した無数の欲望を満足させることによってのみなれたとらわれたる人間が, どうして自分の習慣からはなれることができよう, そうして, どこへ行くことができよう. 孤独の中に閉じこもった人間にとって, いったいとして人類などということに何のようがありえようぞ. かくしてついに, 物質を蓄えると同時に喜悦を失う, という結果に到達したのある.

*** ドミトーリイ・フョードロヴィチ・カラマーゾフ
    情欲は嵐だ. いな, 嵐以上だ! 美・・・美というやつは恐ろしいおっかないもんだよ! 美しい心と優れた理性を持った人間までが, 往々マドンナの理想を抱いてその一歩を踏み出しながら, 結局ソドム (悪行) の理想を持って終わるのだ. いや, まだまだ恐ろしいことがある. つまりソドムの理想を心に抱いている人間が, 同時にマドンナの理想をも否定しないで, まるで純潔な青年時代のように, 心底から美しい理想の憧れを心に燃やしていることだ. 大多数の人間にとっては, 全くソドムの中に美が潜んでいるのだ・・・お前はこの秘密を知ってたかい? 美は恐ろしいばかりだなく神秘なのだ. これがおれにはおっかない. いわば悪魔と神の戦いだ, そしてその戦場が人間の心なのだ.

    なぜ人間は貧乏なんだ, なぜ餓鬼は不幸せなんだ, なぜ喜びの歌を歌わないんだ, なぜ暗い不幸のためにこんなに黒くなったんだ. これからはけっして餓鬼が泣かないようにしてやりたい. 今この瞬間から, もう誰の目にも涙のなくなるようにしてやりたい, どんな障害があろうとも, 一分の猶予もなく, カラマーゾフ式の無鉄砲な勢いを持って, 今すぐにもどうかしてやりたい. (するとかれの心臓は燃え立って, なにかしらある光明を目指して進み始めた). 生きたい, どこまでも生きたい, ある道を目指して進みたい, なにかしら招くような新しき光明のほうへ進みたい, 早く, 早く, 今すぐ! おれはあの餓鬼のために行く. なぜなら, われわれはみな, すべての人のため, すべての餓鬼のために責任があるからだ. なぜなら, 小さい子供もあれば, 大きな子供もあるからな. みな餓鬼なんだ. おれはすべての人のために行く.
    ああ, そうだ, われわれは鎖につながれて, 自由がなくなるんだ. しかし, そのとき, われわれはその大きな悲しみの中にいながら, さらに歓喜の中へとよみがえるんだ. 人間この歓喜がなくちゃ, 生きることができない. だから, 神様はあるんだ. なぜって, 神が歓喜の分配者だからだ. 歓喜は神の偉大な特権だからだ・・・ああ, 人間よ, 祈りの中に解けてしまえ!
    それに, いったい苦痛とはなんだ? おれはたとえ数限りない苦痛が来ても, 決して, それを恐れやしない. おれはすべてを征服し, すべての苦痛を征服して, ただいかなる瞬間にも, 「おれは存在する! 」と自分で自分に言いたいんだ. 幾千の苦しみの中にも・・・おれは存在する. 拷問のさいなまれながらも, おれは存在するんだ! そして太陽を見ている. 太陽があるということを知るのは, それがすなわち全生命なんだ. おれはな, 種種様々な哲学で殺されていたんだ. 哲学なんかくそ食らえだ!
    もし神がなかったらどうだろう? 神は人類の持っている人工的観念にすぎないとしたらどうだろう? そのときは, もし神がなければ, 人間は地上の・・・宇宙のかしらだ. えらいもんだ! だが, 人間, 神なしにどうして善行なんかできるだろう? これが問題だ! おれはしじゅうそのことを考えるんだ. なぜって, そうなったら人間はだれを愛するんだね? だれに感謝するんだね?

*** アリョーシャ・フョードロヴィチ・カラマーゾフ
    泣かないでください. この世が楽園です. ぼくたちはみんな楽園に住んでいるのです. ただ, それを知ろうとしないだけなのです.

** 地下室の手記    江川卓訳
     人間があれほど破壊と混沌を愛するのは, 目的を達し, 自分たちが創っている建物を完成するのを, 自身, 本能的に恐れているからではないだろうか?
  もしかしたら, 人類がこの地上において目指しているいっさいの目的もまた, 目的達成のためのこの不断のプロセス, 言い換えれば, 生そのものの中にこそ含まれているのであって, 目的それ自体の中には存在していないのかもしれない. 人間は到達を好むくせに, 完全に行き着いてしまうのは苦手なんだ.

  ひょっとして, 人間が愛するのは, 泰平無事だけではないかもしれないではないか? 人間が苦痛をも同程度の愛することだって, ありうるわけだ. いや人間が時として, 恐ろしいほど苦痛を愛し, 夢中にさえなることがあるのも, 間違いなく事実である. 泰平無事だけを愛するのはむしろ不作法なことにさえ思われる. 善悪は別として, 時には何かを思い切りぶち壊すのも, やはりたいへん愉快なことではないか.
  僕の確信によれば, 人間は真の苦悩, つまり破壊と混沌を決して拒まぬものである. 苦悩こそ, まさしく自意識の第一原因にほかならないのだ.

** 罪と罰    米川正夫訳  新潮文庫 
   (ラスコーリニコフ) 「つまり世の中には, あらゆる不法や犯罪を行いえる人・・・いや, 行いえるどころか, それに対する絶対の権利をもったある種の人が存在して, 彼らのためには法律などないに等しい」.

   (ポルフィーリイ) 「問題はだね, この人の論文によると, あらゆる人間が『凡人』と『非凡人』に分かれるという点なのさ. 凡人は常に服従をこれこととして, 法律を踏み越す権利なんか持っていない. だって, その, 彼らは凡人なんだからね. ところが非凡人は, 特にその非凡人なるがために, あらゆる犯罪を行い, いかなる法律も踏み越す権利を持っている」.

   (ラスコーリニコフ) 「『非凡人』は, ある種の障害を踏み越えることを自己の良心に許す権利を持っている・・といって, つまり公の権利というわけじゃありませんがね. ただし, それは自分の思想・・・ときには全人類のために救世的意義を有する思想の実行が, それを要求する場合のみに限るのです」.

   「人は誰でも, 単に偉人のみならずわずかでも凡俗の軌道を脱した人は, ちょっと何か目新しいことを言うだけの才能に過ぎなくとも, 本来の天性によって必ず犯罪人たらざるを得ないのです. これが僕の結論なんです. でなくては, とても凡俗の軌道を脱することは難しい. が, それかといって, そのまま凡俗の起動に甘んじていることは, やはり本来の天性によってできない相談です」.

   「人は自然の法則によって, 概略二つの範疇に分かれている. つまり自分と同様なものを生殖する以外になんの能力もない, いわばたんなる素材に過ぎない低級種族 (凡人) と, いま一つの真の人間, すなわち自分のサークルの中で新しい言葉を発する天稟なり, 才能なりをもっている人です. 第一の範疇すなわち材料は, 概括的に言って保守的で, 行儀がよく, 服従をこれこととして, 服従的であることを好む人々です. 僕にいわせれば, 彼らは服従的であるべき義務すら持っているのです. なぜなら, それは彼らの使命なのですからね. 第二の範疇はすべてみな, 法律を踏み越す破壊者か, あるいはそれに傾いている人たちです. この種の人間の犯罪の多くは, きわめてさまざまな声明によって, よりよきものの名において, 現存せるものの破壊を要求してきます. で, もし己の思想のために, 死骸や血潮を踏み越えねばならないような場合には, 彼らは自己の内部において, 良心の判断によって, 血潮を踏み越える許可を自ら与えることができると思います. しかし, 群集のほとんどはいつの時代にも彼らにこうした権利を認めないで, 彼らを罰し, 彼らを絞殺してしまいます. そして, その行為によって極めて, 公明正大に, 自分の保守的使命を果たしているのです. が, ただし次の時代になると, この同じ群集が前に罰せられた犯罪人を台座に乗せて, 彼らに跪拝するのです」.

   「凡人が非凡人であると勘違いしたとしても, 僕の意見では, たいした危険はないと思うんです. なぜなら, 彼らは決して, 深入りするようなことはないですからね. 刑罰の執行人も要りません. 彼らは, 自分で自分を鞭で打ちます. 何しろ非常に心がけのいい連中ですからね. お互い同士にその面倒を見合うものもあろうし, 中には自分のてで自分を罰するものもあるでしょう. その上, いろいろち公に悔悟の意を表明するようなこともやるから, 美しくって教訓的な効果がありますよ. ようするに少しも心配はいりません. そういう法則があるんですよ」.

   「良心ある人間なら, 自分の過失を自覚した以上, 自分で勝手に苦しむがいい. これがその男に対する罰ですよ」. 「全体に苦悶と悩みは, 遠大なる自覚と深い心情の持ち主にとって, 常に必然的なものなんだ. 僕思うに, 真の偉大なる人間はこの世において, 大いなる哀愁を感じなければならない」.

   彼のまなざしはかさかさして, しかも燃えるように鋭く, 唇はわなわなと激しく慄えていた・・・突然彼はすばやく漸進をかがめて, 床の上へ身体をつけると, 彼女の足に接吻した. ソ-ニャは愕然として, まるで相手が気ちがいか何ぞのように, 彼から一歩身を引いた. 実際, 彼はまるっきり気ちがいのような目つきをしていた.
   「あなたは何をなさるんです, 何をなさるんです? わたしなんかの前に! 」
   と彼女は真蒼になって呟いた. と, 急に彼女の心臓は痛いほど強く強く締めつけられた. 彼はすぐに立ち上がった.
   「僕はお前に頭を下げたのじゃない. 僕は人類全体の苦痛の前に頭を下げたのだ」. 彼はなんとなく気うとい声でいい, 窓のほうへ離れた.

   「僕はお前の不名誉や, 罪悪に対して, そういったのじゃない, お前の偉大なる苦痛に対して言ったのだ. ところで, お前が偉大なる罪びとだってことは, そりゃその通りだ」. と彼は感動に満ちた調子で言い足した. 「お前が罪びとなわけは何よりも第一に, 役にもたたぬことに自分を殺したからだ, 売ったからだ. これが恐ろしいことでなくて, 何だろう! そうとも, それほど憎んでいるこの泥沼の中に住んでいて, しかも同時に, ちょっと目を開きさえすれば, こんなことをしていたって, 誰を助けることにもならないし, どんな不幸を救うことにもならないのを, 自分でもちゃんと知っているんだもの, これが恐ろしいことでなくて何だろう! それに, 第一ききたいことがある」. と彼はほとんど狂墳に近い様子で言った. 「どうしてそんな汚らわしい賎しいことと, それに正反対な神聖な感情が, ちゃんと両立していられるんだろう? いっそまっさかさまに水の中へ飛び込んで, 一思いに片付けてしまったほうがずっと正しい, 千倍も正しい, 利口なやり方じゃないか! 」

   (ラスコーリニコフ) 「いや, 今まで身投げから彼女を引きとどめていたのは, 罪という観念だ. そしてあの人たちだ・・・もし彼女が今まで気が狂っていないのなら・・・しかし, 彼女の気が狂っていないなんて, そもそもだれがいった? 一体彼女は健全な判断力を持っているだろうか? 」

   (ソーニャ) 「もし, 神様がなかったら, わたしはどうなっていたでしょう? 」
   (ラスコーリニコフ) 「ああ, やっぱりそうだった! 」と彼は考えた. 「で, 神様はその褒美に何をして下さるんだい? 」
   ソーニャは答えかねるように, 長いあいだ黙っていた. その弱々しい胸は興奮のために波打った. 「どうか黙っててください! きかないで下さい! あなたにそんな資格はありません! ・・・」いかつい腹だたしげな眼つきで彼を見据えながら, 彼女は急に叫んだ.
   (ラスコーリニコフ) 「そうだったのだ! そうだったのだ! 」と彼は執念深く心の中で繰り返した.
   (ソーニャ) 「なんでもみんなして下さいます! 」また眼を下へ伏せて, 彼女は早口にささやいた.
   (ラスコーリニコフ) 「これが解決だ! これが解決の説明なんだ! 」「狂信者だ! 狂信者だ! 」

   (ラスコーリニコフ) 「今の僕にはお前という人間があるばかりだ」. 「一緒に行こうじゃないか・・・僕はわざわざお前のところへ来たのだ. 僕らはお互いに呪われた人間なのだ. だから一緒に行こうじゃないか! 」
   (ソーニャ) 「どこへ行くんですの? 」
   (ラスコーリニコフ) 「ぼくがどうし知ってるもんか? ただ同じ道づれだということが, わかっているだけだ. それだけはたしかに知っている・・・ただそれだけなんだ. 目あては一つだ! 」
   「お前もやっぱり, 踏み越えたんだよ・・・踏み越えることができたんだよ. お前は自分で自分に手を下した. お前は一つの生命を滅ぼしたんだ・・・自分の生命を (それはどっちだって同じだからな!) お前は精神と理性で生きていける人間なんだよ, しかし結局センナヤで終わる運命なのだ・・・けれど, お前には持ちきれまい. もし一人きりになったら, 僕と同じように気が狂うだろう. お前はもう今でも気ちがいじみている. してみると, 僕ら二人は一緒に同じ道を行くべきなんだ! 行こうよ! 」「破壊すべきものを一思いに破壊してしまう, それだけのことさ. そして苦痛を一身に背負うのだ! え? わからないのかい? あとでわかるよ・・・自由と権力, 特に権力だ. これが目的だ! これをよく覚えておくがいい! 」

   (ポルフィーリィ) あなたはただ信仰とか神とかを見つけさえすれば, よし腸を引き出されようとも, じっと立ったまま笑みを含んで, 自分を苦しめる連中を眺めている, そういう人間の一人だとおもっています. だから, 早くそれをお見つけなさい. そうすれば生きていかれますよ. なに, 苦痛もいいものですよ, お苦しみなさい.

   (ラスコーリニコフ) 「お前はなんて妙な女だろう. ソーニャ, 僕がこんなことを言ったのに, 抱いて接吻するなんて. お前, 自分でも夢中なんだろう」.
   (ソーニャ) 「いいえ, 今世界中であなたより不幸な人は, 一人もありませんわ! 」
   (ラスコーリニコフ) 「じゃ, お前は僕を見捨てないんだね, ソーニャ」
   (ソーニャ) 「ええ, ええ. いつまでも, どこまでも! 」「わたしはあなたについて行く, どこへでもついて行く! おお, 神様! ああ, わたしは不幸な女です! なぜ, なぜわたしはもっと早く, あなたを知らなかったのでしょう! なぜあなたはもっと早く来てくださらなかったの? おお, 切ない! 」

   彼は急にソーニャの言葉を思い出したのである. 「四つ辻へ行って, みんなにお辞儀をして, 地面へ接吻なさい. だって, あなたは大地に対しても罪を犯しなすったんですもの. そして, 大きな声で世間のみんなに「私は人殺しです! 」とおっしゃい」
   この言葉を思い出すと, 彼は全身をわなわなと振るわせ始めた. この日ごろ, ことにこの四五時間の, 出口もないような悩ましさと不安は, すっかり彼を征服しつくしたので, かれはこの新しい, 充実した渾然たる感情の可能性へ飛び込んでいった. それは一種の発作のように, 突如として彼を襲い, 彼の心の中で一つの火花をなして燃え上がり, たちまち火焔の如く, 彼の全幅をつかんだのである. その刹那, 彼の内部にあるいっさいが時ほぐれて, 涙がはらはらとほとばしり出た. 彼は立っていたままその場も動かず, 地面へどうと打ち倒れた・・・.
  
   彼は広場の真ん中に膝をついて, 土の表に頭をかがめ, 歓喜と幸福をかんじながら, その汚い土に接吻した.

   ソーニャの姿を認めた. 彼女は, ずっと始終, 彼の悲しい歩みに随っていたのである. ラスコーリニコフはこの瞬間, いまこそソーニャが永久に自分を離れることなく, 運命がどこへ彼を導いていこうと, 世界の果てまでも着いてくるに違いないとはっきり直感し, 了解したのである.

   現在においては, 対象もなければ目的もない不安, 未来においては, なにものをも与えない不断の犠牲・・・これがこの世で彼をまっているいっさいである. 何のために生きてゆくのだ? なにを目標に置くのだ? なにに向かって突進するのだ? 存在せんがために生きていくのか? しかし, 彼はもう以前から百篇も千篇も, 思想のため希望のために, いやそれどころか空想のためにすら, 自己の存在を投げ出す覚悟をしていたではないか? たんなる存在そのものは, 彼にとって常に多くの意義をもたなかった.

   彼らが誰も彼も人並みに人生を愛し, かつ尊重しているのに一驚を喫した! 彼らは獄中にいるときのほうが, 自由なときよりも, はるかに人生を愛し, 尊重しているのであった.

   彼は泣いて, 彼女の膝を抱きしめた. はじめの一瞬間, 彼女はその場から躍り上がり, わなわなと震えながら彼を見つめた. けれどすぐその瞬間に, 彼女はなにもかも悟った. 彼女の眼の中には無限の幸福がひらめいた. 彼女は悟った. 男が自分を愛している, しかも限りなく愛しているということは, 彼女にとってもう何の疑いものなかった. ついにこの瞬間が到来したのである・・・.

   彼らは口をきこうと思ったけれど, それができなかった. 二人の目には涙が浮かんでいた. 彼らは二人とも青白くやせていた. しかし, この止み疲れた青白い顔には, 新生活に向かう近き未来の更生, 完全な復活の曙光が, もはや輝いているのであった. 愛が彼らを復活させたのである. 二人の心はお互い同士にとって, 生の絶えざる泉を蔵していた.

   彼は甦った. そして自分でもそれを知っていた. 自分の更生した全存在で, それを完全に感じたのである. そして彼女は・・・彼女はもとよりただ彼の生活のみで生きていたのだ!

* レフ・ニコラエヴィチ・トルストイ
** 人生論    原卓也訳  新潮文庫  
   貧乏人が身につけるすべての知識は, 彼にとってもっぱら, 自分個人の幸福をさらに増すために必要である. 金持ちが身につける科学や芸術のあらゆる知識は, 科学や芸術の意義などという高尚な言辞にもかかわらず, もっぱら退屈をしのいで楽しく時を過ごすためにのみ必要なのである. 他人との闘争は激化し, もっぱら個人の幸福のためのみに生命の習慣 (惰性) が確立されてゆく. 天上の生命の神秘を解くパリ祭のとの教えも, 宇宙や人間の起源を調べて未来の運命について結論を出す学者の教えも, 行為の指針を与えてはくれない. だが, 行為の選択において指針がなければ, 人は生きてゆかれない. ここにいたっては, 否応なしに, もはや判断にではなく, 過去・現在を問わず常にどの人間社会にも存在し続ける外面的な生命の導きに従うのである. この導きはなんら合理的な説明を持っていないけれど, まさにこれこそがあらゆる人間の行為の圧倒的な大部分を動かしているのである. この導きは人間社会の生活の習慣であって, 自己の生命の意味に対する人々の理解が少なければ少ないほど, ますます強力に人々を支配する.

   人々は, こんな残酷で無意味な苦しみに満ちたこの人生から逃れるために自殺する安直なさまざまな方法を誰でも知っているにもかかわらず, 生きているのだ. こんなことがおこる説明はひとつしかない. つまり, 人々はみな心の奥底で, 自分たちの生命の幸福のためにあらゆる苦しみが常に必要であり, 不可欠であることを知っているのであり, だからこそ, 苦しみを予見したり苦しみに遭ったりしながら, 生きつづけているのである.
   あらゆる人が苦しみによって育てられたのであり, 全生命が当人の味わい, 他の存在に加える苦しみの連続なのである. だから, もうそろそろ人間は苦しみになれ, 苦しみにおののかず, なぜ何のために苦しみがあるのかなどと自問しなくてもいいころだという気がする. どんな人でも, ちょっと考えさえすれば, 自分のあらゆる快楽が他の存在の苦しみによってあがなわれているのであり, 自分のあらゆる苦しみは快楽のために不可欠なのであって, 苦しみなしには快楽も存在せず, 苦しみと快楽とは, 一方が他方にとって不可欠な, 二つの相反する状態である, ということに気づくだろう.

** クロイツェル・ソナタ  原卓也  新潮文庫  (1974) 
   われわれの間では, 結婚というものを性行為以外の何物にも見出さずに, 人々は結婚するんです. だから, その結果は, 欺瞞か, 出なければ強制ということになってしまうのです. 夫婦が一生いっしょに暮らすという対世間的な義務を背負い込んでしまい, 二月目からも疑いに憎みあって, 別れたいと望みながら, それでもやはりいっしょに暮らしているということになると, これはまさに互いに殺しあったりするようになるんです. (p22)

   放蕩とは, 真の放蕩とは, 肉体関係を持った女にたいする同義的関係から自己を解放することにほかならないのです.

   私は現代の青少年の九十九パーセントまでがそうであるように, 悶々と悩んでいたのです. 恐怖におののき, 苦しみ, 神に祈りながら, 堕落し続けていたのですからね. 私はすでに創造の世界でも, 現実においても堕落していましたが, 最後の一歩はまだ踏み出していませんでした. 一人で自分を汚してはいましたが, まだ他人の身体に手をかけてはいなかったのです.

   女たちは, この上なく高尚な, われわれのいわゆる詩的な愛とやらが, 精神的な価値によって左右されるわけではなく, 肉体的な親密さや, さらにはヘアスタイルとか, ドレスの色や仕立てでどうにでもなることを, じつによく知っているんです.

   わたしたちは, 肉や野鳥などのあらゆる興奮性の食べ物や飲物をとっていて, これがいったいどこへ行くのでしょう? 性欲の過剰になるのです. この弁を閉じたりすると, とたんに興奮が生じ, それが人工的な生活のプリズムを通って, きわめて純粋な恋や, 時にはプラトニック・ラブとさえなって現れるのです.

   女は男の性欲に働きかけ, 性欲を通して男をすっかり支配してしまうため, 男は形式的に選ぶだけで, 実際に選ぶのは女だ, という結果になっているのです. いったんこの方法を会得すれば, 女はもうそれを悪用し, 男に対する恐ろしい支配を獲得するんですよ. i いたるところに女の支配はありますよ! よく見てください. 人生のあらゆる贅沢品は女性によって要求され, 維持されているんです. 工場の大部分が, 女性のために無益なアクセサリーだの, 馬車だの, 家具だの, 遊び道具だのを作っているのです. 数百万人の人間が, 幾世代にもわたる奴隷として, ただただ女性の気まぐれのために, それらの工場での過酷な労働で身を滅ぼしてゆくのです. 女性はまるで女王のように, 人類の九十パーセントを, 隷属と重労働の中にとりこにしているのです. それもすべて, 女性が辱められ, 男性と対等の権利を奪われてきたためなんですからね. だから女性は, われわれの性欲に働きかけ, われわれを網の中に捕らえることによって, 復讐するのです. そう, すべてはそれが原因ですよ. 女性は自分を, 性欲を刺激する道具に仕立ててしまったため, 男は冷静に女性と応対することができなくなってしまったのです. 女のそばに近づいただけで, 男はその妖気にあたって, ぼうっとなってしまうのです. 私は, 女のドレスを見ると, いつも気づまりな, 薄気味悪い思いを味わっていたものですが, このごろはまったく恐ろしくて, それこそなにか世間にとって危険な, 法に反するものを見るような気がして, 警官を呼びたくなるほどなんです. この危険に対する庇護を求め, 危険物を早く片付け取り除くことを要求したくなるんです. おや, 笑ってらっしゃるのですね!
   いったいどういうわけで, 賭博が禁じられていながら, 女たちが性欲を挑発する, 売春婦のような服装をすることは禁止されないんでしょうか?

   でも, なぜ生きていかなければいけないんですか? 仮に何の目的もなく, 人生のために生命が与えられたのだとしたら, 生きてゆく理由なぞありませんよ. また, 人生に目的があるとしたら, その目的が達成されたときに人生が打ち切らねばならぬことは明らかです.
   仮に, 人類の目的が幸福なり, 善なり, 何なら愛でもかまいませんが, とにかく人類の目的が, 予言にいわれているようなこと, つまり全ての人間が愛によって一つの結びつき, 槍を打ち直して鎌にする, などということ t だとしたら, その目的の達成を妨げているのはなんでしょうね? 妨げるのは, さまざまな欲望ですよ. さまざまな欲望の中で, 一番強烈で, 悪質で, 根強いのは, 性的な肉の愛です. ですから, もしすべての欲望や, 中でも一番強烈な, 最後の, 肉体的愛情まで根絶されるとしたら, 予言は実現され, 人々は一つの結びつき, 人類の目的は達せられるのですから, もはや生きている理由はなくなるでしょう. でも, 人間が生きている間は, 目の前に理想が立ちはだかっているのです. 抑制と純潔によって達成される善の理想なのです. 人々は常にそれを志向してきたのですし, 今も志しているんですよ. しかも, それがどういう結果になるか, 一つ見てください.
   つまり, 性愛が安全弁ということになるんですよ. もし, 現在生きている人類の世代が目的を達成できなかったとすれば, それはもっぱら, さまざまな欲望や, その中でも一番強烈な性欲が存するからに過ぎないのです. 性的な欲が存し, 新しい世代も存するとあれば, したがって, 次の世代に目的を達成する可能性もあるわけです.
   もし, 人間が不滅だとして, 仮に彼らが何千年もの歳月ののちに目的を達成したと仮定すると, そのときには彼らはなんのために存在することになるのでしょう. 人間は, 無制限に子供を増やすべきじゃないんです. つまり, 禁欲を志すべきであって, われわれの生活機構全体が目指しているような性欲の刺激など, 決して思考すべきじゃないんですよ.

   性欲は, たとえどんなに飾り立ててあろうと, やはり悪なのです. これは, われわれの間でやっているように奨励したりせず, あくまでも戦わねばならぬ, 恐ろしい悪ですよ. 情欲を抱いて女を見るものは, すでにその女と姦淫したに等しいという福音書の言葉は, 他人の妻に対してのみ向けられたものではなく, 何よりもまさに, 自分の妻に向けられたにほかならないのです.

   愛とは何か理想的な高尚なものだと理論では考えられているのに, 実際には, 愛とはそれについて語るのも思い出すのもいやらしく, 恥ずかしいくらい, なにかいやらしい下劣なものだ, ということなんです. なにしろ, それがいやらしい恥ずかしいことだという事実を, 自然が作ったのには, それだけの理由があるはずですよ. いやらしい, 恥ずかしいことだとしたら, そのように理解しなけりゃなりません. ところが反対に人々はいやらしい恥ずかしいことが美しい高尚であるようなふりをしているんですからね. わたしの愛の最初の兆候はどんなものだったでしょう? ほかでもありません, 有り余るほどの動物的欲望を私が恥じぬばかりか, むしろなぜかそうした精力のありあまっていることを得意がって, それに浸りきり, しかもその際, 妻の精神生活はおろか, 肉体的な生活さえ考えてやろうとしなかったことなんです.

   できるだけ多くの快感を得ようなんてことにばかり, 心を砕いている始末なんだ. しかも, それが誰かと思いや, 万物の霊長たる人間なんですからね. いいですか, 動物が交尾するのは子孫を作りうる時期に限られています, ところが, 汚らわしい万物の霊長は時を選ばずで, 快感さえ得られりゃいいって始末ですよ. そればかりじゃなく, こんな畜生道を珠玉の創造物にまで, 愛にまで, 高めるのです. そしてこの愛, つまり汚らわしい行為のために, 滅ぼしているのです, 何をか? 人類の半分をですよ. 真理と幸福とを目指す人類の運動において, 本来ならば協力者であるべき全女性を, 男はおのれの快楽のために, 協力者どころか, 敵にしているのです. 人類の進歩の動きにいたるところでブレーキをかけているのが何か, よくごらんになるといい. それは女です.

   女は快楽の道具なんです. 女の身体は快楽の手段なんですよ. 女のほうもそれを承知しています. 女を解放し, 男と対等のあらゆる権利を与えてはいるものの, 依然として女を快楽の道具として眺めていますし, 子供時代からの世論によって女はそう教育されているんです. だから女はいつになっても, 卑しめられ堕落させられた奴隷であり続けるのですし, 男は依然として堕落した奴隷所有者であり続けるのです.
   これを変えうるのは, 男性の女性観や, 女性自身の女性観の変化だけです. これが変わるのは, 女性が純潔の状態を最高の状態とみなすようになるときだけです. この最高の状態が恥や醜態と考えられている現在とは違って, ですね. これがないかぎり, どういう教育が行われようと, あらゆる娘の理想は依然として, 選択の可能性を持つためにできるだけ多くの男性を, できるだけたくさんの牡をひきつけることであり続けるでしょうよ.
   男を篭絡すれば, 女は幸せになり, 望みうるすべてを獲得するんですからね. だから女の最大の仕事は, 男を篭絡するすべを学ぶことなんです. 今までもそうだったし, これからもそうです.

   概して音楽ってのは恐ろしいものですよ. あれはなんなのでしょう? わたしにはわからないんです. 音楽とはいったいなんなのでしょう? 音楽がどんな作用をすると思いますか? なぜ, ああいう作用をするのでしょうね? 音楽は魂を高める作用をするといわれていますが, あれはでたらめです, 嘘ですよ! たしかに音楽は効果を発揮します. しかし, 魂を高めるるなんてものじゃ全然ありませんよ. 魂を高めも低めもせず, 魂をいらだたせる作用があるだけです. 音楽は自分自身を, 自分の真の状態を忘れさせ, 自分の感じ, 理解できないことを理解し, できないこともできるような気がするんですよ. わたしはこれを, 音楽があくびや笑いのような作用をするというふうに, 説明付けているんですがね. つまり, 眠くもないのに, 人があくびをするのを見ると, こっちまであくびをしたり, べつにおかしいこともないのに, 人の笑い声を聞いていると, 自分も笑い出したりするでしょう.
   この音楽ってやつは, それをつくった人間の浸っていた心境に, じかにすぐ私を運んでくれるんですよ. その人間と魂が溶け合い, その人間といっしょに一つの心境から別の心境へ移ってゆくのですが, なぜそうしているのかは, 自分でもわからないのです. たとえばクロイツェル・ソナタにしても, それを作ったベートーヴェンは, なぜ自分がそういう心境にあったかを知っていたわけですし, その心境が彼を一定の行為に駆り立てたのですから, 彼にとってはその心境が意味を持っていたわけですが, こっちにとっては何の意味もないんですよ.
   苛立たしさをかきたてるだけで, しかも苛立たしさに駆られながら, なすべきことがないんですからね. だからこそ音楽は時によるとじつに恐ろしい, 不気味な作用を及ぼすのです.
   クロイツェル・ソナタの導入部のプレストにしても, ですよ. いったい, 肌も顕なデコルテ・ドレスを着た婦人たちの間で, あんなプレストを演奏していいもんでしょうか? 演奏が終われば拍手して, その後アイスクリームを食べながら, 最近の世間話にふけるなんて. ああいう作品を演奏してよいのは, 一定の, 重要な, 有意義な状況の下に限られるので, それも, その音楽によってムードを掻き立てられたエネルギーや情感が, なんらはけ口を見いだせぬまま, 破滅的作用を及ぼさずにはいませんからね. 少なくとも私に対しては, あの作品は恐ろしく効き目がありました. 気のせいか, まるでそれまで知らなかった, まったく新しい情感や, 新しい可能性が開けたかのようでした. ああ, こうでなければいけないんだ, これまで自分が考えたり生活してきたやり方とはまったく違って, まさにこうでなければいけないんだ, と心の中で告げる声があるかのようでした. 私が突き止めたこの新しいものが, いったいなんだったのか, はっきりさせることはできませんでしたけれど, この新しい状態の自覚はきわめて喜ばしいものでした.

   私がおちいったのは, けだものの状態か, さもなければ, 危機に瀕して肉体的な興奮に支配された人間の状態で, そんなときには人間はあせらず正確に, それでいてただの一分たりとも無駄にせず, たえず一つのはっきりした目的だけを抱いて, 行動するものなのです.
   その表情が私に苦しいほどの喜びをもたらしたからです. それは恐怖の表情でした. まさしくそれこそ, 私の求めるものだったのです. 私の姿を見た最初の瞬間, どちらの顔にもあらわれた, あの絶望的な恐怖の表情を, 私は決して忘れないでしょうよ.

   憤りの発作にかられると自分のしていることを覚えていない, なんていう人がいますけれど, あれはでたらめです, 嘘ですよ. 私はすべてを覚えていましたし, 一秒たりと記憶をとだえさせたりしませんでしたからね. 自分の内部の憤りをますます強く煽り立てれば煽り立てるほど, 意識の光がいっそう明るく燃え上がるので, その光の下では自分のしていることのすべてが見えぬはずはないのです. どの瞬間にも私は, 自分が何をしているかを承知していました.
   それはまるで, あとで後悔できるよう・・・あのときに思いとどまることだってできたのだと自分にいうことができるようにするためみたいでした. 自分が何か恐ろしいことを, 今まで一度もしたことのない, そして恐ろしい結果を生むに違いないことをやっているのを, 知っていたのです. しかし, その意識は稲妻のようにちらとひらめいただけで, 意識の後にすぐ行為が続きました. その行為も異常なほど鮮明に意識されたものです.
   あの行為に先立って一瞬, ほんの一瞬だけ, おれはかよわい女を, 自分の妻を殺そうとしている, いや, 殺してしまったのだという恐ろしい意識があったのを, おぼえています.

* フランス文学
** レ・ミゼラブル    清水正和訳  福音館書店  ヴィクトル・ユーゴー
*** はじめに
  法律や慣習によるきびしい社会的制裁が存在する限り, つまり, 神聖であるべき運命を人間がゆがめ, この文明社会の真っただ中に, 宿命的な地獄を作り出しているかぎり, また, 今世紀が抱えている問題, すなわち, 貧困による男の堕落, 飢餓による女の転落, 暗黒におびえる子供たちの不幸, この三つの問題が解決されないかぎり, また, あちらこちらの地方で, 社会的な窒息状態の生じる可能性がある限り・・・要するに, この地上に無知と悲惨が存続する限り, このような性質の書物も決して無益ではないだろう.

*** ミリエル司教
  「人間は肉体を持っているが, それは重課であるとともに誘惑である. 人は肉体を引きずって歩き, その誘惑に負けやすい. それを見張り, できるだけ抑制しなければならない」.
  「無知な人にはできるだけ教えねばならない. 教育を無料にしないのは社会の罪である. 社会は自らのつくった暗黒に責任がある. 魂は闇に包まれ, そこで罪が犯される. 罪人とは, 罪を犯す人でなく, 闇をつくる人なのだ」.
  「あれがあんなに恐ろしいものとは思わなかった. 死は神の手にのみあるものだ. どんな権利があって人間は, この計り知れないものに手を触れるのだろうか」.
  彼は, 苦しみ悩むものの上に, 罪の償いをするもののうえに, 身をかがめた. 彼には, 世界が大きな病気のように思われた. いたるところに熱病を感じ, 痛みを覚えた. しかもその謎を解こうとはせず, 傷に包帯をしようとした. この世に存在するものは, このまれにみる善良な聖職者にとって, なぐさめを求めている永久に悲しいものなのであった.

*** ジャン・ヴァルジャン
  労働者である私が, 働きたくても仕事がなく, パンにもありつけなかったというのは, 重大なことではないのか? 次に, 盗みの罪はあるにしても, 受けた刑罰はあまりにもひどすぎるのではないか? 犯した罪以上の法律の濫用があったのではないか? さらに, 脱獄未遂で次々と刑期が延長されて十九年になったのも, 強者の弱者に対する暴行ではないのか? これは個人に対する社会の虐待という犯罪ではないか? いったい, 人間の社会にそんな権利があるのだろうか?
  人生とは戦いであり, 自分はその戦いに敗れたのだ, と思い込むのであった. 彼にはもはや, 憎しみだけが武器だった. それを徒刑場で鋭く磨き, 出獄のときにたずさえていこうと決意していた.

  「この握りこぶしをみてください. 襟首をつかんで離さないように見えるでしょう. そう, こういうこぶしがもう一つあるんです. 良心というこぶしが. 私は良心に服従する懲役人なんです.

  海より大きい眺めがある. それは空である. その空よりももっと大きな眺めがある. それは人間の心の内部である. 複雑で, 神秘で, 無限のものをもつ人間の心, 幻想と欲望と誘惑が絡み合い, 夢想のるつぼであり, 恥ずかしい想念の巣窟であり, さまざまな情念の戦場である人間の心, その内部を, 奥底をのぞき見ることは, 感動と戦慄なしでは済まされない. これ以上恐ろしいものはない.

  立派な人間は, 天頂に星がきらめくときに, みずからの精神に火をともすのだ.

  それは恐ろしい試練だった. 弱いものを下劣にし, 強いものを優れた人間に鍛え上げる, 運命のるつぼとも言うべき試練だった. 人生における不幸とか, 孤独とか, 貧困とかは, 人間を悲惨に突き落とす一方, 英雄を生み出す戦場である. そのような無名の英雄の方が, 世に知られ栄誉に包まれた英雄よりも偉大なことがある.

  人間のどんな社会にも, 劇場で「奈落」とよんでいるどん底がある. 人間の社会を鉱山にたとえると, そこには二つの層がある. 上方の層, それは, 宗教の坑道, 哲学の坑道, 政治・経済の坑道, 革命の坑道, といったものが縦横に走っている層であるが, 今いっているどん底, 奈落のそこは, それらの坑道からさらに下の層, つまり光の届かぬ闇だけの穴蔵, 地獄としかいえない層のことである.
  そこにうごめく不気味な人影, それは, ほとんど獣にも幽霊にも等しい姿である. 思想も言葉もない. ましてや, 世の中の進歩などにはまったくの無関心, 無関係である. 彼らの考えることといえば, ただ自分の欲望を満たすことだけである. 彼らには二人の母がいるが, どちらも邪険きわまる母である. つまり, 無知と貧困という母である.
  そこには貪欲だけが支配している. 飢えと渇きが出発点であり, 悪魔になることが到達点である. 人間はみな同じである. 同じ土から生まれたものである. 少なくともこの世での宿命には, なんの差別もない. つまり, 前世では同じ闇, 現世では同じ肉体, 来世では同じ灰である. しかし人間をつくっているねり粉に無知が混じると黒くなる. その黒さが内部にまで達すると, 「悪」となる.

#+begin_src text
彼, ここに眠る. 数奇なる運命に耐え,
彼は生きた. 天命を失うや, 彼は死んだ.
万物の流転のごとく,
昼が去り, 夜の来るごとく.
#+end_src

  「ユゴーの『レ・ミゼラブル』を今読んでいるところだ. いろんな感情のみずみずしさを忘れないようにするためには, こうした書物を再読するのがいいことだと思う. とりわけ人間性への愛とか, それから, より高いところにあるなにか, 要するにかの高みにあるものへの誠実とそれについての意識といった感情だ. こうした書物は人の心を熱くする. ミレーの作品と同じようにこの作品は激した心とよばれるものによって書かれている」. (ファン・ゴッホ)

* ロマン・ロラン
** ジャン・クリストフ 
この現実, 唯一の現実, 死のそばに持ってきたとき, いっさいのものはなんというとるに足らぬものであることか. そこにたどり着くためには, あれほどたくさんに苦しみ, あこがれ, もがく必要があったのか・・・・・.

  クリストフはどんなにか死のそば近くまで行っていたことか. 卑怯にも自分の苦しさから免れようがために, 生命を絶とうという誘惑に負けかねていたではないか.
  クリストフは人生が休戦のない, 情け容赦を知らぬひとつの戦いであり, そこでは人間の名に値する人間でありたいと思うものは絶え間なく, 目に見えない敵の軍勢, つまりは自然のもつ破壊的なもろもろの力, 人をまどわす数々の欲望, 陰険にも知らぬまに人間を堕落させ, 滅ぼしてしまう, とらえどころのない秘められた思想などを向こうに回して戦わなくてはならぬことを悟った. 幸福や恋は一時のごまかしで, 心の武装を解かせ, 降伏させるためのものであることを悟った.

「行け, 行け. 決して休むことなく」
「でも, 主よ, 私はどこに行ったらよいでしょうか. なにをしても, どこにいっても, 行きつく先はいつでも同じであり, 最後は, そこに見えるあれではありませんか」
「行け, そして死ね. ついには死ぬべきおまえである. 行け, そして苦しめ. 苦しまねばならぬおまえである. 人は幸福であるがために生きているのではない. 私の掟を成就するがために生きているのだ. 苦しめ, 死ね. しかし, おまえがあらねばならぬものであれ. 『人間』であれ」    「朝より」

庭でゆらめいていた明かりが消えた. いっさいのものが消えた・・・
  闇・・・深淵・・・光もなく, 意識もない・・・生命. 身をかむ暗黙の生命の力. 全能の歓喜. 引き裂くような歓喜. 空洞が石を吸いよせるように, 生命を吸いこむ歓喜. 思考力をしぼりとる欲望の竜巻. 闇の中に渦巻くめくらめっぽうな陶酔の世界の不条理な, 無我夢中な「法則」・・・
  闇・・・ふたりの混ざり合う呼吸, 溶け合う二つの肉体の金色の温かみ, ともどもに落ちてゆく忘我の深淵・・・いく夜をひと夜にした夜・・・一時間が数世紀である時間, 瞬間瞬間が死である瞬間・・・共通な夢. 目を閉じての言葉. 半ば眠ったまま求め合うあらわな足の甘美な, ひそかな接触. 涙と笑い. ものみなすべて空虚のなかで愛し合い, ともに眠りの虚無を分かち合う幸福. 頭脳の中を漂う群がる映像. ざわめく夜の幻影・・・
  闇・・・死・・・なんのために, また生きかえる必要があるのか・・・  「青春より」

  この一年来, なにをしていたか. 自分の永続性のためになにをしていたか. 失われ, そこなわれ, 汚されなかった一日だにもなかった. 作品ひとつ, 思想ひとつ, 永続的な努力ひとつない. 互いに破壊しあう混沌とした欲望の渦. 風, 埃, 虚無・・・欲することだけでなんの役に立つだろう. 欲したことをなにひとつ成し遂げてはいなかった. 欲したことの反対ばかりをしていた.

ゴットフリート「肝心なことは, わかるね, こうありたいと思うことや生きることに飽かないということだ. あとのことは, 人間の力ではどうにもならない」
「明けてゆく日の前につつましい心を持つんだよ. 一年のうち, 十年のうちにどうなるというようなことを考えるんじゃない. 今日のことを考えるのだ. 理屈はやめるんだ. ばからしいものだ. 人生は無理をしてはいけない. きょうの日を生きるのだ. 毎日毎日に対して, 謙虚な心を持つんだ. その日その日を愛し, 尊敬するんだ. なによりも枯れしぼませてはいけない, 花が咲くのを邪魔してはいけない. きょうのような灰色な, 悲しい日でも愛するんだ. くよくよすることはない. ごらん. いまは冬だ. なにもかも眠っている. このよい大地もやがて眼を覚ますだろう. よい大地になりさえすれば, 大地のように辛抱強くありさえすればよい. つつましくするんだ. 待つのだ. おまえがよい人間なら, 万事はうまくゆく. やってできないことを悲しんだって仕方がなかろう. できるだけのことをしなくてはならん」

クリストフ「自分も眼をさますんだ」

「吹け吹け・・・おまえのしたいように, おれをしてくれ・・・吹きとばすがよい・・・おれはどこに行くのかよく知っている」

  音楽は, このつらい生活の中で, 彼らの楽園だった. 彼らの生活に大きな場所を占めていた. 彼らをおし包んで, ほかの世界を忘れさせてくれた. それは危険を伴わないでもなかった. 音楽は現代の強力な溶解剤の一つである. 蒸し風呂のような, またはけだるい秋の日のような, その熱気をふくんだ陶酔感は官能を極度に刺激して, 意志力を殺してしまう. しかし, アントワネットのように過度な, そして喜びのない活動を強いられている魂にとっては, ひとつの憩いだった. 日曜日の音楽界は, たゆみない労働の一週間の中に輝く, ただひとつの光明だった. 彼らは前の音楽会の思い出, 次の音楽界への希望, 時を忘れ, パリを忘れて過ごす二時間か三時間かのために生きていた. 雨, 雪, 風, 寒さの日, 互いに寄り添って, 場席がなくなることを心配しながら長いあいだに外で待たされたのち, 劇場の中に吸い込まれ, 人ごみの中に解けて, 狭くて暗い座席についた. 息が苦しくなり, 押しつぶされそうになって, 暑さと窮屈さで気分が悪くなりかけた. それでも彼らは幸福だった. 自分が幸福であり, 今ひとりが幸福であるために幸福であり, ベートーベン, ワーグナーの偉大な魂からほど走り出る善意と力と光明の波が彼らの心の中を流れるのを感じるのが幸福であり, 愛してやまない姉であり, 弟であるものの顔…疲労と, 年が若くしてなめている苦悩のために蒼ざめたその顔が輝きだすのを見るのが幸福だった. アントワネットはひどく疲れていて, まるでひしと抱きしめてくれる母親の胸の中にいるような気持ちがしていていた. 彼女は心地よい, 暖かいその巣の中に身体をすくめていた. 恐ろしく広い会場の中の暗がりの中では, 誰も二人に注意を払うものはいなかった. 音楽の母の翼のもとに避難所をみいだしている傷ついた魂は, 彼ら二人だけではなかった.

彼にはもはや, 人間が何のために生きているのかわからなかった. そして, 音楽の創造も, もはやクリストフには避難所ではなかった. 音楽は間歇的で, 不規則で, 目的がなかった. 作曲する. 誰のために作曲するのか. 人間のためにか. 自分のためにか. 彼は死の空虚を満たす力のない芸術のはかなさをあまりにも痛感していた. なんという味気ない現実.

クリストフは, 万策尽きるまで努力したが, ついに, ゆきずまった.
いまや, すべてが終わった」.
彼はもはや, 生きるなんらの理由ももっていなかったが, しかも生きていた.

ある日, クリストフは小さな村にやってきた. 男が立っていた. クリストフはたずねた.

「なにをみているのですか」.

待っているんだ. 

「なにを」

「復活を」

その言葉が, 一閃の火のように彼を貫いた.

「おお, おまえ, おまえだ. ついに帰ってきた」.

なぜ戦う必要があるんだ. お前は<存在>する<すべて>ではないのか
「わたしは<存在>する<すべて>ではない. 虚無と戦う生命なのだ. 私は闇に燃える火だ. 私は永遠に戦う自由な意思だ. 私といっしょに戦え. そして燃えるがよい」.
僕は敗れたんだ」.
お前が敗れたって. それではほかのものたちが勝利者になる. お前のことを考えないで, お前の軍隊のことを考えるんだ」.
「ぼくはひとりきりだ」.
「おまえはひとりではない. お前は決して敗れることのない軍隊に属している. お前は死んでもなおかつ勝つだろう」.

クリストフは寝床に釘付けにされて, じっとしていた.
「もう長いことはあるまい」
彼は自分の人間的利己心の脈をはかるために自問した.
「どちらを選ぶかね. クリストフの思い出, その一身と名前との思い出が永久に残って, その作品が滅びてしまうのがよいか. それとも, 作品が永続して, お前という人間や名前は跡形もなく消えてしまうのがよいか」
  ためらうことなく彼は答えた.
「自分が滅びて, 作品が残って欲しい. クリストフは消えてなくなれだ・・・」
しかし, それからしばらくたつと, , 彼は作品も, 自分自身と同様に, どうでもよくなってゆくのを感じた. 自分の芸術の永続性を信じるなんて, 子供っぽい夢だ. ほかのどんな言葉よりも早く, 音楽の言葉は燃え尽きる. 一世紀か二世紀の後には, もうわずかな, その道の通にしか理解されなくなる.

・・・芸術の廃墟の上に涙するというのか. 廃墟は, その労に値しない. 芸術は自然の上に投げられた人間の影である. 人も芸術も太陽に吸い込まれて, ともどもに消えてしまうがよい. 太陽を見るのに邪魔になる. 精神は不可解なものを理解するために, この虚構を必要とする. それを信じたかったので信じたのである. しかし, それは本物ではない. 生きてはいない. そして精神が自分で作ったこの秩序が, 精神に与える楽しみは, 実在するものに対する直接の直感をゆがめないでは得られない. 芸術の雑言は私にはうるさい. 精神は黙っているがよい. 人間に, 沈黙あれ・・・.

おお, 歓喜. 一生の間, つかえようと努めた神のしろしめす平和の中に, 自分が消え去るのを見る歓喜・・・.
「主よ. わたしは戦い, 苦しみ, さまよい, 創造いたしました. 父であるあなたの腕の中で, わたしに息をつかせて欲しいのです. いつの皮下, わたしは新しい戦いのために, また生まれかわりましょう」.
「お前は生まれかわるだろう. 休むがよい. すべてはもはや, ただひとつの心でしかない. さらば, ジャン・クリストフよ」

  今日の人々, 若い人々よ. 次は君たちの番である. 諸君はわれわれの亡骸を踏み台にして, そうして前進したまえ. われわれよりもさらに偉大で, いっそう幸福でありたまえ.
  私自身は, わたしの過去の魂に別れを告げる. わたしは, むなしい抜け殻のように, わたしの過去の魂を後ろに投げ捨てる. 人生は死とよみがえりの連続である. 死のうではないか, クリストフ, 生まれかわるために.

** 魅せられたる魂  宮本正清訳
  さあ, 進め! 人生にまたがったきびしい騎手よ, おまえの拍車でその横腹を傷つけるがいい! この子供たちの横腹を傷つけるがいい! 世界は拍車のもとにのみ進むのだ. 進まなければならない. もしおまえが立ち止まれば, おまえは倒れるのだ・・・おまえは倒れてはならない! 自分は苦悩によっておまえをひきおこしてやろう.

  それは淋しい空地において, 暗い闘いを行う烈々たる行動のたいまつである. 失敗も勝利も問題ではない, 行動だ! 行動し, 戦闘することが, 虚無に対する唯一の肯定なのだ・・・

  そして「名づけがたいもの」が雷鳴とともに底から現れる. 爪がくいこむ. いっさいが打ち砕かれ, いっさいがその無数の巻き髯によって探られる. 脇腹も, 眼も, 口も, 性も, いっさいが吸い取れらる. それは名状しがたい苦しみの中の, 名状しがたい死の交接の快楽である. 粉砕され, 伸びた魂は聞き, 至上の「存在」と合体する. 至上の存在は彼女を抉り取りながら, 彼女を併合する.

  「おまえはわたしのものだ, そしてわしはおまえのものだ・・・」

  おお, 充溢! 一致! ・・・この瞬間に, 彼女はいっさいを理解する, 善のかなたも, 存在のかなたも. 全体験が完成する. 「魅せられたる魂」の周期が完成する・・・彼女はひとつの曲がり角に, 空間にかけられた梯子のひとつの環だった. 彼女の生涯のすべての苦しみは「運命」の前進の曲がり角であった・・・

  「運命! 進め! 自分を踏み台にしてくれたことを感謝する! ・・・そして自分はおまえについて行く. 自分が運命だ」

*** アンネット・リヴェール
 彼女はとりわけ信ずる必要がある. 人がなすことを, 欲することを, 求めることあるいは夢見ることを信じ, あらゆる嫌悪と幻滅にもかかわらず, あるがままの人を信じ, 自分と人生を信じるのだ! アンネットは, 自分が尊敬されないことよりも人生に対する敬虔の念・・・自分を失う・・・ことが耐えられないだろう. なぜならそれは力の源だからである. 行動する力なしには, アンネットは何者でもなくなるだろう. 受身の幸福は, 彼女にとっては死である. 人々の相違の本質は, ある人は能動的であり, 他の人々は受動的であるという点にある. そしてすべての受身の中でも, アンネットにとって一番致命的な受身は, 懐疑すらも知らないで「虚無」の流れに, 官能的に無関心に身を任せる快適の中に落ちつき収まっている精神的受身である・・・自殺だ! ・・・否! 彼女は拒絶する.
 一つの目標に向かって躍進だ・・・未知のものか? 幻影的なものか? そうかもしれない. かまうものか! 躍進は幻影的ではないのだ. 途中で倒れてもいいのだ, 自分の道で倒れるのならば!

   しかも本当の正義はその天秤の前にすわって, 皿が上下するのを眺めていることではないのです. それを判断し, 決断することです. 彼は断行してほしいものです! ・・・夢はもうたくさんです! 来たれ, 目覚め! ・・・おさらば, 空想!

   彼女の中には, 根底にひとつの宿命感があった. それは意志と合致する. ・・・ (『自分の意志はまさにそうなるべきものと同じだ. なるべきものはそうなるであろう』) ・・・河の流れが私たちを運んでいく. 私たちは小舟の舵を握っているだけでいい. 舵, 小舟, 流れ, それは自分だ. 河の意志に従ってなされるのだ!

   夢想はもうたくさんだ! 彼女は全快した・・・『人生は夢なり・・・』そうかもしれない! ・・・しかし稼がないことにはパンが口の中に入ってこないところではそれは夢である・・・彼女は寝台から飛び降りた. さあ仕事だ!

   『おまえがなんであろうと・・・, 無であろうといっさいであろうと・・・自分は自分の運命の窮極までいくだろう! なぜなら, 自分の意志だけは, それだけは少なくとも自分のものだから. 譲歩しないこと. またたきしないで見ること. 前進中に死ぬこと・・・』.
   一人が倒れたら, 他の一人が最後まで彼を運んで行くだろう. 自分は自分の追憶の中に, 悲しみの中に, 希望の中に, 寝ている権利はないのだ. 立て! 歩むのは自分ではない, 彼なのだ. 自分は自分の肉体を彼にあたえるのだ. しかし自分の身体の中にあって, 彼は, 死んでも, 生きていたときに進んだよりもっと遠くまで進むだろう.

   ええ, 自分の傾斜を見いだすのは幸福です. 人生は他に目的を持たないのです. その他のことは, 目的地へは, 河が私たちをそこにつれて行ってくれます. 河といっしょに溶けるだけでいいのです. 何もよどまないこと! 前進する生命・・・前進です! 死の中においてすら, 波が私たちを運んでいきます.

*** マルク・リヴェール
   僕たちはこの地上の秩序の中で呼吸しています. その秩序が不正によって腐敗しているときには, 呼吸ができるようにガラスを打ち破ることが義務です. 多数の人命を奪う, 自然に反した, 死んだ秩序, 無秩序よりも間違った秩序は破るべきです.
   より高い, より広い秩序を, 来つつある人々, すでに来ている人々・・・人間, つまりぼくらの身丈に合うように作り直すべきです! 空気を! もっと多くの空気を! 善も悪も拡大しましょう! それは僕たちとともに大きくなりました. 嵐です. 嵐ばんざい!
   僕が見るのは人間です, 大群をなす人間, さまよい, 身を寄せ合い, ぶつかり合い, そして足元に思想の塵埃を立てる人間です. 僕は人生の中に, ひとつの悲喜劇を見るのです. そのシナリオは突撃を指揮する人々の意思の即興に従って, 次々に, 書かれるのです. ところで, 僕は突撃隊員です. 僕は指名を受けています. そして僕の所属の部隊が勝負に, 負けようと負けまいと, 僕は最後の決勝まで行きましょう, 尻込みしないで! ぼくらは信じ, 行動し, 破壊し, 歩み, たたかわねばなりません, しかし, 前進しなければいけないんです, どんなことがあろうとも. 打ち破るんです, 自分の道をまっすぐに進むために!
 マルク「人生が嘘なしにやっていけないのは, 人生が大きな幻なのはそれが真の『生命』でないからないんです. 真の『生命』はもっと彼方にあります. それをふたたび見出さなければなりません」
 アンネット「それはどこにありますか」
 マルク「僕の中に. あなたの中に. この真理に対する要求のなかに. この要求がどうして僕たちをとらえることができるでしょう, 真の生命が僕たちの内部で呼吸しているのでなかったら? あなたの人生はなんのためです? あなたはあなたの真理にしたがって, 生きられたではないんですか? 」

   『最後まで行く』言い換えると, 途中で倒れないことだ. 倒れるには倒れても, ただ最後においてだ! 災難, 恥辱, それもいい! ただ突破するのだ, どんなことがあろうとも! 突破する? おお, 神よ! 突破してしまったら! ・・・いまから, 突破してしまったときの休息を思って, 彼は伸びをした・・・もはや存在しなくなる! ・・・それは存在した後にしてはじめてできることだ.
   一番急を要するのは, 享楽することか, それとも知ることなのか? ・・・知ることだ, まず! 知らないうちに人生を立ち去ると思うと耐えられない. それは, あらゆる想像をたくましくした地獄よりも悪い絶望の夜の中を, 今後ずっとさまようのと同じだ! 空虚は知性を狂わせる. なるほど, 自然を空虚を恐れる. 知らなければならない. それとも死ぬかだ.
   ところがまず食わなければならない. もうたくさんだ! 今後は自分の稼いだパンを食うのだ. 美よりも先に, 平和よりも先に, 戦争よりも先に, 人類の未来よりも先に, 口があるのだ. その口は飢えて, 開いている・・・それを沈黙させろ! それを養え!

   下方へ, 忘却・・・快楽のもっとも強い餌である忘却の深淵をあこがれる! ・・・自己逃避・・・努力の回避・・・『それを自分に強いるのは誰か? 非人情なこの時代の運命? 自分はそんな時代に生きることを頼んだのか? 自分はそれを拒む! ・・・それはできない, この運命は自分だ. あの高いところによじ登るのを自分に命ずるのは自分だけだ・・・しかしあの高地に達する可能性がどれだけあるのか? しかも, 精根も尽きるほどの苦労をして, かしこに達したときに・・・疲れはて, 自分の内容が空っぽになってから・・・自分は果たして何を見出すだろうか? 何物かを見出すだろうか? それとも切り立てた稜角の向こう側は, 虚無か? ・・・』いたるところ虚無であり, 死だ! もし生きるつもりなら, 自分は身を脱して逃げ, 享楽に堕するか, それとも, 突破するかだ. 突破するのは, 向こう側になにがあるかを知ることだ. ・・・知ること, 能力を有すること! それができるだろうか? マルクは逃れることができない. なにごとにも. 快楽の中にも, 苦しみの中にも.

*** マルク
「僕は死にたいと思います. 死ぬのは怖くありません. そればかりか, 望んでいます! ・・・しかし犬死はしたくありません! 自分だけのためではありません! 卑怯な利己主義の宗教家や思想家のように, 自分を救うためではありません」.
   「心配しなくてもいいよ! 時は来るでしょう. きみは人類のために身を捧げるでしょう. 今日はそうした機会に不足はしないからね. 忍耐したまえ! 機会はきます. 待っていたまえ! 支度をしていたまえ! 」
   真実であることが彼の使命だった. 苦しみ, 迷い, 矛盾し, 倒れ, 身を汚しても, 真実であるのだ! また立ち上がるだろう. 身を洗うだろう. 真実な魂は呪われることはありえない. いよいよ死ぬときにわかるだろう・・・それまでは鍛えるがいい! おまえの肉で, おまえの苦しみで! ・・・必要な場合はおまえの身を焼くがいい, だが断じて火を消してはならない!

***  シルヴィ
   「なんにもならないのさ. 生きるためだよ. 人生は何かの役に立つの? お腹からでて, 生まれる, 何のためにだかわからないわ. お腹を膨らせ, 食って, 恋して, 騒ぎまわるのが, 何のためだかわからないわ. 死ぬ, なんだかしらないところに入るのが, 何のためだか知らないわ・・・何のためだかわかっていることはたった一つしかない, それは人は退屈することだわ! この世で人がすることはみんな, 退屈なことを考えないというただひとつの目的のためだわ・・」
   根本に, 子供のない自分の生活に対する無頓着, 人生に対する一種の怨恨の念がある・・・人生のつまらなさを何もばかなマルク輩から教わる必要はなかった・・・だから, くたばるがいい, 屍! しかし最後の息まで, 働け, そして享楽せよ!

*** ジョルジュ
   しかしそれは遠いことだ! それに反して, 生きるのは千万遍だ, 毎日一分ごとだ. おしまいのことなどかまっている暇はない. それがなんの役に立つのか? なにがわかるものか? 自分はこれでもいいし, それでもいい. 自分の知らないことをとやかく議論するのは自分の仕事じゃない. 自分には他に興味のある仕事が多すぎるのだ. ぜひそうしたいなら, 自分のかわりに, そうしたことについて考えてもらいたい!

   快楽は飲み心地はいいものです. しかしそれほどの子牛にだってできることです. いちばんいい, 本当にいいことは, 人が自分の苦しみを噛みはじめた時なんです. 舌にのせたこの味に匹敵するものは何もありません. あんたの汗をなめなさい! さあ! おやり! ・・・もっと! ・・・もっと! 

* イギリス文学
** ドリアン・グレイの肖像  オスカー・ワイルド  仁木めぐみ訳  光文社 
   二十歳の頃に高鳴った歓喜の鼓動は, だんだん鈍くなっていく. 手足は弱り, 感覚は衰える. 醜怪な人形のような姿に衰え, 恐れのあまり近づけなかった情熱や, 身を任せる勇気のなかったすばらしい誘惑の記憶ばかりに苛まれるようになる. 若さ! 若さ! 若さをのぞいたらこの世になにが残るというのだ!
(p51) 

* 中国文学
** 臥薪嘗胆 (十八史略より)  會先之 
子胥復事之. 夫差志復讎. (子胥復た之に事ふ. 夫差讎を復せんと志す).
朝夕臥薪中, 出入使人呼曰, (朝夕薪中に臥し, 出入するに人をして呼ばしめて曰はく)
「夫差而忘越人之殺而父邪」. (「夫差, 而越人の而の父を殺ししを忘れたるか」. と).

  夫差は, いつかきっと復讐 (ふくしゅう) してやる, と強く誓い, 父が殺された恨みを忘れないために, 積み重ねた薪 (たきぎ) の上に寝て, 毎日その痛みに耐えていました. さらに, その部屋に人々が出入りするたびに, 「夫差よ! おまえは父が越の国にやられたのを忘れたのか! 」という言葉をあいさつ代わりに言わせました.

勾践反国, 懸胆於坐臥即仰胆嘗之曰, (勾践国に反へり, 胆を坐臥に懸け, 即ち胆を仰ぎ之を嘗めて曰はく),
「女忘会稽之恥邪」. (「女会稽の恥を忘れたるか」. と).

助かった勾践は, 屈辱的な敗戦を忘れませんでした. 朝起きたときや夜寝る前には, 必ず獣の胆 (きも) を嘗 (な) めてそのとても苦い味をかみしめました. 食事のときも必ず胆を口にして「おまえはあの恥 (はじ) を忘れたのか! 」と自分に言い聞かせていました.

臥薪嘗胆 (がしんしょうたん) とは, 復讐の為に耐え忍ぶこと, また, 成功するために苦労に耐えるという意味を持つ, 中国の故事成語である.

* 日本文学
** お目出たき人    武者小路実篤 
   自分が女に飢えている.
   誠に自分は女に飢えている. 残念ながら美しい女, 若い女に飢えている. 七年間, 若い美しい女と話したことすらない自分は, 女に飢えている.
   日比谷を抜けるとき, 若い夫婦の楽しそうに話しているのにあった. 自分は心ひそかに彼らの幸福を祝するよりも羨ましく思った. 羨ましく思うよりも呪った. その淋しい自分の心の調べの華なる調子で乱されるときに, その乱すものを呪わないではいられない. 彼等は自分に自分の淋しさを目の当たりに知らせる. 痛切に感じさせる.

   女によって堕落する人もある. しかし女あって生きられる人が何人あるか知れない. 女そのものはつまらぬものかもしれない. しかし男と女のあいだには何かある.
   女そのものは知らない. しかし女の男の与える力は知っている. 女の男に与える力は強い.
   所謂女を知らないせいか, 自分は理想の女を崇拝する. その肉と心を崇拝する. そうしてその理想的なの女として自分の知れる範囲において鶴は第一の人である.
   鶴に幸あれ!
   しかし自分はいくら鶴を恋しているからといって, 自分の仕事をすててまで鶴を得ようと思わない. 自我を犠牲にしてまで鶴と一緒になろうとは思わない. 女に飢えて女の力を知り, 女の力を知って, 自我の力を自分は知ることができた. 自分は自我を発展させるためにも鶴を要求するものである.

   「しかし僕だって道楽をしたくないことはない. 自分は女に飢えている. 華やかな快楽にあこがれている. 例の人がいなかったら遊んでいるかもしれない. 今逢っている時分かもしれない」.

   鶴が自分の妻にならなくとも, 恋の味わいを味わることができなくとも, 自分は自分の心をすさまさずに見せる. 自分はすべてのことに超越しなければならない. 勇士勇士! 自分は勇士だ! こう心に叫んだ. そうしてややもすると女々しい感じが心に流れこむのふせいだ.

   一日として鶴のことを考えない日はなかった. 自分は鶴と一緒になって始めて全人間たることができるように思えた. なにか書くにつけ, 読むにつけ, 見るにつけ鶴が居たらと思う. 嬉しい時も淋しい時も悲しい時も, 鶴と一緒だったらと思う.

   彼女の心が見たい. 鶴が自分を愛しているか, 愛していないかが知りたい, それを知れば思い切るのもきりいいし, 不安をつづけるのもつづけ甲斐ができるわけだ.

* 批評・エッセイ
** シーシュポスの神話  カミュ  新潮社  (1969)
  真に重大な哲学上の問題は一つしかない. 自殺ということだ. 人生が生きるに値するか否かを判断する, これが哲学の根本問題に答えることなのだ. それ以外のことは, 遊戯であり, まずこの根本問題に答えなければならぬ. そして, 哲学者たるもの身をもって範をたれてこそはじめて尊敬に値するというのが真実であるとすれば, そのとき, この根本問題に答えることがどれほど重要なことであるか, 納得できよう.

  ふと, 舞台装置が崩壊することがある. 起床, 電車, 会社や工場での四年間, 食事, 電車, 四時間の仕事, 食事, 睡眠, 同じリズムで流れてゆく月火水木金土, ・・・こういう道を, たいていの時はすらすらと辿っている. ところがある日, 《なぜ》という問いが頭をもたげる, すると, 驚きの色に染められたこの倦怠の中ですべてがはじまる. 《はじまる》これが重大なのだ. 機械的な生活の果てに倦怠がある, が, それは同時に意識の運動の端緒となる. 意識を目覚めさせ, それに続く運動を巻き起こす. それに続く運動, それは, あの日常の動作の連鎖への無意識的な回帰か, 決定的な目覚めか, そおどちらかだ. そして, 目覚めの果てに, やがて, 結末が, 自殺あるいは再起か, そのどちらかの結末が訪れる.
  とりたててこともない人生の来る日も来る日も, 時間がぼくらをいつも同じように支えている. だが, ぼくらの方で時間を支えなければならぬときが, いつか必ずやって来る.

  いかなる美であろうと, その奥底には, なにか非人間的なものが横たわっている. かなたに連なる丘, 空の優しさ, 木々のたたずまい, ・・・それらが, まさしくその瞬間, ぼくらから着せかけられていたむなしい意味を失い, もはやそれ以後は, 失われた楽園よりもさらに遠いものとなってしまう.

  生の純粋な炎以外のいっさいのものに対する, あの信じがたい無関心, ・・・そう, 実にはっきりと感じられよう, こうした状態においてこそ, 死と不条理とが, 妥当な唯一の自由の, つまり人間の心情が経験し生きることのできる自由の原理となるのだ. こうして不条理な人間は, 炎と燃え上がりしかも冷たく凍った宇宙, どこまでも透明でしかも限界のある宇宙, なにひとつ可能ではなくしかもすべてが与えられている宇宙, それをすぎた先は崩壊と虚無にほかならぬような宇宙を垣間見る. そのとき彼は, このような宇宙の中を生きることを受け入れ, そこから力と希望の拒否とを引き出し, 慰められることの決してない人生を執拗に証しようとする決意を固めることができるのだ.

  重要なのは最もよく生きることではなく, 最も多く生きることだ. 同じ年数を生きた二人の人間に対して, 世界は常に同じ量の経験を提供する. それを意識化するのは受け取る側の問題ということ, しかも可能な限り多くを生きるということだ. そして, すべてを明晰に見分けているとき, 価値のシステムは無用となる. どのような深さ, どのような感動, どのような情熱, どのような自己犠牲があろうと, 四十年の意識的な障害と六十年にわたる聡明なまなざしとが, 不条理な人間の目に等しいものとして映ることは, ありえないだろう.

*** シーシュポスの神話
  神々がシーシュポスに課した刑罰は, 休みなく岩をころがして, あるや間の頂まで運び上げるというものであったが, ひとたび山頂にまで達すると, 岩はそれ自体の重さでいつも転がり落ちてしまうのであった. 無益で希望のない労働ほど恐ろしい刑罰はないと神々が考えたのは, 確かにいくらかはもっともなことであった.

  緊張したからだが, あらん限りの努力を傾けて, 巨大な岩を持ち上げ, ころがし, 何百回目もの同じ斜面にそれを押し上げようとしている姿が描かれているだけだ. 天のない空間と深さのない時間とによって測られるこの長い努力の果てに, ついに目的は達せられる. するとシーシュポスは, 岩がたちまちのうちに, はるか下の方の世界へと転がり落ちてゆくのをじっと見つめる. その下の方の世界から, 再び岩を山頂まで押し上げてこなければならぬのだ. 彼は再び平原へと戻ってゆく.

  こうやってふもとへと戻ってゆくあいだ, この休止の間のシーシュポスこそ, ぼくの関心をそそる. 彼の不幸と同じく, 確実に繰り返し舞い戻ってくるこの時間, これは意識の張りつめた時間だ. 彼が山頂を離れ, 神々の洞穴の方へと少しずつくだってゆくこのときの, どの瞬間においても, あれは自分の運命よりたち勝っている.
  この神話が悲劇的であるのは, 主人公が意識に目覚めているからだ. 今日の労働者は, 生活の毎日毎日を, 同じ仕事に従事している. その運命はシーシュポスに劣らず無意味だ. しかし, 彼が悲劇であるのは, 彼が意識的になるまれな瞬間だけだ. 無力で反抗するシーシュポスは, 自分の悲惨なあり方をすみずみまで知っている. まさにこの悲惨なあり方を, 彼は下山の間じゅう考えているのだ. 彼を苦しめたに違いない明哲な視力が, 同時に, 彼の勝利を完璧なものたらしめる. 侮蔑によって乗り越えられぬ運命はないのである.
  このように, 下山が苦しみのうちになされる日々もあるが, それが悦びのうちになされることもあるのだ. 幸福と不条理とはひとつの大地から生まれた二人の息子である.

  彼の努力はもはや終わることがないであろう. 人にはそれぞれの運命があるにしても, 人間を超えた宿命などありはしない. 少なくとも, そういう宿命はひとつしかないし, しかもその宿命とは, 人間はいつか必ず死ぬという不可避なもの, しかも軽蔑すべきものだと, 不条理な人間は判断している. それ以外については, 不条理な人間は, 自分こそが自分の日々を支配するものだと知っている.

  ぼくはシーシュポスを山の麓に残そう! ひとはいつも, 繰り返し繰り返し, 自分の重課を見いだす. しかし, シーシュポスは, 神々を日手氏, 岩を持ち上げるより高次の忠実さをを人に教える. かれもまた, すべてよし, と判断してるのだ. このとき以後, もはや支配者を持たぬこの宇宙は, 彼には不毛だともくだらぬとも思えない. この石の上の結晶一つ一つが, 夜に満たされたこの山の鉱物物質の輝きの一つ一つが, それだけで, 一つの世界を形作る. 頂上をめがける闘争ただそれだけで, 人間の心を満たすのに十分足りるのだ. いまや, シーシュポスは幸福なのだと思わなければならぬ.

** 邪悪な文学誌 (監禁・恐怖・エロスの遊戯)  許光俊  青弓社  (1997)
   私は, 小学校のときから, 倦怠に溺れそうだった. <普通>に息づまりそうだった. だから, いつも主流から離れたところに行って, さらにそこでも少数派のものばかり見つけては, 異常性の中で退屈を紛らわしている. ここでもまたバタイユを引けば, 「文学とはついに再び見出された少年時代のことではないだろうか. ところで, 少年時代とは, もしそれがこの世界で支配的な立場に立つことがあるとして, そのときもなお真理を宿しているものだろうか」 (文学と悪) (LINK)

   感覚的なものを優先してみれば, 対象には主流も傍流もありはしない. 異端的なものは異端的なものであり続ける矜持を持つべきだろう. 異端を愛するものは, 異端の価値を見出し, 嘆賞, 決してそれを皆に見せようと陽の当たるところに引きずり出すべきではあるまい. 妖異の花は, 夜にひっそりと道を這う人にのみ見えるのだし, それが美しさである. 「文学とは霊的なコミュニケーションである. それは誠実さを要求する. ・・・この峻厳なモラルは当然悪の認識による共犯関係から出発して与えられるものである」 (バタイユ  文学と悪)

   細部の仕組みを解き明かす作業が, 作品から表現の温度を失わせてはならない. ここの細部が全体となるとき, それを可能としているのは, ほぼ, 論理であるが, 常に論理であるとは限らない. 速度もまた論理の代わりとなってディテールを張り合わせることができる.

   夢野久作の作品がたちまちにして愛読者をその妖しい世界に引きずり込み, 危険な魅力で持って中毒状態に陥らせる力のひとつは, 彼の描き出す世界がこれ以上はないというほど激烈な明暗のコントラストを思い切って隣り合わせ, それどころか力ずくで一体化して, 感覚的・心理的な眩惑を味わわせることである. 大聖堂の中では楽園と地獄, 美と醜, 善と悪, 愛と憎悪, 優しさと残酷さのこもごもが共存しつつ天に向かって上昇するように, 夢野の中では相反する要素が独立的ではなく, 互いに依存しつつ, 抱き合って無限落下へと身を躍らせる. 対比のもととなるに要素は常識的にはあたうかぎり最も遠い性格を持つ. それが夢野の筆によって一瞬のうちに距離を縮めて一体化させられるスピード感は, すでにそれだけで酔いを呼び起こす. 「接近する二つの現実の関係が遠く, しかも適切であるほど, イメージはいっそう強まり, いっそうの感動の力と詩的現実性を持つようになるであろう」 (ピエール・ルヴェルディ  シュールレアリスム宣言)
   作者たる夢野は凄惨なコントラスト図を心ゆくまで眺めて堪能するのだが, そのヨーロッパ中世絵画さながらのぎらぎらとした陰惨な対比や共存の仕方こそが, 戦慄美のひとつであり, さらには世界の存在の在り方となる. その際, 極端な二元論の要素間には優劣もなければ, 優先順位もなく, ただに要素が, 業のごとく超越的なしがらみとなって同じ生を生きはじめる神秘が描かれる.

   文と写真によるコラージュを作ること. ビックバン的運動力学にのっとった (すなわち, 初速が次第に加速していく) 猥雑さ. さまざまな欲望は, 結局総体性をめざす, という予定調和的な希望.

   ショーウィンドーは商品を神聖化する祭壇である. それは購買者に動機も結果も要求はしない. ただ, 信仰と服従のみを求めるのである.

   コンピューター・ネットワークは, ことさら性的ではなく, 進歩のイメージや有用性の強調によってカモフラージュされてはいるが, 実質的にはポルノグラフィーである. モニター画面を流れる文字は, 匿名性の欲望を乱射する. その攻撃を受けたものも欲望に伝染し, ネットワーク自体が巨大な欲望の集積回路となる. ネットワーク自体が巨大な欲望の集積回路となる. ネットワークはポルノのように無限に要望を刺激し続け, 膨大に消費され, 膨大に需要される. そのますます急速に拡散していく有様をビックバン後の膨張宇宙にたとえることができよう. とすると, ネットワークの死は, 宇宙と同様, 温度の低下によっておこることになる. 事実, ネットワークにとって量は加入者増大のための強力な誘引剤であると同時に, やがて構造的に麻痺をひきおこす時限爆弾でもある.

   戦慄文学において最も重要なことあ, 時間の流れの効果的な統御ということだ. ある部分では読者をじらし, あるところでは急速に話を進め, というテンポの調整である.

   「お前は生涯休みなくこの美しい私的な陶酔の中に居続けなくてはいけない. 全人生がひとつの音楽でなければならない」.

   恋愛においてはその女の美とその女によって与えられる快楽が<女>の美であり<女>の与える快楽であるのに対し, マゾヒズムにおいては最初に与えられたものは個別的な一人の女なのではなく, 概念たる<女>の美であり, 快楽なのだ. 前者は与えられたものがすべてであるのに, 後者では一人がすべてを与えなくてはならない. 恋愛では個人の中に概念が吸収されるのに, マゾヒズムにおいては個人が概念に吸収されるのである.
   マゾヒズムは何よりも享受の姿勢, 際限ない快楽への渇望である. マゾヒストのひきおこす現象は, 苦痛を探し求める活動の連鎖なのではなく, 快楽を骨までしゃぶりつくす貪欲さの結果なのである. これは美食家に特有の態度である. 健康上の配慮などは彼の破壊的な情熱においては一顧だに値しないのである. 美食家は冷静である. 快楽の量を精妙に計算するためには意識が覚醒している必要がある. 美食家は目の前のものを存分に味わいながらも, それを上回る快楽があるであろうと考える. 彼は素朴な陶酔を, 卑しく野蛮な俗人の興奮として軽侮する. それは, 一過性のものに過ぎないし, そのような陶酔の襲撃に無防備に身をさらすのは無知なるものの愚行でしかない. 美食家は同じ刺激からより豊かな快楽を取り出すことができるし, それが美食術なのである. 快楽を事前に連想する快楽というものも存在するのだ.
   対象が主体にいかなる作用を及ぼしたかが重要なのだ. 強い作用を内面にひきおこすものは快楽だけではない. 苦痛もその点では同様なのであり, それゆえマゾヒストは苦痛と快楽を並置する. 「実際愛する女の不実さの中には苦痛を伴う刺激, 最高の快楽がありますね」「身体の奥の方からぞっとする戦慄が襲ってくる」「私は不意に甘い恍惚感に襲われた」マゾヒストにとっては, 喜びの驚きであれ, 不意の不幸であれ, 突然の愛の告白であれ, すべて歓迎されるのである.
   快楽を生み出す儀式は繰り返しが可能であるが, 刺激は次第に強まらなくては刺激であることを止める. 刺激を強化するのが障害である. 障害は克服されえる限りで困難なほどよい. 絶望のさなかでの希望ほどマゾヒストを鼓舞するものはない.
   マゾヒストは追跡を行いつつも獲物を手に入れることはない. 追跡の遊戯の面白さが彼を捉えている. 遊戯は未来を持たず, その魅力は現在の中に尽きる. 男女間の関係という生の最も暗く悲劇的な関係が, 最高の陶酔を獲得するというわけである. 遊戯の最大の目的は, 結末ではなく, 享受である. 結末への期待は遊戯を面白いものにするが, 結末の到来は遊戯の終了を意味するから, その到来を遅らせようという努力がなされる. オルガスムスへの期待は期待にとどまらなければならない.

** 暗い青春    坂口安吾    角川文庫 
     青春は暗いものだ. 発散しようもないほどの情熱と希望と活力がある. そのくせ焦点がないのだ.
  私は小説を書いた. 文学に生きると言う. しかし, 何を書くべきか. 私は真実書かずにはいられぬような言葉, 書かねばならぬ問題がなく, 書き表さねばやみがたい生き方も情熱もなかったのだ. ただ虚名を追う情熱と, それゆえ, 絶望し, 敗北しつつある魂があった.

  青春は力の時期であるから, 同時に死の激しさと密着している時期なのだ. 人生の迷路は解きがたい. それは魂の迷路であるが, その迷路も死がわれわれに与えたものだ. 矛盾撞着, もつれた糸, すべて死が母胎であり, ふるさとでもある人生の愛すべく, また, なつかしい綾ではないか.
  私はまったく野心のために疲れていた. その野心は, ただ, 有名になりたい, ということだった. ところが私は, ただ有名になりたいとあせるばかりで, 何を書くべきか, 書かねばならるか, 真実, わが胸を切り開いても人に語らねばならぬという言葉を持たない. 野心に相応して, 盲目的な自信がある. すると, 語るべき言葉の欠如に相応して, 無限の落下を見るのみの失意がある. 23:45 2006/12/24 

** 我が闘争    アドルフ・ヒトラー    角川文庫
   この不確かさは, ただ自己がこういう堕落の悲劇に対して責任があると感じていることにその根拠がある. しかしそれは, 真剣なしっかりした決意を麻痺させ, そのため自己保持に一番必要な処置をとることすら動揺し, 弱く, 中途半端であるがため, そのようにしてしまうのだ.
   自分の責任であるという意識の陰影につきまとわれなくなったとき初めて, 内心の落ち着きとともに, 野草の芽を残酷にし, 断固として刈り取り, 雑草を引き抜く外面的な力を持つようになるのだ.

   際限もなく多く「読む人を私は知っている. しかし彼らは, 自分にとって勝ちあるものと価値亡き者を選別する技術が欠け, さらにあるものはいつも頭の中に保持し, あるものはできるなら無視するというように, どんな場合でも無用なやっかなものを引きずっていくことをしないという技術が, 欠けている. 読書というものは, それ自身目的ではなく, 目的のための手段である. 第一に読書は, 各人が自己の職業に必要な道具や資材を供給するべきである. しかし第二に, 読書は一般的な世界像を媒介すべきである. だがいずれの場合にも読書は, そのときどきに読んだ内容が, ほんの記述の順序や, あまつさえ読んだ本の順序によってとどめられるのではなく, モザイク様の石のように, 一般的世界観の中でそれらに与えられるべき地位に場所を占め, そして読者の頭の中にこの像を形成する助けとなることが必要である. そうでなければ, 混乱が生じ, 無価値であるばかりでなく, うぬぼれさせる. というのも, 彼が実際に大真面目に〓教養がある〓と信じ人生に関して何か理解しており, 知識を持っていると信じているからである. 知れば知るほど, 世間から遠ざかるにもかかわらず.
   今人生に, 突然なんらかの検討や解決を要する問題があるとするならば, ただちに既存の観念の喜寿運をとらえ, そこからこの問題に関係している過去十年間に集められたここに役立つものをすべて引き出し, 問題を解決したり, 解決したりするまで検討したり, 新しい検分をしたりするために, 知性を提供するのである.
   読書は, そのときのみ意義と目的を持つのである.
   日々の生活経験は, いろいろの問題を常に新しく研究しようとする刺激になった. ついには現実を理論的に基礎付け, 理論を実際で試そうという姿勢をとったため, わたしは, 理論の中で窒息してしまったり, 現実の中で浅薄化されたり売ることから免れたのである.

   理論的文献の中の自由とか, 美とか, 品位に関するきらきら光る名文句や, 見たところこのうえもなく深遠な知識を苦心惨憺して表現している大言壮語, いやみたっぷりの人道的道徳と, あらゆるウソと下劣さが混じった日刊新聞との間に, いったいいかなる区別があるというのか.

*** 大衆の心理
   大衆の心理は, すべて中途半端な軟弱なものに対しては, 感受性が鈍いのだ. 女性のようなものだ. かの女らの精神的感覚は, 抽象的な理性の根拠などによって定められるよりも, むしろ足らざるを補ってくるる力に対する定義しがたい, 感情的な憧れという根拠によって決せられるのだ. だから, 弱いものを支配するよりは, 強いものに身をかがめることをいっそう好むのである. 彼らは破廉恥な精神的テロや, 彼らが人間的自由を癪に障るほど虐待されていることにも気がつかないのだ. 彼らは全教説に潜む狂気に決して気づかないのである.

   最も重要な利害において, 態度決定するために必要な知識を持っているものが二, 三人しかいないのに, なぜ五百人も選挙するのか? 今日の民主主義的議会主義の目的は, おそらく賢人の会議を形成することでなく, むしろ精神的に従属しているゼロに等しい群を寄せ集めることにある. 個々人の人格的偏狭さが大きければ大きいほど, 一定の方向へ指導することがますます容易になる. ただそうしてのみ, 今日の悪い意味での政党政治がなされうるのである.

*** 演説の意義
   今日, 文筆のたずさわる騎士やうぬぼれ屋はみんな, 次のことをよく覚えておくがいい. すなわちこの世界における最も偉大な革命は, 決してガチョウの羽ペンで導かれたものではないのだ! ということを.
   そうだ, ペンにはつねに革命を理論的に基礎付けることだけが残されている.
   だが, 宗教的, 政治的方法での偉大な歴史的雪崩をおこした力は, 永遠の昔から語られる言葉の魔力だけだった.
   大勢の民衆は何よりもまず, つねに演説の力のみが土台となっている. そして偉大な運動はすべて大衆運動であり, 人間的情熱と精神的感受性の火山の爆発であり, 困窮の残忍な女神によって煽動されたか, 大衆のもとに投げ込まれた言葉の放火用たいまつによってかきたてられたかであり, 美を論ずる文士やサロンの英雄のレモン水のような心情吐露によってではないのである.
   だから偉大な目標を持つ運動は, 幅広く民衆と関係を失わないよう, 几帳面すぎるほど努力しなければならない.

   概してどんな時代でも, 本当に偉大な民衆の指導者の技術というものは, 第一に民衆の注意を分裂させず, むしろいつもある唯一の敵に集中することにある. 民衆の闘志の傾注が集中的であればあるほど, ますます運動の磁力的吸引力は大きくなるのだ. いろいろの敵を認識することは, 弱い不安定な性格のものにとっては, 自己の正当を簡単に疑わせるきっかけだけを作りやすいから, 別々にいる敵でさえも唯一つの範疇に属していると思わせることが, 偉大な指導者の独創力に属しているのである.

*** 宣伝は手段
   宣伝は手段であって, したがって目的の観点から判断されねばならない. それゆえ宣伝の形式は, それが奉仕する目的を援助することに有効に適合していなければならない.
   宣伝は永久にただ大衆のみ向けられるべきである! インテリには, 宣伝は不要であり, 学術的強化というものがある. しかし, 宣伝はその内容上学問ではない. 宣伝の課題は, 個々人の学問的な形式ではなく, ある一定の事実, ある過程, 必然性等に大衆の注意を促すことにある. そのためにまず宣伝の意義は, まず大衆の視野にまでずらさなければならない. その作用はいつもより多く感情に向かい, いわゆる知性に対しては大いに制限しなければならない.
   宣伝はすべて大衆的であり, その知的水準は, 宣伝が目指すべきものの中で最低級のものがわかる程度に調整すべきである. それゆえ獲得すべき大衆の人数が多くなればなるほど, 純粋の知的高度はますます低くしなければならない. 宣伝の学術的な余計なものが少なければ少ないほど, そしてそれがもっぱら大衆の感情をいっそう考慮すればするほど, 効果はますます的確になる.

   宣伝の技術はまさしく, それが大衆の感情的観念界をつかんで, 心理的に正しい形式で大衆の注意を引き, さらにその心の中に入り込むところにある. 大衆の需要能力は限られており, 理解力は小さいが, その代わりに忘却力は大きい. この事実からすべて効果的な宣伝は, 重点をうんと制限して, そしてこれをスローガンのように利用し, その言葉によって, 目的としたものが最後の一人にいたるまで思い浮かべることができるように継続的に行わなければならない.

   大衆は相手の不正がどこで終わり, 自分の不正がどこから始まるのか, そのとき判断する立場にはいない. そういう場合に彼らは不安になり, 邪推したりする.
   民衆の圧倒的多数は, 冷静な熟慮よりもむしろ感情的な感じ方で考え方や行動を決めるという女性的素質をもち, 女性的な態度をとる.
   しかしこの感情は複雑でなく, 非常に単純で閉鎖的である. この場合繊細さは存在せず, 肯定か否定か, 愛か増加, 正か不正か, 真か偽かであり, 決して半分はそうで半分は違うとか, あるいは一部分はそうだがなどということではない.

   宣伝工作の独創性はすべて, いつも同じに基礎的原則が鋭敏に顧慮されなければ, 成果は上がらない. 宣伝は短く制限し, たえず繰り返すべきである. 宣伝の分野こそ, 耽美主義者や鈍感なものによって決して指導されてはならない. 前者からは, その内容が形式上, 表現上やがて大衆に通ずる代わりに, その魅力が文学的お茶の会向きになってしまい, 後者は独特な新鮮な感覚がかけているために, いつも新しい刺激を求めてくるからだ.
   大衆は, ひとつのことについて知識をもとうという気になるまで, いつも一定の時間を要する. 最も簡単な概念を何千回も繰り返すことだけが, 結局覚えさせることができるのである.
   変更のたびに, 宣伝によってもたらされるべきことを決して変えてはならず, 結局はいつも同じことを言わなければならない. 継続とその利用のむらのない統一性が成果をもたらすのだ.

   不可能に見える要求や課題を満たすためには, 民衆の全注意を, ただこの一つの問題に限って統一しなければならない. しかもその解決に実際, 生死がかかっているかのように, 注意させなければならない.
   征服しなければならない行程を, 個々の段階に分割し, 諸段階を計画的に, あらゆる力をきびしく集中して, 一つずつ克服しようと努力しなければならない. 目標に向かって近づこうとする, この努力は一つの技術だ.

   腐った肉体は輝かしい精神を吹き込んでも, 全く美しくならない. ギリシャの美の理想を不滅ならしめたものは, すばらしい肉体の美と輝かしい精神と, 最も高邁な心情との驚くべき結合である.

   すべての若い同胞の教育や訓練は全体に, 自分たちが他のものより絶対に優っているのだという確信を与えるようにはかれねばならない.

   95%までは, 若い頭脳が必要とせず, それゆえ忘れてしまうようなことは一般的に詰め込まれるべきでない. 精神的な需要能力, 思索能力, 特に頭脳の記憶力の訓練だ, というのは一部正しい. しかし, 重要性の多い少ないによって個々の要素がふるいにかけられたり, 評価したりもできないような, 多くの印象を横溢させることに危険がある. たいてい本質的でないものだけでなく, 本質的なものを忘れてしまい, 無駄になる.
   人間が若いときにたくさんの知識を詰め込まれすぎるために, その後これをもはや全体に忘れてしまっているか, あるいはまさしくその中の本質的なものを, もはやとっくの昔に忘れてしまっているならば, これは妄想になってしまう.

   演説にさいし, 敵の手からただちにその抗弁の武器を叩き落すことが重要である. どんな演説のときにも, 討論の際に出てきそうな相手の異論の内容や形式を想定して, 前もってはっきりとしておき, そしてこれをさらに自分の演説の中で, 手回しよく残るくまなくやっつけることが重要である. 出てきそうな反駁自体をいつもただちに挙げて, そしてその根拠の薄弱さを示すことが, その場合有効であった.

   朝は・・・日中ですらもそうだが・・・人間の意志力は, 自分と異なった意図や異なった意見を強制しようとする試みに対しては, この上ないエネルギーで抵抗するように思える. これに対して晩には, それらはより強い意志の支配に, もっと容易に屈伏するのである.

** 今日の芸術  岡本太郎  光文社

  すべての人が瞬間瞬間の生きがい, 自信を持たなければならない, その喜びが芸術でもあり, 表現されたものが芸術作品なのです. 近代は, 自己疎外が起こり, 人間の個々の動きが部分化され, 目的, 全体性を見失ってくる. 社会的生産が自分本来の創造の喜びと一致しない. 瞬間瞬間の自己放棄, 不条理, 無意味さ, バカバカしさ. ほとんどの人は諦めて適当にやってます. 芸術とは, 失われた人間の全体性を奪回しようという情熱の噴出といっていいでしょう. 現代の人間の不幸, 空虚, 疎外, すべてのマイナスが, このポイントにおいて逆にエネルギーとなってふきだすのです. 力, 才能の問題ではない. たとえ非力でも, その瞬間に非力なままで, 全体性を現す感動, その表現. それによって見るものに生きがいを触発させるのです.
  失われた自己を回復するための最も純粋で, 猛烈な営み. 自分は全人間である, ということを, 象徴的に自分の姿の上にあらわす. そこに今日の芸術の役割があるのです.

  「いい」と思ったとき, その人にとって, そう思った分量だけ, わかったのです. いつでも自分に率直に. 何かを発見すれば, それがあなたにとっての価値なのです. 絵は, クイズではありません. 白紙でどんどんぶつかってゆき, それによって古い己を脱皮し, 精神を高めていくべきです.
  優れた芸術家たちは, たくましい精神で, 常に前進し, 新しい創造をしています. 当然, 持ち合わせの常識では, ただちに判断できません. つまり, 創造と鑑賞は永遠の追いかけっこです. この驀進の中に芸術と, その鑑賞の価値があるので, とどまって固定的に理解されるものではないのです.

  芸術は, 絶対に新しくなければなりません. 新しいということは, 芸術の至上命令であり, 絶対条件です. それは, 美術史, 芸術史がそれを明らかに証明しています. 芸術は, 時代の要求にマッチした流行の要素を持っていると同時に, 実は流行を突き抜けて, 流行の外に出るものです. しかも, それがまた新しい流行を作っていくわけで, 実際に流行を根源的に動かしていくのです. 芸術家は, 時代とギリギリに対決し, 火花を散らすのです.

  人に先んじ, 無理解と戦いながら問題を出す. そして, 新しい美を発見していく. 猛烈なぶつかりあいが, 刺激になって世の中を進めていく. 最初に抵抗によってつくられたものと, 後で抵抗なくてつくられたものとは, その中にこもった気配がどうしても違います. 内容が違うのです. 一方は, 実際に激しさを内に秘めた, 純粋の芸術的な発想. 大変な努力と精神力によって自分自身を開いていった, 苦悩によってだけつかみとるなにものかであり, 他方は, それを応用してつくった, 惰性的な気分でも受け入れられるようになったもの.
  
  本当の芸術とは, これまでのすぐれた芸術の条件が全くなくして, しかも見るものを圧倒し去り, 世界観を根底から覆してしまい, 以後, その人の生活自体を変えてしまうというほどの力を持ったものです.

*** 芸術はここちよくあってはならない
  すぐれた芸術は, 鑑賞者に一種の緊張感を強要します. 見る人は持ち前の知識では理解できず, そこに不安を感じるからです. モダニズム芸術ならば安心感がありますが, 創造的な芸術には不安があります. しかし, 芸術家は激しい意志と決意を持って, 規制の常識を否定し, 時代を新しく切り開きます. 創造者とほとんど同じ緊張感, 覚悟を持って, 逆にこちらも, 向こうを乗り越えていくという気でぶつからないかぎり, 本当の芸術は理解できないものです. つまり, 見るほうでも創造する心組みでぶつかっていくのです. そうして, 作品に追いつけない場合には, 疑惑と苦痛感を覚えるものなのです.

  愛されるようになったゴッホは, もはや, われわれに今日の問題を投げかけてはいません. その生涯は, 今なお残酷にわれわれの心を打ち, 芸術家の共感を呼び覚ますものがありますが, 作品はすでに今日の問題ではないのです. 現在のわれわれに暴力的に働きかけてくればこそ, いやったらしい. だからこそ, 強烈にひきつけられる.

  生活にぴったり合って, ずれを感じさせないモダニズムは, 素直に楽しめる. しかしそこには, 生きてあることの力とか恐ろしさ, 根源的な歓喜というものを感じることはできません. つまり, 芸術・人生における第一義ではないのです. いわば, よい意味でのレクリエーション, 気晴らしでしょう.

  ところで, これとはべつに, 何かこちらの気持ちの中に入り込んできて, 麻酔薬のように末梢神経をしびらせ, 一種の慰めと陶酔感を覚えさせるようなものもあります. 俗受けする絵画の大部分がそうですし, 私小説, エロ小説, メロドラマ, 歌謡曲, 浪花節など, みなそれです. しかし, これは人間を低さや弱みに妥協させ, 甘えさせるもので, およそ精神を積極的に高めるものではありません.

*** 芸術はきれいであってはならない
  きれいさということは, 芸術の本質とは無関係です. 女の顔が綺麗だとか, 着物の模様が綺麗だとかは, ただ単純な形式美をさしています. それは, かならず見慣れてしまうものであり, 見あきるものです. それは自分の精神で発見するものではなく, 時代の典型, 約束事によって決められた型です.

芸術はうまくあってはならない
  うまいことも, 芸術の本質とは無関係です. しかし, それを勘違いして, いわゆる職人的巧みさとか器用さなどというものが絵の価値, 芸術の精神的内容みたいに, ごっちゃにされ, すりかえられている面が多いのです.

  芸術は創造です. これは, 決して既成の型を写したり, 同じことを繰り返してはならないものなのです. 芸術の技術は, つねに革命的に, 永遠の創造として発展するのです. これが芸術の本質です.
  これに対して芸は, 古い型を受け継ぎ, それを磨きに磨いて発達するものなのです. 芸術が過去を振り捨てて新しさに賭けてゆくのに, 芸道はあくまでも保持しようと思います. 定められた型の中で完成するのです.

  まず, 誰のために描くのか, したがって何を描いたらいいのか・・絵描きは苦しみます. 描かなければならない真の絵とは何だろう. いったい絵画とは何ぞや, という問題になった. そういうことを自分の責任において, トコトンまで突っ込み, 社会, 人類に対して, これだという一つの答えを出さなければ絵はかけない. この虚無を乗り越えて, 絵画は芸術となったのです.

  芸術の本質は技術であり, 芸能の本質は技能です. 技術は, つねに古いものを否定して, 新しく創造し, 発見してゆくものです.

** 辻邦生
   一体文学に何ができるのか, 「美」などというものに果たして存在価値があるのか・・・この重苦しい疑惑が青年時代の辻邦生の心を長い間占めていた.

   ある日, 啓示のように「西欧の光」が差し込んだ. 目の前に広がる見慣れたパリの家並みの奥に「街を形成し, 街を支え続けている精神的な気品, 高貴な秩序を目指す意志, 高いものへ登ろうとする人間の魂」がはっきりと姿を見せたのである.

   かつて, 僕はパルテノン神殿を見て, 「美」という大いなる秩序を感じた. 人間は現実の荒廃と虚無に抵抗して高貴な秩序を求め, そこに人間として生きる意味を見出してきたのだ. パルテノン神殿は大いなる秩序であり, 僕らはその中に入るとき, 人間である喜びを感じるのだった.
   真の理性による思索はあくまでも人間存在の枠の内部の思索であり, かつての神の秩序にかわって理性の秩序を作り出し, 人間存在を守る働きをする. この人間的心情に基づく美の秩序の中にあるとき, 世界は単なる外界ではなく一つの意味を持った存在となり, それと自己とが一体となって生きていることを爽やかな快感と共に実感して, 生存の喜びを覚えるのである.

   僕らは人間の幸福のために美の世界を作るべきではないだろうか. 才能の問題ではない. 好きでさえあれば, あれこれ考える前にやってみるのだ. (06/7/16) 
