#+OPTIONS: toc:nil
* Philosophy: 哲学
  哲学について
* 読書記録
** ヨブ記  (旧約聖書)  関根正雄訳  岩波文庫

ヨブは, 幸福に包まれて, 神を敬い生活していた. そこでサタンは, 神に言った. 「ヨブは, 利益もないのに神を敬うでしょうか? 」そこで, 神は, そのことを試すために, 命以外のすべてのものを奪って, 彼に苦難を与え, ヨブを観察してみた. ここまでが序曲.

ヨブはまず, 自分の存在を嫌悪し, 死への願望を持ち始めた. 「なぜ, よりによってオレがこんなにも苦しまなければならないのか, 何も悪いことをしてないのに」しかし, この段階では, 神を呪っていない. 「この苦難にも意味があるはずだ. 神が何の理由もないのに, 苦しめるはずがない. もしかしたら, 過去にした罪を俺は見逃しているだけかもしれない. そうだ, 罪があるはずだ. その報いを果たさなければいけないのだ. しかし, わからない. いくら考えても, こんな目にあうようなことをした覚えがない. なぜ? なぜ? わからない. 教えて欲しい! 神と直接話して, 教えて欲しい! 」

友達たちも, ヨブに罪があるから神は苦難を与えるのだ, といった. エリパズは, 「神は世界をそれ自身の法則に委ねているので, 君の不幸も神から与えられるのではなく, きみの罪から自動的に発生するのだよ」, といった. エリフは, 「きみは何も悪いことはしてないが, 君には謙虚さがない. 君は何も知らないし, 無力だ. きみは自分を正しいと思っているが, きみは何も知らないのだ. そのことを自覚しなさい」. といった.

しかし, ヨブはそれに納得がいかない. 友達に反論しているうちに, ついには, ヨブは「自分は正しい! 自分には罪がない. 神が間違っているんだ! 」と思うようになる. ここで, ついにヨブは, 神を呪った. 神と自分を対等の位置に置き, 命がけで, 神と対決しようとした.

そこで神が現れた. 神はヨブに言った. 「お前は神なのか? 私はすべてを知っている. 私は全能だ. お前は何も知らない. お前は何もできない. お前は弱い. 私が全てだ. 私に従え」. ヨブは, 言った. 「おっしゃるとおりです. 従います」. ヨブは, 自分の無知を自覚した. 謙虚さを身につけた.

神は, 友人たちに「お前たちはエゴイストだが, そのことに怒っているぞ」といった. ヨブは神から恩恵を受け, 幸福になった.

** パンセ  パスカル 
   「あきらかに, 人間は考えるために造られている. それは彼のすべての尊厳で あり, 彼のすべての価値である. 彼のすべての義務は, 考えるべきように考えることである. ところで, 思考の順序は, 自己から始めること, 又自己の創造者と自己の目的か ら始めることである」. (146)

   「思考が人間の偉大をなす」. (346)

   「人間は自然のうちで最もひ弱いひとくきの葦にすぎない. しかしそれは考え る葦である. ・・・・」 (347)

   「考える葦. ・・・・空間によって宇宙は私を包み, 一つの点として私を呑む . 思考によって, 私は宇宙を包む」.

** ハイデガー=存在神秘の哲学  古東哲明  講談社現代新書
   存在は, とほうもなくうまい. 至高の味がする. 極上のワインの百兆倍. この世のものとは思えないほどだ. 極度にありえないことがありえている. そんな香味さえただよう. それを一瞬でも味わえば, あらゆる悩みが消えてしまうほどだ.
   
   生の事実性. だから, 死んでいるのではなく, あくまで現にこの世に生きてあることそのこと. そんな生や世界の存在に, ありありとでくわす. そしてあらためて驚く. 「驚異中の驚異, つまり存在者が《在ることそのこと》を経験する」なにごとも, 失ってはじめてわかるのだ. 死が失うものは生, そしてこの世の存在. 気づいた当人にとっては, とんでもない悦びがはじけとぶ体験だ. 存在忘却の根本体験といわれている. 存在神秘とは, この世の存在の法外な凄さ (天国性=志向性) に撃たれる体験. 「神の死」 (ニヒリズム) のときには, 不安や吐き気の対象でしかなかったこの世この生. その存在の事実が, 気づいてみればあまりにも凄い. あまりに凄すぎ<この世ならぬ>ほどの驚嘆をひきおこす. この世ならざる何か超絶的な説明原理 (神のようなもの) でも想定しないと, おさまりがつかない. それほどこの生を, あるいはこうしいて生きることそのことを, 神々しく思うということである.

*** 最初に置かれる神
   いわゆる創造神. この世という被造物を作り出した起源として想定された神. キリスト教伝来の神も, 諸神話の神々も, おおむねそうだ. こうした起源神を最初に置けば, もう悩みは起こらない. 後は以下にそれにあわせてこの世を生きたらよいのか. そんなハウツー的事後問題式を解くばかり.

*** 途中で求められる神
   病気. 生活苦. 存在不安. 愛しいものとの永訣. さまざまな苦しみがぼくたち人間を襲う. つらい時だ. その激しい苦しみや不安に耐えかね, つい求められてしまう神. それがこの途中神. 救済神とか救世主.

*** 最終最後の神
   それまでの神は, 存在不安やこの世の存在のわからなさを<解消>する神. 苦しみを緩和したり, なぞや疑念をなくしたりするために持ち出される一種の護摩だ. 薬. 麻薬である. その意味で, 創造神も途中神もとても役に立つ. おかげで, この世この生は否定されたまま. どこまでもニヒリズムを隠蔽して成り立つ<生活の知恵>にすぎない. だが, 最後の神は違う. 存在が神, 神とみまごうほど神々しい, ということである. 存在神秘の体験が, はじめて最後になって, 神なんてものを<存在>させるにいたるということである. こんな凄い存在を可能にしたなにかとして, 神なるものを想定しても不自然ではないほどの感興に包まれるという意味である.

   「存在の真実からはじめて, 聖なるものの本質を考えることができる. 生なるものの本質から始めて, 神性の本質を考えることができる. 神性の本質の光り輝く中で初めて, 《神》という言葉がなにを言っているのかを考え言うことができる」.

   繰り返すが, 順序が大切だ.

   - 神の死
   - ここで死ぬ神とは, 創造神や途中神, あるいは超越的な究極原理のことである.
   - 存在不安・存在否定
   - 擬死の極致
   - 存在神秘・存在肯定
   - 最後の神 

   《神の死》を真剣に引き受けて, さまよい, 惑い, 苦しみ, 死ぬほどの破局の果てに, まるで思いもしなかった《別の神》を体験する. それは, 最後に神さえ想うほど, 深く真正面から, 存在の真理 (存在神秘) に撃たれたことの別表現. そしてそれだけのこと.

*** 世界劇場論
   「世界は劇場, 人生は演劇, 人間は役者」 (シェイクスピア). そう思いきり, この世この生を, 一幕の舞台劇と見立てる世界観. それが世界劇場論である. 世界と生のリアリティ (真実性) を透視する, 西洋古来のの解釈装置, ものの見方, 考え方である. それは, それまで夢中で熱演し没頭していた現世の悲喜劇を, 観客席のように場外に立って突き放してみる工夫. つまり, 存在神秘に撃たれることですべて吹っ切れ, 再び人生劇に復帰し, 今度は, 目覚めながら生きなおす道である.

   役者の立ち振る舞いを触媒に, 「なんにもない空間」 (P. ブルック) に突然, 濃密な意味と情動の空間としての演劇世界が浮かび上がってくる. まるで「無からの創造」. ぼくたち観客も, もはや絵空事とは思えない感動空間 (演劇世界) にすっぽりとつつまれてしまう. しかもそれはじつに動的. 役者の一挙手一投足に, あるいは照明の光彩や音楽の鼓動に微細に呼応しながら, 刻一刻, そのすがたをかえる. 演劇は, まさに劇的に流動する複雑な運動体.

   まずいえることは, 生と世界の密接な結びつきである. ぼくたち人間が生きる生の現場にはかならず, ある一定の「世界」がつむぎだされてくる. 重層的で可動的で濃密な, 意味と情動のネットワークとしての「世界」が分泌されてくる. つまり, 生と世界とは, 分離不可能な仕方で錯合しあっている. 世界は生に依拠し, 生との深い相関性の中で初めて成立する. まず世界なるものがあって, そのあとに人間の生がはいりこんでくるのではない. 世界を生み出すのは, ぼくたち人間の生. 人間の生抜きの世界などない. 逆に, 無世界的な生もありえない. 生と世界は一体二重的に生起する.

   独我論的方向で誤解してはならない. ぼくたち人間の生は, 世界の包まれ, その統制下におかれている. それは, 役者が, みずからつむぎだしているはずの演劇世界にすっぽり包まれ, そこに没入し, さらにその世界に逆に規定されてはじめて生きた舞台が進行するのと, 同じことだ. 生は, 自ら分泌する世界に逆規定され, 世界依存的であることで, 生たりうる. 演劇世界が何か物質的事柄ではなく, 重層的に織り上げられた不可視の意味と情動の空間であることを考えれば, 「世界」の本質的な性格 (世界性) が, 意義連関とされた理由も, ご理解いただけよう.

   だからといって, 世界は個人的なものなのではなく, 同時にすでに最初から, 共同世界的な成り立ちをしている. 大小の舞台装置, 役柄, 場面, シナリオが複雑に絡み合う生活コンテキスト (世界性) が刻一刻形成され, その不可視のコンテキストに多面的重層的にに織り込まれるようにして初めて, ぼくたち個人の生存活動が, 実現されていく. 世界は同時に共同世界なのだ.

   場面, 場面でどう演じたらいいのか, その役者の一挙手一投足が可能になるのは, あたりまえのことであるが, まずはすでにある特定の舞台劇に出演してしまっているからであり, その場に出来上がっている筋立てや雰囲気に暗黙裡に入り込み, 一体化できているからだ. つまり, 演劇内世界にすっかり没頭し, 「はまっている」からである. これが被投性であり, そこにピタッとはまって没頭し<眠る>側面が耽落という. ぼくたちはふだん, この世の人生舞台にすっかり思いを吸い取られ, 夢中になり没頭して生きる姿を, うまくとらえている.

   ぼくたちは, 役者同様の二重分裂構造と自己消去構造を生きている. むしろ生きざるをえない仕組みになっている. このしくみ, 現代思想の文脈では「演劇体制論」 (エヴレイノフ) とか「役割存在論」 (ゴフマン) として, よくしられたことである. その際, 演じている役柄上の自分と, 演じている自分は別物だ. ハイデガーは, 生身の役者レベルの自己を本来的自己と名づけ, 役割上の自分をダス・マン自己となづけた. だが通常ぼくたちは, あまりにも賢明に, 与えられた役柄や立場を生きてしまう. 生身の自分のことなど忘れ, ひたすら役柄になりきっている. 「世界」に夢中なのだ. そのうち, 演じている自分自身など, 忘れてしまう. むしろ自己忘却こそ, 毎日を, 生き生きとスムーズに生きるための前提. そのうち, 役柄を自分自身と取り違える. 懸命にこの世を生き, だからこの世に没頭し, だからこの世での役柄と同一視してしまう. これが, 耽落だ. 耽落は生きがいに満ち, 活気ある人生を送るために, ぜひ不可欠な要素だ.

   不安の正体とは, この自己分裂構造である. この世に生きていること. それは二重性の中で生きることだから, 構造的に不安定だ. だから静かに不安だ. ズレを生きるのだから, いやでもそうなる. 自分ではない自分 (ダス・マン) と自分自身とが統合され, 均等を保っているうちはいい. だが, 限度がある. まさに, 自己分裂症に陥るわけだ. 普段は, 通奏低音のように, かすかに響くばかりである. その地底に響く根本気分 (不安) が, 突如噴出すときがある. スムーズに流れていた舞台劇が停留したり, 破綻するときである. 慣れ親しんでいた自明な舞台劇全体が, なんだか嘘っぽく, 実は居心地の悪い場所と化す. 共演者たちも, そこに貫通していたシナリオ (思想・規範・道徳) もすべてが, その慣れ親しんだ表情を剥落させ, 不気味な相貌で押し迫って来る. 離婚を決意した日の家庭劇のように.

   それは, 夢 (ねむり) からさめただけだ. 舞台上で悦に入っているダス・マン自己にたいし, 本来の自己が「それはわたしではない」という自己疎外の声を, 静かに上げていることの別表現である. 懸命に生きてきた熱演舞台への没頭状態 (耽落) から, フーッと覚めるのである. そんな不安が明確に訪れるのは, やはり死を痛感するときだ. この世という舞台も幕を下ろす. その終幕を実感するそのとき. 不安 (=自由) は最高潮に達する.

   ハイデガーの死の思想は, 最期 (生の末端の死去のとき) が, 実はどの瞬間にも当てはまる様式だと見抜くところにある.

   「死は, 現存在 (生) においてまだ未済ななにかのことではない. 死は, 現存在 (生) が現存在であるかぎり, その存在の中で差し迫るもの, しかもたえず差し迫っているもの」

   「死への存在」とは, 日常性. まさに「死の瞬間が生命の標準時」というわけだ.
  
   動画である上映中の画面は, 映し出された端から消失し, 消失しながら同時に現出しているはずだ. 同様に, 死が生で, その生が死となり, その死において生がはじまる・・・. そんな生 (初発) と死 (終滅) との奇妙なパラドックス構造, あるいは同時進行. だからもはや, 終わりと初め, 死と生といった思いなれた二分法では割り切れない, 両項の奇妙な回互運動の中で刻一刻, 画面が生起してきているのだ. 毎瞬毎瞬が終わっていく動性と, 始まってゆく動性. この仏なら互いに矛盾しあうにこうの同時進行現象として生起していることを, うっすらと感じ取れるのでは? この二つの動性があいより, しのぎあう, 張りつめた一点に, 刻一刻の生の瞬間が成立しているはずだ.

   「死とは, 人生の経過のつながりがパチンと途中で途切れること」
   「死は生の現象である」
   「死は, 現存在が存在するやいなや引き受けている在り方なのである」.

   時とは, 一瞬の運動生起. そして, はかない刻一刻の<時>が, 現存在の全貌というわけだ. 死して消失してゆく将来的動性は, しかし同時に, 次の瞬間を取り戻し創出させ, 死なずに「在った」という既在的動性へ変成し, その結果, 刻一刻の現在へ見開かれていくことに, 連なる. この三つの動性 (将来性・既在性・現在性) が, 三位一体的に作り出す一瞬の生起, それが時だ. 消えてなくなろうとしているはずなのに, その将来的な動性としての「死の可能性のほうから, 立ち戻って《生誕すること》」が結果とし, 存在してしまっている. 「事実的な現存在は生誕するという仕方で実存しているが, しかしまた, 死への存在という意味では, 生誕しつつも死んでいるのである」. この将来的動性 (死への存在) と既在的動性 (生誕への存在) とが同時進行するその, もはや一瞬の間隔すらない<間>に, 今ここの現在のときが, 刻一刻, 実っていく. それはもはや静止画像のような「停止現在」ではない. 一方で死へ, 他方で生誕へ向かう, ある張りつめた力動現象. 打ち寄せる波の波形が, 実は空と海との間の実体なき境界線でしかないように, 現在もまた, 固定的実体ではない. そして, このはかない一瞬のときを刻んで生きるぼくたち現存在のあり方. これが刻時性というのだ.

   前駆と後駆が合わさって初めて時 (生) という車輪が動く. 刻一刻の死への動性 (前駆). そのつもりで前駆する車輪 (生) なのだがしかし同時に, 後駆し, 今この一瞬の生へ立ち戻ってしまっていく. これが既在性の動性. そのことに気づいて, 自覚的に生の車輪を駆動させていくことが「本来的刻時性」であり, そのことに気づかず生の車輪を生きている姿勢が「非本来的刻時性」である. ぼくたちは, 車輪 (時) の痕跡を, 車輪そのものと取り違えている. しかし, それは錯覚だ. リアルな時をすっかり忘れ, 時が残していく線状の痕跡 (轍・足跡) を時だと勘違いしているのだ.
  
   音は現れては消え, 消えては現れる. むしろ消えながら現れる. 「音楽は, 音をどうならすかではなく, どう消すかの工夫である (武満徹) 」いずれにしろ, 現出かそれとも消失かの二者択一しか認めない, ぼくたちにはなじみの二分法思考を軽々と突き破って, もはや両者が同時進行するとしか言いようのない緊密さで, 音は経験されてくるはずだ. 音は在るのに無い. まるで時の構造といっしょだ.

   森羅万象は, 死と再生との, 相互矛盾的な同時同一性の中に生起する. ニーチェも言うように, 「あらゆる事物には同時に, 消滅と生成という二つの顔がある」ぼくたちは, 毎瞬死んで, 毎瞬に生まれ直している. 消滅 (死滅) が同時にその出現 (生誕) というわけだ. ハイデガーは, 「存在と無は同一」  「在と非在との根源的な回互性」「滅びの中の生成」といっている.

   「存在と無とは同一」というとき, 厳密には, 次の三つが同時に示されている.

*** 存在の非-存在者性 (存在は存在しない)
   存在するもの (たとえば神) の存在を仮定したとする. 「存在は存在する」. すると, 存在は在るもの (存在者) ということになる. とするとさらに, その「在るものである存在」はどうなるか. これも初めの前提より, 在ることになる. つまり, 「在るものである存在」は存在する. だがそうなると, さらにその存在, さらにさらに・・・と, つまり「在るが在るが在るが在るが・・・・」となる. この連鎖に限りはないから, 議論は無限にさかのぼり, 無限退行の誤謬に陥ってしまう. よって, 背理法によって, 「存在が存在する」としたのが誤りであった. つまり, 存在は無にほかならないのだ.
   存在には, 二者択一の論理は通用しない. あえて言えば, 存在は, 無と化す, 隠れるという仕方でしか<現れ>ない. まるで空気. まるで夜. 存在は説明化や存在者化を越えた秘密としてしか生起しない. だから, 万物はそもそも, 人間側の自然な意味づけ・説明欲・合理化・生活感情を, 横暴に踏みにじるという仕方でしか, 存在しえない.
   存在の無底性 (存在は底なしだから底)
      
*** 存在の非在化 (存在は念念起滅そのこと)
    他律的な上福構造
    この世この生それ自体の自律的 (内在的) 意味や価値や目的や理由を説明してはいない. いつかどこかに仮想された「最高価値」から, 他律的に, 価値や目的や理由を授与する方式.
    
    だから当然, 希望が叶えば, 浄福はきえる. それを防ぐために, 更なる希望を作り出す. 高校では大学入学を, 大学では就職, 家庭という希望をつくり, それを求めて競い合う. そうやって, 芋づる式の他律的浄福論を連続させ, やがて死ぬ.
    
    それが虚構の幸せだとしても, それを求めて努力することは幸せだ. しかし, いったん手に入ると, それが徒な希望であることがわかり, 極度の意気喪失と絶望感が襲うのだが, それゆえさらに激しく, 新しい希望を打ちたて, それに邁進してゆく.
    
** 嘔吐 サルトル
   私たちは, 自分自身に迷惑し, 困っているものの堆積であった. 私たちは一人として, そこにそうしていることの理由をもたなかった. それぞれ存在するものは, 当惑し, なんとなく不安で, 互いに他のものとの関係において余計なものである, と感じていた.

** 純粋理性批判 カント
   形而上学は危機に瀕している. 合理論は独断主義に, 経験論は懐疑主義に陥ってしまった. 形而上学は人間理性の一切の能力を超えているのだ. 哲学の義務は, 誤解から生じたまやかしを除くにあった. したがって, 私がここになすことは, 人間の理性能力一般を批判し, 形而上学の源泉, 範囲および限界の規定である.

   すなわち, 「学としての形而上学は可能であるか」である.

   (そこで, カントはまず人間の認識のメカニズムの解明に取り組んだ. それは, 経験的素材を人間の純粋理性が能動的に整理することにより知識が成立する, というものである. (対象⇒直観⇒感性⇒悟性⇒理性の順) これで, 形而上学の中の存在論が片付いた. 次に, 霊魂論, 宇宙論, 神学の批判に入る. (この三つは特殊形而上学という) すなわち, 魂の不死, 宇宙の無限性, 神の存在は人間の理性では証明不能であることを明らかにした. これにより, 形而上学が学として成り立たないことを示した).

   理性を使用することの究極目的は, 意志の自由, 心の不死, および神の存在の証明である. しかし, 今までの議論により, その可能性は否定された. けれども, 学問としては成り立たなくても, 信仰としてなら成り立つのだ. 私は, 道徳的に, これらを確信している.

   私たちは一定不変の自然法則に従って行動している. それでも, 意志の自由を確信するとはどういうことか. それは, 道徳的法則が自然法則と重なるように行動する, ということだ. 道徳的法則とは, 幸福 (われわれの一切の傾向を満足させること) に値するということだけを動因とするような自由意志の法則である. すなわち,
   「幸福を受けるに値するように行動せよ」
   , ということである. このとき, 私たちは完全に自由になり, かつ, 必然的に行動しているのである.

** 啓蒙とは何か? その問いの答え カント
  啓蒙とは人間が自らに責めのある未熟状態から脱出することである. 未熟状態とは, 他人の指導なしに自らの悟性を使用する能力のないことである. この状態は, 決意と勇気との欠如 (怠惰と怯に原因がある. したがって, あえて知れ! (Sapere  oude!) 汝自身の悟性を使用する勇気を持て!

  啓蒙のためには, 自由以外何も必要とせず, その中で最も無害のもの, すなわち, 自己の理性をあらゆる面で公的に使用する自由より以外のものは何も必要とせられない. 自己の理性の公的な使用はいつでも自由でなくてはならず, また, 自己の理性の私的使用はしばしば非常に狭く制限されてよいのであり, このことによって啓蒙が妨げられることはない.

  理性の公的使用とは, ある人が学者として読者界の全公衆を前にして彼自身の理性についてなす使用を意味している. 私的使用とは, ある人が委託されている市民的地位あるいは公職において彼の理性についてなすことが許されている使用のことである.
  公共体の利害関係が関わる用務には, ある種のメカニズムが必要である. これを介して若干の構成員は受動的に行動しなければならないが (なぜなら秩序を守るため), これは彼らを政府によって人為的な一致を通して公的な諸目的に適合させるためであり, この目的の破壊から遠ざけておくべきである. したがって, この受動的部分であるものが同時に全共同体の構成員, それどころか世界市民社会の一員とみなし, 公的に著書を通して語りかける学者の資格のあるものとしてみなすならば, 彼はもちろん議論してさし支えないのであり, このことによって彼が受動的構成員として部分的に任ぜられている用務が傷つけられることはない.

** 方法序説  ルネ・デカルト  落合太郎訳  岩波文庫
   私は書物による学問をまったくやめてしまった. そうして私自身のうちにか, あるいは世間という大きな書物のうちに見いだされうるであろう学問のほかは, どのような学問にしろもはや求めまいと決心し, 旅行するために, 宮廷と軍隊とを見るために, 運命の差し出す偶然の事件で己を鍛えるために, またいたるところで目の前に現れてくる物事については, そのものから何か利益を引き出せるような反省を加えるためにも, 私は残りの青年時代を用いたのであった. おのれに何の影響も与えぬ空理のために, 学者たちが書斎で操る推論においてよりは, 一つの判断を誤ればすぐにも処罰されればならぬ結果をきたすような, おのれにとって重要なことのために各人が試みる推論においてこそ, はるかに多くの真理に出会うことができようと思われたからである.

   第一は, 明証的に真であると認めることなしには, いかなることをも真であるとして受け取らぬこと, すなわち, よく注意して即断と偏見を避けること, そうして, それを疑ういかなる隙もないほど, それほどまで明晰に, それほどまで判明に, 私の心に現れるもののほかは, 何物をも私の判断に取り入れぬということ.
   第二は, 私の研究しようとする問題のおのおのも, できうる限り多くの, そうして, それらのものをよりよく解決するために求められる限り細かな, 小部分に分割すること.
   第三は, 私の思索を順序に従って導くこと, 知るに最も単純で, 最も容易であるものからはじめて, 最も複雑なものの認識へまで少しずつ, だんだんと登りゆき, なお, それ自体としては互いになんの順序もない対象の間に順序を仮定しながら.
   最後のものは, なにひとつ私が取り落とさなかったと保証されるほど, どの部分についても完全な枚挙を, 全般にわたってあますところなき再検査を, あらゆる場合に行うこと.

   第一の格率は, 神の恵みをもって私を幼い時から育ててきた宗教をつねに守りながら, またその他のすべてのことにおいては, 私がともども生きてゆかねばならぬ人々のうちの, 最も聡明な人たちが実践上では一般に承認する最も穏健な, 極端からは最も遠い意見に従って自分の舵を取りながら, 国の法律および習慣に服従してゆこうということであった.
   第二の格率は, 私の平生の行動の上では私に可能である限り, どこまでも志を堅くして, 断じて迷わぬこと, そうしていかに疑わしい意見であるにせよひとたびそれと自ら決定した以上は, それがきわめて確実なものであったかのように, どこまでも忠実にそれに従うということであった.
   第三の格率は, 運命に, よりはむしろ自分に打ち勝とう, 世界の秩序を, よりはむしろ自分の欲望を変えよう, と努めることであった. 一般的に言えば, 私どもの権力の府内にそっくりあるものは私どもの思想だけである. したがって, 私どもの外なるものについては最善をつくしたのち, なお私どもの成功を妨げるものがあれば, 私どもの関係上, そのものはすべて絶対的に私どもの及ばぬものであると信ずるように自分をしつけること. この格率はただこれだけで, 自分にはえらるまじきものを未来に得ようなどと, 虚しい欲望を起こさないために, つまり足ることを知れと戒めるために, 十分であると私には思われた.

   私の理性を開発するために, 私が私に命じた方法に従って力の限り真理の認識へと前進するために, 全生涯を使い尽くすことにより以上に善いことをなしえないと私は考えたのであった. 私はたえず自分の計画を追及してやまなかったのだ. かくて書物を読むだけの, 学者と交わるだけのことに過ぎなかったであろうよりは, 私としてはおそらくそれ以上に真理の認識において前進してやまなかったつもりだ.

   私がそんなふうに一切を虚偽であると考えようと欲する限り, そのように考えている「私」は必然的に何物かであらねばならぬことに気づいた. そうして「私は考える. それ故に私は有る」というこの真理がきわめて堅固であり, きわめて確実であって, 懐疑論者らの無法きわまる仮定をことごとく束ねてかかってもこれを揺るがすことのできないのを見て, これを私の探求しつつあった哲学の第一原理として, ためらうことなくとることができる, と私は判断した.

** <反>哲学教科書 ミシェル・オンフレ
   極東の地の麗しい光に包まれて, 私は京都の寺にいる. ここには誰もいない. 静寂は長く, 濃密で, ゆっくりと流れていく. 縁側の板敷きに座っている私は, つい自問してしまう. このような場所で, デカルトやその「方法序説」はなんの役に立つのだろう? 明晰と判明, 推論の順序とこぎと, 方法的懐疑と良識などが, この魔法のような庭園を理解するうえでどれほど有用だろうか, と.

** 「精神現象学」序論    ヘーゲル
   私の言いたいことは, すなわち, 真なるものを, 実体としてばかりではなく, まさに主体として把握し表現すること, これである. 同時に, 実体性という場合, そこには, 存在としての直接性, すなわち知識にとっての直接性とともに, 知識そのものの直接性としての, 一般的なものも含まれている, ということに注意しなければならない.

   生きた実体は, 存在といっても, 真実には主体であるところの存在である. いいかえれば, 生きた実体とは, その実体が, 自分自身を定立する運動であり, 自ら他者となりつつそのことを自分自身に関係づけ媒介するという, この限りにおいてのみ真に現実的であるところの存在である. 主体としての限りでは, それは単純な否定性であり, まさにそのことによって, 単純なものを分割するはたらきである. その際, 対立的なものへと二重化しながら, 互いに交渉のないそれら二つの項の間の差異と対立が再び否定される. このように自分を回復する同一性, あるいはほかであることにおいて自分自身に帰ってくる反省, これが真なるものなのである. 真なるものは, それ自身になりゆく生成としてある. それは円環, すなわち, 前もって目的として立てた自分の終わりを初めとして, そして, それを実現する過程と終わりとによってのみ現実的であるところの円環である.

   精神は, 自分自身がまったく引き裂かれた何かにあってこそ, 自分の真理を獲得する. 精神がこの威力でありうるのは, それが, 否定的なものから目を背けるという意味で肯定的なものであるからでない. すなわち, われわれが何かあるものについて, これはつまらないとか, 間違っているといい, もうそれは済ませたことにして次に別のものへ移ってゆく, といった場合のようなことなのではない. 精神の威力は, 否定的なものに面と向かってそれを直視し, そのもとに身を置くという, まさにそのことに存する. 否定的なもののもとに身をおくことが, それを存在へ転ずる魔力なのである.

** 哲学の練習問題    本田有明    洋泉社 (2002)
   悩みに陥ったときは, その対象を正確に把握し, 分析しようと努めること. たとえば「人生は無意味だ」という悩みにとらわれたとき, 上手な悩み方は, 人生が無意味であると思われる理由を詳細に書き出し, さらにはその反対の側面についてもよく考え, じっくり比較検討してみることだ. 書くという行為は能動的な行為である. 没頭するうちに精神の浄化作用が働き, 一種の達成感を味わえる.
   対して「下手な悩み方」とは, 頭の中でグチグチと同じ思いを反芻すること. 出口のない観念の迷路を堂々巡りすることである. 自分は愚かなことをしていると自覚していながら, にもかからわず, やめられない. やがて, いつまでも「同じ悩みを悩んでいる自分自身」にだんだん腹が立ってくる. ここで悩みの対象が, 不毛な悩み方をしている自分自身に移る. 悩みの対象が「客観的な問題」ではなく「主観的ないらだち」へとすり替わる. 悩む自分に悩むのは, 絶望の袋小路, 自暴自棄にしかつながらない. 書き出してみること, 問題を整理してみることで《対象の明確化》に取り組もう.

   繊細な精神の持ち主であれば, その精神をできるだけ健康に保つよう配慮しなければならない. いずれ人生の大きな問題と正面から対峙したいと望むならば, それにふさわしい知力と体力が必要だ.
   「運動の後のシャワーの味には, 人生で一等必要なものが含まれている. どんな権力を握っても, どんな放蕩を重ねても, このシャワーの味を知らない人は, 人生の生きるよろこびを本当に知ったとはいえないであろう」 (荒野より  三島由紀夫  中公文庫)
   《自己への配慮》と《健康への意志》が, 実り豊かな精神生活への必要条件だ.
   「青年の苦悩なんか, たいていはランニングをすれば吹っ飛んでしまう. それでも残る苦悩こそ生涯をかけてとりくる価値のある苦悩だ」 (三島由紀夫)

   ものごとを「 A は B である」と命題の形で表現するときには慎重に対処しなければならない.
   - A は常に B であるのか
   - A はときどき B であるのか
   - A はごくまれに B であるのか
   - A は一定の条件の下で B であるのか 

   「義務ってのはね, なにも義務だからやるってもんじゃない. それを怠ることが, その人間を不安にさせるからやるにすぎん. 人間の果たす義務なんてものは, ようするに唯一つだけ・・・おのれの心の満足を求めるということ, そして自分でもいい気持ちになるという, ただそれだけだな」
   「高潔無比の衝動も, 低劣無類の衝動もすべて根源は一つ, 揺り籠から墓場まで, 人間ってやつの行動は終始一貫, まず自分自身の安心感を求める以外には絶対にありえん」 (マーク・トウェイン「人間とは何か」)

   ここで考えるべきことは, 人は自己満足を得ようとするから他人に奉仕するのか, それとも逆に, 奉仕するから自己満足の感情が生まれるのか, というところだ. 人が良心の満足を覚えるのは, 付随的で, 必然的であり, 大事なのはなにによって良心の満足を覚えることができるかである. 人間の行為は, なにがそれに起因しているかを重視する立場とともに, どのような結果をもたらしたかを重視する立場もあるのだ. 著者は, 結果について一言も触れようとしない. 人間はみな偽善者だと主張するためには, その方が都合がいいわけだ.

   哲学の出発点は自分・他人・世界など, 多様な現象に対する《素朴な疑問》と《探求の精神》だが, 探求をすすめてゆくうえで, 不可欠な条件は, できるだけ《明晰な言葉》, 間違いようのない意味判明な言葉によって考えようとする姿勢だ. つかう言葉の意味を明らかにしながら, 論理的に考えるということだ. 哲学的思考は言葉を正確に定義づけることから始まる. 大切なのは, きみ固有のこだわりや疑問を論理的に解明してゆくこと. 哲学を学ぶのは, そのための感性と能力を磨くレッスンだと思えばよい.

*** まとめ
   - 《事実判断》をそのまま《価値判断》に結びつけないこと.
   - 主観的な「好いこと」を客観的な「善いこと」に結びつける努力を.
   - 《自己反省》と《懐疑の精神》がきみを正しい思考に導く.
   - 自分自身の変容をじっくり見定めてみようではないか.
   - なにに良心の呵責と良心の満足を感じるかに人間の貴賎が現れる.
   - 人生のキーワード. 「われ□□□□□, ゆえにわれ在り」
   - 《罪深い自分》を自覚したなら, その罪深さをきわめてみよう.
   - その自己愛は第三者を傷つけていないだろうか.
   - すべての責任はきみ自身にある. 出発点はそこだ. そこにしかない.

** 人はなぜ生きるのか, 答えよ!  鈴木剛介  河出書房 (2007)
   人はなぜ生きるかというのは, わたしとは, 人間とは, なぜ存在しているのかという形而上学的問題と, 私は如何に生きるべきかという実存的問題に因数分解できます.

   犬やねずみが人生を考えないのは, 言葉を知らないからです. 人間の特別なところは, 言葉を持っている点にあります. 人間固有の文化, 文明, 情報の最も基礎となる初めの一歩が言語発生だったのです. 人間を人間たらしめるものは, 精神です. しかし, その精神を作るものは「言葉です. 言葉はどうやって生まれたのでしょうか?

   簡単に言えば, 耳から入る (RINGO) 音声入力と, 目から入る丸くて赤い物体の視覚入力が, 「=」 (等価) で結び付けられることによって, 脳内に言語が発生します. その「リンゴ」という言葉が, 「丸い赤い「スッパイ」などと細分化して行って, 脳内の言語が多様化し, その言葉が増殖しネットワーク化されることによって, 人間は自分も含めた周囲の世界を認識するのです. そしてその, 「意味づけされた言語のネットワークこそが, われわれの認識している世界そのものです. なので, 人間とは何か」という問いの答えは, 言葉を持つ動物」です.

   この考え方からすれば, プラトンのイデア界は消えうせます. 「心」や「愛や神という言葉をつくってしまったから, そういうものが, なんだか実際に存在しているような気がするのです. 宇宙には初めも終わりも無も有も存在しません. それは, 人間が後づけ的かつ人為的に作り上げた概念に過ぎないのです. なので, 真剣にそのことを考えるなら, 言葉の定義を定めるしかありません.

   原初の昔, 世界は「一」 (アナログ) だった. そこに「言葉が生まれ, 対象が細分化され, 多様化した結果, 世界はいろいろな意味や価値を持つものが存在する多」 (デジタル) になったということです. (科学からすれば, とんでもないが, これが哲学の世界!) 世界は言葉のない世界 (A) とある世界 (B) に分かれます. A が仏教的世界で, B がキリスト教的世界です. 「天国と地獄」神と人間」善と悪」という二元論的世界観と, 苦と楽」生と死」心ともの」は同一という一元論的世界観です.

   絶対的な判断基準の確立」万人が納得するような道徳 (&自然科学) の根本原則を発見すること」・・・これが, 哲学に与えられた本来の使命です. 長きに渡る歴史の中で, 多くの哲学者が宗教に屈服し続けてきたのは, まさしくこの一点です. 文化や時代を超えて完全に人類を掌握することができない以上, それを「真理」と呼ぶことはできません.

   宗教的真理とは「自分が信じることのできる限定された世界の中で, 絶対に正しいこと」です. 数学的真理とは数学的記号を使用する限定された世界の中で, 絶対に正しいこと」です. となると, 哲学的真理というのは, 言葉を使用する限定された世界の中で, 絶対に正しいことです」. 真理とは, 社会という限定された世界で, 誰もが納得できるものであり, そのための論証も反証も必要ありません. 宗教や信念といった個人的かつ無根拠な価値基準 (良いか悪いか) と, 公的な場における判断基準 (正しいか否か) を混同してはいけません.

   人間の認識, 思考とは, 分かる, 知る, ではなく, 決めることです. 人間は真理を分かる」知る」ことはできません. しかし, 決めることはできます. ボクシングやチェスにおいて, 勝者が絶対に正しいです. それは, そういうルールだからです.
   『この問題について, 双方とも尤もな見解だけれども, 同じ組織に属する以上, 双方が同じ見解を持たなければ, 統一性のある介護はできない. M さんは戸惑い, 混乱するだけです. この判断基準は, 価値観やキャリアではなく, 双方が共有するルールに基づくよりほかない. そして, 本年度の事業計画が「    」である以上, M さんの自由意志に任せるというのが, この問題に対する「絶対的に正しい」答えです.

   人間が行う判断というのは, 三つに分けられます.

   - 『~とは何か』という形で問うことのできる形而上学的判断
   - 特定の目的に対して選択肢のメリットとデメリット, 合目的性, およびその根拠を比較検討する個人的判断
   - 特定のルールに対しての『正しいか否か」による社会的判断.

   それではルールが確立されていない分野ではどうするのか?
   
   人間が言語を使って社会活動を営む上で発生する問題というのは, は,

   - 意見の受け皿がない
   - 判断基準が共有されていない
   - 責任と決定権があいまい
   - 情報の伝達経路が不明確 

   です. 逆にいえば, 『 1. あらゆる構成員の意見を無条件に吸い上げるルートを確保し, 2. 業務の遂行に必要な判断基準を共有した上で, 3. 責任と決定権が個人に帰着し, 4. 情報の伝達経路が明確に規定された組織」であれば, 理想的な職場ができます.

   スポーツや数学の勝敗がクリアで結論が一致するのは, 同一の前提からはじめて同一のルールにのっとって戦うからです. であるならば, 社会問題に対しても同一の前提からはじめて同一のプロセスで議論を行えば, 導かれた結論は対立を生みません. そうならば, 合意の内容ではなく, 合意に至るプロセスを規定することによって, 正当な法や倫理規範が得られるはずです. 議論や争いが耐えることなく繰り返されるのは, 合意に至る過程をあいまいにしたまま無理やりに合意を形成しようとするからです. 要するに, 正しい, と考えるにいたる認識⇒思考⇒判断⇒決定のプロセスが, 完全にガラス張りの状態で共有されればよいのです.

   世界平和=同一の意思決定プロセスを共有した世界全体の組織化, です.

   一番不幸な人間は, 「基本的な生活を送ることにはなんの支障もないが, 確固たる夢も思想も宗教もなく, 自我だけが強くて, 日常的なことだけでは満足できない. 『つまらない, でもなにをしたらよいのか分からない』ただ, なんとなく生きていかざるをえない人間」. のことです.

   夢は生きがいであり, 人生の目的です. 夢を持つ人間は, 夢の実現こそが自分が幸福になるための道です. それゆえ, 夢を持つ人間は, なぜ生きるかなんて考えず, 唯一「夢」だけが, 実質的で普遍的な力を持っています.

** なぜ人を殺してはいけないのか    小浜逸郎    洋泉社
   人間が生きていてぶつかる疑問には, うまく答えられないものが多い. それには理由がある. 一つは, 人は言葉で疑問を出す前に, すでにその問題について解決できない矛盾した現実をそのまま生きてしまっているからだ. 疑問が疑問として意識にあがったときは, たいていその前から, どうもうまく解決できないという欲求不満を背負っている. 問いは, その欲求不満の表現としてやってくるので, 形になった瞬間から, なかば袋小路に入り込むことが予想されているのである. たとえば, 「人は何のために生きるのか」といった問いは, 数学の命題のように, 純粋に論理的に構成された世界の中で設定された問いとは違っている. 「人は何のために生きるのか」という問いは, それを発したものがどんな動機からそういう問いを発したのかということ自体がそのつど問題であるような問いである. 問いを発したもの (主体) 自身の生の中に, それについてうまく答えられなくて悩むだけの原因がすでに潜んでいるのだ. だから, この種の問いにきちんと向き合うには, 自分自身はどういう動機からこの問いを出したのかということをたえず念頭に置きながら答えを考えていく姿勢が重要な意義を持つ. 人間は個別的な生を生きながら, 人類共通の困難な課題にぶち当たる. それだからこそ, これらの一般的な問いの形がある力を持って私たちの心に宿り続けるのである. 人間一般, 人生一般, 社会一般について考えるための手がかりは, 自分の個別的な動機の中に必ず隠されている.

   もうひとつの理由は, 問いそのものの出来不出来に関わっている. 問いというものは, 出された瞬間から, 一つの枠の内部に人を拘束するので, 多くの場合, 答えようとする思考経路が問いそのもののありようの中に閉じ込められてしまう. その結果, その問いがそもそも適正な問いであるかどうかについての反省が行われにくい. 出口の見えない人生上の難問につかまってくよくよ悩み続けることが無駄に思え始めたとき, どうすればよいか. 答えは単純で, 問い続けることをあきらめるか, 問いの外にいったん出て, ある仕方で頭を切り替えて再びその問いに挑むかどちらかである. 多くの人は前者を選ぶ. しかし, 人は成長し, 成熟し, 老いていく途上で, はじめの素朴な難問のパターンに何度もであることを経験するだろう. そして, それらがすこしも解決されていないことも. 青春期にふとぶつかってしまう問いには, この種の根源的な意味が含まれていることが多いのである. 哲学や思想という営みが人類史の中でつづけられてきた理由がそこにある. 後者の方法, つまりどのようにして問いの外にうまく抜け出すことが出来るのか.

   一つは, なぜ自分がその問いにつかまってしまったのか, そもそもその問いを発した根本の動機はなんだったのかを振り返ってみることだ. もう一つは, 問いの立て方に何かまずいところはないか反省してみること, そして同じような問題を考えるのに, もっと別の問い方はないかどうか模索してみることである. 以下に要点をまとめる.

  - なぜ自分がその問いにつかまってしまったのか, その動機を考える.
  - 簡単な解答はありえないと自覚する.
  - 問い方そのものにまずい点はないかどうかを検討し, まずければ, もっと良い問い方を編み出す工夫をする.

*** 人は何のために生きるのか
   そもそもこの問いは, 「人生全体」という, 時間的に長大な視野を見込む観念に対して, 意味とか目的とかいった観念を結び合わせることが適切なのかどうかが良く反省されないままに大上段に提出されている. そこで, まず, どんな状態にあるときに, こういう問いに心を占領されてしまうかという点, 次に, 「意味」とか「目的」とかいう意識は, 本来どういう生活場面で必要なものとして呼び出されるかという点にある.

   青年期は, 自我の確立期とよばれている. このじきは, 親からの心的な自立の時期に当たっているから, 人間の個体性, つまり他とは切り離された一個の身体や心の持ち主としての「自分」を強く意識させられる時期なのである. 自分の人生は自分で作っていかなくてはならない. 自分のしたことは自分で責任を負わなくてはならない. 自分の努力や器量しだいで幸不幸, 成功失敗も左右される. こうした観念が自我結合の課題として強く迫ってくるようになる. かくして, 自分固有の人生全体が視野に入ってくる. 自分はいったい何をして生きていったらいいのか, 自分は何に向いているのか自分は何をすべくこの世に生まれてきたのか, 自分の人生の意味とは何か・・・このように戸惑いが繰り返されるうち, 問いは次第に抽象的, 一般的なものに上昇してゆく. そして, 最終的に「そもそも人は何のために生きているのか」という問いにたどり着く.

   近代化を果たして豊かな成熟社会を迎え, 不況と停滞に陥っているいまの日本は, ある全体的な目的を達成してしまって, 次の目標がまだ見つからないような時代に訪れている空虚感に染まっている. 意味や目的をことさら問わずに入られない時代というのは, その根底に, じつは自分たちの生きる意味や目的がかんじられない空虚な気分が流れていることをしめしている.

   人は, ある行動や表現が, 他の行動や表現の間の本来あるべき関連性を失ってそれだけとして浮き上がるとき, 「無意味」とか「無目的」を意味する. ある行動や表現が意味や目的をもつとは, さしあたり, それらがほかの行動や表現に従属するような関連を維持しているということなのだ. しかしその場合, 他の行動や表現は, また別の行動や表現に従属する形で関連を持ち, それらは結局, 自分自身の生の従属それ自体という究極目標に帰着するような連鎖構造を形作っている.

   意味とか目的は, その向かう終局点との間の距離を, なんらかの理由で意識せざるをえなくなったときに発生する. ある行動や表現の外側に出て, それらをその終局点の見地から対象化し, 他の行動や表現に関連づけることである. だが人間は, 自己意識を極端に発達させた動物である. 自分の行動や表現にまつわる意識や感情を積み重ねて意識の次元を高次化させ, いわば意識についての意識とか, 感情についての意識といったものを獲得してしまった. この場合に即して言い換えると, 人間は, 「意味」や「目的」の意識それ自体を独立して心の対象として扱うことを覚えてしまった.

   「人生全体」といった包括的な観念に対してまで意味や目的を求めるにいたって, そこにひとつの転倒が起きたのである. そのつどの行動や表現をそのつどの意味や目的によってつなぎ合わせた連鎖の体系であるはずの「人生全体」の観念に, 人は意味や目的の観念を適用しようとしてしまったのである. 意味とか目的の意識とかは, 本来, そのつどの行動や表現をさせる機能を持っていただけであって, 「人生」とか「生きる」とかあまりに抽象的で大きな射程を持った観念に適用するには向かないのである. また, 意味や目的の意識とは, 行動や表現をその終局点の見地から対象化することであるとみなすなら, 一方で人生の終局点が死であることを人間は知ってしまっているのであるから, 人生全体の意味や目的はしに他ならないということになりかねない. 人生の個々の断面や場面の意味や目的は, 人生の内部だけにあってその外に出ることができない. したがって人生全体をその外側の何かに関連付けうるような, そういう他の「何か」などは存在することができない. だから人生そのものに「意味」や「目的」などを求めるのはもともと無理なのであり, 要するに人生には「意味」も「目的」もありはしないのである. 人生にはじめから何か意味や目的があると考えることは人間に特有の, そしてその本姓にいかにも見合った錯覚である.

   ところで, ある行動や表現に意味や目的を問う意識は, 次々にその連鎖をたどってゆけば, 必ず, 自分自身が従属した生を送るためにという究極地点に帰着する. 「ある行動や表現の目的は自分自身の生の充足のためである」という答えは究極的であって, その先を求めることができない. そうすると,

   人生そのものに意味や目的を見出そうとする問いのうちには, じつは, 人はいかにすれば自分の生を充足させることが出来るのかを知りたいという動機が潜んでいることになる.

   このような問いがいま私たちの意識を占領してしまうとしたら, その背景にはなにがあるか. それは, 個体的には, 自我の不安と, その不安を解消して確かな生の不公正をみいだしたいとする願いとが渦巻いており, また社会的には, 近代化というひとつの時代が終わり, 何をよりどころに共通の生き方を選び取ればよいのかわからない過渡的な状態に特有の空虚な気分が支配している. したがって, このような問いの背後にある, 生の充足を求める感情の要求に応えようとすることには, 大きな意義がある.

   生の自然な本能や感情は, 当たり前の状態では, いかなる「~のために」の意識よりも以前に, 無意識な, ひそかな形で, 私たちに対して常に「生きよ, 何かをなせ」と命じている.

   意味や目的の観念を, 超越的なものにまで及ぼそうとするのは, 人間特有の逃れられない性向である. そうである以上, 生においては, 自ら納得しうる意味や目的をいかにうまく虚構するかということだけが問題なのだ. そこで, はじめの問いは, 次のように言い換えられるべきだろう.

   人はいかにすれば自分の生を充足させうる意味や目的を作り出すことができるか.
   この問いは, これを問題にしている当人が, 生きる意欲を旺盛に持っているならば, 答える必要がなくなる. 生きる意欲を十分に持っていさえすれば, その人はいやおうなく何かをなし, 何かをなせば, その行動や表現について自分を納得させるような意味や目的は, そのつど自然についてくる. (similar)

   したがって問われるべきなのは, いったい人間の生きる意欲はどこから生まれてくるのか, それは何によって規定されているのか, 何が人間の生きる意欲を失わせてしまうのか, どういう仕組みやからくりがあるために, 人間は生き続けることが可能になっているのか, などである. そしてこれは結局, 人間の生存 (実存) の構造がどうなっているのかを問題にすることにつながる. そこで次のような問いが成り立つ.

   人の生きる意欲を支える一般的な原理はあるのか. あるとすればそれは何か.
   このような原理は, 当然, 「ある」と想定しなくてはならない. そうでなければ生きる意欲が事実上存在しているのもかかわらず, 私たちの思考の中ではその存在が保証されなくなり, そうなると, 「人はいかにすれば自分の生を従属させうる意味や目的を作り出すことができるか」という要請にこたえることができなくなってしまうからである.

* 中島義道
** 孤独について 中島義道    文芸春秋
   人生の折り返し点を過ぎた人の多くは, 自分に与えられた「小さなもの」あるいは自分の獲得した「小さなもの」を黙々と守るだけの生活を続けている. そして, まもなく死んでゆくのだが, そのことはひたすら考えないようにしている・・・.

   ごまかすのはやめなさい! あなたはまもなく死んでしまうのだ. あなたをまもなく襲う「死」をおいてほかにもっと大切な問題があるのだろうか? あなたは「死」と共にまったく無になってしまうかもしれないのだ. そして, 何億年たっても二度と生き返らないかもしれないのだ. もうじき終わってしまうこの人生が, あなたに与えられた唯一に生きる機会, 考える機会, 感じる機会なのかもしれないのだ. もうすぐ死んでしまうあなたが, 必死に日常的な問題にかかずらっていること, それはたぶん最も虚しい生き方である.

   ニーチェの不可解きわまる思想のうち, 私がごく最近了解し始めたことがある. それは「何事も起こったことを肯定せよ. 一度起こったことはそれを永遠回繰り返すことを肯定せよ」という「運命愛」と名づけられている思想である. つまり, 私に起こったことすべてを「私の意志がもたらしたもの」として捉えなおすことだ. 私が他人から嫌われ, 排除され孤独に陥っているとしよう. 「運命愛」とは, こうした場合そもそも俺が悪いんだからと泣き寝入りする態度ではない. 何もかも自分のせいにして安堵する怠惰な態度ではない. この運命は自分が「選び取ったもの」だと, 無理やりでも, 考えてみることなのだ. 自分が孤独になったことは誰のせいでもない, ほかならぬこの俺がじぶんの身にもたらしたものなのだと, 無理やりにでも, 考えてみる. この意味で, 孤独を完全に肯定することだ. すると, 孤独の苦痛ははるかに軽減する. やせ我慢ではない. こうした状況はまさに自分が臨んだのだ, と思ってみることである. そして, それまでの自分の行動を点検してみるがよい. いかに, 自分はこの状況をつくることに加担してきたかがわかってこよう.

** 生きにくい・・・私は哲学病  中島義道  角川書店  (2001)
  歳をとると, 時間はだんだん「速くなる」傾向にある. では, なぜ過去の持続感の場合には時間は速く流れるのか. ここに, 記憶が関係している. 主観的時間が記憶に結びついている場合, われわれは鮮明な記憶を「近い」とみなしてしまい, ぼんやりした記憶を「遠い」とみなしてしまう. 歳をとると, 記憶は総じて鮮度を失うが, そんな中にポッポッとわずかに鮮明な記憶の灯がともっている. すると, ほかの部分がぼんやりしているから, その灯がたいそう近いものに思われてくる.

  歳をとると日常生活は定型化し, 新鮮な感動も薄れ, つまり上手く生きてゆくための習慣が蓄積される. われわれは, 習慣の蓄積によって, あまり考えなくとも, あまりわくわくしなくとも, 新しい事態に対処できるようになる. そして, たいそう恐ろしいことに, こうして身につけた生活の知恵がわれわれの命を縮める現況となるのである. スムーズに抵抗なく生きることができればできるほど, それらの記憶は互いに区別がつかなくなり, 定型のうちに埋没してゆく. 毎日の朝食のメニュー, 通勤電車から見る風景, 出社したときに風景は, きわめて特殊なものでない限り, 記憶から消えてゆく. 歳をとればとるほど, 生活の効率化が記憶を消し, 過去を消してゆく. そうしながら, のっぺりとした過去の中にあの日の光景だけがフッと鮮明に浮かび上がってくる. その一年前の光景は昨日のことのように思われるのに, 本当は一年前なのだ.

  こうして考察してくると, 子供の時間が「ゆっくり」流れるのも理解できる. そもそも子供の客観的時間は短く, 人生はとてつもなく新鮮で, まだ人生の定型化を学んでいないので, 主観的時間と客観的時間のずれはあまり生じない. そのつどの記憶がはっきりしていて, 凹凸があまりない. 言い換えると, 彼らにとっては些細な記憶はほとんどなく, 何でもかんでも大切な記憶なのである.

  このすべては厳密には錯覚なのであるが, その錯覚を通じてわれわれは人生の妙味に触れる気がする. いかに生きるべきかのひとつの答えに直面している気がする. 苦労なく, 工夫なく, 苦しみもなく, 感動もなく, ・・・平板になにごとも能率的に人生を送れば送るほど時間は速く流れるのだ. 人生は短くなるのだ. 逆に, 危険に身をさらし, 恐怖におののきながら, 明日の生活をも知れない過酷な想いで生きていると, 人生は長くなるのだ. 楽をすると時間を殺すことになり, 過酷な人生は時間を生かすということである.

  以上の考察から, 長く充実した人生を送るには, 定型的な摩擦のない楽な生き方を破壊する必要がある. 夜, 寝床の中で「ああ今日もなにごともなくすぎた」というだけの人生はつまらないものである. その積み重ねは記憶を減退させ, 過去を消失させ, 人生をあっという間に終わらせることであろう. だから, 覚醒しているときは, あえて周囲を観察し, あえて事件を見出し, 問題を見出すこと. あえて「驚く」訓練をすること. 子供のように, いや別の天体から始めて地球にやってきた宇宙人のような目で周囲を眺めること. あるいは, 明日処刑される死刑囚のような気持ちで周囲世界を眺めること. 世界は突如光を放ち, 汲み尽くせないほどの豊かさに輝くことであろう. 哲学する理由もここにあるといえる.

  わたしにとって時間はいっこう「速く」流れない. わたしはあえて時間を「長く」する技術を身につけているのだ. わたしは幸福や安寧を求めない. 客観的には貧しい自分の一日の体験でも, 細かい襞に至るまで思い起こし, 反芻し, 言語化し, 点検し, 評価し, ・・・という作業を繰り返している. とくに「嫌なこと」は隅々まで覚えている. 「嫌なこと」を何度も意図的に思い出して, 何度も冷や汗をかき, 何度もああすればよかったこうすればよかったと後悔するのである.

  そして, 朝から晩まで「死」のことを考えている. どんなに楽しいときでも, どんなに無我夢中のときでも考えている. こうした努力を九例返しているうちに, いつしかわたしにとって時間はたいそう「ゆっくり」流れるようになってしまったのである.

幸福を求め懸命に能率的に苦労なしに生きると, 時間は短く貧しくなる. だが, 死を見つめ不幸にまみれ苦しさを背負って生きると, 時間は長く豊かになるのである. これこそ人生の妙味ではないだろうか.

** どうせ死んでしまう・・・私は哲学病  中島義道  角川書店
   自殺したいものは楽しいはずの人生なのに自ら絶とうとする誤りに陥っているわけではない. 人生がある程度楽しいことはわかっている. しかし, 私の人生はその楽しいはずのことも含めて, もううんざりなのだ.

   幸福のほとんどは, 社会的な基準に照らし, 他人の評価に即して幸福であることなのだから, 幸福を目指すことは, 社会的評価を目指すことだ. 「自分の幸福は自分ひとりで決める」と居直ることも, はななだしく欺瞞的である. 幸福は「心の持ちようしだい」でどうにでもなるものではない. やはり, 社会的評価にかなりの程度依存している. それをまったく遮断して「これでいいのだ」と居直り, 「自分は幸福だ! 」と叫ぶこと, それは真実を見ようとしない怠惰な態度である. なぜなら, 本当に幸福なら, 仕事に成功し人望もある"幸福な"男を軽侮しないはずなのだから. 彼らに無関心なはずなのだから.

   各人は, 絶望的な不平等のもとにこの世に生を受ける. このことをきっかり脳髄に叩き込むと, 生きる気力もうせるほど虚しくなる. さらに, 欺瞞的なのは, そうと知りながら, みんな, ある人を尊敬し賞賛しある人を軽侮し非難することである. いや, これに留まらない. さらに骨が打ち砕かれるほど過酷なのは, あらゆる成功があたかも当人の努力のゆえであるかのような, あらゆる失敗が当人の努力の欠如であるかのような言説がはびこっていることである. すべては見通せない. しかし, われわれはそれと知りながら, 才能のある人を尊敬し, 無能な人を軽侮し, 美人を崇拝し, ブスを嘲笑する. なんと, なんと, すべてが理不尽なことであろう.

   大学生たちは総じて従順であり, 勤勉であり, 礼儀正しい. 金持ちに対しても, 社会訂正後者に対しても, たいした憧れを持っていない. こういう具合で, 現代日本の学生たちは私の美学的趣味にかなっておるのだが, ひとつだけ彼らに対して大きな不満を抱いている. それは生きる力が弱すぎることである. 彼 (女) らはともすると守りの姿勢に入りやすい. 善良なだけであった, 後は何のとりえもない生き方を選択しやすい. その瞬間に, 美しい弱さは醜い弱さへと転落する.
   では, どうすればいいのか. 大学で思考の体力をつけることである. それは「真実から目を逸らさない」という一転に収斂する. みな, いずれ死んでしまうことを, 苦痛にあえぐ何億もの人が地上にいることを, 個々人の間の資質や環境の恐るべき不平等を, 人生における「運命」や「偶然」等なのたぶらかしを, つまり人生の理不尽をしっかり見据えることであり, しかもここには原理的にいかなり解決もないことを悟ることである. 大学生とは, 人生のあるときにゆったりと時間が与えられて, 人生の理不尽を身体の隅々までいきわたらせる贅沢が許されたもの, 言い換えれば親権に「ぐれる」チャンスが与えられた特権者のことである. ぐれるといっても, 知的で高度のぐれ方でないと, 大学生がすたる. 具体例だって? 大学という隠れ蓑をとことん利用して, 社会的にぜんぜん役に立たないことに身を投じたっていいわけだし, さらに大学院に進んで研究者になるという口実の元, ずるずる人生の勝負を引き延ばしたって言い訳である.

   学問や芸術に専念している人たちよ, 中でもその仕事が世間的にわずかでも評価されて幸せを感じている輩よ, 一度すべてを無理にでも反省してみたらいかがであろう. そのために費やした膨大な時間 (青春) は, 果たして無駄ではなかったのか. あなたがそれをする必要があったのか. あなたがしなければ, 何か困ることでもあったのか. つまり, その仕事は, あなたにとってのみ, あなたの生きがいとしてのみ重要だったのではあるまいか. あなたの仕事は, たぶんあなたが死んだ瞬間に忘れ去られるであろう. そうでなくても数十年だ. たとえそれを誰かが覚えているとしても, 死んでしまい無になってしまったあなたにとって, それが何であろう. そう確信したら, あなたはまもなく死んでしまう自分を見つめなおそう. そして, 果たしてあなたの人生がこれでよかったのか点検してみよう. あなたは, ほかのことをしたかったのではないか.

** 哲学の教科書    中島義道  講談社学術文庫
   われわれは日常的には自分をごまかして, なるべく「死」を直視しないようにしている. しかし, あらゆる哲学の問いは, まもなく「自分が」死ぬというこの差し迫った問いに収斂するといえるかもしれません. もし私が明日死んでしまったら, 私は世界の終わりまで, いやその後まで, 何億年もその何億倍年も, いや永遠に, 再び生きるチャンスはないでしょう. 「ぼくの死」は「人類の滅亡」を巻き込む宇宙論的な広がりをもってすぐ近くに控えている. これが私の「死」の実感であり, だから冷や汗が出るほど恐ろしいのです.

   はっきりいって, 哲学は何の役にも立ちません. しかし, 哲学をすると, 見え方が確実に変わってくる. 世界は当然なものではなく不思議なものとしてたち現れてくる. 世界の骨格が揺らぎだしてくる, これは大きなことです. 有用であること, 社会に役立つこと以外の価値を教えてくれる. 本当に重要な問題は, 「生きておりまもなく死ぬ, そして再び生き返ることはない」というこの一点をごまかさずに凝視することです. そして, このどうすることもできない残酷さを冷や汗のでるほど実感し, 誰も逃れられない理不尽な徹底的な不幸を自覚することです. ここに, 「死者の目」が獲得されます.
   あと一億年すれば, いや一千万年でもいいかもしれない, たぶん人類の記憶は宇宙に一滴も残らないであろう. このことを実感して, 夜の電車の中にすしずめになり家路を急ぐくたびれ果てたサラリーマンたちを, その上に揺らめく刺激かつ下品なつり広告を見ていると, すべてがガラス細工のようにもろくはかなく美しく見えてくるのです.
   つまり, 簡単に言えば, 哲学は「死」を宇宙論的な背景において見つめることによって, この小さな地球上のそのまた小さな人間社会のみみっちい価値観の外に出る道を教えてくれます.

   私はいかなる (いわゆる) 些細な悩みであれ, 本人がそれを悩むかぎりは, 彼 (女) にとって悩む理由はあると思っています. ある欠点に悩む人はその欠点を消去ないし改善するのではなく, それを (へんな言い方ですが) 「伸ばす」ことです.
   中略
   しかし, 最近のことですが, なんでぐちゃぐちゃ考えてはいけないのだろう. 別にいけないことはないんだ, と思うようになりました. いやもうどうしようもないのだから, 諦めるほかはないと悟り, そして「この欠点を伸ばそう」と思いなおしました. つまり, もっともっとトコトンまでぐちゃぐちゃ考え続けよう, 他人を羨み続けよう, 他人から言われたことをテープレコーダーのように何から何まで記録し書きとめておこう, 過去をヘトヘトになるまで後悔し続けよう, と思い立ちました.

   愛は科学とは絶対的に相いれない. なぜなら, いかなる愛もその人という個物を「愛する」という了解がありますが, それをその構成要素に分解してしまうことは, その構成要素がなくなれば愛さなくなること, よりすぐれた構成要素の持ち主が現れれば乗り換えうることを含意するからです. 家柄・財産・学歴・肉体等とにかく計測可能であり序列可能なものはすべて愛の敵対物です. 愛する対象がもし個物なら, 厳密にはいかなる理由もいえないはずなのです. ここの属性ではなくその人だから愛するのです.

   哲学とはあくまでも自分固有の人生に対する実感に忠実に, しかもあたかもそこに普遍性が成り立ちうるかのように, 正確な言語によるコミュニケーションを求め続ける営み, といえましょう. 哲学の問いには最終的な答えはありません. 0:45 2006/10/20 

** 働くことがイヤな人のための本    中島義道    新潮文庫
   いかに真摯な嘆きでも, 自分の中に閉じこもってしまうと, それはぐるぐる同じところを回るだけで, 一向に進捗しない. 病的な自己確信, 病的な他人嫌悪, 病的な世間恐怖・・・という具合に進んでゆき, もともと清潔で美しくさえあった悩みはいつしかどす黒く醜い炎に変身してゆき, 自分をも他人をも焦がしてゆくのだ. だから, そうした事態にならないためにも, 自らの言葉を批評可能な場に曝すこと, つまりそれを他者とのコミュニケーションを通じて鍛えてゆくことがぜひとも必要なのだ. 身体を隠したコミュミケーション (ミクシィとか?) ではなく, 身体をあらわにしたコミュニケーションの場を設けることが必要なのだ.
   君が布団の中に描いていた壮大な幻想世界など, 粉々に打ち砕かれればいいのだ. そしてその廃墟の中からはじめて, それもきみが立ち上がろうとするとき, 君は本当に思索しだすのである.

   現代日本においては, 人間の評価が仕事によって決まることを知っている. だから, そこに足を踏み入れたくはないのだ. 自分のプライドが傷つくような失敗を自分に対して決して許さないのだ. それは何か? 学生時代は学力であり, 社会にでてからは仕事に変わる.
   しかし, 誰もが仕事において勝者になれるわけではない. 学力において勝者であり続けてきたものこそ, 社会にでることが恐ろしい. そこは, 学力だけがものをいう社会ではなく, 見とどけられないほどの多様な要素が絡み合って, 必ずしも勝者であり続けることができない予感に恐怖を覚えるのだ.
   そこで, プライドを維持するために, 彼らは不戦敗という道を選ぶ.

   戦うと負けるかもしれないが, 戦い自体を拒否してしまえば, 致命傷は負わなくてすむ.
   問題はここからなんだ. 戦いの拒否の仕方について, 彼らはまた壮大な夢幻空間をひねり出すのだ. すべての仕事はよくよく考えればくだらない. 仕事の成功者はみんなずるい汚い奴らばかりだ. 仕事にうつつをぬかす奴らは, 「人生とは何か」を真剣に考えないアホばかりなんだ. 「人生とは何か」という問いに苦しめられている俺は, この根源的問いを発せずにひたすら仕事に邁進しているやつらより高級なんだ. なにやかや言っても, 結局みんな死んでしまうんだ.
   と, 不健康な夢幻空間を膨らますうちに, 一条の光がさしてくる. それは, 哲学や文学あるいは宗教や芸術という名の仕事である.

   大学受験生の S 君は毎日呟いている. 自分にはやりたいことは何もない. このアホ勉強なんか蹴飛ばしてしまいたい. だが, ここを通過しなければ, 自分はこの国では知的人種として認められないのだ. 自分は, そこにバカがうんざりするほどいると知っていながらも, 知的社会に迎えられたい. 知的エリートとして扱われたい. それには東大に受かることが一番だ. だが, その後の長い人生をどうやって生きていったらよいのだろう? いつまでもがんばる. いつも一番になれるとは限らないのに. 限りない靴冗句を, 敗北感を味わうことだろう. そして, 結局死ぬんだ. むなしいなあ. といって, ただ楽に生きるだけがすばらしい人生でもないだろう.

   彼らのほとんどは自分が何をしたのかわからない, という考えが時節心の片隅をさあっとかすめるのに気づきながらも, ただ自分が崩れるのが恐ろしくて, そう言い出さないだけなんだ.

   人生とは「理不尽」の一言に尽きる. 思い通りにならないのが当たり前. いかに粉骨砕身の努力をしても報われないことがあるんだ. そして, 社会に出て仕事をするとは, このすべてを受け入れるということ, この中でもがくということ, その中でため息をつくということなのだ.
   多くの人は, 「成功した人はみんな大変な努力を重ねたのだ」と言ってしまうが, それは違う. これは, ありとあらゆる世の中の理不尽を消してしまいたいという願望から出た怠惰な言葉なのだ. いかに努力を重ねようとも, 成功しない膨大な数の人がいることは事実である. 多くに人は, 「しょせん, 才能がないのだ」といって, 割り切ってしまおうとする. たいそうな暴力だ. 成功した人は, 自らの類まれな成功の理由を自他に納得させたいのであり, 失敗した人も, 納得できないことを無理にでも納得して楽になろうとする. なぜか? そうしなければ, その理不尽に耐えられないのだ. みんな, 安心したいのだ. 狂暴な心でいたくないのだ. 世間の人は不平等や理不尽に耐えられず, つい納得したいという衝動に駆られてしまう. しかし, その理不尽を直視しなければ, 解決はありえないのだ.

   好きでたまらない仕事を見出し, かつその仕事において成功した人は, こうした要素のいくつかが本人の意思を超えたところで与えられてきた極めてまれな例なのだ. ほとんどの人は, いくら頭をひねっても自分の天職を見出せない. 「自分のやりたいことがきっと何か一つあるはずだ」というお説教はウソだ. たとえみいだせても, 挫折してしまう. 不合理なことに, 成功者のみが発言する機会が与えられている. 彼らは, 成功の秘訣を普遍化して語ろうとする. 「こうすれば成功できるという一般論を語ろうとする. 実はたいそうな天分とそれ以上に不思議なほどの偶然に左右されてきたのに, 誰でも同じように動けば必然的に成功が待っているはずだと期待させる. それが実現できないのものは怠惰なのであり, 努力が足りないのであり, 適正を誤っているのだと力説する. これは大嘘である. 彼らは, たまたま運がよかっただけのくせに, 彼らの犠牲になった膨大な数の人を切り捨ててしまう. むしろ, 人生の偶然的要素にもしっかりと視線を注ぐことによって, 仕事に報われなかった棒大な数の人生にも価値があることを認めたいのだ.

   君の仕事に対する理想は高い. そして, それを下げることはできない. 理想を追い求め続けることはつらい. その欲求を押さえつけ, 考えないようにすれば, それなりの仕事にありつけるかもしれない. しかし, 君はそれで納得できないんじゃないかと思う. 君はそれほど巧みに自分をだませないんじゃないかと思う. 逆にその欲求からヒントをみいだして, なにをすべきかを徹底的に考えなければならない. あえて言おう. 君のような青年は, たとえ不幸になっても, 「身のほどを知らない」生き方を熱心に探求するべきだと思う. たとえ, 君が不幸に陥り家族など周囲のものを不幸に陥れることになろうとも, その生き方を貫くほかないのだ. 君は, かなりの蓋然性を持って成功しないだろう. しかし, それもまた豊かな人生になりうるんだ.
   もう少し具体的にいうと, 才能とか年齢とか親の反対とか生活の安定とかすべて切り捨てて, 自分が一番したいことをまず確認すること. それがわかったら, それを実現するありとあらゆる方法を考えること. いかなる失敗も, その目標の火が消えない限り, 君は耐えられる. 最終的には, その目標を実現しなくてもいいんだ. 完全に失敗してもいいんだ. だが, そうした運動を通じて, 君はたぶんつらいけれど充実した人生を味わえると思うよ.

   あなたのような安全な道をたどってきた人に一つ知ってもらいたいのは, 不安定な道を歩むことがどれほどの緊張と恐怖を人に与えるかということだ. 苦しくなるほどの信念がなければ, 芸術や哲学の世界へなんぞ歩みだせるものではない. 「自己実現したい」という抽象的な願望だけでもだめなんだ. 具体的にその現実の方向に向かってからだを動かし始めなければならないんだ. 人生を支配している理不尽に向かって, からだごと戦いを挑まねばらならないんだ.

   「才能がない」といってあきらめてしまえるものは, そのことを持って才能がないのだといわざるをえない. 才能とは, 少なくともそういう形であきらめてしまえるものではない. 才能とは, 具体的に表現されたものの積み重ねを持ってその意味を獲得してゆくものであり, いかなる兆候も示さないものが「俺には才能がある」といっても誰も信じない. 才能とは, なんらかの形で少なくとも一度は外に現れでるものでなければならない. そして, 才能の開花には, ある人との決定的な出会いが, ふと手にした一冊の本が, ある偶然が降りかかった体験が大きな手を貸していることがある. これが, 掛け値なしの真実だ. しかし, すべてが偶然ときめつけることはよくない. 成功者に共通な何かがある. その求める気持ちは一種の狂気のようなものだといっていい. かららはなぜそれほど真摯に求めるのか? 芝居でも料理でも哲学でもいい. その自己実現の方法がなかったら, 自分の人生はまったく無意味だと直感しているからなのだ. ほかの生き方など考えられないのだ.
   自己表現者は, 将来ひたすら書きつづけ, ほとんどの人には知られず, そしてこれを死ぬまで続けるだけであろう. 日々刻々と, 「こんなことをしていていいのだろうか? 」という呟きが全身をずたずたに切り刻むのだ. まともは職業についている人は, 社会に役に立っていると思うことで救われる. しかし, 膨大な数の作品がすでにもう存在するのである. 自分がさらに一つ生み出したところでなんになろう. 自分は自分のために書きたい. だが, 誰にも望まれていない作品を書いてなんになろう. 「無駄だ! 」という叫びが, 自分のからだを押しつぶす. その圧力にめげずに創作すること・・・それは並大抵のことではないのだよ.

   普通の場合, 同じほどの能力を持っていても, 所を得たものはますます努力し, 所を得ないものはますます努力から遠ざかる. 適当な地位を手に入れた人は, 適当な虚栄心から, 周りのものからとやかく言われないためにも自分の痩身に鞭打ってがんばる. こうして 10 年経つと, 差はどうしようもなく開いてしまう.

   仕事において, 契約者は, 労働者の人間全体とではなく, その労働力だけと契約したのであり, その結果を達成する労働力に対してのみ, 金を払っているのだ. 考えてみれば, 人間としての情を植えつけたこうした契約関係はずいぶん不自然なものだ. ミスを許さないのが仕事なのだ. 契約して金をもらうからには, その仕事が達成されないとき, いかなる弁解も許されない.

** 不幸論  中島義道  PHP 新書  (2002)
  幸福とは求めれば求めるほど遠ざかるもの, そういう構造を持っていると思うようになった. 幸福を過度に追求すると, 絶えず「自分は幸福でない」と不平を言いたくなるし, 「ああ幸福だ」と実感したとたん, わずかでも不幸に傾斜することが恐ろしいし, 自分より幸福な人を嫉妬するし, 自分より不幸な人に無関心なそぶりはできない. つまり, 私が幸福を求めれば求めるほど, 必ず害悪を及ぼすことがわかった.
  
*** 幸福とは
   幸福とは, 以下の四つの柱の上に建っているように思える.

**** 自分の特定の欲望が叶えられていること
     幸福を感じている人とはある特定の欲望に関して満足を感じているのであって, それは客観的に決まることではない. とはいえ, ここには自己欺瞞がある. 人は, 満足していないときにこそ満足しているふりをするのであり, あるいは, 自他に対する「政策的」配慮から満足しているときにも不満なふりをするものだからである. また, 幸福感 (=満足感) は「知らない」ことに支えられている場合が多い. さらに, 幸福は対象のうちにあるのではなく, 判断を下す各人の心の構えにある.

**** その欲望が自分の一般的信念にかなっていること
     瞬間的快楽は, 幸福につながらない. 瞬間的快楽を満たすために, 自分の信念を曲げる場合, 幸福でないことはみんな知っているだろう. 往々にして「これでよかったんだ」という叫びが聞こえてくる. しかし, いつまでも釈然としない気持ちがくすぶっている. 多くの人は幸福であるふりをしたがり, 幸福であるつもりになりたがるのだ. この欲望は大きいので, つい思考を停止して「これでよかった」といいたがる. そして, 「私は幸福だ」と自ら確認するのである. それは, ただ当面の難局を逃れただけであり, 断じて幸福に達したのではない.

**** その欲望が世間から承認されていること
       幸福とは, 世間から排斥されてもなお成立するものではない. ここで重要なことは, さしあたり現実の社会で承認されることなのだから, 承認される当人の言動が「道徳的に正しい」ことを含まないということである.
**** その欲望の実現に関して, 他人を不幸に陥れない (傷つけない, 苦しめない) こと
     だれも苦しめないで幸福になることはできない. 自分の幸福の実現が膨大な数の他人を傷つけながらも, その因果関係の網の目がよく見えないために, われわれはさしあたり幸福感に浸っていられるのである. それがすっかり見渡すことができたら, この世に幸福はありえないだろう. つまり, 幸福は, 盲目であること, 怠惰であること, 狭量であること, 傲慢であることによって成立している.

     世の多くの人は, 幸福を「自分の望んでることが叶えられること」くらいに解して, 無理にでもさしあたり幸福だと叫びたいのだ. 「このあたりで満足ではないか」と納得したいのだ. しかし, 不条理をそっと横に置くと, この世のすべての物事が忽然と光を失う. なにをしても面白くない. なにをしてもくたびれる. あまりにもきついから, 時々忘れようとする衝動に駆られるが, そうした自分をまた鞭打つのだ.

*** ヒルティの「幸福論」
    およそ存在する不幸の中で最大の不幸は, 仕事のない生活, 生涯の終わりにおいて仕事の成果を持たない生活である. したがって, また労働のけりというものがあり, それがなければならない. それは, あらゆる人権の中でもっとも根源的なものでさえある.

*** ラッセルの「幸福論」
     五歳のときつくづく考えたことは, もしも七十歳まで生きるとすれば, まだ生涯の十四分の一を耐え忍んだに過ぎない, ということだった. そして, 行く手に横たわっている長い退屈はほとんど耐え難いものに思われた. 思春期には私は生を厭いつつも自殺の淵に立たされていた. しかし, 何とか自殺を思いとどまらせてくれたのは, もっと数学を知りたいという思いだった.

*** ショウペンハウエルの「意志と表象としての世界」
     あらゆる幸福は消極的な本性のものにすぎず, 積極的な本性のものではない. まさしく子のゆえに, 持続する満足や幸せというものはありえず, 常にただ苦痛とか欠乏とかから救い出されてきただけであり, その後に続かざるをえないのは, あらたな苦痛であるか, そうでなければ, 物憂さ, 虚しい憧れ, 退屈ですらある.

*** まとめ
    大体, 幸福論を書こうという人の動機が気に入らない. 彼 (女) は, まずだれでも幸福になれるという基本態度を押し出す. 次に, この定石の上に, 自分の体験を重ね合わせて, 幸福とは大それたものではないこと, それは考え方を変えることでだれの足元にも転がっている, という壮大な建造物を作り上げる. つまり, 幸福論は, 第一に, 自分が幸福であると確信している人が書く. そして, 第二に, だれでも自分と同じようにすれば幸福になれると説く.
 幸福とは, 思考の停止であり, 視野の切り捨てであり, 感受性の麻痺である. つまり, 大いなる錯覚である. 世の中には, この錯覚に陥っている人と, 陥りたいと願う人と, 陥ることができなくてもがいている人と, 陥ることを諦めている人がいる. ただそれだけである.

    幸福であると思われたい症候群の人は, 自分が幸福であることの確証がどうしてもつかめないので, 他人にそれを決めてもらおうと必死になる. 彼らにとって, 幸福とはみんなが幸福と認めてくれることである. さらには, 不幸をことさら演じて同情をかい, 幸福にいたる, という曲芸も時節行う. そのためには, 同情をかいうるような不幸に執着しなければならない. 自分を悲劇の主人公に祭り上げることができ, 自分に向かってさめざめと泣くことができるからである. そして, 自己陶酔することができるからである. さらに, あえて「不幸そうに見せかける」技術は, 他人から気に入られる技術でもある. 人は他人の不幸を好むからであり, ましてさまざまなものが与えられている人が不幸に陥ることを熱望するからである.
    
    不幸になるのはひどく簡単である. 幸福であると実感したときに, なるべく多くの要因を考え, 隅々まで波及効果を考えるだけで, 人は簡単に不幸になることができる.
   
* ニーチェ
** ツァラトゥストラはかく語りき      ニーチェ
  生は悦楽の泉である. 認識すること, それは獅子の意志を持ったものには悦楽である. 弱い人間たちの特性は, 彼らが道中で自分を見失うことである. 「いったい何のためにわれわれはおよそ道を歩き出したのか. 一切は同じことではないか」と. こういうものたちの耳には, 「人間のすることは何にもならない. お前たちは意欲してはならない」という説教が, 快く響く. しかし, これは奴隷になれと勧める説教である. 意欲は解放する, なぜなら意欲することは創造することであるからだ. そして君たちはただ創造するためにのみ学ぶべきだ.

  「教養人」という名を持つ, 群がりたがるうじ虫を追い払ってやるがいい. このうじ虫は, 英雄たちの汗をなめて, よろこぶ虫だ.

  苦痛はまたひとつの悦楽なのだ. おまえたちは, かつて悦楽に対して「然り」といったことがあるか. おお, 私の友人たちよ, そういったことがあるなら, お前たちは一切の苦痛にたいしても「然り」を言ったことになる.

  お前たちがかつて「一度」を二度欲したことがあるなら, かつて「お前は私の気に入った. 幸福よ, 刹那よ, 瞬間よ」といったことがあるなら, それならお前たちは一切のことの回帰を欲したのだ.

  お前たち, 永遠な者たちよ, 世界を愛せよ, 永遠に, また不断に. 痛みにむかっても「去れ, しかし帰ってこい」と言え. すべての悦楽は, 永遠を欲するからだ.

  おお, 人間よ, 心して聞け.

  深い真夜中は何を語る?

  「わたしは眠った, わたしは眠った・・・,

  深い夢からわたしは目覚めた. ・・・

  世界は深い, 昼が考えたより深い.

  世界の痛みは深い・・・,

  悦び・・・それは心の悩みよりいっそう深い.

  痛みは言う, 去れ, と.

  しかし, すべての悦びは永遠を欲する・・・

  深い, 深い永遠を欲する! 」 

** 悲劇の誕生    ニーチェ  中央公論社
  ミダス王は, シレノスにむかって, 人間にとって最も善いこと, 最も優れたことはなんであろうか, と問うたのであった. 「最も善いことは, 御身にとってはまったく手の届かぬことだ. それは, 生まれなかったこと, 存在しないこと, なにものでもないことなのだ. しかし, 御身にとって次に善いことは, すぐに死ぬことだ」 

** 若き人々への言葉  ニーチェ  原田義人訳  角川ソフィア文庫
  「ディオニソス的」という言葉を持って表現されるものは, 統一への衝突であり, 人格, 日常, 社会, 現実を超え, 推移の深側を超えて, 掴み掛ることであり, ほの暗く, 充実した, 漂うような状態に, 情熱的に, また苦悩しつつ, 充実してゆくことにある. すべての転変のうちにあって同じであるもの, 同じように力強いもの, 同じように浄福であるもの, である生の全性格に対して, 歓喜して肯定することである. 大きな汎神論的な同楽同友の共感であり, それはまた, 最も恐るべき, そして最も問題を含む, 生のもろもろの特質を是とし, 神聖化するものである. 生むこと, 実ること, 回帰すること, への永遠の意志であり, 創造と否定との必然性の統一感情である.

  「アポロ的」という言葉を持って表現されるのは, 完璧な即=自=在への, 典型的な「個」への, 単純化し, 抽出〓, 力強く明瞭にあいまいでなく典型化するいっさいのものへの, 衝動であり, 法則のものにおける自由である.

  芸術が幾千年を通じて教えてきたところは, 関心と悦びとをもって, あらゆる形態における生を見, ついに「どうあろうとも, 生はよいものである! 」と叫ぶにいたるまでにわれわれの心情をもってゆく, ということである.

** ニーチェ (for beginers)  現代書館  竹田青嗣
   人間は「成長しようと欲する」「力」がその身体性や環境の条件に応じて違った形をとる. それが解釈の違いを生むのだ. 僧侶にとっては神はいなければ困るものであるし, 物理学者にとっては神はあっては困るものなのだ. こういう, 生活上の要請が, 彼らの確信をもたらしているに過ぎない.

   「私たちの知性に権力と安全の感情を最も良く与える仮説がその知性によって最も優遇され, 尊重され, したがって真と表示されるのではなかろうか? 」

   ヨーロッパのニヒリズムは
   <苦悩>⇒<ルサンチマン>⇒<三つのカテゴリー>⇒<ニヒリズム>という経路でたどり着く.
   この三つのカテゴリーとは「神」「真理」「目的」だ.

   「超人」思想は, 「価値の基準」を<意識>, およびそこに表れる快苦においてはならない. なぜなら, 意識に基準を置く観点からは, 常に能動的な力ではなく, 反動的な力が勝利するからだ. 第一の価値転換は, <肉体>や<自然>を嫌悪し断罪する弱者の意識から, 強者の意識へと価値基準を置き換えることだ.

   権力を平準化しようとすれば, かならずルサンチマンをうまく組織したものの手に渡ることになる. また, 個々の人間はもっぱらルサンチマンを晴らすことに生の理由を見いだすことになる.
   強い人間の目標となるべきは, 凡庸な人間に自己を合わせたり, また凡庸な人間を見て自分の優越感を味わうのでもなく, 常にいっそう高次の生き方へと自分を推し進めることである.
   また, 弱い人間が目標とすべきは, もっと弱い人間を見て相対的にルサンチマンを晴らしたり, ルサンチマンを自己に向けて自分の生を否定するのではなく, 常に強い人間が示す高次の生き方に憧れつつ, 自分がそのように生きられない場合もその生き方の「圏に置く」ということである.

   問題なのは, こういうことは「頭では」理解できるがしかし実際, 人はルサンチマンと無縁で生きることはできない. その理由は, くやしい, 憎い, という思いが, 認識ではなくて感情にほかならないからだ. ルサンチマンは感情そのものであり, その意味では肉体的な強さをもってこの要求を阻んでいる.

* バタイユ
** 内的体験 (無神学大全)  ジョルジュ・バタイユ  出口裕弘訳  平凡社ライブラリー  (1998)
   至高の行為とは, 次のようなものだ.
    - 陶酔, 酩酊
    - エロティックな流出
    - 笑い
    - 供儀 (映画や小説も含む) の流出
    - 詩の流出 

** エロスの涙  ジョルジュ・バタイユ    樋口裕一訳  (1995)
   性行為 (これこそが人間の起源であり, 始まりである) における人間の本質は, 狂乱という出口しかない問題を人間に提出する. この狂乱は「小さな死」 (性行為によってひきおこされる恍惚状態を指す俗語) の中で味わうことができる. 「小さな死」を最終的な死の予感としてこそ初めて私は十全に生きることができるのではあるまいか.
   痙攣的な喜びの荒々しさが私の心の中にある. この荒々しさは, 言うも恐ろしいことだが, 同時に死の中心にもある. その中心は私の中で口を開いている.
   理性の「末端」は理性を超えるものであり, それゆえ, 理性の「目的」は理性を超越することと矛盾しないという事実, その事実にこそ, 理性の限界があるのだ.
   笑いと嗚咽の混乱の中にいて, 自分を破壊されそうな興奮にかられながら, 私が超越の荒々しさによって捕らえるのは, わたしの力を超える快楽と恐怖とが似ているということであり, 耐え難い悦びと最終的な苦痛とが類似しているということなのである.

   エロティシズムの基本は性行為である. ところで, この行為は禁止を受けることになる. 愛の行為を行うことは, こっそりとするのでない限りは, とんでもないことであり, 禁じられているのである. ところが, こっそりとそれをすると, 禁じられているものは禁じられているがゆえに, 変貌し, 不吉であると同時に神聖な明かりで照らし出される. 一言で言えば, 宗教の明かりで照らし出される. 禁止に違反することが人の心を魅了するのだ.
   しかし, この輝きを放つのは単にエロティシズムだけではない. 死が喉を開いて, 一人の人生を終わりにする瞬間に作用する荒々しい激しさが働くたびに, その輝きが宗教生活を照らし出す.
   私たちの人生全体は死に覆われている. しかし, 私の中では, 決定的な死は奇妙な勝利の意味を持っている. 詩は輝きで私を浸し, 私の中に限りなく楽しい笑いを開く. 消滅の笑いである. 「小さな死」においては, 実際には死なないままで, 大勝利の感覚の中で崩れ落ちることができる.

   宗教的恍惚とエロティシズムと, とりわけサディズムとは同じものなのだ. エロティシズムは, 恐怖と宗教的なものの一体としての宗教的エロティシズムの中にある. 宗教は全面的に供犠に立脚している. しかし, 果てしない遠回りによってのみ, エロティシズムは, いくつもの対立がはっきりと結びつきあっているように見える瞬間に達することができたのである. すなわち, 協議の中にある宗教的恐怖が, エロティシズムの深遠にある, エロティシズムのみが光を当てることのできる最後の嗚咽と結びつく瞬間に.

* 立川談志
** あなたも落語家になれる  三一書房 (現代落語論其二)
  落語とは一口に言って「人間の業の肯定を前提とする一人芸である」といえる. 笑わせる中に, 人間の業の肯定を追及していくのを本当の落語だと私は思っているし, これこそ落語の本質だと考えている.
  落語家は「笑わせ屋」だけではない. 笑いはたしかに誰しも持っている快き生理であり, 歓迎されるものであるが, 落語にとって大事なことは, 人間の業を肯定することだ. 眠いときには寝ちまうモンなんだ, これだけはしてはいけないということを, やってしまうものが人間なのだ.

  昔は, 人間の枠をはずされたものが落語家であり, 笑われるではなく, 嘲われるであり, 嗤われるであったのだ. 人間の道徳的な規範で律することができなかったのである.
現代は落語家は特殊家業ではなくなってしまったし, 大衆にとって文化人として, スターとして, 道徳的に生きることを求めるようになった. 寄席と落語家が, 明るく立派になってしまったのだ.
ワイセツでない芸術はないというが, それに近い落語は, ワイセツ・反社会・反モラルがあった. 落語家自身, はみ出し者であった. 当時は, 寄席に行くことは不良とみなされ, 遊び人だった. 落語と落語家は, やはりそこへもどるべきなのではなだろうか・これが, 落語家の最後の砦であり, 死に場所のように私は思えるのだし, そのように生きてやろうとも考えてはいるのだが・・.

  いまや, 伝統だけを語っていても客は聴いてくれない. 現代が理解できて, また現代人としてのメディアを確立したものだけが, 伝統を語ることができるし, 客も聞いてくれる. そのまま現代をドキュメントとして通用しているわけだし, これらの人が落語をやったら大衆の共感と支持も多く得られる.

  大衆芸というものは, つねにその時代時代のなかで生きていかねばならぬ宿命みたいなものをもっており, 次から次へと, 時代とともに内容・主題が変わっていって, その結果, およそ従来からの落語とは縁遠いものになったとしても, それなりに意味のあることだし, むしろそれこそ落語と認めなければいけないのだと考えている.

  大学の落語研究会でよく言うのだが,
「きみたち, 落語家の作品のリフレインも楽しみの一つだろうが, キミたちしかできないこと, 君たちしか見えない世界, 君たちの年代にしか感じないことがあるはずだろう. なぜそれを喋らないのだ. 第一, 客は落語の形もわからないのだし, 上手・下手を形の基準で決めたりはしない. 逆に形で決めりゃ, 君たちはプロと比較すると前座に毛の生えた程度だ. なら, むしろ面白いか面白くないかで勝負してみろよ. そうなると私たちプロも, 君たちのセンスを見習うところも出てくるはずだが・・・」
作品を演じるよりも, 主題を先に出してやったら面白いのではないか.

  業の肯定は, 業を克服するという人間の心がけがあってはじめて成り立つもんだ. 本楽それが人間の生き方の基本であったが, このごろでは生き方への努力, つまり, 業の克服への努力が少なくなってきた現在, 科学文明の進歩は, 人間になるべく辛いこと苦しいことをさせないように, 便利に便利により多くよりはやくにと進んできた. 科学が進歩するほど業の克服も必要なくなり, したがって業の肯定も, 受けなくなる危険がある. 3/3/08

** 絶好調  立川談志  講談社
   落語とは, 業の肯定だ. 人間ってのは, 眠くなると寝ちゃうし, 遊びたくなったら仕事を放りだすし, 勉強しろといわれたって, やなもんはやだし. [業の克服」が講談だとすると, 落語は業を肯定する. 人間てなあ, その程度のもんだよ, と. 国が一致協力してがんばる時代, 業の克服をしないと生産性が上がらない. そんな時代に業の肯定をしたから, 落語が喝采を浴びた. 熊さん, 八つぁんに自己を投影して安心したり, つらいときのなぐさめにした. しかし, 現代みたいに, 寝たいときは寝ちゃえ, 食いたいときに食え, みたいに, みんなが業の肯定をするようになっちゃった. 我慢したり, 努力したりしなくなっちゃった. さァて, 落語はどうしましょ.

   落語のバックホーンである貧乏がなくなっちゃった. 現代人の前で古典落語をやっても, 彼らにはわからない.

   現代の言葉が落語の中に入ってくるのは, 嫌です. 落語の中の情感を壊すから.

   経済的に満足しちゃってる連中になにか言ったってダメだネ. 日本はもう発展途上国ではなくなってから, 世の中をてきとうに仕事して, お金もらって満足してる. 落語の世界も, 楽な世界になっちゃった. 「落語よ, 滅びよ」と思ってる. 落語なんぞなくなっても誰も何も困らない. (許光俊のクラシック音楽は滅びる, と同じだ)

   作品よりも, 己の存在の方が, 芸人, 大事なんだ.

   感情の芸ってのは, 感情移入しないところに成り立っているもんで, あまり演じる人物が感情を出すと, その芸は野暮なのだ. ところが, これをテレビでやると, 鑑賞に堪えなくなる.

   「贅沢な時間」といやあ, なんてったって寝てるときだ. こんな贅沢なことはないネ. 何も生産しないんだから・・・. ふとんの中にジーっと入っているとき, ぬるま湯にボォーッ, とつかっているとき, そこでジーンとしびれているみたいな快感を味わっている幸せ. それでいいんだと思っている. 自分の幸せのボーダーラインが低い. それで贅沢しているという意識が強いのだ.

   一口にいやあ, 物の基準がわからなくなった. どれがよくて, どれが悪いのか, わからなくなった. 大人たちが文明に振り回され, 量のみの幸福を追い, 子供に示せなくなった. 落語家というのは, 落語を通して人間の業を語るものであり, その業を肯定して, 容認してやるのがその内容だ. 常識という, 人間が集団で暮らすために無理して作ったシステム. 所詮人間がつくったシステムだから当然無理がある. それをつくことによって起きる同感の笑いだったのが, 現代やその基準が崩れ, ここがそれぞれ, かって基も見える生活ができるようになった. 早い話が, 落語が通用しなくなった. 「もっと勉強しろ! 」. なあ, 若い衆よ, 人間として生きる努力は要らないのかね. すべて文明という他人のつくったもので快適を得ていていいのかネ. そんなリッチマンのルールができるのかエ.

   すべての行為というのは不快感の解消から始まるんだ. 一番の不快感の解消というのはなんだというと, これは死に対する不快ね. それから「飢え」「寒さ」, いわゆる「貧乏」とかね. その不快感の解消のためにすべてやるわけよ. その不快感の解消を自分でやるのが文化というんだよ. それを人にやってもらうのを文明というんだよ. 俺の周りにはあまりにも文明が多くなって, 俺の文化がいられなくなっちゃった.
*
** 大名人のつもり  立川談志  講談社

  常識とは, それで抑えないとうまく生活していけなくなっちまうので創り上げたもの

  人物や形にとらわれず, 感情注入ができてしまえば, 細かなテクニックによる芸のうまい, ヘタはどうでもよくなる. ようは, その噺を語る落語家の中身だ. 生き様だ.

  昔は, 常識は問わず語らずのうちに, 社会に浸透していたから, 噺家はそれを冷やかせばよかった. でも, 今は落語も, 昔とは違った解釈, 構成で再編する必要があるんじゃないか?

  伝統のリズムとメロディーがあり, それらにあらゆる「受けるフレーズ」をぶっこんでやってみるとか, 会話として不可能に近いものまで可能にしてやろう, しゃべってやろう. そんなことをしながら落語をやっていきたい.

  お前ほどの才能があるやつが, 何でこんなことができないの

  落語は個人芸だから一人がってに「狂える」, 「狂」になれる. ほかのものだったら共同制作だから, それをやったらひどいことになってただろう.

  今は, 世間体が少なくなった. 常識とは, 「己と世間体との共同の価値観」だが, 時代とともに変わりつつある常識, みんなで共有していた常識がミニになったり, またはマスコミがそれを動かしている企業が, 金儲けのために常識のルールを勝手に変えて, それを「常識」と言わせているのではないか? 早い話が, ファッションショーだ. 落語とは, 常識を揶揄し, 非常識の肯定である.

  笑わせるためにはいろんな手を使うのは当然で, 古典落語の中から「人間の業の肯定」する部分の抽出, 又は強調. 現代をしゃべるときは, ニュース性, そのものの本質をわたしなりの分解, つまり解説か, 時には罵倒. これが受けるのだ. タブーを語る. バカバカしい噺, くだらないシャレ, うまいシャレ, つまりウィット, ナンセンス, パロディ, シニック等々・・・. それらを含めた, ピエロとしての己をさらす. 己の人生そのものを同様に扱う, 立川談志そのものがドキュメントとしての落語, 落語家.
  落語家なんてなあ, 世の人たちがつくった人間の暮らしのためのルール, つまり常識という, 無理をしてもつくらニャ生きていけない人間たちの, またそれらを学習している世間というものに, それらは, 基本的にいやぁ, 無理をしているのだから, たまにゃあ, それを無視したり, 反発したり, 非常識を進めて, 「自分勝手に生きろい」といい, 「人生なんざあ所詮なりゆき」と言うのである.

  楽に暮らす方法の数々を文明と呼ぶ. つまり, 生き延びるための知性が, より楽に生きるための「文明」として発展してきたことを俗に「世の進歩」という. 人間が楽になることが良しとされ, すべてがそれに準じていて, それに参加するために学校があり, 職場がある. それらは知性というものに支配されているから, 人間本来の「業」ともいえる欲望, それぞれの持っている非生産的な行為や, 反社会的な行動, 思考は排除されるようになる. それらは常識というルールで押さえているが, 抑えているのだからどっかで無理が出る. それじゃあ困るから, ある部分で許したのが「芸術」であり, 「スポーツ」であり, 「 SM クラブ」であり, 「新興宗教」である. しかし, 文明は人間を楽にするものではないのだ, と気づき始めてきたのが今日だろう.
  欲望のかぎり=業をとめるのが知性だが, 知性の集大成である常識を, どの辺で線を引くのか, という問題がある. 昔は, 世間体といったが, 今ではそれがメッチャメチャ. その時のマスコミの流れに従っているだけで, ただやたらにワアワアと叫ぶ.
  わたしならこういう.
「にんげんなんざあ, 生きていることにさして意味も意義もないのだから「食って」「寝て」「やって」チョン, でいいものをそれではあまりにも「生き甲斐がない」というならば, 仕方がないからどっかで生き甲斐を探すこった. その生き甲斐は何でもいいが, できれば小さい方がいい. 他人に, 社会に, 地球にあまり迷惑のかからない方がいい. すくなくとも「文明」とか「正義」とか「親切」とか「純粋」とかにしないほうがいい. そんなものを生き甲斐にすると, 当然それを他人に認めさせたくなるものだから, よしたほうがいい.
  人間死んだらなんにもないから淋しくてたまらず, なにかいいことをしようと余計なことをする. これは未練というものだ.

  本なんぞ読んでいると時間の無駄遣いであるし, 了見が悪くなり人生が混乱する. 生きていくことに自信が無かったり, 不安がっているやつが本を読むのである. ついでにいうと勉強をすることを善いことと決め, 「努力」という無理なムダをしたり, 必要も無い知識を得ようとあがくのが人生なのかもしれナイ. してみりゃ, 無駄なことである. 「努力とは馬鹿に与えられた夢」だし, 「貧乏人の暇つぶし」だ. 本なんざあ, ま, 趣味というか, 「退屈しのぎにいくらか必要」程度であって, 酒や女や博打のほうがはるかに健康的であり, 身体にいい. この情報文化だが, 文明だかはワカレねど, 「これでもか, これでもか」「さあ来い, さあ買え, これを知れ」との日夜の脅迫, 不安, 不快. 気づいたときは完全な被害妄想となっていた.
  
  所詮人間なんてムダなんだ. 科学も道徳もあるもんか, 全部がムダなんだ.

  投票に行かないことはけしからん? バカいうな. 本当に困りゃあ行動に移す. なにしろ人間の行動のすべての基本は「不快からの脱出」から始まるのだから・・・.

  とにかく日本人, 騒ぎたいのだ. 騒ぎの歯止めなんザァいるものか. なにかあったら騒いで, 己の生きているのを, そこに感じているんだ. それが「現代人の生き甲斐」なのだろう. 本当の自分を見つめると気が狂うかもしれナイからなのだろう.

  人生なんてたいして意味も意義もないから, そこになにか意義らしいものを探しているのだ. 3/3/08

  落語を縦横無尽に使いきれる「己派」とも言うべきパーソナリティを大切にすべきであった.
  整理すると, 落語という形式を伝統の線上において仕上げてくる「噺家」 (文楽, 円生, 小さん・・・) と, 時には伝統の線上などをはるかに越え, 人情・常識をはるかに超えた「イリュージョン」の世界に近い内容を語ってきた落語家 (志ん生, 円遊, 金語楼, 権太楼・・・), この両輪がくずれだしたのだ. すばらしき個性派が育たなくなってしまった.
  立川談志がなにをやってきたかというと, 内容的には, 貧乏のどん底, 人間の情, ルールなぞ出る余裕もない, とにかく生きるのが精一杯で, そのためには, 死んだ隣のやつの腹を裂いてもってっちゃう「黄金餅」, あれに代表される咄. または, 常識がある程度出来上がったけども, 作り物だから無理がある. そこでそれらを揶揄する. 「親孝行なんて無理だよな」「夫婦喧嘩はあたりまえ」という世界.
  ところが, この二つ, 飢えと寒さ・・・つまり「貧乏」は解消される, そしておまけに, 作られてきた「常識」というものの無理と嘘に気づいてきた. じゃあ, どうする. イリュージョンしか手があるまい.

** 文句と御託  立川談志  講談社
  人間の業とは, 「人間なんザァ腹いっぱいになりゃあうごかないもんだし〓働かないもんだ」ということを前提にしていた. つまり, しかたがないから働くのだし, また, 人間の欲望にはかぎりがないもの, といっても知性というものがあるはずだから, どこかで欲望をとめる作業をするはずであり, 曰く「人間そんなにやるもんではないよ」だった. 人間, やってはいけないことを決めていた. それは人間が生きてゆくために必要なものであり, 長い年月をかけてやっとみつけ, 守ってきたものだ. つまり, 常識. 人間なんて弱い動物だから, 知性を働かせて, これを「文明の進歩」という. その延長線上に, 宇宙の征服まであるのだろうか?

  いい加減な言い方だが, 業の肯定といってもそこそこのものであり, それはお江戸の町の人間の中での業の克服の限界があった. 落語の登場人物は, 「欲張るとろくなことがない」「便利になってもたいしたことがない」ということを知っていた. 今の日本はどうだろう. すべて札束しか価値を持ってない. そしてその価値が, 「すべての価値を優る」のが今の日本国だ. これも業の肯定といっていいのか?

  違うといいたい. どこか人間, 知性という歯止めがかかるはずだ. それを含めて業の肯定であり, その知性は文明の進歩に疑問を持ち続けるはずであり, その根本は, 生物の生きている理由は, 種族の継続と自己保存ならば, 「何もそんなに文明を求めなくてもいいのではないか」とどこかで忠告しているはずだろう.

  人間てのは生きるために無理して暮らしてきた. 「文明」なんと言って人間が楽になるために, 発明, 発見してきたが, 所詮人間無理して生きているのだから, やはり無理だ. 無理してこしらえたものがルールという規則, 何々主義・・・に「どうも無理があるなぁ」と与太郎に, 熊さんに喋らせてきた.
落語がはやった頃は, 世の中に常識が定着していた. だから, それをからかったり, 非常識なやつを登場させて, 観客のどこかに「そうだよな」と賛同も得てきた. ところが, 現代は, そんな常識がなくなってしまった. それは貧乏という「飢え」と「寒さ」がなくなってしまったから.

  人間の一生なんて, 所詮「食って, 寝て, やって, チョン」」で, たいした意義も目的もないので, それを作ろうとする. つくらないと不安でいられない. 「死ねねえから生きてるんだし, ただ生きているとどうしても退屈をしたり, つまらなかったりするから意義をどっかから持ってきて, それにすがっているだけだ」. ,

  落語がわかる落語家が落語家なのに, 他のほとんどはは落語という作品をただ話すだけ, 噺家なのだ. それだから己の世の中に対する不安や不満, 生きていることの嬉しさ, 悲しさ, そして死の恐怖・それを茶化しての世の面白きこと, バカバカしきこと, あきれたこと, ものすごいこと, 思い切ったこと・・・とても喋れない.

  人間, 明日を処理し, 来年を企画し処理するてんで, のべつに先へ先へだから, 今日も昨日も, つまり過去はそのまま未消化に残っちまう. 未消化に残ってしまうから仕方なく, 忘れよう, とする. 過ぎたことはない, 悔恨すらない. あったら狂う.
  人間「なにが不安か」「なにが情けない」かといって, 己の過去が確認できないほどつらいことはない. だって自分の歴史が意識から消えちまうのだから.

  最近, なにをしてもつまらない. ツマラナイというのはどういうことなのかを考える. もしつまらないのが日常であり, それが正常なら大事なことだ. 無理して面白いことを探すにゃ及ばない. つまらないが健康であり, 幸福でもある. 早い話, なにをしたって, 見たとて, たいしたことがないとわかったんだから, それは当然の反応である.
  世間では, クソつまんないものを無理に面白がらせようとする

  「業」とは常識以外のもの, 非常識. それに加えて常識非常識以前のなんとも説明のつかない夢のようなものである. それは部分的には表現できても, 全篇それでやったらわけがわかんなくなる. 落語にはそれらが積み重なって古典として残っているものの, それに気がつかずにむしろその部分を排除しているのが今の噺家である.
  早い話, 「笑わせればいいさ」ならばそれもいいサ. 芸能なんザァ, 観客を一つのユートピアに入れればそれで済む. しかし, ユートピアに入れるための背景に, 非常識とイリュージョンが必要だ, といっているのだ.

  世の中に無駄なこととか, 無駄なものてえのは山ほどある. 人間生きていくためには, ほとんど必要ないことなのだ. ところが, 人間てのは, 生きていくために「必要ないものを必要」しないと生きていけない代物らしい.

  理屈を言わないと生きていけない連中のために「学問」というジャンル, 部分を残してある.
「でも, 学問のおかげで月も, 星も, 風も, 雨もわかるようになったろう」
「別にわかんなくてもよかったイ. お月様ンなかには兎がいたのにいなくなっちゃった〓」

  家元の落語は, 世にある正常というか, 「類型」みたいなものに「異常」という「変型」を思いつくまま浮かぶままに会話に放り込んで, 「類型化された落語に活性を」・・・と言えば聞こえがいいが放り込んで遊んでみる.

  世の中に安定はない. その不安から逃れるために, それを克服しようと人間は修行を積んだり教養を身につけたりする. それが現代なくなったからさあたいへん. 不安から逃れようとして人は騒ぎ, ただただハシャグ, それを煽り, たきつけているのがテレビ, とこうなる.
で, 野球場, コンサートで, 街で, 我が家のテレビの前で・・・とこうなる.
  不安定で安定を求め, そのために己を鍛えて「不安定を克服する」. けど, 克服したとしてもすぐ「つぎの不安がくる」, それを解決したとき, 進歩であり, 成功である. でも, またつぎの不安がくる. その繰り返しが人生. 騒ぎまくって忘れようとしても, ダメだ. 気づけば不安定だし, 年中騒いでいるやつの如くバカにもハレンチにもなれまい. 不快だけど不安定の場所にしかいられない. 安定も不安定.
家元, 「人間に安定はない, 不安定なところでしか暮らせない」ということを覚えた.

** 立川談志遺言大全集
   落語には, その頃の人生のすべてがあった. つまりそこに生きた人間である. その人間の苦しさ, 楽しさ, 嫌らしさ, 執念, 無念・・・これらを交差させ, 人間を描いた. それを己にダブらせた. それらが, 「一つの作品として完成」したとき, 落語は庶民から離れていった. あとは演者のパーソナリティのみである. この全集は, 立川談志という落語家を通しての発表であり, 加えて, 人間の奥底にあるデイモンというか, イリュージョンというか, それらをひっくるめての挑戦である.

   「やかん」のテーマは, 人間の答えなんていい加減なものでいいんで, 「とりあえず答えがあればそれでいい」ということだ. 「思考ストップ」「どこまで行っても際限がないから, どこかでとめておく」

   どうして, 化けることの対象として, たぬきやきつねが選ばれたのか? 動物なら他にもいるじゃないか. きつねたぬきは, 化かしそうに見えたからそうなったのか? それとも人間, どっかで化かしてもらいたいのかもしれない. 人間はどこかで何かにだまされたいのだ. 不完全である人間は, きっとだまされることによって安心したり, または戒めの材料としたのであろう.
   騙されてばかりでは, 暮らせないから無理しているのだろう. 学習なんザァ, 一口にいやあ, 生きていくための方法である. すると, どっかでだまされたくなる. あまり己に害のない騙され方がいい. 手品なんて, その一つ. 上手くだまされれば, 拍手するし, 下手に騙されれば文句をつける.
   もっといやぁ, なんだかつじつまの合わない世界に行きたいのかもしれない. 「たぬさい」

   ことによると, 昔は落語はもっと色っぽかったのではないか?    しかし, 明治の御世ともなって神国がはじまり, 戦争が始まり, 戦争を優先するために, こういう色事の話というのは兵隊の士気にさわる, 軟弱であるというんで, これらを取り払ったばかりか, その国策に追従して, はなし塚なんて実にばかげたものを作って, そこへその種の落語を禁演落語と称して埋めてしまった. 戦争に負けて, また掘り出したのだが, 落語家は不精で不勉強だから, そのまんま色気抜きの艶話として残った.

   前座が出ると, 無条件で手をたたく, 昔からのくすぐりで, 何でも面白くもなんともないのに, みんな笑う. 昔なら, まずこいつは自分の鑑賞に堪えるかを吟味された.

   志ん生のらくだが, へんに落語的リアリティがある. 「食うと蚊がバカになっちゃう」 (これをしなければ) 的なところがない.

** 東京人  2001 年 11 月
   立川談志インタビュー

   業の肯定というのは, 「イリュージョン」だと思う. イリュージョンというのは, 学習しなければ人間なんてのは何もありませんから, 学習はするんです. でも, 学習されたことが, 全部その通りに出てくるとは限らない. 夢の中の世界のように, 非常に混沌としたものが存在して, それを学習という名で, どうやらまとめているのが, 人間というものである. でも, そのまとまらない部分があるはずなんですよ. それを求めるから, イリュージョンという名の手品を見たり, 夢でバランスを取ってみたりするのではないかと.
