#+OPTIONS: toc:nil
* Poetry: 詩
  詩について

** フランス
*** ジュ・トゥ・ヴ
(*) あたしにはあなたの苦しみがわかります (J'ai compris ta detress

大好きなあなた (Cher amourex

そしてあなたの決意には負けてしまいます (et je cede a tes voeux

あたしをあなたの情婦にしてちょうだい (fais de moi ta maitresse

悲しみの向こうに (Loin de nous la sagesse

分別なんか追いやってしまいましょう (Plus de tristesse

貴重な一瞬をあたしは心底から望んでいるのよ (J'aspire a l'instant precieux

二人が幸福になれるような一瞬を (Ou nous serons hereux

あなたが欲しいの (Je te vex

(*)

後悔することなどあたしにはなくて (Je n'al pas de regrets

ひとつの欲望しかありはしません (Et je n'ai qu'une envie

あなたのお側で寄り添うように (Pres de toi la tout pres

一生を送ることなんです (Vivre toute ma vie

あたしの心があなたのものとなる暮らし (Que mon coeur soit le tien

あなたのくちびるはあたしのものになって (Et la levre la mienne

あなたの身体があたしのものになり (Que ton vorps soit le mien

あたしの肉体はすべてあなたのものとなって・・・・ (Et que toute ma chair soit tienne


そうよあたしはあなたの目の中に (Oui je vois dans tex yeux

崇高な約束を見るの (La divine promesse

あなたの愛に満ち溢れた心が (Que ton voeur amoureux

同じ炎に燃え上がり (Vient chercher ma caresse

永久に絡み合う (Enlaces pour toujours

あたしの愛撫を求めにくるのよ (Brules des memes flammes

お互いの愛の夢の中で (Dans des reves d'amours

あたしたちは魂を交換し合うことになるのね (Nous echangerous nos deux ames!

*** シャルル・ボードレール
**** 「悪の華」より  読者に

#+begin_src text
     しかしながら    金狼    豹    牝狼
     猿    さそり    はげ鷹    蛇
     われらの悪徳というけがらわしい動物園の
     啼き    吠え    唸り    這いまわる怪物どもの中に

     ひときわ醜く    性悪な    不潔な獣が一匹いる!
     大げさな身振りもしないし    大げさな叫び声も立てないが
     みずから好んで    この大地を廃墟にして
     あくびをしながら    世界をのみこむ

     そいつこそは倦怠だ!    目には思わず涙を浮かべ
     水煙管をふかしながら    断頭台を夢みている
     読者よ  君もご存じだ    この微妙な怪物を
     -----偽善の読者よ-----わが同類よ-----わが兄弟よ! 
#+end_src

**** 酔いたまえ    「パリの憂鬱」 
  常に酔っていなければならぬ. それがすべてだ. 問題はそれしかない.

  しかし, 何に? 酒にでも, 詩にでも美徳にでも, お好きなように. とにかく酔いたまえ.

  風に, 波に, 星に, 鳥に, 時計に, およそ移ろうもの, およそ呻くもの, およそめぐるもの, およそ歌うもの, およそ語るもののすべてに, 訊ねるがいい, いまなん時かと. すると, 風も, 波も, 星も, 鳥も, 時計も, 君に答えるだろう. 《いまは酔うべき時! 「時間」の奴隷として虐げられたくなかったら, 酔いたまえ, 絶えず酔いたまえ! 酒にでも, 詩にでも美徳にでも, およそ好きなように》と.

* ドイツ
** リヒャルト・ワーグナー
*** 神聖祝祭劇「ニーベルングの指環」
**** 第二夜「ジークフリート」

#+begin_src text
ジークフリート
ああ! なんと美しい!
輝く雲がうねりつつ,
明るい空をふちどっている.
雲の波のかなたから
輝く太陽の笑顔がのぞく!

快い口元にわが眼はひきつけられ,
この, 燃える唇は, 情熱にかわく,
私の眼を喜ばせるその口で, うるおして欲しいのだ!

ブリュンヒルデ
私は永遠でしたし, いまも永遠ですが,
あなたの幸せのためにこそ永遠です.
甘い憧れの喜びの中でこそ永遠なのです!
ジークフリート! ジークフリート! すばらしい人! 世界の宝!
大地の命! 微笑む英雄!
さあ, 私から離れてください.
私に近寄らないで下さい.
力任せに, 荒々しく, 無理強いをしないで下さい.
貴方を信頼する女をそっとして置いてください.
自分自身の姿を澄んだ池に映した事が在りますか?
其処には活気溢れた貴方自身の姿を見出したでしょう.
でも一度かき回し波を立てれば写す水面は砕け,
波の狭間に消えてしまいます.
私は貴方を写す水面のような存在です.
だから私に触れないで下さい.
そうすれば永遠に貴方の笑顔を, 明るい英雄の姿を
映し出していましょう.
ああ! ジークフリート! 輝く若葉!
私をそっとしておいて.
私によって貴方の価値を貶めないで下さい.

ジークフリート
己 (おれ) は貴女を愛しているし
貴女は己 (おれ) を愛すべきだ.
貴女を得ることが出来れば, 己 (おれ) は己 (おれ) 以上のものとなります.
すばらしい小川が眼の前でうねっている.
おれの姿がくずれれば, 燃え上がる炎を,
おれ自身で燃えたたせ, その上, 流れで冷やそうと,
あるがままのこの姿で
小川の中に飛び込むのだ.
ああその大波が, おれを飲み込んで,
流れの中に憧れが消えればよい!
目覚めよ!, ブリュンヒルデ!
起きてください. 少女よ.
生きて, 笑え, 甘い喜び!
貴女は己 (おれ) のものとなってください.
いえ! 己 (おれ) そのものなってなって下さい.

ブリュンヒルデおお, ジークフリート!
私は前から貴方のものでした.

ジークフリート
前からそうでしたら,
今からも己 (おれ) のものとなって下さい.

ブリュンヒルデ 永遠に貴方のものになりましょう.

ジークフリート

貴女は己 (おれ) のものとなって下さい.
この腕は確り貴女を掻き抱き
この胸は高鳴り貴女と同じ鼓動を感じます.
眼と眼はたがいに燃えあがり,
熱い息がはずむ.
眼と眼, 口と口.
それであなたはわたしのもの.
ブリュンヒルデは己 (おれ) のものにならないという不安から開放してください.

ブリュンヒルデ
今私は貴方のものなるのですか?
神々しい静寂に包まれた心は波立ち,
無垢な光が灼熱の焔へと変わり燃え上がる.
天上の智恵も知識も悦喜の嵐の前には吹き飛ぶ.
今私は貴方のもの?
ジークフリート, ジークフリート!
解りますか?
私の眼彩を見た時
貴方の眸は燃え上がらなかったのですか?
私の腕が貴方を抱きしめた時
貴方の体は燃え上がらなかったのですか?
私の血が激流となって貴方に流れた時
野生の炎を感じなかったの?
この荒々しく激しい女を見て
ジークフリート! 貴方は恐ろしく無いの?

ジークフリート
ああ!
血潮が炎に換わった時
己 (おれ) と貴方の眼彩がお互いを焼き尽くす時
貴方を熱烈に抱きしめる時
俺の勇気が今もどって来ました.
終ぞ知らなかった恐れをブリュンヒルデが教えてくれたが,
莫迦な己 (おれ) はすっかり忘れてしまったみたいだ.

ブリュンヒルデ
ああ! 子供らしい英雄よ
ああ! 輝ける少年よ!
崇高な行為をそれと知らずやり遂げる愚かな宝よ!
笑いながら貴方を愛しましょう.
笑いながら  盲 (め) しいましょう.
笑いながら私達は滅びましょう.
ヴァルハラの, 輝く世界よ, さようなら.
誇り高き城よ塵となって砕けよ.
光り輝く神々の栄華よ, さようなら.
永遠の一族よ喜びの内に終末を迎えよ!
ノルンよ! 運命の絆を断ち切れ!
神々の黄昏よ, たそがれはじめよ!
破滅の夜よ! 湧きあがれ!
今はジークフリートの星が輝くのだ.
彼はわたしには永遠で, わたしには恒久,
すべての宝で, 唯一で, すべて.
光り輝く愛! 笑ってる死!

ジークフリート

微笑みながら目覚めた女よ
ブリュンヒルデは生き
ブリュンヒルデは笑う
我等を照らすこの陽に祝福を!
我等に陽を射す太陽に祝福を!
夜を終らせた光に祝福を!
ブリュンヒルデが生きている世界に祝福を!
ブリュンヒルデは目覚め, 生きている,
おれに向かい, 微笑みかける.
おれに向かい, 光り輝くブリュンヒルデの星よ!
彼女はおれにとり永遠で, おれには恒久,
すべての宝で, 唯一で, すべて.
光り輝く愛! 笑ってる死! 
#+end_src

