#+OPTIONS: toc:nil
* Psychology: 心理学
  心理学について
* 読書記録
** 青年期の自己形成    伊藤順康    川島書店 (1982
   「教える→わかる→暗記する」で完結する学びではなく, いわば発展性を備えた関心システムの基礎を気づくことが大事なのだ. だが, われわれの学生時代のほとんどが前者の学びだった. 試験勉強, 中でも大学受験がそうだ. 学びの課程よりも, その結果のほうを重んじ, ただひたすら物事を覚えることに努力を傾けていたといえよう. 数学さえも, パターンを覚えて機械的に解くところまで至っていたと思う. 恐ろしいのは, もしかするとこういう学びが普通だと思ってしまうことだ. われわれは, ひたすら結果を獲得することを, 自分の学びの中心にすえて平気になってしまったのではないだろうか?

   学んでいるつもりで学んでいない人には, 次の三つのタイプがある. (「学びの構造」佐伯胖  東洋館出版社より) つまり A. 無気力型, B. がり勉型, C. ハウ・トゥ型の三つである.
   A はやる気がない. 勉強は, ただのやっつけ仕事であり, 何の興味もなく, 熱中もなく, 毎日毎日をなんとなく生きているというタイプである. 知るということが, 善いことだという実感がまるでなく, 勉強といえばつらいもの, しんどいもの, だけどやれといわれるからせめて最低の要求水準でやり, 後は自由になれると思い込んでいるわけである.
   B は, 実は A とあまりかわない. ただ, 勉強という「無意味な作業」に課す要求水準が高いだけである. 勉強はあくまでやるべき作業であり, やるという動作が勉強のすべてであると考えている. 一生懸命, 丁寧に, きちんきちんと答えを出し, よく勉強しているという評価を得ることだけが彼の生きがいとなっている.
   C は, 方法には興味があるが, その理由には興味がない. 知識は役立つものだと考えてはいるが, その知識の真理に迫ろうとしない.

   教育を受けても, ものはまったく見えてこない. これを「生と知性の乖離」の中に見る. 学ぶことによって, 自分の人間的成長があり, 生き方が深くなり, その集積の上に充実した人生, 自己実現の追求があるという自覚には程遠い.
   一般に, 人間の能力は次の四つのカテゴリーから成るという.

   - 労働・技術の能力
   - 人間関係を統制・調整し自治を行う能力
   - 自然と社会を科学的に認識する能力
   - 世界の状況に感応し, 表現する能力 

   (勝田守一  「能力と発達と学習」  国土社)

   現在は, (3) のみが, しかもかなり歪んだ形で発達している. これは"受験学力"とでも呼ぶべきものになろう. これが通用するのは, 試験だけである. このように操作主義・機能主義に傾き, 結果を重視して記憶力に重みがかかり, 従って生徒はいわゆる根性, つまり相当の忍耐心によって答えていくという構図からは, 真の学びの息吹はますます聞き取りにくくなってしまうだろう.

   詰め込み教育, テストの氾濫の中で, 子供たちは学ぶ楽しさを味わうことができず (従って学習の楽しさ・面白さから自分の将来の方向を見出すことも困難となり), 学ぶ内容が生活からはなれ, あるいは学ぶことが生活の内容を引き上げていくことが少なくなるに連れて, 人間としての正しい, 豊かな価値観を獲得することも少なくなり, 個性的な自己実現を展望することがほとんど不可能になっているということである. 認識能力, 表現能力, , 自治能力, 想像力, などの発達の裏づけのないところでそれは望むほうが無理なのである. 今の状況では, こどもたちは, なにをしたいのか, なにならできるのかを自らとい, 自己の人生・未来の展望を定めることができない, つまりアイデンティティを確立できずにいるということなのである. この状況の中で, 要求される限定的な能力を伸ばすことができると, あるものは思い上がったエリートになり, またこれに順応できないと, あるものは失意のうちに「落ちこぼれ」となり, あるいは「非行」へと走るものもでてくるわけである.

   アイデンティティの未確立, その原因のひとつが「生と知性の乖離」.

   現在の自己のあり方と環境を分析し, そこで課題とされていることを, 自ら担っていくこと, こういう「煩わしいこと」は極力避けようとするのである. 言い換えれば, それをすることが望ましいとは思っても, それを担っていくだけの心情と実践力は持ち合わせていないわけである. 現在の, 目先の安楽さを選んでしまうのである.
   まあ, これは一つは感性の問題 (自分の気持ち第一主義) といえよう. これを安易な自己愛と名づける. 本来の学びは, 自己の生活を豊かにしていくはずのものである. 今まで見えなかったものが見え, 社会の出来事の関連を知り, 新たな価値に目覚め, 自己の生き方が豊かで確かなものになるのを援助するはずのものである. しかし, 学びが形式化すると, 人格形成は放棄される. すると, 本能的・衝動的な側面が現れるのも不思議ではない.
   朝眠たくて起きられないときに, 確かに布団の中にいるほうが楽であり快適であるだろう. だからといって, そうしていると, 人生を棒に振りかねない. このときあえて気持ちに逆らって, 布団から起きるには, 強い目的意識, あるいはそれに支えられた生活習慣の確立がなくてはならないだろう.

   少年期にあっては, 人はいわば社会によって「作られる」ものである. それに対し成人期にあっては自己を「作る」と同時に社会をも「作りかえて行く」存在になっていかねばならない. その転換期が青年期である. 青年期に自己を確立し, 社会の中における自己の位置を定め自己実現の道を歩み始めるべきところである. 既成の価値との葛藤も必要なことでさえあるだろう. しかし, 今は, 葛藤も対立も衝突もなく, あるのはただうつろいやすい感覚だけである.

** 至高体験    コリン・ウィルソン    河出文庫
   至高体験の瞬間は純粋であり, 積極的な幸福感に満ちている. あらゆる疑惑, 恐怖, 禁忌, 緊張, 弱さが追い払われる. 今や, 自己意識は失われる. 世界との分離感や距離感は消滅し, 同時に彼らは世界と一体であると感じ, 世界に融合し, まさに世界に属し, 世界の外側にあるのではなく, 世界の内側に見入るのだ. あたかもその地にやっと到達したかのように, また元来人生がどこかの場所へ到達するための抗争や努力であって, この地こそが到達点であり, これこそがその地にある実感そのものであるかのように! 人はすべて何物かの欠乏感なら知っているが, 一体なにが欠けているのかは知らない. ここに述べた神秘体験は, あいまいな満たされぬ望みに対して, 究極的な満足を与えるものとして感じられる.

*** 至高体験とは
    至高体験の必須条件の一つは, 「エネルギー」である. 至高体験は本質的にエネルギーの噴出なのである. したがって, エネルギータンクに大量のエネルギーを備えている人々のみ至高体験ができる. 至高体験はまっていれば向こうから来るものではなく, 用意周到に, エネルギーを蓄えていなければならないのである.

    カール・ポパー卿はこういった. 人間の偉業は, 精神の, 知性の, 想像力の世界を創造し, それを実在せしめることにある. この世界を「第三世界」と呼んだ. この世界は, ニュートン, アインシュタイン, ベートーベン, トルストイ, プラトンなどの業績を包容する. すなわち, 人類の遺産の中で最も重要な部分なのだ. ちなみに, 第一世界は客観的世界. 第二世界は主観的世界である.
    第三世界は根本的に, 純粋な「意味」の世界である. 意味が意志を刺激し, 意志を欲望で満たして新しい世界を創造する. 意味の世界に近づくほどに, 人間の生命力は超人的段階に向かって増大する. 至高体験とは意味の波の突然のうねりだ. ここで問題になるのは, どうやってうねりを起こすかである. それは「精神集中」によってなされる. 精神集中はタンクの深層からエネルギーをくみ出すポンプの役割をする.

    意味は生への意志を旺盛にする. 至高体験は, 私に努力することの理由を与えてくれるのであり, 努力を通じて, 意志は健康を保つのである. 至高体験とは意味の爆発であり, 意志の強度に正比例している. 人間は外的意味感覚を通じて前に進む. 意味感覚が強いときには, 高度の意志操縦と全般的健康とを保ち得る. 外的意味感覚が失われると, 主観的感情の犠牲となる. 人間はこうした事態を避けようとして, 宗教, 芸術などを生み出した. 音楽, 詩, 自然, 哲学, 数学. これらはすべて, 私が「偏頗な精神」に捕われており, 「本当の自己」は全体的により広範囲の反応を示すものだ, と私に「想い出させ」, あの「汚れた醜い姿」から私を解放してくれる.

    人間の基本的な問題とは, 至高体験が可能である状態を絶えず保っておくことにある. これは現実的には一定の前進力であり, 意気消沈や落胆, さまざまなニュアンスの敗北感の受け入れを頑強に拒むことである.

** 無気力の心理学  波多野誼余夫  稲垣佳世子  中公新書  (1981)
   「獲得された無力感」とは, 自分がいくら努力しても, それが現在ある不都合 (苦痛や生理的欠乏ないしはそれになぞらえられる知的課題での失敗など) を解消するのに役立たないと認知されると, いわば努力一般が信頼されなくなり, 「どうせダメさ」といった諦めが生まれている, というものである. その逆が, 「効力感」, つまり, 努力すれば好ましい変化を達成できるという自信のみならず, それがばねになって意欲的に生き生きと環境に働きかけている, というものである.

   失敗そのものより, その失敗をなんのせいにするかが, 決定的なのである. 成功や失敗に対する原因は, 次の三つの次元で分けられる.

   - 焦点の次元
   - 原因が自分の内部にあるか, それとも外部にあるかの軸. 努力, 能力, 気分などは内部, 運は外部ということになる.
   - 安定性の次元
   - 内部にあるものでも, 能力は安定しているが, 努力や気分は容易に変動する.
   - コントロールの可能性
   - 努-力のほうが, 自分の意志でコントロールできるのに対し, 気分はそういきにくい.

   失敗を努力に起因するものは, 粘り強い. しかし, 努力万能主義は, 一種の非合理的信仰である. 世の中は, いくら努力しても, 実際に能力がなく, どうにもならない場合がある. しかし, それにはきわめて多くの時間を要し, 生活のほかの側面の犠牲を必要とする場合もある. 努力信仰は, 失敗をすべて本人のせいにする. また, 努力したにもかかわらず, ぜんぜん成果が上がらないとき, 能力不足のせいにせざるをえない. そして, 能力不足だと思えば, 意欲は低下する. また, あらかじめ努力しないことによって, 自分が能力がないと人から思われないようにしたい, また自分でもそう思いたい, という行動もでてきかねない.

   自分に合った分野, 自分が特に力を発揮できそうな分野を探すように奨励することが重要である. どの分野で自分がよく力を発揮でき, どの分野は自分は比較的不得意か, といった自分の能力や適正や興味を性格に知っておくことは, よりよく人生を生きるためには重要であろう. 正確な認知に基づいて, 自分にとって「やりがい」のある課題を選び, そこでの努力の有効性を確認して初めて, 本当の自信が得られるというもので, ただなんでも「一生懸命やれば失敗しない」と信じるのでは, 自信にはつながらない. どのように努力するか, そのやり方を工夫することに重点を置くように促すことである.

   他人によって報酬を与えられたり, 評価されたりすると, もともとある興味や向上心が強まるどころか, 逆に消失してしまう. それは, 金銭やごほうびなどの報酬や外的評価の導入が, 自律性の感覚を失わせるためである. 人間には, 自分は自分の行動の源泉でありたいという基本的な要求があると強調する. 効力間の形成には, 努力の主体, つまり行動を始め, それをコントロールしたのは, ほかならぬこの自分であるという感覚, 自律性の感覚が必要不可欠なのだ.

   他者との暖かい交流は, 事物を扱う上での達成の喜びを増幅させ, 効力感を導くことが多い. 自分の成し遂げた仕事が, 誰か他の人のために役立った, 他の人に喜んでもらえた, という実感は, 決して自律性の感覚や内的興味を低下させるものではなく, むしろ達成や成就により大きな意味を与える. 競争的な関係が強調されている文脈は, 効力感は育ちにくい. 他者との競争が強調されるときには, 満足感は, 自分が努力したことからではなく, 自分の能力の高さや好運から来るとする見方が強くなる. 自分や相手の「能力」を評価することにもっぱら関心が向けられる. 競争が強調される文脈では, 人々が結果思考的になるが, この結果というものは, 自分の意志では変えることの難しい「能力」や「運」によって決まっていると考えるようになるのである. その意味で, 競争的な文脈は無力感を生みやすい.
   目標を共有しながら, 各自で積極的に意見を出し合い, 討論する, 仲間同士でのこのようなやりとりが, 自分は相手に認められているという実感をもたらすのであろう. そして, 自分はひとりではない, 自分が困ったときには手助けをしてくれる友達があるのだ, と思えるようになるのである. 自分の存在感や自信も強まろうというものだ. また, 協同的学習を通じて, 他人のためにつくすという気持ちも育ってくるらしいことは興味深い. 使命感や奉仕の精神も, このように「貢献する喜び」を通じて伸びてくるのかもしれない.
   人間が生き生きと, 充実感を持って暮らしていくことは, 自分ひとりでは難しいといえよう. 仲間の中で, 仲間と相互に暖かく, しかし忌憚なくやりとりするなかで, 彼の効力感も育ち, また強められるのである.

   幼いころから目標にしていた有名大学に首尾よくは入れたとしても, それを親や友人が喜んでくれたとしても, それがただちに効力感をもたらすとは必ずしもいえない. それによって時 b んはがんばればやれるのだという実感もわいてこないし, ましてそれがバネになって, より生き生きとした, 充実した楽しい日々がおくれるとは限らない. 実際, せっかく大学に入ったのに, やりたいこと, やりがいのあることを見つけようともせず「無気力」に暮らしている人は驚くほど多いのである.
   これは, なぜなら, ひとつには彼の目標達成が「他人の」判断, それも合格かだめかという大まかな二分法的判断に左右されるものであって, 自分がいかに成長したのか, 何に関して熟達したのか, 本人にははっきりと実感としてつかめない, ということがあろう. 自己向上に伴う内的充実感がないと, 成功は外的な報酬になってしまい, 自律性の感覚を失わせることにもなりやすい. それと, 自己向上の実感はあるものの, それが本人にとって価値のある成長や熟達でない, という場合があろう. 何年も受験準備に打ち込んでいれば, 「受験学力」に関する限り, 自分なりに力がついたと感じることはありそうだ. けれども, 彼の立てている目標は, もともと受験に成功することだから, 「受験学力がついた」こと自体が内的満足を与えるものではない. つまり, 自分にとって本当に「好ましい」変化を成し遂げた, とはみなせないので, 真の効力感が生まれないのである.
   これから, 本人が自己向上を実感しうる, ということが大事だということがわかる. 向上の判断基準が外部にある限り, 成功の喜びも, せいぜい一時的なものにとどまるのである.
   熟達者の的確な判断は, 結局, 彼らがその分野に関してよく構造化された知識を持ち, それを上手に利用しているためだ. この知識の構造は, スキーマとよばれる. 発達したスキーマは, それ自体, 機会があるたびにそれに沿った行動をひきおこす. また, 自他の行動やその所産をスキーマに沿って評価するようになる. このため, 人々の行動は外側から与えられる刺激や評価に依存することがより少なくなる, という方向への変化をもたらすはずだからである. おそらく腕のいい職人というのは, 自分の仕事を自分なりに評価し, そこからある種の内的な満足を引き出していると考えられる. さらに, スキーマが発達してくると, あれこれ判断に迷って苦しむことは, ほとんどなくなる. 外的な成功・失敗や他人の評価というものに一喜一憂することもなくなる. 彼にとってもっとも意味のある評価は, スキーマによって内的に与えられるものなのである. 同時に, 自分で力がついてきた, という内的な感覚と満足が, スキーマから得られるようにもなってくる. これが, 自分の努力によって自分自身を好ましい方向に変ええたという満足につながるのである.

   心理学的な常識からすると, 熟達に至るまでには五百時間, 千五百時間, 五千ないし一万時間といった三つの壁があるように思われる. このためには, 粘り強さと自発性の両方が必要になる. 一般に事物に働きかけ, 他者と交流しつつ人生を送っていく家庭で, 人々は自分自身の存在の意味についての問いを発し, そしてそれに答えていくと考えられる.

   効力感を伸ばしうるためには, 誰もが意味のある熟達の機会を持て, 熟達に伴う内的満足に重きを置き, 外的な成功・失敗にこだわらなくても, それなりの生活を維持できるようでなくてはならない. われわれの住んでいるのは, 基本的に, 生産性第一の管理社会である. そこでは, 生産性を高めることが, 結局, みんなの幸福につながる, となんとなく仮定されてしまっている. そのために, 人々の行うべき活動が, 管理者によって定められ, 評価される. こうした社会が, 意味のある熟達の機会をひどくせばめてしまう. そうなると, 人々は, 直接に外的成功を求めて生きていくか, あるいは, せめて「安心感」を確保しようとするだろう. 有名大学に入って大企業に勤める, などという試みはまさしく後者に当たる. われわれの社会では, 安心感の追求も, 結局このように, 外的成功を求めるという形態を取る. 外的成功を求める一尾 t にとって, 職業とはそれ自体目的ではなく, 手段なのであるから, 最も効率よく所有・権力の欲求を満たしてくれる職業こそが好ましいと評価されるようになって来る. 知的興味などの内的動機付けと報酬を求める外的動機付けとは, 相いれない. 富や地位を手に入れれば, 一時的な効力感をもたらすが, 内的な充実感に裏打ちされない外的成功の効き目は, 長続きしない. だから, 成功によって効力感を持ち続けるには, たえずチャレンジし, 成功し続けなければならない. それも, 次第に大きな成功を目指さなければならない. 成功し続けている限り, そうした人々は効力感を持ち, 文字どおり企業体を, 時には社会や国家全体を「背負って立つ」意気込みで働くことであろう. 彼らこそまさに, エリートというにふさわしい. 成功し続けるのが無理だとわかった人々は, 外的成功にこだわればそれだけ意気阻喪しがちであろう. そこで, 外的成功が人生の目標として追及される社会では, 普通, ごく少数のエリートと, 多数の大衆がはっきり分離してくる. 前者は, 「勝者」たらんと意欲満々だが, 後者はそうした希望を失って無気力だ, という二分法的な図式が成立する.
   もっとも, それでは困る事態も生じる. そこで「それなりに」という発想が強調されることになる. 成功の主観的基準をある程度低く抑えて, 「ささやかな」蓄財や昇進に成功感を味わおう, というのである. 出世競争にも, 幾つもの水準が設けられ, その中での勝者がそれぞれ成功感を味わう. これによって, 出世競争がいわば大衆化されることになる. しかし, 中間や下級の水準での成功のもたらす「効力感」は, よけい一時的な, はかないものにとどまらざるをえない. 自分の生活を犠牲にし, 自分の管理下にある人々に我慢を強いてまで達成した「成功」がたいしたものでないとわかったとき, 彼らは, 無気力に陥るのは当然だ.

   こういう社会で, 熟達に内的な満足を持って生活しているのは, おそらく二つの異なったタイプがあると思う. つまり, 企業体に属さないで, 高度な知識や技術を発揮しうる「スペシャリスト」と, 「細々と」自営したり, 時として企業体に属し収入は得ながらも, そこに心からは帰属せず, 生活のほかの部分や趣味に, より大きな価値を見出す「局外者」である.

** 人間性の心理学    A.マズロー
   人間の衝動・動機・欲求は, それ自体は, 決して悪いものではなく, 中世的あるいは良いものである. 人間には, 生得的・本能的で, 基本的な欲求があり, 階層的に存在している. 基本的な諸欲求を適度に満たされれば, 人間は, 停滞することなくますます成長し, 心理的にいっそう健康になっていく.

#+BEGIN_QUOTE
            -------------
            |自己実現欲求|…自己達成, 生きがい
          -----------------
          |    尊敬欲求    |…尊敬, 承認, 顕示,
        ---------------------  支配, 名誉など
        |    所属・愛情欲求  |…所属, 愛情, 親和など
      -------------------------
      |      安全・安定欲求    |…恐怖, 危険, 健康
    -----------------------------  苦痛からの回避など
    |        生理的欲求          |…飢え, 渇き, 排泄,
  --------------------------------  睡眠, 性など
#+END_QUOTE

社会的に立身出世することとか, 経済的に金持ちになることが重要なのではなくて, 何よりも自己に対して, 「自己を楽しく実現しているかどうか」ということが, 自尊心を維持する欲求につながっているのだ. 自己実現を行わなかった人は, 深刻な生きがい喪失の状態に陥るであろう. 大きな目標に身を投じて, われを忘れてそれに打ち込むことによって, 知らないうちに自分のうちにある能力を最大限に発揮することが生きがいにつながってくる.

** 人はなぜ戦争をするのか?    アインシュタインとフロイトの往復書簡  花風社
*** アルバート・アインシュタイン
    [人間を戦争というくびきからときはなつことはできるのか? 」・・・これがわたしの選んだテーマです.

    すべての国家が一致協力して, 一つの機関をつくればよいのです. この期間に国家間の問題に対しての立法と司法の権限を与え, 国際的な紛争が生じたときには, この機関に解決を委ねるのです. 個々の国に対しては, この期間の定めた法を守るように義務付けるのです.
    ところが, 裁判というものは人間の創り上げたものです. 何かを決定しても, 実行力がなければ, 法以外のものから大きな影響を受けます. 法や権利と, 権力とは結びついてます! 司法機関には権力が必要です. 権力・・・高く掲げる理想に敬意を払うように強いる力・・・それがないと役に立ちません.
    国際的な平和を実現しようとすれば, 各国が主権の一部を完全に放棄し, 自らの活動に一定の枠をはめなければならない. しかし, 現実には, 望めないでしょう. 数世紀もの間, 多くの人々が平和への努力をしてきましたが, いまだ平和は訪れません.

    人間の心自体に問題があるのだ. 人間の心の中に, 平和への努力に抗う様々の力が働いているのだ. たとえば, 権力欲. 自分の利益の追求. なぜ少数の人たちがおびただしい数の国民を動かし, 自分たちの欲望の道具にすることができるのか? なぜ少数の人間の欲望に手を貸すような真似をするのか? それは, 少数の権力者が学校やマスコミ, そして宗教的な組織ですら手中に収め, その力を駆使することで抱いたすの国民の心を思うがままに操っている! しかし, それだけではありません.

    人間には本能的な欲望が潜んでいる. 憎悪にかられ, 相手を絶滅させようとする欲求が! 破壊への衝動が!
    人間の心を特定の方向に導き, 憎悪と破壊という心の病に犯されないようにすることはできるのか? これが最後の問いです.

*** ジークムンド・フロイト
    権力は「暴力」と言い換えられます. 人と人との間の利害の対立, これは基本的に暴力で解決されるものです. 動物はみんなそうして決着をつけます. 人間の場合, 意見や思想の対立もありますので, 暴力とは異なる新たな解決策が求められますがこれは文明が発達してからの話です.

    敵を徹底的に倒すには, 暴力を使い, 二度と立ち向かってこれないようにすればいい. しかし, 恐怖心を徹底的に植えつけ, 生かしておき, 何かの労働に使おう! 暴力で敵を殺さずに, 屈伏させるだけで満足するようになるのです. これが, 敵に情けをかけることの始まりです.
    はじめは, 力の強いものが支配権を握りました. むき出しの暴力, あるいは才知に裏打ちされた暴力が支配者を決めたのです. しかし, 誰でも知っているように, このあり方は, 社会が発展して行くにつれ, 暴力による支配から, 法 (権力) による支配へ変わっていったのです.

    しかし, どのように? それは, 多くの弱い人間が結集し, 法として, 一人の権力者の強力な力に対抗したのです. 法とは, 共同体の権力です. しかし, この力も, 暴力であることには変わりません. 一人の暴力から, 多数の暴力に変わったのです.

    暴力の支配から法の支配へ移るにあたっては, 多数の人間たちの意見の一致と強力が満たされ, 長く続かなければなりません. そのために, 幾つもの組織を創設し, 社会を有機的にしてゆく. 規則, つまり法律を作り, それを守らせる. 法にのっとった暴力を行使できる機関を定める・・・そうしなければならないのです. 個人の暴力が克服されるには, 多数の人間への権力の移行が必要ですし, そのためにはメンバー間の感情の絆, 一体感, これです.

    そこで, 個々人の自由・・・自分の持てる力を他人への暴力として用いることができる自由・・・をどの程度制限しなければならないのか, これを社会が法として定めれば, 問題は解決します. しかし, そもそものはじめから, バラバラな能力とバラバラな力を持った人間たちが住んでいます. こうなると, 法は, 支配者によって作り出され, 支配者の都合のよいものになってゆきます.

    すると, 社会には, 法を揺るがす二つの要素があります. 一つは, 支配者層の動き. 「法による支配」から「暴力による支配」へ歴史を押し戻そうとします. もうひとつは, 抑圧された人間がたえず繰り広げていく運動. 「不当な法」を「万民に平等な法」に変革しようとするのです. 第二の方向が現れるのは, 歴史の変革期です. このような場合, 暴力がすべてを決する状態へ逆戻りし, 再び新たな法秩序が生み出されます. (ちなみに, 社会メンバーたちの文化は, 暴力によって変わりません) このように, 法による社会が一度出来上がっても, 利害の対立が起きれば, 暴力が問題を解決するようになります.

    とはいえ, 人間が「永遠の平和」を達成するのに, 戦争は決して不適切な手段ではないだろう. 戦争は大きな単位の社会を生み出し, 強大な中央集権的な権力を作り上げることができるのです. 中央集権的な権力で暴力を管理させることができるのです. しかし, 現実には戦争は「永遠の平和」を実現させてはいません. それは, 征服によって勝ち得た状況は, 長続きしないからです. あなたの結論のように, 国際連盟を作ることこそ, 中央集権的な権力ですが, 国際連盟は権力の実行力を持ちません. しかし, これは人類史上かつてなかった実験であり, 権力をある種の理想に訴えることで手に入れようとしているのです!

    社会をまとめるためには, 暴力ともう一つ, 共同体の一体感 (そしてこの一体感を表現する理想や理念) が, 必要と述べましたが, はたして, そうした理念や理想では, 権力は現実には手に入りません. 今でも, 暴力が不可欠です.

    人間には二つの衝動がある. 一つは, 保持し統一しようとする衝動. エロス的衝動. 場合によっては性的衝動と呼んでもよい. もう一方の衝動は, 破壊し殺害しようとする衝動. 攻撃本能や破壊本能. タナトス的本能. 愛と憎しみ, 引力と斥力.
    気をつけなければいけないのが, こうした対立物の一方を「善」, 他方を「悪」と決めつけがちなことです. 二つの衝動が, お互いに促進しあったり, 対立しあったりすることから, 生命のさまざまな現象が生まれます. 愛するものを守るためには, 攻撃的な振る舞いが不可欠です.

    破壊への衝動はどのような生物の中にも働いており, 生命を崩壊させ, 生命のない状態へと引き戻そうとします. エロス的衝動が「生への衝動」だとすると, 破壊への衝動は「死への衝動」です. 死への衝動が外へ向けられると, 破壊への衝動になるのです. 内へ向かうと, 精神病的な症状が現れるのです. 攻撃性が外部世界に向けられるなら, 内面への破壊が緩和され, 生命体によい影響を与えます. すると, 戦争は生物学的に正当化してしまうことになるのです. 生物である以上, 仕方ないという結論に達するのです. 以上からの結論は, こうです.

    「人間から攻撃的な性質を取り除くなど, できそうもない! 」

    しかし, 問題は戦争とは別のはけ口を見つけてやればいいのです. それは, その反対の衝動, エロスを呼び覚ませばよいことになります. だから, 人と人との間の感情と心の絆を作り上げるものは, すべて戦争を阻むはずなのです.
    実は, この感情の絆には, 二種類あります. 一つは, 愛するものへの絆のようなものです. もう一つは, 帰属意識や一体感によって生み出されます. こうした結びつきこそ, 人間の社会を力強く支えるものなのです.

    人間は指導者と従属する人間に分かれます. 大事なのは, 優れた指導者です.
    どのような状況が理想でしょう. 当然, 人間が自分の衝動を余すことなく理性のコントロール化におく状況です. このような状況にたどり着けば, 感情の絆は消えるかもしれませんが, 人間の社会はいつまでも完全な一体化を見せるに違いありません. しかし, それはユートピアな幻想です. 現実の問題を解決しようとして, 理論家に相談しても, あまり多くの成果は返ってきません.

    私たち (平和主義者) はなぜ戦争に強い憤りを覚えるのか? 自然世界や生物学的には, 好ましいもののはずなのに・・・.

    なぜなら, どのような人間でも自分の生命を守る権利を持っているから.
    なぜなら, 戦争はひとりの人間の希望に満ちた人生を打ち砕くから.
    なぜなら, 戦争は人間の尊厳を失わせるから.
    なぜなら, 戦争は望んでもいない人の手を血で汚すから.
    なぜなら, 人間が苦労して築き上げてきた貴重なもの, 貴重な成果を台無しにするから.

    私たち平和主義者は, 体と心の奥底から戦争への憤りを覚えるからです. 心と体が反対せざるをえないのです.
    はるか昔から, 文化が人類の中に発達し広まってきました. 人間のうちにある最善のものは, すべて文化の発展があったからこそ, 身につけることのできたものなのです. 文化が発展していくと, 人類が消滅する危険性があります. 文化の発展のために, 人間の性的な機能がさまざまな形で損なわれてきているからです. 文化が発展していけば, 肉体的なレベルでの変化がひきおこされると思われるのです.
    それと同時に, 人間の心のあり方にも変化を起こします. ストレートな本能的な欲望に導かれることがすくなくなり, 本能的な欲望の度合いが弱まってきました. 私たちの祖先なら強く興奮を覚えたもの, 心地よかったもの, 今の時代の人間には興味を引かないもの, 耐え難いものになっています.

    このように, 私たちが追い求めるもの, たとえば道徳や美意識にまつわるもの, が変化してきたわけですが, この変化をひきおこしたものは, 心と身体の変化です. 文化は, 知性を強め, 情動をコントロールし始めます. また, 攻撃本能を内に向けます.

    文化の発展が人間に押し付けたこうした心のあり方・・・これほど, 戦争というものに対立するものはほかにありません. だからこそ, 私たちは戦争に怒りを覚えるのです. このようなあり方が戦争の残虐さそのものに劣らぬほど, 戦争への嫌悪感を生み出す原因となっている, と.

    文化の発展が生み出した心のあり方と, 将来の戦争がもたらすとてつもない惨禍への不安・・・この二つが近い将来戦争をなくす方向へ人間を動かしていくと期待できるのではないでしょうか?
    文化の発展を促せば, 戦争の終焉へ向けて歩みだすことができる!

** 脳が「生きがい」を感じるとき  グレゴリー・バーンズ
  脳の深いところには, 行動と報酬を結びつける構造がある. 満足感の鍵となるこの部分は, チャレンジと新しい経験によって成長する. 新しいことへの挑戦や初めてのことは, 避けて通りたいもののように思われがちだが, 実はそれらこそ満足感をもたらす要因なのだ.
  脳が, 満足感をつかさどる. 人間の動機は「快楽原理」 (快楽を求め苦痛を避ける) のではない. ドーパミンは, たしかに食べ物やセックスのような快感に反応して分泌されるが, 騒音 (歌劇「軍人たち」がいい例) や電気ショックなどの不快なものへの反応としても分泌される.
  ドーパミンは, 「新しさ」によって分泌される. 知的で好奇心旺盛で常に新しいものを探している人類を作ったのは, 新しさへの欲求なのだ.

  「あたれられた結果に満足を覚えている最中もその満足感は薄れてゆき, 次第に無関心になり, 新たな渇望が沸いてくる」. 快楽の踏み車は, 主観的な満足感を同じレベルに保つために, より高いレベルの報酬を求めさせる.

  SM の世界は, 体験そのものよりも, 期待がすべてなのだ. 期待している状態のほうが, 体験している状態よりもいい. 傷みの快感は不安から生じ, その不安は, 脳の新しさへの渇望に根ざしている. 結果を先送りすると不安が生まれる. 痛みをコントロールされることが快楽だ. コルチゾールとドーパミンの相乗効果が, 痛みによる満足感の鍵. コルチゾールはストレスから生じる. とくに, 肉体的ストレスから. ドーパミンは新しさから. よって, 肉体的なチャレンジが, もっとも満足感を得やすい.

  快楽の本質は飽きっぽいもの. 快楽は心地よいものだが, そのはかなさゆえ, 最後にはむなしくなってしまう.
  満足の追求と, 快楽の追求は別のものだ. 満足とは, 自らの行動に意味を見つけたいという行動だ. 意味とは, 喜びよりも, さらには幸福感よりも長く持続する.
  満足感を得るには, まず行動が求められる. それこそが, 快楽と幸福感との決定的な違いだ.

* V.E.フランクル
** 夜と霧      
   苦悩するもの, 病む者, 死につつある者, 使者----これらすべては数週の収容所生活の後には当たり前の眺めになってしまって, もはや人の心を動かすことができなくなるのである.

   われわれは夜寝る前に虱を取りながら裸のわが身を見るときなど, 皆大半同じことを考えるのであった. 一体この身体は私の身体だろうか, もうすでに死体ではなかろうか. 一体自分は何なのか? 人間の肉でしかない群集, 掘立小屋に押し込まれた群集, 毎日その一定のパーセントが死んで腐っていく群衆, の一部分なのだ.

   元来精神的に高い生活をしていた人間は, ある場合には, その比較的繊細な感情素質にもかかわらず, 収容所の生活のかくも困難な, 外的状況を苦痛ではあるにせよ彼らの精神生活にとってそれほど破壊的には体験しなかった. なぜなら彼らにとっては, 恐ろしい周囲の世界から精神の自由と内的な豊かさへと逃れる道が開かれていたからである. かくして, そしてかくしてのみ繊細な性質の人間がしばし頑丈な身体の人々よりも, 収容所生活をよりよく耐え得たというパラドックスが理解され得るのである.

   すると私の前には私の妻の面影が立ったのであった. 彼女の眼差しは, いまや昇りつつある太陽よりももっと私を照らすのであった. そのとき私のみを震わし私を貫いた考えは, 多くの思想家が叡智の極みとしてその生涯から生み出し, 多くの詩人がそれについて歌ったあの真理を, 生まれてはじめてつくづくと味わったということであった. すなわち愛は結局人間の実存が高く昇り得る最後のものであり, 最高のものであるという真理であった. 私はいまや, 人間の詩と思想とそして信仰とが表現すべき究極の極みであるものの意味を把握したのであった.

   ユーモアもまた自己維持のための戦いにおける心の武器である. ユーモアへの意志, すなわち事物を何らかの形で機智のある視点で見ようとすることは確かにトリックではあった. しかしまさに一種の生活術の意味におけるトリックが問題であったのである.

   収容所の囚人についての心理学的観察は, まず最初に精神的人間的に崩壊していった人間のみが, 収容所の世界の影響に陥ってしまうということを示している. またもはや内面的な拠り所を持たなくなった人間のみが崩壊せしめられたということを明らかにしている.

   強制収容所における内的な生活理想は, 人間的に崩壊してしまった人間にとっては過去への回顧的な存在様式になるのであった. 囚人の仮の存在様式に相応じている現実の完全な価値低下は, 囚人に自ら放棄して以下せしめるようにいざなうのである. なぜならばいずれにせよ「すべては目的がない」からである. かかる人々は, 著しく困難な外的状況こそ人間に内面的に自らを越えて成長する機会を与えるものだということを忘れているのでる. 囚人として過ごす時間の言語に絶する多くの艱難の下で, ある倫理的な高みに飛躍することなくして, かかる人間の生活は次第に埋もれていってしまうのであった. もちろんかかる高い飛翔は少数の人間にのみ可能であった. しかし彼らはその外面的な挫折や, また死においてさえも, 以前の日常生活でおそらく決して到達したことのないであろう人間的偉大に達することができたのである.

   未来を失うとともに彼はその拠り所を失い, 内的に崩壊し身体的にも心理的にも転落したのであった. 強制収容所における人間を内的に緊張せしめようとするには, まず未来のある目的に向かって緊張せしめることを前提とするのである. ニーチェの「何故生きるかを知っているものは, ほとんどあらゆる如何に生きるか, に耐えるのだ」が, このことをよくあらわしている. すなわち囚人が現在の生活の恐ろしい「如何に」 (状態) に, つまり収容所生活のすさまじさに, 内的に抵抗に身を維持するためには何らかの機会がある限り囚人にその生きるための「何故」をすなわち生活目的を意識せしめねばならないのである.

   ここで必要なのは生命の意味についての問いの観点変更なのである. すなわち人生から何をわれわれは期待できるかが問題なのではなくて, むしろ人生が何をわれわれから期待しているかが問題なのである. 人生というのは結局, 人生の意味の問題に正しく答えること, 人生が各人に課する使命を果たすこと, 日々の務めを行うことに対する責任を担うことに他ならないのである.

** 苦悩する人間  ヴィクトール・ E ・フランクル  春秋社
   実存分析ないしロゴセラピーにとって本質的に重要なことはただひとつ, 人間は (実存的な意味において) 何を「なすべき」かということだけであります. ニヒリズム的な意味の否定の代わりに, 意味解明の試みがなされなければなりません. (そのつど存在する) 意味を見出さなければなりません.

   さて, 私たちは意味をいかにして見出すのでしょうか. これに対して, 私たちは「人生の意味は人生そのもののうちにある」という現存在の答えから出発することにしましょう. 現存在の意味は, ただそのつどの人格に即して, またそのつどの状況に即してのみ妥当するのです. それゆえ, 人生の意味へのといはただ具体的にのみたてられうるのであり, 答えもただ活動的にのみ与えられうるのです. 「人生問題」に答えるとは, 答えを「行う」ことなのです.

   意味への問いは「このものに即して」立てられなければなりません. よって, もし意味への問いかけが全体 (個別を超えたもの) に向けられるならば, その問いは無意味なものになります. というのも, 全体の意味は私たちの把握能力を必然的に超えているからです. したがって, 全体の意味は, 「超意味」といえるだけです.

   超意味については考えることが不可能なものでありますが, また考える必要がないものでもあります. すべてが意味を持ち, いたる所に超意味があるなら, それは私にわかるはずもありません. だから, こういえるかもしれません. 超意味を信じることこそ意味がある, と. 超意味は, 「結果において」はじめて, またそのときにのみ与えられるのです. いつもただ, 行為を通してのみ, あとから感じ取ることができるだけなのです.

   苦悩によって, 現在生の悲劇的構造を垣間見ます. 人間存在が最終的には受苦であること, 人間の本質は苦悩する人間, 苦悩人であるということです. 苦悩する人間はまさに真理のすぐ近くにいるのであり, たやすく真理に気づくのです. 苦悩への敢然さ, 勇気, これこそが重要なのです. 苦悩を引き受けること, 運命を肯定すること, 運命に対して態度をとることが大切なのです. この道を歩んでこそ, 私たちは真理に近づくのです.
   苦悩が意味で満たされるためには, 何のため, 誰のために苦悩するときだけなのです. つまり, 苦悩は自己目的であってはならないのです. 自己目的に陥った瞬間, 苦悩はマゾヒズムに転化します.

   人間が本当に欲しているのは意味深く生きることです. 決定的な基準となるものは, 実存の持続時間ではなく, 実存の意味充実なのです. 短い人生でも有意味でありえますし, 長い人生でも無意味なままでありうるからです.

** それでも人生にイエスと言う    V.E. フランクル    春秋社
   生きる意味がないということは, 時代が宣伝したことなのです. 原子爆弾の発明は, 世界規模の破局の恐怖をはぐくんでいますし, 一種の世界滅亡の気分が, 二十世紀の終わりを占領しています. 世紀末の雰囲気だけが敗北主義的だったのではありません. こうした世界滅亡の気分はすべて, その根底に宿命論があります.

   しかし, そのような宿命論は克服しなければなりません. しかしこの場合, 私たちはもはや, 安易な楽観主義に立って, 最近の時代に出てきた問題を簡単に無視することができません. わたしたちは, 悲観主義的になったのです. わたしたちは, もはや進歩そのものを信じていません. いぜん, 活動主義は, 楽観主義と結びついていましたが, こんにち, 活動主義の前提になっているのは悲観主義なのです.

   私たちは, 悲観主義にもとづいてしか, 行動を起こすことができません. 懐疑的な態度をとってはじめて, なおなにかしようと手を伸ばすことができるのです. こうした懐疑にも振り動かされないためには, 生きる意味があるという信念がびくともしないものでなければならないでしょう. このような懐疑と悲観主義をも引き受けて担うには, 私たちは, 人間として生きている意味と価値を, 絶対的に信じていなければならないでしょう. しかし, そのためには, やはり理想主義や熱情に訴えるしかないのに, 現代は, あらゆる熱情が乱用されたあげく, ありとあらゆる理想主義が打ち砕かれた時代なのです.

   この結果, すべての主義が, まったく信用を失いました. したがって, 現代の哲学が, 世界を, 無から成り立っているかのように考えているのも, 不思議ではありません. しかしながら, 私たちは, このようなニヒリズムを通り抜け, 悲観主義と懐疑主義を通り抜け, 新しい人間性に, 今こそ到達しなければなりません. 最近の否定的なプロバガンダ, 「生きる意味がない」と唱えるプロパガンダに反対して, 別のプロパガンダを開始しなければなりません. このプロパガンダはそのつどそのつど, 第一に個人的なものでなければなりません. 第二に活動的でなければなりません. そうであってこそ, このプロパガンダは, 現実的であることができるのです.

   よく言われることですが, 人間は楽しみのために生きているのではありません. 生きるということは, ある意味で義務であり, たった一つの重大な責務なのです. 幸せは目標ではなく, 結果にすぎないのです. なぜなら, 幸せとは思いがけず手に入るものにすぎず, 決して追い求められないものであり, 幸せを得ようとすれば, いつも失敗することになるのです.

   私たちが「生きる意味があるか」と問うのは, はじめから誤っているのです. つまり, 私たちは, 生きる意味を問うてはならないのです. 人生こそが問いを出し私たちに問いを提起しているからです. 私たちは問われている存在なのです. 私たちは, 人生が絶えずそのときそのときに出す問い, 「人生の問い」に答えなければならない, 答えを出さなければならない存在なのです. 生きること自体, 問われていることにほかなりません. 私たちが生きていくことは答えることにほかなりません. そしてそれは, 生きていることに責任を担うことです.
   こう考えるとまた, どのような未来も怖くはありません. もう, 現在がすべてであり, その現在は, 人生が私たちに出すいつまでも新しい問いを含んでいるからです. どんな未来が私たちを待ち受けているかは, 知るよしもありませんし, また知る必要もないのです.

   私たちは, 人生の問いに答えることによって, その瞬間を実現することができます. ところで, 人生が出す問いは, 瞬間瞬間, その人その人によって, まったく違っています. ですから, 生きる意味の問題は, まったく具体的なここと今において問われるものでなければなりません.

   人生はたえず, 意味を実現するなんらかの可能性を提供しています. ですから, どんなときでも, 生きる意味があるかどうかは, その人の自由選択にゆだねられています. つまり, 瞬間を意味のあるものにするかしないかの二社選択しかないということです.

   私たちは, いつかは死ぬ存在です. 私たちの人生は有限です. このことによって, なにかをやってみようと思ったり, , 時間を充実させたりする意味があると思われるのです. 死とは, そういったことをするように強いるものなのです. そう考えると, どれだけ長生きするかということは, 本質的にはまったくどうでもいいことだということがはっきりするでしょう. 長生きしたからといって, 人生はそれだけでは必ずしも意味のあるものにはならないのです. また, 短い生涯に終わっても, ずっと意味のある人生だったかもしれません.
   以上のことからわかることは, 苦難と死こそが人生を意味のあるものにするということです.

   大きくいって二つの考え方の可能性があると思います. どちらの可能性も反駁できないし, 証明もできません. つまり, すべては結局まったく無意味だとも十分主張できます. 同じように, すべてに大きな意味があるばかりか, そのような全体の意味, そのような意味の全体がもはやとらえきれないほど, 「世界は超意味を持つ」 (世界は意味を超えている) としか言えないほどの意味があるのだとも主張できるでしょう. そう, 世界はまったく無意味だというのも, 世界のすべてが有意味だというのも, 同じく正当な主張です. まったくの無意味か, すべてが有意味かという決断は, 論理的に考えると, 根拠がない決断です. 言い換えると, 根拠が何もないということが, 決断の根拠になるのです. 人間は, もう論理的な法則からこの決断を下すことができません. ただ自分自身の深みから, その決断を下すことができるのです. どちらを選ぶかを決断することができるのです.

   ただひとつのことははっきりしています. 究極の意味, 存在の超意味を信じようと決断すると, その創造的な結果が現れてくるでしょう. 信じるというのは, ただ, 「それが」真実だと信じるのではありません. それ以上です. 信じることを, 真実のこととするのです. というわけで, , 一方の考え方の可能性を手に入れるということは, 単にひとつの考え方の可能性を選ぶことではないのです. たんに考え方の可能性にすぎないものを実現することなのです.

** 意味への意思    V.E.フランクル    春秋社
   人間は, 動物とは異なって, なにをなさねばならないかを本能から告げられることはないし, また現代の人間はもはや, なにをなすべきかを伝統から告げられることもない. その上, 人間はもはや, 自分が何を本当に意志しているのかを知らないように思われることもしばしばである. それだけに人間はいっそう, 他人がなすことだけに意志しようとするか, あるいは他人が意志することだけをなそうとするか, のいずれかになる. 前者は画一主義にいたり, 後者は全体主義に至る.

   自己実現を目標にすえるものは, 次のことを見落とし忘却しているのです. つまり, 人間は結局のところ意味を満たす (自己自身のうちにおいてではなく, 自己の外, 世界において意味を満たす) その程度に応じてのみ自己を実現することができるということです. 言い換えれば, 自己実現は目標として設定されるものではなく, 私が人間的実存の自己超克 (自己自身を超えて, 自己自身ではないなにか, すなわち満たされるべき意味や自己がである人間存在に自己を差し向けるという根本的事実) と呼ぶところのものの副次的結果として生じるものなのです.

   人生において重要なのは, 意味を与えることではなく, 意味を見出すことなのです. 意味を探し求める際に, 人間を導くのが良心です. われわれは無意味感の蔓延する時代に生きています. われわれの周りには, 性的な刺激だけではなく, さまざまな刺激があふれています. 人間がこのマスメディアによる刺激の氾濫に打ち勝とうとするならば, なにが重要でなにがそうでないか, なにが本質的でなにがそうでないか, 一言で言えば, なにに意味がありなにに意味がないのか, ということです. こんなわれわれの時代には, 教育は, 単に知識を伝えることだけでなく, 良心を洗練することをも心がけなければなりません. その結果, 人間は, 状況の一つ一つに内在している命令を聞き取ることができるほどに耳ざとくなるのです. そのときには, まさにこの彼の人生は新たに意味に満ちたものに思われるようになり, またそればかりか, 画一主義や全体主義に対する免疫性も彼自身に与えられることになるでしょう.

   われわれは他者の人生に意味を与えることはできません. というのは, 人間の苦悩, 人間の人生の究極的意味への問いに対しては, もはや知的な答えはありえず, ただ実存的な答えしかありえないからです.

   人間であるということは, 自分自身ではない何かに向かって方向付けられ, 秩序付けられているということです. 人間の現存在がもはや自分自身を越えて外へとさしむかうことがなくなるならば, そのとたんに生きながらえることは無意味になる, いやそれどころか, 不可能にさえなります.

** 「人生に意味はあるか」  諸富祥彦  講談社現代新書
  人生の意味は, 自分で求めていくよりほかない. 自分ではじめて, "発見"した答えでないと, 納得できない.
  "答え"が見つからなければ, もう生きていけない, 死んでしまうかもしれない. そんなところまで, 自分自身を追い込んで, "本気で"求め続ける. それしか道はないのです.
  「人生の意味は」は, 「知るもの」ではなく, 機が熟したときに「目覚めるもの」なのです. その真理と初めて出会うとき, それは「言語を絶した体験」としてやってくるのです.
  求めぬく, 悩みぬく. このことによって, その人の心身のあり方に, 根本的で, かつ, 持続的な「変容」が生じてきます. そしてついに, 自我が破れて, 「真理の目覚めの体験」が訪れるのです.

  その真理とは, 「いのちのはたらき」. まず「はたらき」そのものがあり, あるときは花, あるときは鳥, というように次々と異なる形を取っていくけれど, すべてはこの世界の一切が等しくそれであり, すべては「ひとつ」なのです. そして, この私も, 他ならない「はたらき」のひとつの形であるという真理に目覚めて生きるのです.

はたらきには, 使命が与えられています. 私たちは, その使命を果たし, 人生の意味の物語という, 「未完のシナリオ」を完成させなければなりません. (06/6/12) 

** フランクル心理学入門    諸富祥彦   コスモス・ライブラリー
   フランクル心理学の要点は, 一言で言えば, 次のメッセージにあります.
   どんなときも人生には意味がある.
   なすべきこと, 充たすべき意味が与えられている.

   それはこういう意味です. 「わたしたち一人ひとりには, 「なすべきこと」「充たすべき意味」が与えられている. そしてそれとともに, 今・ここに定め置かれている. そしてその「何か」は, わたしたちによって発見され実現されるのを「待っている」. わたしたちは, 常にこの「何か」によって必要とされ, それを発見し実現するのを待たれている, そういう存在なのだ」. 生きている限り, そのつど送り与えられてくるこの「なすべきこと」「実現すべき意味」に耳を傾けて, ただ淡々にそれに取り組み続けていくならば, そのときわたしたちは, いつの間にか, 自分の「いのち」が輝き始めていることに気づくことができます.
   まず「私」を立て, 「私の幸せこそが一番大事」と考える「幸福主義」 (エゴイズム). そして, それと裏腹の関係にある「心のむなしさ」 (ニヒリズム) フランクル心理学はこれを超える原理となりうるのです.

   「自分の存在が何の意味も持っていないという感情」「底なしの意味喪失感」. それをフランクルは「実存的空虚」と呼びます. 仕事だ勉強だと多忙な毎日を送る. たえず刺激と快楽を追い求める. 現代人の抗した多忙の背後に, フランクルは, 自らの内的空虚さから逃れようとする隠れた動機を見て取るわけです. 強い刺激を求めるあまり, 暴力や援助交際, はては怪しいカルト宗教に若者たちは引き寄せられていくのです. 国家的な目標喪失状態, 国家的な実存的空虚に陥っている現代の日本は, 自らを包むその虚無を覆い隠すかのように, 「快楽」と「権力」と「金銭」を盲目的に追い求め続けていきます. 自らの内的空虚を見つめずに済ませるための「感覚麻痺」の文化が蔓延しているのです.

   幸福, 快楽, 自己実現, 健康, 至高体験・・・こういったものを追い求めても, それは必ず失敗に終わるとフランクルはいいます. そういった欲望は尽きるところを知らないからです. じゃあどうすればいいか. どうすることもできない. ただ, 幸福に対するこだわりを捨て, なすべきことに取り組むがいい. そうしているうちに然るべきときがくれば, おのずと幸福は手に入るはずだ, というのがフランクルの考えです. 「幸福は目標ではなく結果である」人の心が本当に満たされるのは, 自分や自分の幸福のことを忘れ去り, 自分のなすべきこと, 自分にとって意味あることに無心で取り組んでいるときであるということ, これは「幸福のパラドックス」として, 古くから知られていることです.

   「意味への意思」は, フランクルが人間の根本動機とみなしたものです. 人間は, 人として生まれついたはじめからその生命の終わりにいたるまで, 「意味と目的を発見し, 実現せんとする基本的努力」をたえずくれ返していくものだ, とフランクルは言うのです. 権力や快楽を求めるのも, 自分は意味ある人生を送っていると思いたくても思えないから, そのような虚しさの感覚から逃げ出したいからなのだ.

   人間は人生の意味を求めてはいけない. 人間は人生から意味を問いかけられている存在なのだ. 人生にはどんなときであれ, 「なすべきこと」「実現すべき意味」がなくなることは決してない. その人のことを「必要としている誰か」, その人によって「実現されるべき何か」が必ずあって, その人によって発見されるのを「待っている」. これはいかなる人にも当てはまる人生の真実であるのだ.

   自分の実現すべき意味を探す指標として, フランクルは「三つの価値の領域」を提示する.

   - 創造価値
   何かを行うことによって, つまり活動し創造することによって実現される価値のこと. 具体的には, その人になされるのを待っている仕事, その人に創造されるのを待っている芸術作品.
   - 体験価値
   何かを体験することによって, つまり自然の体験や芸術の体験, 誰かを愛する体験によって実現される価値のことです. 真善美の体験や人との出会いによって, 世界から何かを受け取ることによって実現される価値であるとも言えます.
   - 態度価値
   自分自身ではどうしようもない状況, 変えることのできない運命に直面したとき, その窮状に対してある態度をとることによって実現される価値のことです.

   「すべては意味を持つ」と「すべては無意味である」という二つの考えを比べてみる. 論理的に考えれば, この二つの考えは, 等しく正当な権利を持っている. しかし, この二つの可能性のいずれかを選ぶ決断は, 論理的に考えると根拠がない決断であり, 根拠がないということが決断の根拠となるような決断である. (?) 人間はただ, その存在の深みからその決断を下すことができる. どちらを選ぶか決断することができるのだ. それは言い換えれば, 「信仰」である. 私たちはただ, すべては意味に満ちている, 超意味を持っている, と信じることができるだけである. しかし, それがどんな意味を持つのか, どのような意味ですべては超意味に満ちているのか. ・・・これらのことは一切, 私たちに知ることはできない. 究極の意味, 超意味は, もはや思考の問題ではなく, 信仰の問題である. 私たちはそれを知的な基盤でとらえるのではなく, 実存的な基盤で, 私たちの全存在から, すなわち信仰を通してとらえるのである.

** <むなしさ>の心理学    諸富祥彦  講談社現代新書
#+begin_src text
とくに何かが足りないわけではない.
とびぬけて幸せだとは思わないけれど, とくに不幸せだとも感じない.
人並みには, 幸せな人生をおくれそうな気がしている.
けれどその一方で, 「何か」が足りない.
どこかむなしい. つまらない.
心のそこから満たされる「何か」が足りない, と時折ふと感じてしまう.
それなりには楽しいし, 充実もしている.
けれど, やはりそれなりにはつまらない.
そんな人生が, ただどこまでもくりかえされていく.
昨日も今日も明日も・・・.
それがずっと続いていって, わたしの一度きりの人生は終わってしまうのだろうか.
そんな風に考えると, 「これでいいのか」「人生ってこんなものなのか」と, ぼんやり不安を感じることがある.
あるべき「何か」がかけている気がする.
けれど, それがなんなのかよくわからない・・・.
#+end_src

このような, 理由なき無気力や疲労感を訴える人が増えている. 自分で解決するしかないのはそうなのだが, 彼女の苦しみは, あれやこれやの「生きがい」を見つけることで解決するような類のものではない. 学生は疲れている. しかし, 何か意味のある仕事を終えたときのあの心地よい疲れではない. 自分のエネルギーをもてあましてどこにふりむけばいいのかわからない. 見えない何かに自分を押さえ込まれたまま, ただいたずらに時間ばかりが過ぎていく. そんな毎日を繰り返す中でエネルギーを奪い取られていく. そんなふうにして蓄積された慢性的な疲労感・倦怠感である.

  社会との接触感のなさ, 自分はこの社会で必要とされているという意識の低さがその一因である.
  かれは日本でも有数の一流大学の出身なのだが, 三十代前半の同級生が集まると, 人がうらやむほどの大企業に勤めている彼ら全員, 口をそろえて「できれば会社を辞めたい」と言うというのだ. 「企業としても, 個人としても, 夢や希望を抱くことができなくなっている. すっかり, くたびれ果てているんです」. 多くの会社員が, ますます自分の仕事に意味や希望を見出せなくなっている. そして十年近い勤務の中で, 自分が会社にとって「歯車」でしかない現実を見せつけられる. 無力感に打ちのめされ, どうしようもない「むなしさ」を感じて辞職に踏み切る. そんな二十代後半から三十代前半の人間が増えているようだ.

  「こんなに豊かなのに, なにをいまさら耐えたりがんばったりする必要があるの. これ以上, なにを手に入れる必要があるっていうの. もういいじゃない. だったらもっと楽に生きていこうよ」. つまり若者たちの目に映っている世の中は, どこを探しても「ありふれた可能性」しか見出せない, そんな「まっ平な世の中」である. そして, どこまでいってもただ「ありふれた可能性」しか手に入らないのであれば, 「無理してがんばっても疲れるだけ出し, そこそこやっておくのが一番」ということになってしまう. ふわふわまったりの「脱力文化」とは, どこを探しても「輝ける未来」も「目指すべき目標」も見当たらない, そんな「まっ平らな世の中」で違和感を持たずに生きるために, 若者たちが生み出した「適応の知恵」なのである. 早々と人生を見切り, あきらめの早い若者たち. そんな彼らにも, たった一つだけ, どうしても大切にしなくてはならないものがある. 「友達」の存在である. 若者たちはもはや, 「恥」の意識を喪失している. そんな若者たちに唯一残された「規範」が, 「仲間」や「友達」との関係である. 携帯電話とは, 「輝ける未来」をたたれた「果てしない日常」の中で, 友達との「ささやかな幸せ」を教授するのを可能にしてくれる大切な小道具なのである.

  人間の本性には, 何かと確実につながりたいという衝動が潜んでいる. 増してや若者の衝動は激しい. その衝動を振り向ける何かを求めずにいられない. しかし今の世の中では, そのターゲットが見つからない. だからエネルギーが内向する. 若者たちは「とくに楽しいわけではないけれど」ただ仲間とたむろする心地よさに浸っているのだ. 「終わらない日常」とは, 男が男らしくあるために必要な何かを「剥奪された」世の中である.

  オウムにひかれた若者の心情は, 「管理社会に埋没するのがいやで, 自己実現の場を求めて」, 「心の空白を生める人間としての『生きがい』を求めて」である. オウムにはよく理系のエリートが多いといわれる. 彼らはおそらくその過程のどこかで大きな挫折感を味わっている. 中学, 高校, 大学と秀才街道を走ってきた彼らも, 修士課程を終え学会発表をするころになると, 自分の無力さを痛感させられる. 自分が他の誰かでもこなすことのできる研究を担当する「歯車」にすぎないことを実感させられるのだ. 「自分はなすべきことがある」という使命感は, 私たちの生きる意欲を強く掻き立ててくれる. だからそれを剥ぎ取られたものはつらい. ある脱会信者は, 教団の教えが偽りとわかった今でも, 強い空虚感に苛まれ苦しんでいるという. たとえ幻想でもいい, 自分を満たしてくれる何かがほしい. 生きる目的が, 使命がほしいと訴えている.

  ある欲望を満たしたと思ったとたん, 必ずすぐに次の欲望が生まれてくる. もっともっと, 必ず何かがほしくなる. だから, いったん自分の「幸福」を求め始めた人間は, どこまでいっても心のそこから満たされることはない. 「何かが足りない」「どこか満たされない」という欠乏感をどこかで感じてしまう. このように, 人間の欲望はそれ自体, 際限のないものである. 欲望の際限のなさは第一に, 人間の欲望それ自体の持つ本質的な性質である. それに加えて現代社会とは, 「必要を離陸した欲望」の無限空間を開くことによって, 市場を自己創出する力を獲得した社会なのである. あふれんばかりの情報によって次々と作り出されていくわたしたちの欲望は, まさに「必要を離陸して」しまっており, だから際限はない.

#+BEGIN_QUOTE
    <実感>
    自分の内面に巣くう「むなしさ」を見つめる. 「どこかむなしい」「なにか足りない」といった心のつぶやきと, そのメッセージとに耳を傾ける.
    <懐疑>
    自分が「当たり前」と信じており, その生き方の前提となっている諸諸の考えを, それは本当に「当たり前」か, その根拠はどこにあるのかと疑っていく.
    <離脱>
    周囲の人々や世間との内的なつながりを断ち切る. 自分がそれまで, それに慣れ親しみ, そこに内属し, その内部で生きてきた生活世界からの離脱をはかる.
    <探求>
    自分の新たな生き方, これが<本当の生き方>だと思える生き方を, 自分自身, 真に納得の感覚が得られるまで, どこまでも問い求めていく.
    <限界>
    しかし, <本当の生き方>はどれほど求めても求まらない. そのため自ずと, 如何ともしがたい窮地に追い込まれていく.
    <覚醒>
    しかしその極限で, ついに力尽き倒れたとき, 不意に人間存在の真実を, いわば「向こうから」つげ知らされる. 自己本位のあり方に目ざまされるのである.
    <自覚>
    こうして目覚めた自己本位のあり方と, その意味と構造とを, 言葉ではっきりとつかみ出す. 明らかな自覚と了解へともたらす.
    <反復>
    その本来的あり方をすこしでもわが身に定着させるには, 日常生活の中でそれを何度でも反復しつづけなくてはならない.
#+END_QUOTE


この哲学的自己探求のプロセスにおいて, 最も重要なのは, とりわけ次の三つの原則を貫徹することだ.
第一の原則は「懐疑」の徹底である. 自分の今の行き方と, その前提になっている諸諸の考えとをどこまでも疑っていく. それと同時に, それまでの生活様式から離脱しなければならない. これが第二の原則だ. 自己変革を真剣に望む人は, 日常の生の流れを停止させ, 自己と世界とのつながりを断ち切って, 通常の生の軌道からいったん完全に下りてしまわなくてはならない. するとそこに, 世界で共有されている時間の流れから隔絶された, 内的な<真空地帯>が作り出される. そこで自分の新たな生き方, これが<本当の生き方>だと思える生き方を, 真に納得の感覚が得られるままでどこまでも問い求めていくこと. これが第三の原則である. しかもそこで定めた新たな生き方は, 毎日の生活の中で一つ一つの行為の中で, 実地に検証されなくてはならない.

文学でも芸術でもいい. 音楽でもスポーツでもいい. 要は, 自分が本当に求めているなにかを「どこまでも徹底的に求め抜いていく」こと. 妥協のない<求め>の徹底が, 真の自己への目覚めの道なのである. なぜか? それは, どこまでも求め抜いていく過程で, その人のエゴ, 自分や自分の人生を思い図るエゴの力が次第に弱まっていく. そしてついにそれが消えうせたとき, そこに真の自己が自ずと現れ働き始めるのだ. 「自分ではないなにか」が働き始めるのだ. わたしは断言していいが, たとえいっさいを失ってもかまわない, そんな覚悟をしてなにかを求める人だけにわかるある境地が確実に存在する. おそらく, この境地が, そしてその境地にいる自分への気づきが, 「無我」とか「真の自己の目覚め」とよばれるものなのだ. 学問でも芸術でも趣味でもいい. 「自分」が溶けてなくなるまでなにかを真剣に求め続けた人にとって, この境地はいつでもそこにあるものである.
