#+OPTIONS: toc:nil
* Embeded System
組み込みシステム.

特定の機能を実現するために機械や機器に組み込まれるコンピュータシステム.

- [[http://ja.wikipedia.org/wiki/%E7%B5%84%E3%81%BF%E8%BE%BC%E3%81%BF%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0][組み込みシステム - Wikipedia]]

組み込みシステムの主な構成要素は以下.

- Embedded Systems
  - MicroCotroller
    - Memory
      - RAM
      - ROM
    - Processor (CPU)
    - I/O Ports
    - DAC
    - Bas
    - Timer
  - External Circuits
  - Physical Device
    - Sensor
    - ADC

以下のような特徴をもつ.

- A microcontroller hidden inside
- A dedicated purpose
- Run in real time
- Input/output is important
- High volume, low cost
- Extremely reliable
- Low power
- Small size and weight

* MicroController
  マイクロコントローラー. いわゆる, マイコン.
  - [[http://ja.wikipedia.org/wiki/%E3%83%9E%E3%82%A4%E3%82%AF%E3%83%AD%E3%82%B3%E3%83%B3%E3%83%94%E3%83%A5%E3%83%BC%E3%82%BF][マイクロコンピュータ - Wikipedia]]

  Microcontrollers, which are microcomputers incorporating the processor, 
  RAM, ROM and I/O ports into a single package, 
  are often employed in an embedded system because of their low cost, 
  small size, and low power requirements.

** I/O Port
   Input Port/Output Port の略.
   Input Port は 外部の世界 (外部の集積回路, sensor, etc)
   からの情報をコンピュータのなかに入れる. Output Port はその逆.

   A port is a physical connection between the computer and its outside world.

*** device driver
    a set of software functions that facilitate the use of an I/O port.

*** GPIO
    GPIO は General Purpose Input/Output (汎用入出力) の略語.

    [[http://ja.wikipedia.org/wiki/GPIO][GPIO - Wikipedia]]

    LSI チップや電子機器の備える入出力端子の一種で,
    設定次第で様々な用途に利用できるもの.

    ソフトウェアの指示によって任意の入力あるいは出力に利用することができる.
    複数の端子が GPIO に割り当てられている場合には,
    これを一つのグループとして一括して制御することができ「GPIO ポート」などと呼ばれる

    [[http://e-words.jp/w/GPIO.html][GPIO とは 【 General Purpose Input/Output 】 - 意味/ 解説/ 説明/ 定義 : IT 用語辞典]]

    Pin は GPIO の構成要素. たとえば, GPIO PortA は, PA0-PA7 の 8 つの Pin からできている.

    Pins can be configured for digital I/O, 
    analog input, timer I/O, or serial I/O. 
    For example PA0 can be digital I/O or serial input.

    Pin のそれぞれが外部デバイスに接続される.
    用途は, レジスタの設定によって自由にできる.

    - PA1 ... LED への Output 用
    - PA2 ... Switch からの Input 用
    - PA3 ... UART の Input 用
    - PA4 ... UART の Output 用

*** I/O Address
    I/O ポートアドレスとは周辺機器 (デバイス) と
    CPU がデータをやり取りする際に使用する 16 ビットのアドレス.

    Linux では, 以下で確認.

#+begin_src language
ls /proc/ioports
#+end_src

** Register
   コンピュータのプロセッサなどが内蔵する記憶回路で,
   制御装置や演算装置や実行ユニットに直結した,
   操作に要する速度が最速の, 比較的少量のものを指す.

   一般に, 論理回路において, フリップフロップなどにより状態を保持する装置をレジスタと呼ぶ.
   コンピュータにおいては, プロセッサが内蔵しているそれを指す.
   プロセッサには, プログラムが読み書きできるレジスタ以外に,
   プロセッサ自身が動作するためのレジスタがあり, 内部レジスタなどと呼ばれる.

   [[http://ja.wikipedia.org/wiki/%E3%83%AC%E3%82%B8%E3%82%B9%E3%82%BF_(%E3%82%B3%E3%83%B3%E3%83%94%E3%83%A5%E3%83%BC%E3%82%BF)][レジスタ (コンピュータ) - Wikipedia]]

   Registers are high-speed storage inside the processor.

   データを記憶したり取り出したりすることができる順序回路.
   out (t) = out (t-1) を実現する.

*** Register のプログラムでの扱い
    Pin を操作するためのレジスタには,
    アドレス空間の決められたアドレスが割り振られている. (仕様)

    プログラムでは, あらかじめ Define を利用してレジスタのアドレスを宣言するのが王道.
    volatile をつけることで, コンパイラが最適化してアドレスを変更するのを防ぐ.

    #+begin_src c
#define PA5   (*((volatile unsigned long *) 0x40004080))
    #+end_src

    これは以下と同値.

    #+begin_src c
data = (*((volatile unsigned long *) 0x40004080));
data = 0x40004080;
data = (*0x40004080);
    #+end_src

    そうすると, 以下のようにして Register の値を Read/Write できる.

    #+begin_src c
# Register Write
PA5 = 0x20;
# Register Read
data = PA5;
    #+end_src

    初期設定はこんな感じ.

    #+begin_src c
void PortF_Init (void){ volatile unsigned long delay;
  SYSCTL_RCGC2_R |= 0x00000020;   // 1) F clock
  delay = SYSCTL_RCGC2_R;         // delay  
  GPIO_PORTF_LOCK_R = 0x4C4F434B; // 2) unlock PortF PF0 
  GPIO_PORTF_CR_R |= 0x1F;        // allow changes to PF4-0      
  GPIO_PORTF_AMSEL_R &= 0x00;     // 3) disable analog function
  GPIO_PORTF_PCTL_R &= 0x00000000; // 4) GPIO clear bit PCTL 
  GPIO_PORTF_DIR_R &= ~0x11;      // 5.1) PF4,PF0 input,
  GPIO_PORTF_DIR_R |= 0x08;       // 5.2) PF3 output 
  GPIO_PORTF_AFSEL_R &= 0x00;     // 6) no alternate function
  GPIO_PORTF_PUR_R |= 0x11;       // enable pullup resistors on PF4,PF0      
  GPIO_PORTF_DEN_R |= 0x1F;       // 7) enable digital pins PF4-PF0       
}
    #+end_src

*** L チカ Example 抜粋

#+begin_src c
// symbolic names instead of addresses
#define GPIO_PORTF_DATA_R    (*((volatile unsigned long *) 0x400253FC))
#define GPIO_PORTF_DIR_R     (*((volatile unsigned long *) 0x40025400))
#define GPIO_PORTF_AFSEL_R   (*((volatile unsigned long *) 0x40025420))
#define GPIO_PORTF_PUR_R     (*((volatile unsigned long *) 0x40025510))
#define GPIO_PORTF_DEN_R     (*((volatile unsigned long *) 0x4002551C))
#define GPIO_PORTF_LOCK_R    (*((volatile unsigned long *) 0x40025520))
#define GPIO_PORTF_CR_R      (*((volatile unsigned long *) 0x40025524))
#define GPIO_PORTF_AMSEL_R   (*((volatile unsigned long *) 0x40025528))
#define GPIO_PORTF_PCTL_R    (*((volatile unsigned long *) 0x4002552C))
#define SYSCTL_RCGC2_R       (*((volatile unsigned long *) 0x400FE108))

// 2. Declarations Section
//   Global Variablesp
unsigned long SW1; // input from PF4
unsigned long SW2; // input from PF0

// Subroutine to initialize port F pins for input and output
// PF4 is input SW1 and PF2 is output Blue LED
void PortF_Init (void){ volatile unsigned long delay;
  SYSCTL_RCGC2_R |= 0x00000020;   // 1) F clock
  delay = SYSCTL_RCGC2_R;         // delay  
  GPIO_PORTF_LOCK_R = 0x4C4F434B; // 2) unlock PortF PF0 
  GPIO_PORTF_CR_R |= 0x1F;        // allow changes to PF4-0      
  GPIO_PORTF_AMSEL_R &= 0x00;     // 3) disable analog function
  GPIO_PORTF_PCTL_R &= 0x00000000; // 4) GPIO clear bit PCTL 
  GPIO_PORTF_DIR_R &= ~0x11;      // 5.1) PF4,PF0 input,
  GPIO_PORTF_DIR_R |= 0x08;       // 5.2) PF3 output 
  GPIO_PORTF_AFSEL_R &= 0x00;     // 6) no alternate function
  GPIO_PORTF_PUR_R |= 0x11;       // enable pullup resistors on PF4,PF0      
  GPIO_PORTF_DEN_R |= 0x1F;       // 7) enable digital pins PF4-PF0       
}

void FlashSOS (void){
  //S
  GPIO_PORTF_DATA_R |= 0x08;  delay (1);
  GPIO_PORTF_DATA_R &= ~0x08; delay (1);
  GPIO_PORTF_DATA_R |= 0x08;  delay (1);
  GPIO_PORTF_DATA_R &= ~0x08; delay (1);
  GPIO_PORTF_DATA_R |= 0x08;  delay (1);
  GPIO_PORTF_DATA_R &= ~0x08; delay (1);
  //O
  GPIO_PORTF_DATA_R |= 0x08; delay (4);
  GPIO_PORTF_DATA_R &= ~0x08;delay (4);
  GPIO_PORTF_DATA_R |= 0x08; delay (4);
  GPIO_PORTF_DATA_R &= ~0x08;delay (4);
  GPIO_PORTF_DATA_R |= 0x08; delay (4);
  GPIO_PORTF_DATA_R &= ~0x08;delay (4);
  //S
  GPIO_PORTF_DATA_R |= 0x08; delay (1);
  GPIO_PORTF_DATA_R &= ~0x08;delay (1);
  GPIO_PORTF_DATA_R |= 0x08; delay (1);
  GPIO_PORTF_DATA_R &= ~0x08;delay (1);
  GPIO_PORTF_DATA_R |= 0x08; delay (1);
  GPIO_PORTF_DATA_R &= ~0x08;delay (1);
  delay (10); // Delay for 5 secs in between flashes
}
#+end_src



* HDL
  Hardware Description Language
  - [[http://ja.wikipedia.org/wiki/%E3%83%8F%E3%83%BC%E3%83%89%E3%82%A6%E3%82%A7%E3%82%A2%E8%A8%98%E8%BF%B0%E8%A8%80%E8%AA%9E][ハードウェア記述言語 - Wikipedia]]

** VHDL
   - [[http://www.iis.ee.ethz.ch/~zimmi/emacs/vhdl-mode.html][Emacs VHDL Mode]]

** Verilog

** VHDL と Verilog の違い.
   - VHDL は「ada」というプログラム言語をもとに開発された「使用記述言語」
   - Verilog は「C 言語」をもとに開発された「シミュレーション専用言語」
 
  参考
   - [[http://www.din.or.jp/~yagiyagi/HTML/KNOWLEDGE/gengo.htm][言語?]]
   - [[http://oshiete.goo.ne.jp/qa/392042.html][VHDL と Verilog の違い
     について - その他 (プログラミング) | 教えて!goo]]

* 電子回路 (ゲート)
** 論理ゲート
   ブール関数を実現するための物理デバイス.

   ゲートをまとめたものを回路, チップという.

*** トランジスタ
    2 値のデータ表現を電気で実現する物理デバイス. スイッチング技術.
    - [[http://ja.wikipedia.org/wiki/%E3%83%88%E3%83%A9%E3%83%B3%E3%82%B8%E3%82%B9%E3%82%BF][トランジスタ - Wikipedia]]

    電気であることが一つのポイント. 
    別の物理性質を用いてゲートを作成することもできる.

*** NAND
    もっとも基礎的な論理ゲート.

*** ブール論理
    すべてのブール関数は NAND NOT をつかって表現できる.
    (AND, OR, NOT ) を含む.

    - NOT (x) = (x NAND x)
    - AND (x, y) = NOT (x NAND y)
    - OR (x,y) = NOT (NOT (x) AND NOT (y))
  
    NAND を実現した物理デバイスが自由に利用できれば,
    どのようなブール関数もハードウェアとして作成できる.

*** マルチプレクサ   
    ふたつ以上の入力をひとつの信号として出力する機構.
    - [[http://ja.wikipedia.org/wiki/%E3%83%9E%E3%83%AB%E3%83%81%E3%83%97%E3%83%AC%E3%82%AF%E3%82%B5][マルチプレクサ - Wikipedia]]

    マルチプレクサによって、ハード的に if 文を表現することができる.

** 算術ゲート
   - [[http://ednjapan.com/edn/articles/1308/09/news002.html][マイコン入門!! 必携用語集 (6):CPU の中枢「ALU」を作ってみよう (1/4) - EDN Japan]]

** 順序回路
   ひとつ以上のフリップフロップ回路が組み込まれているもの. 

   以下のような機能をもつ.
   - 状態を保つ
   - 状態を操作する
    
   状態がかわるのは, クロックが次の周期に移行したとき.
   (c.f. 組み合わせ回路は即時)

*** (D) フリップフロップ回路
    順序回路の中でもっともプリミティブなもの.
    NAND とともに, もっともプリミティブなものとして考えられる.

    フリップフロップ回路の実装方法はいろいろある. 
    NAND から構築する方法もある.
    - [[http://home.a00.itscom.net/hatada/dc2/chap09/dff.html][D フリップフロップ]]

*** プログラムカウンタ

** 論理算術ゲート (ALU)
   論理ゲートと算術ゲートをあわせてひとつにしたもの.CPU の中核.

    
* Memory/Cache
  -> コンピュータ・アーキテクチャに移動

* Interface
ハードウェアとソフトウェアを結ぶもの. ここでいうところは, ハードウェアインタフェース.

interface is defined as the hardware and software that combine 
to allow the computer to communicate with the external hardware. 

- [[http://ja.wikipedia.org/wiki/%E3%83%8F%E3%83%BC%E3%83%89%E3%82%A6%E3%82%A7%E3%82%A2%E3%82%A4%E3%83%B3%E3%82%BF%E3%83%95%E3%82%A7%E3%83%BC%E3%82%B9#.E3.83.8F.E3.83.BC.E3.83.89.E3.82.A6.E3.82.A7.E3.82.A2.E3.82.A4.E3.83.B3.E3.82.BF.E3.83.95.E3.82.A7.E3.83.BC.E3.82.B9][インタフェース (情報技術) - Wikipedia]]

I/O Port, 外部電子回路, 物理的デバイス, ソフトウェアなどを集めたもの.

An interface is defined as the collection of the I/O port, 
external electronics, physical devices, and the software, 
which combine to allow the computer to communicate with the external world.

以下の 4 つに分類される.

- Parallel - binary data are available simultaneously on a group of lines
- Serial - binary data are available one bit at a time on a single line
- Analog - data are encoded as an electrical voltage, current, or power
- Time - data are encoded as a period, frequency, pulse width, or phase shift

** Parallel Interface
   パラレルポートとは, コンピュータシステム内で,
   ばらばらの周辺機器をケーブルで接続するために使われる物理的なインタフェースの一種.

- [[http://ja.wikipedia.org/wiki/%E3%83%91%E3%83%A9%E3%83%AC%E3%83%AB%E3%83%9D%E3%83%BC%E3%83%88][パラレルポート - Wikipedia]]
- [[http://www.sophia-it.com/content/%E3%83%91%E3%83%A9%E3%83%AC%E3%83%AB%E3%82%A4%E3%83%B3%E3%82%BF%E3%83%BC%E3%83%95%E3%82%A7%E3%83%BC%E3%82%B9][パラレルインターフェースとは 「パラレルインタフェース」 (parallel interface): - IT 用語辞典バイナリ]]

*** PCI
    コンピュータのプロセッサと周辺機器との間の通信を行うためのバスアーキテクチャの一つ.
    - [[http://ja.wikipedia.org/wiki/Peripheral_Component_Interconnect][Peripheral Component Interconnect - Wikipedia]]

   #+begin_src sh
   $ lspci
   #+end_src

*** USB
    USB (Universal Serial Bus) はホットプラグに対応したインターフェイスの規格です.
    USB デバイスは USB コントローラ (チップ) によって制御されます. 
    また, それぞれの USB コントローラにはモジュール (デバイスドライバ) が必要です.

    以下は主な USB コントローラ, USB の規格, モジュールをまとめたものです.
    
    | Controller | Spec   | USB mod (2.4) | USB mod (2.6) |
    | UHCI       | USB1.1 | usb-uhci      | uhci_hcd     |
    | OHCI       | USB1.1 | usb-uhci      | uhci_hcd     |
    | EHCI       | USB2.0 | -             | ehci_hcd     |

    USB には以下のような特徴があります.

    - USB コントローラは最大 127 台の USB デバイスを制御できる
    - システムが起動している状態でも USB デバイスの差し替えが出来る (ホットプラグ)
    - 接続しているホストから電源を供給できる
    - キーボード, マウス, プリンタなど多くのデバイスが USB に対応している

    なお, USB1.1 規格はカーネル 2.4 から, USB2.0 規格はカーネル 2.6 か
    らサポートされています.

** Syncronization
ハードウェアとソフトウェアの同期処理.

ハードウェアのスピードとソフトウェアのスピードは,
ソフトウェアの方が早いため相互でやりとりするためには以下の手段がある.

*** Blind-Cycle 
決められた時間 Sleep したあとに I/O ステータスをチェックする.

the software writes data to the output device, 
triggers (starts) the device, then waits a specified time. 
We call this method blind, because there is no status information 
about the I/O device reported to the software. 

*** Busy-Wait
Input device のデータが更新されたときに I/O ステータスをチェックする.

状態が Busy ならば Wait (loop), Ready ならば次のステップへ.

Busy Wait is a software loop that checks the I/O status 
waiting for the done state. For an input device, 
the software waits until the input device has new data, 
and then reads it from the input device,

*** Interrupt 
ハードウェアが発生させる特別な通知.

An interrupt uses hardware to cause special software execution. 
With an input device, 
the hardware will request an interrupt when input device has new data. 
The software interrupt service will read from the input device and save in global RAM, 

*** Periodic Polling 
クロックタイマの割り込み契機で I/O のステータスをチェック

*** DMA 
    Direct Memory Access あるメモリから別のメモリに直接情報を書き込む.
    CPU を介することなくメインメモリと周辺機器の間で直接的に情報転送を行う方式.

    #+begin_src language
    # デバイスが使用中の DMA チャネルに関する情報
    # cat /proc/dma
    #+end_src


** Serial Interface
*** UART
Universal Asynchronous Receiver/Transmitter (UART).
調歩同期方式によるシリアル通信をするための汎用 I/F.

- [[http://ja.wikipedia.org/wiki/UART][UART - Wikipedia]]

有名なので, 最近のほとんどのマイコンに搭載されているらしい.
* Thread/Process/Task
** Thread
A thread is defined as the path of action of software as it executes. 

** Process
*** Definition
    - A process is defined as the action of software as it executes. 
    - A process is an instance of a running program.

*** Features
    プロセスは 2 つの抽象化をおこなう
    - 論理制御フロー
      - それぞれのプロセスが 1 つの CPU で実行しているように見える
    - プライベートな仮想メモリ空間
      - それぞれのプロセスが 1 つの メインメモリ で実行しているように見える

    Process は一度にひとつのことしか実行できない.
    - concurrently: 平行で動作しているように見える
    - 実際はシーケンシャル.
    
    その秘密は, OS のコンテキストスイッチにある!

*** fork-exec model
    Fork-exec is a commonly used technique in Unix whereby an
    executing process spawns a new program.

    fork-exec モデルは, プロセス管理手法.

    - [[http://en.wikipedia.org/wiki/Fork-exec][Fork-exec - Wikipedia, the free encyclopedia]]
    - [[http://ja.wikipedia.org/wiki/Fork][fork - Wikipedia]]

    forc と exec の説明は以下.

    - fork: 現在のプロセスのコピーを生成.
    - execve: 現在のプロセスのコードとメモリ空間を別のものへ置き換える.

*** Thread との違い

    スレッドとプロセスの違いは, 変数のスコープの違い?

    Threads share access to I/O devices, 
    system resources, and global variables, 
    while processes have separate global variables and system resources. 
    Processes do not share I/O devices.

    実際は, OS によってバラバラ.

    - [[http://futurismo.biz/archives/2245][スレッドとタスクの違いについてしらべてみた (C++/Linux) | Futurismo]]

* Interrupt
  Hardware Interrupt Software Action.

  非同期例外ともいう. プロセッサの外部からのイベントによってひきおこさ
  れる.

  - I/O  interrupts  
    - hittng  Ctrl-­-C  on  the  keyboard  
    - clicking  a  mouse  buVon  or  tapping  a  touchscreen  
    - arrival  of  a  packet  from  a  network  
    - arrival  of  data  from  a  disk  
  - Hard  reset  interrupt  
    - hittng  the  reset  buVon  on  front  panel  
  - Soft  reset  interrupt  
    - hittng  Ctrl-­-Alt-­-Delete on a PC

  Busy-Wait の制御で待ってられない場合は, Interrupt を利用する.

** Edx
   ここからは, 一般的な説明ではなくて edX の中だけの定義.

*** Arm/DisArm
    - Arm とは, ハードウェアが割り込みをあげることを有効化する.
    - DisArm とは, ハードウェアが割り込みをあげることを無効化する.
    
*** Enable/Disable
    - Enable は一時的に割り込みを有効化する.
    - Disable は一時的に割り込みを無効化する.Disable 中に発生した
      Interuppt は Pending されて, Enable 時に通知される.

*** Interruput の初期化処理
    1. Trigger flag set by hardware
    2. the device is armed by software
    3. the device is enabled for interrupts in the NVIC
    4. the processor is enabled for interrupts (PRIMASK I bit is clear)
    5. the interrupt level must be less than the BASEPRI. 

*** Context Switch
    割り込みをハードウェアが検知したときに,
    foreground と background のスレッドを入れ替える.

    - [[http://ja.wikipedia.org/wiki/%E3%82%B3%E3%83%B3%E3%83%86%E3%82%AD%E3%82%B9%E3%83%88%E3%82%B9%E3%82%A4%E3%83%83%E3%83%81][コンテキストスイッチ - Wikipedia]]

    現在のプロセスの実行を一時停止して,
    スタックにレジスタ情報を覚えておく.

    割り込みハンドラを実行して,
    ハンドラの実行が終了したらもとのプロセスを再開する.

    1. Current instruction is finished,
    2. Eight registers are pushed on the stack,
    3. LR is set to 0xFFFFFFF9,
    4. IPSR is set to the interrupt number,
    5. PC is loaded with the interrupt vector

** Interrupt Service Routine (ISR)
   割り込みサービスルーチン. 割り込みハンドラともいう.

   - [[http://ja.wikipedia.org/wiki/%E5%89%B2%E3%82%8A%E8%BE%BC%E3%81%BF%E3%83%8F%E3%83%B3%E3%83%89%E3%83%A9][割り込みハンドラ - Wikipedia]]

   コンテキストスイッチによって,foreground で動作している busy-wait な
   スレッドと ISR がスワップされる.

   割り込み受け付けによって起動されるオペレーティングシステムやデバイ
   スドライバのコールバックルーチン.割り込みハンドラは割り込み原因によっ
   てそれぞれ存在し,割り込みハンドラがそのタスクを完了するまでにかかる
   時間も様々である.

*** NVIC
割り込みハンドラに対応させたい関数は,
startup script に事前に登録しておく.

vector というメモリ領域にシステムにどの関数を実行すればいいかをアドレスとして教える.

interrupt 発生時は vector を参照して, それに対応する割り込みルーチンの関数を呼ぶ.

nested vectored interrupt controller (NVIC) manages interrupts, 
which are hardware-triggered software functions. Some internal peripherals, 
like the NVIC communicate directly with the processor 
via the private peripheral bus (PPB). 
The tight integration of the processor and interrupt controller provides 
fast execution of interrupt service routines (ISRs), 
dramatically reducing the interrupt latency.

*** Acknowledge
割り込みを ISR が認識すること.
ISR が割り込みの認識を行った後, 同じデバイスからの割り込みが発生しないよう割り込みマスクをする必要がある.
そうしないと, クラッシュする恐れがある.

- [[http://d241445.hosting-sv.jp/community/report/report31.html][レポート 31:割り込みサービスルーチン (ISR) の処理]]

実装でやってはいけないことは以下.

- 長時間の処理はしてはいけない.
- 待ち状態になってはいけない, Delay Loop はつかわないほうがよい.
- 呼んではいけない関数がある.

割り込みハンドラでは必要最小限の処理のみを行い, 別のタスクに通知して,
メインの処理はそっちでさせるように実装すべき.

*** ISR からメイン処理への通知方法
ISR とメイン処理はグローバルなメモリ領域を介して情報を受渡しする.

- Binary Semaphore
ISR で 決められた flag を立てて, メイン処理でそのフラグを監視する.
flag が 1 ならば, それのフラグに対応する処理を実施する.

- MailBox
flag とともにデータも渡すこともある.

flag を Status といい, flag と data を合わせたデータ構造を Mail という.
(MailBox Pruducer-Consumer Pattern)

- FIFO queue
ISR で Fifo なメモリ領域にデータを PUT し,
メイン処理の loop 処理でで定期的に Fifo な data をチェックし, 順次実行する.

* 異常検出の方法について
以下の 2 つがある.

- Interupt (通知)
  - リアルタイムに異常を処理できる.
  - ハードウェアや OS に依存する.

- Periodic Polling (監視)
  - ソフトウェアの処理だけで実装できる.
  - 割り込みを発生できないイベントも監視できる.

- [[https://www.uquest.co.jp/embedded/learning/lecture04.html][学校では教えてくれないこと | 技術コラム集 (組込みの門) | ユークエスト]]

* DAC 
digital to analog converter (DAC).

デジタル電気信号をアナログ電気信号に変換する電子回路.

[[http://ja.wikipedia.org/wiki/%E3%83%87%E3%82%B8%E3%82%BF%E3%83%AB-%E3%82%A2%E3%83%8A%E3%83%AD%E3%82%B0%E5%A4%89%E6%8F%9B%E5%9B%9E%E8%B7%AF][デジタル-アナログ変換回路 - Wikipedia]]

** Sound

* ADC
analog to digital converter (ADC). 

アナログ電気信号をデジタル電気信号に変換する電子回路.

[[http://ja.wikipedia.org/wiki/%E3%82%A2%E3%83%8A%E3%83%AD%E3%82%B0-%E3%83%87%E3%82%B8%E3%82%BF%E3%83%AB%E5%A4%89%E6%8F%9B%E5%9B%9E%E8%B7%AF][アナログ-デジタル変換回路 - Wikipedia]]

** Sensor

* Nand To Tetris
** week0
** week1: ゲートへ
***  論理ゲート
   - And 
   - Or
   - Xor
   - Not
   - Not16, And16, Or16, Mux16 ... 16 進数の 論理ゲート

*** マルチプレクサ
   - Mux ... マルチプレクサ
   - DMux ... デマルチプレクサ
   - Mux8Way16, DMux8Way, DMux4Way .. 16 進数のマルチプレクサ

** week2:  CPU へ
*** 算術ゲート
   - HalfAdder ... 半加算器
   - FullAdder ... 全加算器

   - Add16 ... 16 進加算
   - Inc16 ... 16 進インクリメンタ

*** ALU
   - ALU ... 論理算術ゲート

** week3: Memory へ
*** Memory
   - Bit, Register ... レジスタ
   - RAM8, RAM16, RAM64, RAM512, RAM4K, RAM16K ... RAM

*** Counter
   - PC ... プログラムカウンタ

** week4:  機械語へ
