#+OPTIONS: toc:nil
* Networking
* セッション
コンピューター間でデータをやり取りするために設ける論理的な接続関係.

  - [[http://www.fwoabw.info/entry/20120129/1327789678][「セッション」とは. 色んな セッションの意味まとめ - For Want Of A Better Word]]

** http (web ページ操作) でのセッション
   複数の Web ページにまたがって行われる一連の処理・操作.
   1 回 WEB ページにアクセスして, 複数のページを閲覧したりすると, 1 セッ
   ションで何ページ見た.

** WEB アプリ・プログラムにおけるセッション
   セッションは, シンプルな方法で個々のユーザーのデータを格納する仕組みで,
   個々のユーザーに対して一意なセッション ID を用意します. これを用いて,
   複数ページにまたがるリクエストの間で状態の情報を永続させることができます.

* ソケットプログラミング
** Socket
   - 実行中のプログラム間でデータの送受信を行うための
     標準的なプログラミングインターフェース (API) の一つ.
   - TCP/IP アプリケーションを作成するための抽象化されたインターフェース
   - [[http://ja.wikipedia.org/wiki/%E3%82%BD%E3%82%B1%E3%83%83%E3%83%88_(BSD)][ソケット (BSD) - Wikipedia]]

** EndPoints
   端末.一意に定まる通信先.

   Socket は IP Address と PortNo.をつかって, 通信先のソケットを特定す
   る. ネットワークに接続されたパソコンや PDA, 携帯電話などのネットワーク
   端末の総称.

   - [[http://www.sophia-it.com/content/%E3%82%A8%E3%83%B3%E3%83%89%E3%83%9D%E3%82%A4%E3%83%B3%E3%83%88][エンドポイントとは (end point): - IT 用語辞典バイナリ]]

   エンドボイントに Socket がバインドされる.

** Loopbacks
   IP アドレスは必ずしもリモートホストと関連付けられている必要はない.
   得に開発環境では, ローカルな IP アドレスが役に立つ.

   自端末に対して通信することを LoopBack という.
   LoopBack で指定するアドレスを Loopback Address という.

   - ハードウェアと関係ない, 論理的なインタフェース.
   - Linux では, localhost と言われている. IP は 127.0.0.1

   [[http://e-words.jp/w/E383ABE383BCE38397E38390E38383E382AF.html][ループバックとは 〔 ローカルループバック 〕]]

** Ports
*** PortFowarding
    ポートフォワーディング.
    ローカルコンピュータの特定のポートに送られてきたデータを,
    別に用意した通信経路を用いてリモートコンピュータの特定ポートに送信すること.

    - [[http://e-words.jp/w/E3839DE383BCE38388E38395E382A9E383AFE383BCE38387E382A3E383B3E382B0.html][ポートフォワーディングとは 【 port forwarding 】]]

    たとえば, Windows ファイルサーバに, 
    SSH 経由で (CIFS, port 445/tcp で) アクセスする (した)

    - [[http://akasaka-taro.blogspot.jp/2011/12/cifs-over-ssh-windows7-ssh.html][赤坂タロウの日記: CIFS over SSH, Windows7 ssh 経由でファイル共有
      アクセス]]

** Stream
   データの入力または出力の機能を提供する抽象データ型.
   メッセージの境界という境界がない.

   TCP/IP プロトコルはストリームベースの設計.
   - [[http://ja.wikipedia.org/wiki/%E3%82%B9%E3%83%88%E3%83%AA%E3%83%BC%E3%83%A0_(%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0)][ストリーム (プログラミング) - Wikipedia]]
** Buffering
** Blocking/Non-Blocking
*** ブロッキング
    送受信の完了を待ってから他の処理を開始する通信方法.

#+begin_src ruby
require 'socket'
server = TCPServer.new (2803)
while client = server.accept
  input = client.readline
  client.write "You said: #{input}"
  client.close
end
#+end_src

*** ノン・ブロッキング
    データの送受信を行う際に, 送受信の完了を待たず, 他の処理を開始する通信方法.
     - [[http://e-words.jp/w/E3838EE383B3E38396E383ADE38383E382ADE383B3E382B0E9809AE4BFA1.html][ノンブロッキング通信とは 〔 ノンブロッキングモード 〕]]

#+begin_src ruby
require 'socket'
server = TCPServer.new (2803)
loop do
  Thread.new (server.accept){ |client|
    input = client.readline
    client.write "You said: #{input}"
    client.close
  }
end
#+end_src

** Example Ruby
*** Server Lifecycle
   1. create 
      ソケットの生成
   2. bind 
      - ソケットを利用する Port にバインド.
        + User でバインドする Port は 1025-48999
      - ソケットが通信を許可する IP を指定.
	+ 0.0.0.0: すべて許可
	+ 127.0.0.1: 自端末のみ許可
	+ xxx.xxx.xxx.xxx: ある端末のみ許可
   3. listen 
      通信先ソケットからの通信をまつ
   4. accept 
      通信先ソケットからの通信を受け取り, 通信路 をそのつど生成 (connection)
   5. close
      通信元ソケットの消滅.

#+begin_src ruby
# coding: utf-8
require 'socket'

# 1. create
server = Socket.new (:INET, :STREAM)

# 2. bind
addr = Socket.pack_sockaddr_in (4481, "0.0.0.0")
server.bind (addr)

# 3. listen 
server.listen (5)

# 4. accept
loop do
  connection, _ = server.accept

  ## send message from client.
  # ehco "Hello" | nc localhost 4481
  p connection

  # it should be closed each connection
  connection.close
end

# 5. close
server.close
#+end_src

**** TCPServer 
    Ruby では, 以下のような糖衣構文がある.

    - [[http://docs.ruby-lang.org/ja/2.0.0/class/TCPServer.html][class TCPServer]]

#+begin_src ruby
server = TCPServer.new (4481)
# => 
# server = Socket.new (:INET, :STREAM)
# addr = Socket.pack_sockaddr_in (4481, "0.0.0.0")
# server.bind (addr)
# server.listen (5)
#+end_src

*** Client LifeCycle
   1. create
      ソケットの生成     
   (2. bind ) 
   3. connect 
      サーバと接続
   4. close
      ソケットの破棄

   #+begin_src ruby
require 'socket'

# 1. create
socket = Socket.new (:INET, :STREAM)

# 3. connect
remote_addr = Socket.pack_sockaddr_in (80, 'google.com')
socket.connect (remote_addr)

# 4. close
socket.close
   #+end_src

**** TCPSocket
    Ruby では, 以下のような糖衣構文がある.

    - [[http://docs.ruby-lang.org/ja/1.8.7/class/TCPSocket.html][class TCPSocket]]

    #+begin_src ruby
socket = TCPSocket.new ('google.com', 80)
# =>
# socket = Socket.new (:INET, :STREAM)
# remote_addr = Socket.pack_sockaddr_in (80, 'google.com')
# socket.connect (remote_addr)
    #+end_src

*** Simple Read
    以下の例では, 永遠にサーバは Read を待ち続けて, その先が進まない.

    #+begin_src ruby
require 'socket'

Socket.tcp_server_loop (4481) do |connection|
  puts connection.read
  connection.close
end
    #+end_src

    Socket は指定されたデータ長のデータが到着するまで待ち続ける.
    デッドロックを回避するためには,

    - Client 側で データの最後で EOF を送信する.(EOF event)
    - Server 側で一度に読み込むデータ長を小さくする. (partial read)
      
    Client のソケットが close メソッドを実行すると, その延長で EOF が通知
    される.

* SDN
Software Defined Networking.

** 定義
- 広義:「従来システムのネットワーク要素を抽象化し分割する, コンピュータ ネットワークを構築するアプローチ」 (wiki より)
- 狭義:「 (広義のアプローチを具体化するために) ネットワーク機器のコントロール プレーン, データ プレーンを分離し, 集中化されたソフトウェアからコントロールして, もっと効率的なこと, 便利なことをする!! 」

A new networking paradigm whereby the behavior of a network is controlled 
by a single high-level software program.  
The general term for network architectures whereby the control 
plane (software that controls network behavior) and the 
data plane (the devices that forward traffic) are separate from one another.

SDN allows network administrators to manage network services 
through abstraction of lower level functionality.

[[http://en.wikipedia.org/wiki/Software-defined_networking][Software-defined networking - Wikipedia, the free encyclopedia]]

コントロールプレーンとフォワーディングプレーンを分離し, ネットワークにプログラマビリティを持たせる

[[http://forums.juniper.net/t5/%E3%83%96%E3%83%AD%E3%82%B0/SDN%E6%99%82%E4%BB%A3%E3%81%AE%E3%83%87%E3%83%BC%E3%82%BF%E3%82%BB%E3%83%B3%E3%82%BF%E3%83%BC-%E3%82%A2%E3%83%BC%E3%82%AD%E3%83%86%E3%82%AF%E3%83%81%E3%83%A3-Forwarding-Plane-%E5%89%8D%E7%B7%A8/ba-p/204427][SDN 時代のデータセンター・アーキテクチャ/Forwarding Plane J-Net Community]]


ネットワーク全体で一つの OS として見え,
ソフトウェアから見れば個々のネットワーク機器が隠ぺいされています.
こうすることで, ソフトウェアを開発さえすれば
自由にネットワークを制御することが可能になります.

[[http://thinkit.co.jp/story/2012/02/02/3151][SDN への潮流と OpenFlow の歴史 | Think IT (シンクイット)]]

** SDN の歴史と基盤技術
*** Active networks
    A collection of network architecture projects in the 1990s that shared
    many of the same goals as software-defined networking.

*** Network virtualization
    ネットワーク仮想化. 物理ネットワーク上に複数の論理ネットワークを構築すること.

    The notion of instantiating many distinct logical networks 
    on top of a single, shared physical network infrastructure.

    [[http://ascii.jp/elem/000/000/793/793504/][ASCII.jp:なぜ SDN は生まれたのか? ネットワーク仮想化との関係は? (1/2)|Q&A 形式で学ぶ OpenFlow/SDN]]

   「ネットワーク仮想化」とも呼ばれ, 厳密には SDN の応用の一つであり,
   また, SDN によらず別の技術によって実現する手法もあるため,
   ネットワーク仮想化と SDN そのものとは区別する必要がある.

   [[http://e-words.jp/w/SDN.html][SDN とは 【 Software-Defined Networking 】 - 意味/ 解説/ 説明/ 定義 : IT 用語辞典]]

** 構成要素
*** Control Plane
    The functions in the network that control the behavior of the network 
    (e.g., network paths, forwarding behavior).  
    Typically, the control plane is instantiated as a single, high-level
    software controller.

*** Data Plane
フォワーディング・プレーン, Forwarding plane ともいう.

[[http://en.wikipedia.org/wiki/Forwarding_plane][Forwarding plane - Wikipedia, the free encyclopedia]]

The functions in the network that are responsible for forwarding
(or not forwarding) traffic.  Typically, the data plane is
instantiated as forwarding tables in routers, switches, firewalls
, and middleboxes.

Data plane design goals. 技術革新に素早く対応できること.
    - Flexible (柔軟性)
    - Extensible (拡張性)
    - Clean interfaces (整理されたインタフェース)
      
**** Programmable Hardware
     標準化された, プログラミング可能なハードウェア.
     もうすぐ, 高級言語での記述もできるようになるはず.

     - FPGA
     - Click

**** Flow の構成要素
     - ヘッダフィールド (マッチングルール)
     - アクション
       - Forwarding
       - Enqueue
       - Drop
     - 統計情報

     [[http://thinkit.co.jp/story/2012/02/09/3209][OpenFlow のアーキテクチャと仕様・機能 | Think IT (シンクイット)]]

*** NorthBound API
    Programming interface that allows applications and norchestration systems to 
    program the network .Uses for Northbound API ,

- Path computation 
- Loop avoidance 
- Routing 
- Security

  Northbound API は, アプリケーションから SDN コントローラを制御できる API だ.
  
    - [[http://www.publickey1.jp/blog/12/sdnopenflownorthbound_api.html][SDN/OpenFlow の新しい課題:Northbound API とは何か? - Publickey]]
    - [[http://www.publickey1.jp/blog/12/northdound_apisoftware-defined_network.html][Northdound API は, Software-Defined Network にとって重大な欠落だ - Publickey]]

Northbound API can help,

- Sophisticated events 
- Composition of policies 
- Event handling

*** SouthBound API
Control Plane と Data Plane をつなぐ API.

** SDN のアーキテクチャ
#+begin_src language
                           ---
   Controller Applications  |
   ======================   |
      NorthBound API        | Control Plane
   ======================   |  
     Controller Platform   ---
   ======================   |  
      SouthBound API        | Data Plane
   ======================   |
     OpenFlow Switches      |  
                           ---
#+end_src

** Composition
シーケンシャルな制御方法とパラレルな制御方法.

- Sequential composition :Perform one operation, then the next.
- Parallel composition :Perform both operations simultaneously.

** Event-Driven SDN
   ネットワーク構成のほとんどは, イベント駆動の処理.
   ネットワークのポリシーを Event-Based で表現という考えが
   Event-Based Network Control.
   
    - Event Plane
      - user
      - time
      - history
    - Dinamic Event Handler
      -> State Transition signal to Control Plane.
    - Control Plane
      -> finite state machine で制御される.
      - State
	ドメインの状態 (value) の集合.
      - Events
	ステートマシンにしたがって状態遷移を発生させるトリガ
    - Data Plane

** 他の用語との違いについて整理
*** OpenFlow
    Software-Defined Network (SDN) は, コンセプト, アーキテクチャ.
    それを実現する技術の一つが OpenFlow.
    
*** OpenStack
    OpenStack はクラウドを OSS で管理するためのソフトウェア群の総称.
    OpenStack のネットワーク仮想化にあたる部分が SDN の思想と重なる.

* OpenFlow
  OpenFlow は, スタンフォード大学が中心となっている
  「 OpenFlow スイッチングコンソーシアム」が提唱するネットワーク制御技術.

  SDN を実現するための代表的なフレームワーク.

  - [[http://ascii.jp/elem/000/000/794/794744/][ASCII.jp:SDN を牽引する OpenFlow とは? 業界へのインパクトは?]]
  - [[http://e-words.jp/w/OpenFlow.html][OpenFlow とは 〔 オープンフロー 〕 - 意味/ 解説/ 説明/ 定義 : IT 用語辞典]]
  - [[http://www.publickey1.jp/blog/13/openflowsdnopenflowsdn_japan_2013.html][OpenFlow/SDN はなぜ誕生したのか, OpenFlow 以前にあった問題とは. 生みの親カサド氏が壇上で語る. SDN Japan 2013 - Publickey]]
    
* WAN
** WAN 高速化
** 高速化装置
  通信のレスポンスを決める要素は大きく 3 つ.
   - 遅延
   - 1 回のやり取りで送信するデータ量であるウインドウ・サイズ
   - アプリケーションのバースト転送性

   遅延の影響を受けやすいアプリケーションが存在する.
   その代表格は, 米マイクロソフトのファイル共有プロトコルの CIFS や,
   データベースに使われる Microsoft SQL などのアクセス.

   - [[http://itpro.nikkeibp.co.jp/article/COLUMN/20070606/273782/][ネット設計を激変させる WAN 高速化装置]]

** 高速化技術
*** キャッシュ
    使用頻度の高いデータを高速読み出し可能な記憶装置に蓄積しておく仕組み.

*** プロトコル・アクセラレーション
    プロトコル・アクセラレーションの特徴は, 代理応答という仕組み.

    - 各社の WAN 高速化装置が登場した当初は, 
      ユーザーが多いこともあって CIFS が主要な高速化対象だった.
    - MAPI, NFS も対応してきている.
    - 利用頻度の高さから HTTP (hypertext transfer protocol) に対応する製品も増えてきた.

**** 代理応答
    サーバーがデータ転送を始めると, 
    サーバー側の WAN 高速化装置がクライアントの代わりに Ack を返す
     
    [[http://itpro.nikkeibp.co.jp/article/COLUMN/20070606/273783/?ST=neteng][WAN 高速化装置の高速化テクノロジ--キャッシュとプロトコル・アクセラレーション]]

*** 先読み

** Links
   CIFS に関する WAN Accerelation
   - http://www.snia.org/sites/default/files2/sdc_archives/2009_presentations/monday/MarkRabinovich-IgorGokhman-CIFS_Acceleration_Techniques.pdf
