#+OPTIONS: toc:nil
* Storage
  ストレージ技術について

* Block-Based Storage
  ブロックストレージ.NFS や CIFS で OS からドライブやマウントポイント
  として見ることができる.

** 基本的な設定手順
*** RAID グループ作成
    RAID 構成を行うと, まず複数のディスクは RAID グループとして管理さ
    れます. ここで複数の物理ディスクは論理的にグループ化され, それぞれ
    のパフォーマンスや冗長化要件に合わせ RAID レベルを設定いたします.

*** LUN (論理ボリューム) 作成
    RAID グループを設定した後は, グループ内にあるディスクを論理的に分
    けて使います. この論理的に分けられたものを LUN (Logical Number of
    Unit) といい, Windows や Linux などの OS から物理的なディスクとし
    て認識される単位となります.

*** パーティション作成
    LUN で設定されたディスク容量を論理的に切り分けて使う単位をパーティ
    ションと呼びます. OS が作成するファイルシステムはこの単位で設定さ
    れ, OS やユーザ領域などの目的に合わせ一つのパーティションの中から
    複数のドライブを作ることが可能です.

*** マウント
*** ファイルシステムフォーマット
  
* Object-Based Storage
  オブジェクトストレージ.

** 特徴
  - HTTPS 上の REST (Representational State Transfer) を利用
  - OS やファイルシステムに依存することなく, 
    データの格納や格納したオブジェクトへのアクセスが可能
  - 例外を除き, ファイルシステムは使われない
  - 固有の名前 (UUID のような文字列) が付与され,ストレージ内において,
    データとデータを管理するためのメタデータが関連づけられる.
  - ディレクトリ構造がない, フラットなアクセス.
  - RAID やファイルシステムに必要な, ボリューム設計や複雑な運用管理,
    スペアディスクの設定が不要

** RAS 技術
*** Replication 
    データ複製.オブジェクトをコピーし, ノード間で複製を保持することで
    冗長性を高める手法.

*** Erasure Coding 
    Erasure Coding はオジェクトを分割して消失訂正符号を付加し, 物理的
    に異なるノードに分散して格納することで, その分割したデータのいくつ
    かが消失した場合でも, 元のオブジェクトを復元することができる手法.

    RAID5 のようなことを, ノード間で実施する.

** Links
   - [[http://www.reqtc.com/column/object-storage.html][いま話題のオブジェクトストレージとは!? ]]
   - [[http://www.ctc-g.co.jp/~ctcsp//sp/ostf_02.html][新たな潮流, オブジェクトストレージとは?  『オブジェクトストレージが求められる背景』]]

* Cloud Storage
  クラウドストレージ.
  
* Software Defined Storage
  EMC のとなえる戦略. ストレージにおける Software Defined.

  #+BEGIN_HTML
  <blockquote>
  Software-defined storage (SDS) is a term 
  for computer data storage technologies which separate storage hardware 
  from the software that manages the storage infrastructure
  </blockquote>
  #+END_HTML

  [[http://en.wikipedia.org/wiki/Software-defined_storage][Software-defined storage - Wikipedia, the free encyclopedia]] 

  SDN は OpenFlow という共通技術によって浸透したが,
  ストレージ分野では共通技術となるようなものがないとか.

  [[http://www.publickey1.jp/blog/14/software-defined_storage.html][Software-Defined Storage, これからのストレージ技術が実現する世界とはどのようなものか? - Publickey]]

** Chuck's blog
   Chuck 氏の連載が熱い.

   - [[http://chucksblog.typepad.com/chucks_blog/software-defined-storage-series.html][Software-Defined Storage Series - Chuck's Blog]]
  
*** Software-Defined Storage: Choices 

    [[http://chucksblog.emc.com/chucks_blog/2014/05/software-defined-storage-choices-ahead.html][Software-Defined Storage: Choices Ahead - Chuck's Blog]]

    UNIX が未来の道標を築き上げてきたように, Cloud もこれからの未来を築く.

    For years, I had that wall-sized chart that showed how UNIX evolved over the years. 
    I'm sure one could create a similar wall-sized infographic showing the evolution of "cloud".  

    Software-Defined Storage に適応するために, 様々なアイデアが競合しあう.

    We're going to see something very similar when it 
    comes to software-defined storage. 
    Many flavors of the same idea will compete for adoption.

    よい選択をするために, 過去に学ぼう.

    Learning To Make Good Choices

    - #1 -- Familiar - Or Evolved?

    似たものになるか? それとも, 進化するか?

    私はこのように Software-Defined Storage という単語を使っている.

    アプリケーションの境界と提携して動的にストレージを構築できる能力

    ability to dynamically compose storage services aligned on application boundaries.

    この定義は重大な変化を運用モデルにもたらす.

    This particular definition mandates a serious change to the operational model: 
    using application-centric policies, just-in-time provisioning, etc.  
    And I would argue that the chief goal of software-defined anything is to evolve the model, 
    and not simply recreate the familiar past using new technology.   

    ドキュメントエディタは単にタイプライタをよくしたものではない.

    A document editor is not just a better typewriter.

    - #2 -- Bottoms Up, Or Top Down?

    ボトムアップか? それとも, トップダウンか?

    それぞれのグループが自分たちのテクノロジをつくっている.
    積極的な M&A が結果的にそれらを整理することになった.

    Every group making their own technology choices independently. 
    Aggressive M&A resulting in a cluttered toy box to be sorted out.

    それらの人々は,
    ベンダ間の差異を標準化するストレージ抽象レイヤに大変関心を持っている.

    These folks are quite interested in a storage abstraction layer 
    that normalizes all the differences, 
    and provides a standardized consumption and operational model.

    EMC ViPR こそがベストな選択だ.

    I believe that EMC's ViPR controller is the best example of a 
    technology that meets this need. 

    今日, 多くのプロダクトが Software-Defined Storage の
    攻略対象としてあげられている.

    And - yes - today there are many products being marketed as 
    "software-defined storage" that only have rudimentary northbound APIs at best.

    - #3 -- Managed Separately, Or Converged?

    別々で管理するか? それとも統合するか?

    サーバ, ストレージ, ネットワーク,
    それぞれのチームが思い描くクラウドのイメージが違う.

    The server team reported out what they planned to do, 
    the network team, the storage team, etc.  
    Each team had a plan to implement "cloud" after their own image.

    3 者のレポートがバラバラなのは明らか.

    After the third report-out, 
    it was clear that the teams hadn't done much collaboration :)

    - #4 -- Static -- Or Dynamic?

    静的か? それとも動的か?

    私たちは, 過去数年で手工芸的にそれぞれの要求に答えることから,
    あらかじめ確保されたサービスの選択が出来るようにした.

    We spent the last few years moving IT from hand-carving every request, 
    to having pre-allocated service choices.  

    私たちは, この先数年で要求に応じて動的に構成されたサービスを目指す.

    We'll spend the next few years moving from pre-allocated services 
    to dynamic composition of services from resources as demanded.

    - #5 - Start To Invest Now - Or Wait Until The Dust Settles?

    いまから投資するか? 安定するまでまつか?

    SDS が最大な勝利を収める領域は, 運用モデルだ.
    新しい運用モデルは深く理解され, 実装され, 満足されるまで時間がかかる.

    The biggest win with SDS is the operational model - and it's brand new.  
    New operational models can take a lot of time to fully understand, 
    implement and become comfortable with. 

    個人的な意見としては,
    今が, 新しい運用モデルに慣れ親しむことに投資するのによいときだ.

    Personally, I'm telling people that now is a good time 
    to modestly invest in becoming familiar with the new operational model 

    - The Key Question

    Software-Defined Anything が進むにつれて,
    私たちはここからなににすればいいんだ?

    When it gets down to software-defined anything, 
    the real question is - what the heck are we trying to do here?  

    私たちのゴールは, 今していることを継続的によりよくしていくことか?
    それとも, 新しいモデルを再発明することか?

    Is our goal simply to do what we're doing today, only do it incrementally better?
    Or is our goal to re-invent the model of how things get done?

** 製品
*** EMC ViPR
   - [[http://www.atmarkit.co.jp/ait/articles/1408/18/news006.html][単なる運用管理ツールではない! Software-Defined Storage を使う意味とメリットとは? - ＠ IT]]

*** IBM Elastic Storage

* SMI-S
  ストレージ"管理"のための API.

  2003 にはじまったのに, なぜ 10 年以上たった今でもいまいちな知名度なのか?

  [[http://ja.wikipedia.org/wiki/SMI-S][SMI-S - Wikipedia]]
  [[http://www.snia-j.org/tech/smis/smis/smis1.html][SMIS がストレージ業界に及ぼす影響 (1/4) : SNIA-J]]
  [[http://www.atmarkit.co.jp/fnetwork/tanpatsu/16snw2004/01.html#][＠ IT:特別企画:ストレージ・ネットワーキング・トレンドレポート【前編】]]

* CDMI
  クラウドデータ管理インターフェイス (CDMI)

  [[http://www.sbbit.jp/article/cont1/24892][クラウドストレージ標準「 CDMI 」とは何か?SNIA 会長ウェイン・アダムス氏インタビュー クラウドの標準化動向も一覧で理解|ビジネス +IT]]
  [[http://www.snia-j.org/tech/WH/CloudStorage/CloudStorage4.html][クラウドストレージの実装, サービス提供と使用 (4/6) : SNIA-J]]

  Rest API らしい. EMC の ViPR も Rest を利用している.

* SCM
  Storage Class Memory.

  ストレージ業界にいることもあって, 
  アプリが性能のボトルネックになるというはなしはよくきく. 
  
  以前, 次世代メモリと呼ばれている ストレージ・クラス・メモリ (SCM)
  の技術動向の話をきいたときにも同じはなしが出た.
  アプリがストレージの性能のボトルネックになるとわかったとき,
  我々開発者はなにをすればいいのか? という質問がでたが, 答えは,
  
  *関数型言語をつかうこと* 
  
  All SCM Array が数年後に実現したときにはじめて,
  プログラミングの *パラダイムシフト* が起こるかもしれない.
  
  - [[http://itpro.nikkeibp.co.jp/article/Active/20130529/480627/?ST=act-infra&P=1]["第 3 のメモリー"の衝撃, ストレージと DB が一変する - CloseUp:ITpro Active]]
  - [[http://techon.nikkeibp.co.jp/article/SCR/20130725/294302/?ST=SCR][ストレージ・クラス・メモリをどう活かすのか - 半導体リサーチ - 日経 BP 半導体リサーチ]]
  - [[http://techon.nikkeibp.co.jp/article/COLUMN/20140220/335275/][ストレージ・クラス・メモリー - 半導体デバイス - 日経テクノロジーオンライン]]

* ハードディスク
** BAD Data
   ハードディスクに記録されたユーザデータは, 磁性の劣化等が原因で不正
   なデータとなり, CRC (Cyclic Redundancy Check) やブロック ID の検
   査により不正なデータとして検出される場合がある.このため, ストレージ
   デバイスには書き込まれているものの, 不正なデータとなってしまったデー
   タを BAD Data という.

** 信頼性・寿命
   - [[http://d.hatena.ne.jp/tagomoris/20110419/1303181958#][RAID レベルの話: 1+0 と 6 はどっちが安全か? - tagomoris のメモ置
     き場]]

* Replication
  レプリケーション. 複製. 
  


* イレージャーコーディング
  RAID のような, データ保護技術.誤り訂正, 検出技術.

  QR コードと同じ, リード・ソロモン符号アルゴリズムを利用している.

 - [[http://news.livedoor.com/article/detail/9145853/#][大容量データ保護の福音イレージャーコーディングで「 RAID は不要になる」 - ライブドアニュース]]
 - [[http://www.ctc-g.co.jp/~ctcsp//sp/ostf_02.html][新たな潮流, オブジェクトストレージとは?  『オブジェクトストレージが求められる背景』]]
 - [[http://raven.air-nifty.com/night/2011/01/erasure-coding.html][Erasure coding: 私家版 IT プロフェッショナルの仕事術]]
 - [[http://www.jdsf.gr.jp/backup/stm/201007.html][JDSF | データ・ストレージに関する総合情報サイト | Japan Data Storage Forum]]

* 用語
** アドバンスド・コピー
   アドバンスト・コピー機能は, サーバの CPU を使用せずにストレージだけ
   (筺体内) で高速にコピーを作成する機能.

   - [[http://storage-system.fujitsu.com/jp/products/diskarray/feature/c02/][オンライン中の高速バックアップ アドバンスト・コピー機能 (EC, OPC) : 富士通]]


* Links
  ストレージ開発者が今すぐ登録すべき RSS まとめ
  IT 業界にいると, 情報の流れが早い. すぐに動向に置いてかれる.

  なにかうまい方法はと考えて,
  とりあえず結局業界をリードする人の発信する情報をキャッチすることにした.

  - [[http://www.publickey1.jp/][Publickey - Enterprise IT × Cloud Computing × Web Technology / Blog]]
  - [[http://chucksblog.emc.com/chucks_blog/][Chuck's Blog]]

** SNIA 
   Storage Networking Industry Association.

   http://snia-j.org/
   [[http://www.snia.org/][Home | Storage Networking Industry Association]]

** IDC
   いろいろ調べている調査機関.

   [[http://www.idcjapan.co.jp/top.html][IDC Japan 株式会社]]

* Books

