#+OPTIONS: toc:nil
* RubyTrouble

** Windows
*** コマンドプロンプトで irb エラー

#+begin_src dos
\Users\TSUNEMICHI>irb
DL is deprecated, please use Fiddle
C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rbreadline.rb:2111:in `expand_path': non-absolute home ((
#+end_src

Cygwin で 環境変数を HOME=/home/xxx にしているから, expand_path メソッドがエラーする.

以下を入力.

#+begin_src dos
C:\Users\TSUNEMICHI>set HOME=
#+end_src

- [[http://stackoverflow.com/questions/12028130/ruby-irb-doesnt-work-on-windows][Ruby: irb doesn't work on Windows - Stack Overflow]]

*** Cygwin でで selenium-webdriver インストール失敗
Cygwin64bit 版は依存している ffi ライブラリがバグってる!
パッチを当てる必要があるという茨の道.

- https://github.com/ffi/ffi/issues/284

#+begin_src sh
$ gem install selenium-webdriver

Building native extensions.  This could take a while...
ERROR:  Error installing selenium-webdriver:
        ERROR: Failed to build gem native extension.

        /usr/bin/ruby.exe extconf.rb
checking for ffi.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
#+end_src

Windows 版の Ruby で gem の build がともなう場合は,
development kit という, mingw をベースにしたパッケージを入れるのが王道らしいです.
以下からダウンロードして, 解凍したフォルダの bin フォルダに環境変数 PATH を通す.

http://rubyinstaller.org/downloads/


* Functional Programming
  Ruby で関数型っぽいことをする.

** list, tuple
   Ruby には, Array しかない. [] で表現.

*** list comprehension
    - [[http://www.xmisao.com/2013/11/21/learning-haskell-10.html][もし Rubyist が Haskell を学んだら (10) リスト内包表記 -- ぺけみさお]]

*** collect, map, select
    条件にあう配列を生成する.

#+begin_src ruby
def sum100_i
  rslt = 0
  for i in 0..100 do
    rslt += i * i
  end
  rslt
end

def sum100_f
  (0..100).collect {|i| i * i }.inject (:+)
end
#+end_src

** proc, lambda, curry
   Ruby における closure.
   - [[http://futurismo.biz/archives/2472][Ruby の無名関数についての整理メモ | Futurismo]]

** pattern match
   - [[http://qiita.com/egisatoshi/items/38f7f8aef32ac67ccd4b][Ruby に Haskell よりも強力なパターンマッチを実装した - Qiita]]

** Bookmark
   - [[http://yuroyoro.hatenablog.com/entry/2012/08/08/201720][「関数型 Ruby 」という病 (1) - Symbol#to_proc, Object#method - ( ꒪⌓꒪) ゆるよろ日記]]
   - [[http://www.xmisao.com/tags/learning_haskell/][learning_haskell タグのエントリ一覧 -- ぺけみさお]]
