#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+CATEGORY: MOOC
#+TAGS: 自己啓発
#+DESCRIPTION:
#+TITLE: Immunity to Change

* Immunity to Changeの理論について
この本は、キーガン先生とレイヒー先生の、
25年に渡る研究者人生のすべてを費やして書かれた本。
こういうことを書かれると、それだけで理論に凄みが増す。

** 死ぬのをわかっていても変われない
はじめの書き出しがとても印象的だ。

#+BEGIN_HTML
<blockquote>
最近の研究によると、食生活を改めたり、もっと運動したり、
喫煙をやめたりしなければ心臓病で死にますよと専門医から警告されたときに、
実際に自分をそのように変えることができる人は七人に一人にすぎないという。

たった七人に一人だ！

人は、自分の命に関わる問題でさえ、自分自身が心から望んでいる変革を実行できない。

自分が本心からやりたいと望んでいることと
実際に実行できることの間には大きな溝がある。
</blockquote>
#+END_HTML

** 技術的課題と適応的課題
課題には2種類ある。適応的課題に技術的なアプローチをしても失敗する。

たとえば、ダイエットの達成のために高いマシンや情報教材を購入して
一時的に目標を達成しても、時間がたつとリバウンドする。

これは、心が変わらないから。恒常性を維持する自然な免疫力で適応を阻まれたから。

** 免疫マップ
人が変われない原因は、心の免疫システムにある。

その免疫システムを4つのステップで解明していき、
各ステップの関わりを見える化したものが、免疫マップ。

*** 1.改善目標
改善したい目標。一般的な意味と違いはない。
しかし、この1から展開される2から4が独創的なのだ。

*** 2.阻害行動
1の目標を達成しようとしたときに、それを妨げる自分の行動をリストアップする。

心の免疫システムによって、変化しようとしたときに生じる行動を明文化する。

*** 3.裏の目標
2の阻害行動をやめようとしたときに、生じる感情を不安ボックスに記入する。
ここで記入するものは、感情につよく関連しているものである必要がある。

くそっ！ちくしょう！Shit!, Fuck! 汚い言葉であれば汚いほど推奨される。

そして、その不安ボックスの中から1の改善目標に対立する考えをあぶり出す！
変革に重要なことは、この考えを取り除くこと。これこそが裏の目標。

*** 4.強力な固定概念
強力な固定概念とは、3の裏の目標をもつような人が抱いている思い込み。

変革阻害システムの根底にある思い込みを言語化することで、表舞台に引きずり出す。
そのことによって、免疫観念を克服しやすくなる。

** 継続的発展(Continuum of Progress)
3つの視点から、
目標の達成と強力な固定観念の除去が達成されたときの状態を分析する。

- Behaviors(振る舞い)
- Thoughts(理性的な思考)
- Feeling(感情、心情)

3つタイムスパンから、
目標の達成と強力な固定観念の除去が達成されたときの状態を分析する。

- initial steps forward
- Significant Progress
- Full success
** SMART
よい実験の条件。

*** SAFE
Safe means that if the worst-case outcome were to occur, 
you could live with it! 

*** MODEST
Modest means that the test is relatively easy to carry out 
(ideally, it doesn't require you to go out of your way at all, 
but rather is an opportunity to do something different in your normal day). 
It can also mean you make a small change in what you do.

*** ACTIONABLE
a good test will be actionable in the near-term. 
This means that you are able to carry it out within the next week or so.
 You can easily imagine a setting or upcoming situation 
in which to run your test.

*** RESERCH
"how accurate is my Big Assumption?" and, like any good research, 
it requires collecting data (including data that would qualify
your assumption or call it into doubt).
In addition to how people react to you,
your feelings can be a very rich data source. 

*** TEST
The test, in fact, tests your Big Assumption. 
A "test" should not be some clever way to prove that 
your Big Assumption is true! 
Your test should be designed so that it can generate disconfirming data
 (data that proves that your Big Assumption is not always true),
if it exists.

** Running Your First Test
- 強力な固定観念からスタートする。
What experiment would give you information about 
how accurate it is (or isn't)?

- 振る舞いからスタートする。
What behavior could you change that would get you useful information
 about your Big Assumption?

*** どのようなデータを集めるか
ビデオテープに収めることができるデータまたは、
自分の心情の経験的データをあつめる。

自分の行動に依存しないような、行間を読むような、
たとえば他人の心情を推し量るようなデータはダメ。

- Directly observable data
the actual things people say or do, 
the words or action that would be captured on videotape 
if the event were recorded. 
This includes what you do and say, 
as well as what any other people in the test situation do and say.

- Experiential data on your own inner states
how you feel or make sense of what happens during your test. 
Depending on your Big Assumption and your test design, 
this type of data may be the only type you can collect.

* 自分の挑戦
自分の挑戦体験記を後悔。間違えた、公開。

** 免疫マップ
*** 1.改善目標
早寝早起きをして規則正しい生活をする。 

早寝早起き、自分にとってはもっとも改善が必要な課題。

- 社会人なのに、朝起きられず、遅刻ばかりしてしまう。
- 朝起きられないため、精神科に通って毎日坑不安剤を飲んでいる。

今現在の状況は、遅刻ギリギリまでずっと朝はふとんからでることができない。
土日は毎日12時を過ぎたころからようやくふとんから這い出す。
昨日は14時、今日は13時。

しかし、かつては早起きができていた。
改善しようという努力によって短い間だけれども、早起きが定着してた。

今の状況は、リバウンドだと思っている。
より、早起きできなくなった。これは適応的課題。

*** 2.阻害行動
- 家に帰ってから寝るまでの間に計画していないことをする。
- その日にしなくてもいいことを、その日のうちにしてしまう。
- 寝る前にネットサーフィンしてしまう、ドラクエしてしまう。
- 就寝儀式にしたがって行動していない。
- 翌日の予定を立てて寝ない。
- 寝る時間が不安定。
- 目覚ましをかけて寝ない。 

*** 3.裏の目標
**** 不安ボックス
- ちくしょう！ただでさえ自分の時間がないのに、早く寝るのなんてまっぴらだ！
- 明日もきっと自分の好きなことができない。
- くそ、今日中にするべきことが終わらない。絶対にこれは今日しなければいけないのに。
- また起きれなかったという虚無感を味わうくらいなら、
  取り返しがつかないほどに夜更かししてしまえ。
- 今更寝たってどうせ起きられないよ。またダメだという気持を味わいたくない。

**** 裏の目標
- 朝ゆっくり休みすぎたことよって、満員電車で疲れるようなことはしたくない。
- 今の幸せや快楽に溺れた挙句、長期的な大きな喜びを手放したくない。
- 寝坊してしまい、またダメだった、また変われなかったという屈辱感を味わいたくない。
- どうにでもなれという投げやりで計画性のない人間にはなりたくない。
- よい習慣がいつになってもみにつかず、時間が経っていつも後悔したくない。
- その場の感情で投げやりになって計画性がない人になりたくない。
- どうせダメだろうという諦めの気持だけで、挑戦をしないような人間になりたくない。

*** 4.強力な固定概念
- 寝坊すると怠惰な人間に思われる。
- 寝坊すると計画性のない人間に思われる。
- 寝坊するとなんの目標も達成できない。
- 寝坊するとダメな人間になる。
- その場の快楽や感情に流されているとダメな人間になる。
- 早く寝たって、明日もどうせ早く起きることができない。
- いつも時間がない。
- 明日もきっと自分の好きなことをする時間がない。
- よい習慣を身につけようとしてもどうせ続かない。
- 寝坊するとひどい罪悪感と虚無感を味わうことになる。

*** 完成した免疫マップのレビュー
ここまでの分析をして、自分には"いつも時間がない"という固定観念があるように思えた。

朝起きることができない理由は、時間管理にあるのでは？本当に時間がないのか？
時間がない、という思い込みこそが固定観念で、事実とは違うのでは？

また、なんどもなんども朝起きようとしては挫折してきた結果、
"頑張ってもどうせおきられない"という固定観念があるように思えた。

- どうせ、早く寝ても朝起きられない。
- 睡眠時間を記録しても、どうせ途中で止めてしまう。
- どうせ、またギリギリまでふとんのなかでぬくぬくしている。

まとめると、以下の2つが固定観念として浮かび上がってきた。

- いつも時間がない。
- どうせ早く起きられない。

この2つの固定観念に関する検証をすることにした。

** 実験1 目覚ましをかけずに21時に寝る
*** 実験計画
目覚ましをかけないで、21時に寝る。

目覚ましがないと起きられないのか？今までのように寝坊するのか？

**** どのようなデータを集めるか
起床時間。

**** どういう結果が得られたときに固定観念が反証されたとみなすか
目覚ましをつかわなくても5時に起きれた日が3日あったら。

*** 実験結果
**** はやく寝ようとしたときに生じた感情記録
まっすぐにふとんに入ると、そわそわする。

しかし、それははじめだけで、次第に早く寝たいと思うようになる。

**** 実験データ

|-----------------+-----------+-----------+-----------|
| Date            |       Bed |      Wake |           |
|-----------------+-----------+-----------+-----------|
| <2014-04-14 月> |      21.0 |       4.5 |       7.5 |
| <2014-04-15 火> |      23.5 |       7.0 |       7.5 |
| <2014-04-16 水> |      21.5 |       5.0 |       7.5 |
| <2014-04-17 木> |      22.0 |       7.0 |        9. |
| <2014-04-18 金> |      23.5 |       7.5 |        8. |
| <2014-04-19 土> |      22.0 |       4.5 |       6.5 |
| <2014-04-20 日> |      21.5 |       4.5 |        7. |
| Average         | 22.142857 | 5.7142857 | 7.6428567 |
|-----------------+-----------+-----------+-----------|

*** 結果の解釈
- 目覚ましをかけなくても自然と目が覚める。
- だいたい7.5時間で目が覚める。
- 残業して遅く寝た日ははやく起きられない。
- 夢をよくみる。

早くふとんにはいって寝た日は目覚ましをつかわず、目が覚めた。

よって、固定観念は反証された。

** 実験計画2 計画外の時間と感情の記録
夜更かしをしてしまう日は、心に余裕がないときが多い気がする。

心の不安は、計画どおりにタスクがこなせなかった日が多い気がする。

予定外の仕事をした日と、心の不安感には相関関係があるか？
時間がないという思い込みは、予定どおり計画が進まない不安感からくるか？

実験する前からそんな気がするが、
この仮説を裏付けるデータを採取して検証してみる。

*** どのようなデータを集めるか
タスクを予定・予定外でわけて、予定外の作業に費やした時間を収集する。

一日の終わりに、"時間がない"と感じたか、を5段階で評価する。

*** どういう結果が得られたときに固定観念が反証されたとみなすか    
予定外の作業時間と不安感に相関関係があったとき。

*** 実験結果
**** 実験データ
|-----------------+-------+--------+---------|
| date            |  next | unplan | feeling |
| <2014-04-29 火> |   5.6 |    4.4 |         |
| <2014-04-30 水> |     0 |    1.0 |       2 |
| <2014-05-02 金> |   6.9 |    3.4 |       2 |
| <2014-05-03 金> |  5.35 |      4 |       2 |
| <2014-05-05 月> | 11.25 |    1.8 |       2 |
| <2014-05-06 火> |  12.5 |      0 |       3 |
| <2014-05-10 土> |     0 |      0 |       4 |
| <2014-05-11 土> |  12.5 |      0 |       2 |
|-----------------+-------+--------+---------|

*** 結果の解釈
- やや相関関係があるが、つよくはない。
- 予定外のことをした以外にも、以下の要因がある。
  - 見積もった時間を大幅にオーバーしてしまったとき。
  - 寝坊して、一週間のうちにやろうと思っていたことが遅れているとき。
    日の単位ではなくでもっと長いスパンで遅れを感じると不安になる。

この実験では、あまりよい成果が得られなかった。

時間がないということは、

  1. 物理的に時間がない
  2. 不安感から時間がないと感じる

の2つしかない。2の場合は、克服できるはず。

また、不安感は2つからくることを知った。

  - 予定どおりに進まない、見積りを誤る
  - 予定外のことをする

** 実験計画3 走る
以下のbig assumptionを検証

*** どのようなデータを集めるか
走る前と走り終わったあとの心情をノートに記録する。

よい習慣は、毎日小さく(5分から)はじめることで継続できることを検証する。
時間がないという思い込みは、心理的な不安からくることを認識する。

*** どういう結果が得られたときに固定観念が反証されたとみなすか    
*** 実験結果
*** 結果の解釈

* 継続的発展(Continuum of Progress)
3つの視点から、目標の達成と強力な固定観念の除去が達成されたときの状態を分析する。

- Behaviors(振る舞い)
- Thoughts(理性的な思考)
- Feeling(感情、心情)

** 自己分析
*** 満ち足りた成功(Full Success)
- Behaviors(振る舞い)
  - 目覚ましをつかわないでも、早寝早起きができている。
  - 早寝早起きが当たり前のこととして、継続できている。
  - 規則正しく、安定した睡眠時間が継続できている。
  - 満員電車をさけて出社できている。
  - 澄み切った心で集中して勉強に取り組み、数々の成果を出す。

- Thoughts(理性的な思考)
  - その場の欲望に流されず、感情をコントロールすることができる。
  - やりたいことが発生しても、優先順位を見極めて感情を抑制することができる。

- Feeling(感情、心情)
  - 寝坊しても、罪悪感を感じなくなる。
  - 時間に余裕を感じる。時間に対する不安感や焦り、動悸を感じなくなる。
  - 寝るときと起きたときは、澄み切った感覚を得ることが出来る。
  - 時間の不安感から開放され、意欲が沸いてくる。

*** 前に進むためのはじめのステップ(Initial Steps Forward)
- Behaviors(振る舞い～する。)
  - 家にかえったら、決めたこと以外はやらないで、まっすぐにふとんに入る。
  - 夜、やりたいことが発生したら、メモして後日にまわせるようになる。
  - 今飲んでいる抗うつ剤、抗不安剤の量を減らす。
  - ジムに通う習慣を取り戻す。（時間がないといいわけしない)

- Thoughts(理性的な思考～知る、考える)
  - 遅くまで起きようとしたときの感情を距離を置いて観察できるようになる。
  - 自分がどのようなときに遅くまで起きているか、早く寝るかを観察できる。

- Feeling(感情、心情～感じる)
  - 明日もきっと早く起きれると、信じてふとんに入ることができる。

*** スゴい発展(Significant Progress)
- Behaviors(振る舞い～する。)
  - 朝5時に起きる習慣が身につく。
  - 見積りと実績の作業時間を記録し分析する習慣が身につく。

- Thoughts(理性的な思考～知る、考える)
  - やりたいことが発生したときに、その感情を抑制することができる。

- Feeling(感情、心情～感じる)
  - "時間がない"という無意識的に心の中で唱えつづける声が聞こえなくなる。
