#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+CATEGORY: MOOC
#+TAGS: edX
#+DESCRIPTION:
#+TITLE: Paradigms of Computer Programming 最高の感動を味わえるCourse

* はじめに
感動というものを頭に走る電撃と定義するならば、
このCourseは自分にとって、まちがいなく最高の感動だった。



** プログラミングパラダイムとは
プログラミングパラダイムとは、プログラミングの分類方法、スコープ、見方。

なにかを定義しているようでなにもいっていない・・・すみません、詳しくはwikipedia参照ということで。

- [[http://ja.wikipedia.org/wiki/%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0%E3%83%91%E3%83%A9%E3%83%80%E3%82%A4%E3%83%A0][プログラミングパラダイム - Wikipedia]]

** パラダイムを学ぶ動機・意義
講座のなかでは、以下のような利点を強調してモチベーションをあげようとしている。

- いくつものプログラミング言語がある。全てを学ぶことは不可能。
- プログラミング言語はパラダイムで分類できる。
- パラダイム、そこから導出れるコンセプトを抑えることで、多くの言語を理解できる！

なるほど、利にかなっている。

今は、仕事だとオブジェクト指向が全盛だが、その天下もいつまで続くかは分からない。

技術が進めばマルチコアや並列処理に対応するために、それに適した言語が必要になるかもしれない。
HTMLなんかは宣言的プログラミングの典型で、オブジェクト指向ではどうにもならない。

プロフェッショナルなプログラマを目指すのならば、
オブジェクト指向だけでなくて、他の考え方も知っておきたいところだ。

** 個人的な思い
高校生のころにこんな本を読んで、とても感激を受けた。

パラダイムを学び、そしてその考えに触れることで自分の価値観が揺るがされる。
新たな世界が見えるようになる。そんな知的興奮をパラダイムは与えてくれる。

* 感想
Ozの文法がわからない・・。
情報元やサンプルコードが少なくて、文法を調べるのに苦労した。
概念的にわかっていてもその実装するための文法がわからず時間かかったり。
loopを書くのに2時間つかったり。参考書とforumでサンプルコード漁りまくった。

* 各種プログラムパラダイムの簡潔なまとめ
wikiに移行。

- wiki     [[file:~/futurismo/wiki/src/ProgrammingParadium.org]]
