#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+CATEGORY: 技術メモ
#+TAGS:
#+DESCRIPTION:
#+TITLE: Sikuli 

- [[http://www.sikuli.org/][Sikuli Script - Home]]

* インストール

 sikuli-setup.jarをダウンロードして、インストーラをダブルクリックで起動するだけ。

すると、いろいろとインストールオブションがきかれる。JRubyを選択。

slkulix.jarをダブルクリックで起動。IDEが立ち上がる。

以下のドキュメントが詳しい。

- [[http://www.sikulix.com/quickstart.html][SikuliX QuickStart - SikuliX powered by RaiMan]]

** WinUtil.dllが見つからないエラーではまる
runsikulix.cmdで起動するとエラーした。

#+begin_src sh
[error] ResourceLoader: loadLib: Fatal Error 110: loading: WinUtil.dll
[error] ResourceLoader: loadLib: Since native library was found, it might be a problem with needed dependent libraries
C:\sikuliX\libs\WinUtil.dll: 指定されたプロシージャが見つかりません。ﴀ＀
[error] ResourceLoader: loadLib: Check, wether a valid Sikuli libs folder is in system path at runtime!
#+end_src

よくわからないのだが、環境変数のパスを通して(C:\sikuliX\libs)、JDK 7 を最新版にしたらなおった。

* Hello Sikuli
以下のようなコード。

実行結果はこんな感じ。

#+BEGIN_HTML
<iframe width="420" height="315" src="//www.youtube.com/embed/SoN_zfuG1E8?rel=0" frameborder="0" allowfullscreen></iframe>
#+END_HTML

* 実行ファイルから実行する
もちろん、IDE を経由しないでコマンドラインから実行できる。

ツールバーのファイルから実行ファイルとしてエクスポートを選択。.skl拡張子のバイナリファイルができる。(ここではtest.skl)

runsikulix.cmdの引数として、.sklを渡す（注意: 1.1からの仕様)

#+begin_src language
E:\test>C:\sikuliX\runsikulix.cmd -r test.skl
#+end_src

これで、コマンドラインから実行できた。

* Rubyから実行する
Sikuliの素晴らしいところは、JVM上で動作スクリプト言語を利用できる。JPython, JRubyとか。つまりは、Rubyが使える！

#+BEGIN_HTML
<blockquote>
But be aware: Since the interpreters used are based on Java, the modules available for Python or Ruby might not be available in the Jython or JRuby environment. So before trying to use any non-standard modules or extension packages, you have to check, wether they are supported in this SikuliX environment.
</blockquote>
#+END_HTML

- [[https://answers.launchpad.net/sikuli/+question/221083][Question #221083 : Questions : Sikuli]]

** JRubyを入れる
以下からインストーラを落としてきていれる。

- [[http://jruby.org/][Home — JRuby.org]]
 
#+begin_src sh
C:\Users\TSUNEMICHI>jruby -version
jruby 1.7.12 (1.9.3p392) 2014-04-15 643e292 on Java HotSpot(TM) 64-Bit Server VM 1.7.0_55-b13 [Windows 7-amd64]
#+end_src



** sikulixapi.jarをクラスパスに追加

** 必要なSikuliクラスをimport



* その他Tips
** キーの送信

#+begin_src language
click(Key.ENTER)
#+end_src

エラーする。

#+begin_src sh
[error] script [ HelloSikuli ] stopped with error in line 1
[error] NoMethodError ( (NoMethodError) undefined method `ENTER' for Java::OrgSikuliScript::Key:Class )
#+end_src


** Environment
- windows 7 64bit
- JDK 7 64bit
- JRuby 1.7.12

** Special Thanks
Official

- [[http://www.sikulix.com/][SikuliX powered by RaiMan - Home]]

Java Doc 

- https://dl.dropboxusercontent.com/u/42895525/docs/index.html

Document

- [[http://sikulix-2014.readthedocs.org/en/latest/index.html][Sikuli / SikuliX Documentation for version 1.1+ (01/2014 and later) — SikuliX 1.1+ documentation]]

よくまとまっている日本語のまとめ

- [[http://safx-dev.blogspot.jp/2013/02/sikuliui.html][Safx: SikuliスクリプトでのUI操作自動化を試してみる]]
- [[http://hontech.xii.jp/blog/archives/28][sikuliの簡単な使い方 | hontech]]
- [[http://www-he.scphys.kyoto-u.ac.jp/member/n.kamo/wiki/doku.php?id=study:software:sikuli][Sikuli KamonoWiki]]


Ruby関連

- [[http://blackrat.org/ruby/getting-sikuli-script-working-with-jruby-on-the-mac/][Getting Sikuli Script working with Ruby(JRuby) on the Mac | blackrat.org]]
- [[https://answers.launchpad.net/sikuli/+question/221083][Question #221083 : Questions : Sikuli]]
- [[http://www.software-testing.com.au/blog/2010/08/16/automating-flash-ajax-popups-and-more-using-ruby-watir-and-sikuli/][Automating Flash, AJAX, Popups and more using Ruby, Watir and Sikuli | Illiteration –]]
