#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+CATEGORY: 技術メモ
#+TAGS:
#+DESCRIPTION:
#+TITLE: 

以前より興味があった GlusterFS に触って見ました.

[[http://gluster.readthedocs.org/en/latest/Quick-Start-Guide/Quickstart/][Quick start Guide - Gluster Docs]] にそって、
AWS上に GlusterFSをインストール してみます.

* Getting Started
** Step1 - 2つのノードを準備
   EC2でインスタンスを作成. タイプは無料で利用できるt2.micro.
   - Amazon Linux AMI 2015.03 (HVM), SSD Volume Type

   ストレージとして、EBSを用意する 5GBで用意.

** Step 2 - ディスクのフォーマットとマウント
   作業は、rootで実施.

#+begin_src bash
$ sudo su
#+end_src

   /dev/xvdbに EBSが準備されている.

#+begin_src bash
$ ll /dev/xv*
brw-rw---- 1 root disk 202,  0 Jun 27 15:42 /dev/xvda
brw-rw---- 1 root disk 202,  1 Jun 27 15:42 /dev/xvda1
brw-rw---- 1 root disk 202, 16 Jun 27 15:42 /dev/xvdb
#+end_src

    ここでは、ext4形式、512byteでフォーマットする.

#+begin_src bash
# mkfs.ext4 -I 512 /dev/xvdb
# mkdir -p /data/brick1
# /etc/fstab
#+nd_src

  /etc/fstabに以下を追記.

  #+begin_src bash
/dev/xvdb /data/brick1 ext4 defaults 1 2
  #+end_src

  以下のコマンドでマウント.

  #+begin_src bash
# mount -a && mount
  #+end_src

** Step 3 - GlusterFSのインストール

#+begin_src bash


$ service glusterfs-server status
glusterfs-server start/running, process 1013

# 起動の設定
$ update-rc.d glusterfs-server defaults
#+end_src

** Step 4 - 信頼するプールの作成
   今回のGlusterFS用インスタンスのホスト名のプライベートIPアドレスは以下.
   - server1: 172.31.0.242
   - server2: 172.31.0.241

   それぞれのサーバで以下を実施.

#+begin_src bash
# server1
gluster peer probe 172.31.0.241

# server2
gluster peer probe 172.31.0.242
#+end_src

うまくできたかどうかは、peer status コマンドで確認.

#+begin_src bash
$ gluster peer status
Number of Peers: 1

Hostname: 172.31.0.242
Port: 24007
Uuid: 00000000-0000-0000-0000-000000000000
State: Establishing Connection (Disconnected)
#+end_src

** Step 5 - GlusterFS volumeのセットアップ

両方のサーバで、

#+begin_src bash
 mkdir /data/brick1/gv0
#+end_src

片方のサーバで、

#+begin_src bash
$ gluster volume create gv0 replica 2 172.31.0.242:/data/brick1/gv0 172.31.0.241:/data/brick1/gv0
$ gluster volume start gv0
#+end_src

** Special Thanks
   - [[http://dev.classmethod.jp/cloud/aws/glusterfs-on-ec2/#][EC2でGlusterFSを使ってみた ｜ Developers.IO]]
   - [[http://qiita.com/iron-breaker/items/eab40505cab908da886f][GlusterFS - DockerでGlusteFS。分散ファイルシステムの実装。 - Qiita]]
   - [[http://www.slideshare.net/c95029/awsgluster-fs-20120726public][AWSではじめるGlusterFS]]
   - [[http://askubuntu.com/questions/631183/i-got-this-error-message-glusterd-unrecognized-service][14.04 - i got this error message - "glusterd : unrecognized service" - Ask Ub...]]
   - https://sites.google.com/site/glusterfstech/install
   - [[http://www.hpc-sol.co.jp/support/20121115_glusterfs_howto_install.html][株式会社HPCソリューションズ　～　レビュー GlusterFSの概要と導入手順について GlusterFS rdma]]  
    

   
   #+BEGIN_HTML
   <p style="font-size:32px">以上、Happy Hacking!!</p>
   #+END_HTML
   
