#+OPTIONS: toc:nil
#+TITLE: ダイエット

  - 摂取カロリー＞消費カロリー
  - 朝昼晩＝ 3：5：2
  - [[http://mery.jp/31323][朝昼晩はこれを食べよ♡痩せ体型をつくるお食事ノート｜ MERY]]

  血糖値が下がるタイミングに合わせて食事をすると、 
  消化がスムーズになり、脳もカラダもすぐに活性化します
    - １回目６～７時ごろ
    - ２回目１０～１１時ごろ
    - ３回目１６～１７時頃
  (http://pure-la.net/jamu/dietjamu/diet-eat.htm)

  夜に炭水化物を控え、寝る前までにブドウ糖を使いきっておけば、 
  寝ている間も基礎代謝のために、脂肪がエネルギーとして燃える.

  - 朝：ごはんやパン
  - 昼：肉や魚、卵、揚げ物や油っぽいモノなどのメイン料理
  - 夜：野菜中心

** 朝: 炭水化物を摂取する時間.
   朝の食事は体内時計を正常化するのに効果がある.

   朝ごはんでブドウ糖をしっかり吸収した脳は、
   仕事や勉強に良い影響を及ぼすことが分かっています
   (http://eonet.jp/health/special/special31_2.html)

*** メニュー
   - ごはん, パン
   - 野菜（ジュース)
   - ヨーグルト、バナナ

** 昼: タンパク質を摂取する時間.
   昼食の時間は「炭水化物の消費は朝食時ほどではないが、
   脂肪やたんぱく質の消費はもっとも盛んになる」

   エネルギーをつくる時間

   ごはんやパンなどの主食は少なめにして、
   そのかわりおかずをたっぷり食べる、というのがポイント
   (http://matome.naver.jp/odai/2142233945083086101)

*** メニュー
   - 定食はおすすめ.
   - 天ぷらなどの油を使った定食はやめて、シンプルな刺身定食、魚の塩焼き定食を基本に.
     (http://matome.naver.jp/odai/2142233945083086101)

    - 野菜炒め定食
    - 焼き魚定食
    - 煮物定食
    - 豆腐ハンバーグ定食
    (http://www.diet-carbohydrate.net/rules/menu.html)

** 夜: 食物繊維を入れる時間
   - ご飯とおかずを組み合わせて 500kcl 以内

*** メニュー
   - 野菜
   野菜に含まれる食物繊維が満腹感を与え、食べ過ぎ防止につながります
   - [[http://www.skincare-univ.com/article/006034/][ナイナイの岡村さんが痩せた！サラダボウルダイエット | スキンケア大学]]

   - 豆腐・納豆
     納豆は低脂肪、低カロリーであり、良質な栄養を多く含みます。納豆に
     含まれる酵素は、血液をサラサラにする効果があるので、代謝が上がる
     という嬉しい効果もあります.

     肉や魚、卵、大豆製品などのタンパク質には「トリプトファン」という
     必須アミノ酸が含まれており、ストレス緩和に役立ちます

   [[http://matome.naver.jp/odai/2138188657778439701][20 時以降でも太らない安心の食事方法８つのポイント【夜ダイエット】 - NAVER まとめ]]

